### ISSUE TITLE
Update the Alpheios icon in the alignment editor tab of the browser

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#110]
I noticed that the alignment editor tab does not have the Alpheios icon in Safari, and Chrome and FF/PC. see screenshot attached.

![Screen Shot 2020-12-30 at 2 57 30 PM](https://user-images.githubusercontent.com/41396793/103414206-fa10cc00-4b4a-11eb-8da6-a2e65536432e.png)

**Comment by irina060981** [comment]
Yes, it doesn't have icon - I would add it with the next PR

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
Alpheios icon is visible in the browser's tab
