### ISSUE TITLE
OUTPUT 4 - Simple json output of source data and alignment groups data

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#124]
We should realise the following workflow:

- download/upload middle results of alignment process
- should download/upload source texts, tokens, alignment groups

**Comment by irina060981** [comment]
- added download/upload from json feature
- added downloadType / uploadType in download/upload main menu additional block
- download/upload from json includes
   a. source texts
   b. aligned texts
   c. alignment groups 
   
   active alignment group is not saved
   history is not saved

**Comment by irina060981** [comment]
How to download:
![image](https://user-images.githubusercontent.com/12377640/105990651-897bb180-60ee-11eb-8d5d-f2dd59ef1544.png)

- **Short to csv** - downloads only sourceTexts with lang, direction properties (we used it before)
- *Full to json* - downloads sourceTexts, aligned texts with segments/tokens (if ready), alignment groups (if ready)

Choose a type and click download icon

**Comment by irina060981** [comment]
How to upload:
![image](https://user-images.githubusercontent.com/12377640/105991075-132b7f00-60ef-11eb-82a0-7806ea16608a.png)

- **Short to csv** - uploads from tsv only sourceTexts with lang, direction properties (we used it before)
- **Full to json** - uploads from json file sourceTexts, aligned texts with segments/tokens (if ready), alignment groups (if ready)

Choose a type , choose a file and click upload icon ![image](https://user-images.githubusercontent.com/12377640/105991191-3a824c00-60ef-11eb-8cef-b703fe21eb4c.png)

**Comment by irina060981** [comment]
@monzug, it is ready to be tested

**Comment by irina060981** [comment]
merged and closed

**Comment by monzug** [comment]
tested but waiting for #146 (error on uploading) and #135 (file type removed from upload)

**Comment by monzug** [comment]
verified. if there are outstanding issues will be entered in github.
