### ISSUE TITLE
a couple of minor issues on tokenization

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#127]
1) Shall we add the same text as in the top "Each token needs to be separated by space. Click Enter to insert tokens." 

![Screen Shot 2021-01-27 at 4 19 30 PM](https://user-images.githubusercontent.com/41396793/106013184-810a8300-60bc-11eb-9949-3bb1546d1f94.png)

2) when I add a line break or remove a token, the separation line in the middle has empty space. Is there anything that can be done? Absolutely super low priority. see screenshot

![Screen Shot 2021-01-27 at 4 14 31 PM](https://user-images.githubusercontent.com/41396793/106013268-9384bc80-60bc-11eb-93d5-907ce71068af.png)

**Comment by irina060981** [comment]
>Shall we add the same text as in the top "Each token needs to be separated by space. Click Enter to insert tokens."

Didn't fully understand your question. Will describe the full workflow.

These empty inputs allows to add new words to the start and to the end of the texts. 
A user types words
  - if in the starting empty input - then they would be added to the start of the text
  - if in the last empty input - then they would be added to the end of the text
  
There are no checks what words should be added here. So you could add the the start and to the end different text.
For example:
![image](https://user-images.githubusercontent.com/12377640/106113464-3f500a00-619a-11eb-8a0e-2391c38ba94d.png)

after Enter
![image](https://user-images.githubusercontent.com/12377640/106113505-4a0a9f00-619a-11eb-8b64-361c98ab635f.png)

Hope, I answered to your question

**Comment by irina060981** [comment]
>when I add a line break or remove a token, the separation line in the middle has empty space. Is there anything that can be done? Absolutely super low priority. see screenshot

I would need to check styles there - will do that

**Comment by monzug** [comment]
@irina060981, thanks for the explanation, I got the functionality. My question was more related from user perspective. when I have a looong text (that's what I used for testing), then you have this input box at the end with no info, so it's not straightforward that it's the same as the one on top (except for adding words at the end). Can we do the following?:
1) move the text "Each token needs to be..." above the first input box
2) Add "Adding to the start" and  "adding to the end" in the input field

**Comment by irina060981** [comment]
Oh I think it is a good suggestion - will do that

**Comment by irina060981** [comment]
@monzug, I suggest to modify a little 
add before the first input 
```
Each token needs to be separated by space. Click Enter to insert tokens to the start.
```

add before the last input 
```
Each token needs to be separated by space. Click Enter to insert tokens to the last.
```

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/106446892-899ff680-64cc-11eb-937f-9a294feecfa4.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
Irina, looks good, just too long. I like that we have the same text at the top and bottom, except for the start  and end.
maybe 'Add space between tokens.'?????

**Comment by irina060981** [comment]
>Irina, looks good, just too long. I like that we have the same text at the top and bottom, except for the start and end.
maybe 'Add space between tokens.'?????

Will update this

**Comment by irina060981** [comment]
Would be this way 
![image](https://user-images.githubusercontent.com/12377640/106592032-b91d3480-659a-11eb-8a20-6bf6dddef8e2.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
Irina, did you have time to check style for the second issue reported above? LOW priority

**Comment by irina060981** [comment]
Oh, I missed the style issue - will check it

**Comment by irina060981** [comment]
Fixed
![image](https://user-images.githubusercontent.com/12377640/106692788-e0b6e000-6620-11eb-9b90-555059c06e70.png)

![image](https://user-images.githubusercontent.com/12377640/106692810-e90f1b00-6620-11eb-9fb2-84269ff7d24d.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
@irina060981 I think a side effect of the change you recently merged. if it's not an easy fix to make, can we roll back the fix?
Thanks
![Screen Shot 2021-02-03 at 2 15 22 PM](https://user-images.githubusercontent.com/41396793/106752300-933f7080-662a-11eb-967b-59bb7016ac47.png)

**Comment by irina060981** [comment]
No it is not difficult at all, I forgot to add one line of css styles and didn't test on such a test case.
![image](https://user-images.githubusercontent.com/12377640/106821328-aa34a000-66c8-11eb-8ce1-76b98ff45bc3.png)

Now it is fixed

**Comment by monzug** [comment]
tested in Chrome/PC and Safari/Mac, fixed.

**Comment by monzug** [comment]
tested in Chrome/PC and Safari/Mac, fixed.
