### ISSUE TITLE
Remove upload types

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#132]
from @abrasax 

It could make interface simply if we remove upload types from upload block and choose the upload workflow by file extension.

If csv/tsv => short from csv
if json => full from json

![image](https://user-images.githubusercontent.com/12377640/106227573-25173a00-6235-11eb-8250-7567c7812b32.png)

P.S. But if we woud have an additional dependency on upload type, we would need to return types.
For example we could have short or full types from json file.
But otherwise we could add some metadata to the upload file to define the way it should be parsed.

**Comment by abrasax** [comment]
I find that very attractive, but would like Bridget to sign off on it.  But
we could perhaps leave that until the interface discussion?
In general, I will always vote for simplifying the interface wherever
possible, automating any choices we can make safely for the user without
his participation- reducing the number of keystrokes, reducing what is
being displayed to what is necessary for the current task- etc.

**Comment by monzug** [comment]
we don't have the file type when uploading origin or target texts

**Comment by balmas** [comment]
Eventually if we expand the types of input to specific standard formats we will probably need a way to specify type other than by file extension but I would think for now @irina060981 's suggestion is fine and as @monzug notes it's also consistent with the way we handle text upload

**Comment by irina060981** [comment]
This issue was solved with https://github.com/alpheios-project/alignment-editor-new/pull/144

**Comment by monzug** [comment]
we don't have the file type on upload from top menu. we do only when downloading.
