### ISSUE TITLE
Updated token not shown in alignment groups

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#134]
I can edit a token but the updated token is not shown in the alignment groups.
to repro:
I checked the Allow update token word checkbox, then I edited a word in the origin text and clicked on Enter (also I tried Update a token again). The updated token is not shown in the Alignment groups. More, if I merge the updated token with a left or right token, the original one is shown, not the updated. The updated token is not saved.

**Comment by irina060981** [comment]
@monzug , I believe I didn't understang the case and couldn't reproduce.
My steps:
created and tokenized simple text:

![image](https://user-images.githubusercontent.com/12377640/106427495-38cfd400-64b3-11eb-93ac-9b0ce2ae93d9.png)

updated the first token in the origin text (changed text and clicked the firxt icon ![image](https://user-images.githubusercontent.com/12377640/106427651-75033480-64b3-11eb-8fd8-e1ae50641990.png) )
![image](https://user-images.githubusercontent.com/12377640/106427540-51d88500-64b3-11eb-80a1-29920c53835f.png)

it was updated 
![image](https://user-images.githubusercontent.com/12377640/106427632-6c126300-64b3-11eb-9079-8f1d880b232d.png)

created an alignment group with it
![image](https://user-images.githubusercontent.com/12377640/106427720-9106d600-64b3-11eb-9b5e-7942c4303f8d.png)

![image](https://user-images.githubusercontent.com/12377640/106427743-9d8b2e80-64b3-11eb-85f4-a163b289e270.png)

These tokens from the group became unavailable for changing

On what step do you have the wrong result?

**Comment by monzug** [comment]
Uhm, still it does not work for me. see attachment (I clicked enter and then update a token). it worked for few tokens but never for the first one. 

![Screen Shot 2021-02-01 at 4 08 54 PM](https://user-images.githubusercontent.com/41396793/106477085-0ec4e480-64a8-11eb-9c57-7a3fa141b30d.png)

**Comment by monzug** [comment]
I tried again in Chrome/mac and I was able to edit and update a couple of tokens then it stopped updating any other token. also the downloaded json had the original tokens and not the one I was trying to update (this is obvious but I am just adding this info)
1) screenshot of a couple of token that I am updating but do not get saved
![Screen Shot 2021-02-01 at 5 49 36 PM](https://user-images.githubusercontent.com/41396793/106490966-a9c4bb00-64b6-11eb-97f2-4fdf5642f9d2.png)
2) screenshot of the uploaded json file (as you can see 'motto' and 'chi ' words have not been saved)
![Screen Shot 2021-02-01 at 5 58 02 PM](https://user-images.githubusercontent.com/41396793/106491377-18097d80-64b7-11eb-8811-5b3dec1be7be.png)

**Comment by monzug** [comment]
Irina, really weird that i can edit few tokens but then cannot. could it be related to a set numbers of undo/redo or editing?

**Comment by irina060981** [comment]
@monzug, update of a token works only after icon is clicked. It is not updated by Enter key.
Enter key we use inside an empty input only.

do you have the case when a token is not saved after you clicked an icon?
And may be they are too small? May be I should do them bigger?

**Comment by monzug** [comment]
Irina, I do both (enter and click on icon again).  it looks like it does not work for first word and then it stopped working after  tot # of words. I haven't figured out yet. see attachment
1) first word does not work
![Screen Shot 2021-02-02 at 7 56 18 AM](https://user-images.githubusercontent.com/41396793/106563878-c3084e80-652c-11eb-9ad3-3d002850224f.png)
2) after editing other tokens, first word does also work
![Screen Shot 2021-02-02 at 7 57 36 AM](https://user-images.githubusercontent.com/41396793/106563922-d1566a80-652c-11eb-9cb6-3f5e3575daaa.png)

**Comment by monzug** [comment]
I think it has something to do with undo/redo. when both are grayed out, it does not work, when one is clickable and the other grayed out it does work. I have to try few times to confirm this. later on the day.

**Comment by monzug** [comment]
Irina, it's easier than I thought. If I click on edit token, then I edit the token and click again on Update a token, it does not work!!!!

**Comment by irina060981** [comment]
Monica, great catch! It is easy to reproduce! will fix!
thank you :)

**Comment by monzug** [comment]
so happy it was an easy one. it took me a while to figure out what it was!!!!!

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
this works now. Thanks Irina!!!
