### ISSUE TITLE
Shall we save the updated alignment groups?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#135]
this is probably out of scope but I present my case. Wouldn't it be nice to be able to save (download) the updated alignment groups?
while testing #39, I changed and added few tokens, then checked for the changes in the alignment groups. Those changes are temporary and they will be gone with clear text  or  by uploading a new file.  what if I want to save them?

**Comment by balmas** [comment]
I'm not sure I understand.  Aren't the updates included when you download the alignment? I thought that was working now.

**Comment by monzug** [comment]
yes, you are right. the download on the top menu would do that. Take it back.

**Comment by monzug** [comment]
Actually, I was right. the downloaded version is the old one, the updated tokens are not in the downloaded version.
Let me try with a fresh one to see if it works

**Comment by monzug** [comment]
Confirmed that the updated tokens are not in the downloaded file.

1) screenshot of the origin and target texts
![Screen Shot 2021-01-29 at 5 27 18 PM](https://user-images.githubusercontent.com/41396793/106301076-8cde7c80-6257-11eb-842f-d07bf04948b0.png)

2) tokens been added after alignment
![Screen Shot 2021-01-29 at 5 28 13 PM](https://user-images.githubusercontent.com/41396793/106301164-ac75a500-6257-11eb-9b29-7c14692c660e.png)

3) upload the file previously downloaded (filename alignment-eng-eng-8.tsv)
![Screen Shot 2021-01-29 at 5 28 50 PM](https://user-images.githubusercontent.com/41396793/106301218-be574800-6257-11eb-9f27-9501039c1af1.png)

**Comment by monzug** [comment]
Confirmed that the updated tokens are not in the downloaded file.

1) screenshot of the origin and target texts
![Screen Shot 2021-01-29 at 5 27 18 PM](https://user-images.githubusercontent.com/41396793/106301076-8cde7c80-6257-11eb-842f-d07bf04948b0.png)

2) tokens been added after alignment
![Screen Shot 2021-01-29 at 5 28 13 PM](https://user-images.githubusercontent.com/41396793/106301164-ac75a500-6257-11eb-9b29-7c14692c660e.png)

3) upload the file previously downloaded (filename alignment-eng-eng-8.tsv)
![Screen Shot 2021-01-29 at 5 28 50 PM](https://user-images.githubusercontent.com/41396793/106301218-be574800-6257-11eb-9f27-9501039c1af1.png)

**Comment by balmas** [comment]
@irina060981 I agree with @monzug that this needs to be in scope. thanks!

**Comment by irina060981** [comment]
@monzug , I believe you downloaded it as - short to csv?

We have two types of download/upload now:
**short to csv** - download/upload only source texts without tokens and alignment groups
**full to json** - download/upload source texts, tokens and segments, alignment groups

If you choose the variant **full to json** - alignment groups would be saved too

Monica, did you try this? Do you have the same problem with **full to json**?

**Comment by monzug** [comment]
Irina, yes you are right. I downloaded as short to csv. If I download full to json then I will have the updated tokens in the alignment group, still not in origin and target text. Just to clarify, the origin and target text will never change, correct? I was expecting that to change too. 
Suggestion: can we have the download set to 'full to json'? also, would it be possible to add tooltip for short to csv and full to json?

**Comment by irina060981** [comment]
- removed upload type - now it is defined from extension
- set **full from json** as default from download
- add tolltips for dwonload types:
   - **short from csv** - download/upload only source texts without tokens and alignment groups
   - **full from json** - download/upload source texts, tokens and segments, alignment groups

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
tooltips are in. Great.
However, I am not sure why you have removed the upload type. Could you pls explain your thoughts? it can be a good idea, just curious.

**Comment by monzug** [comment]
tooltips are in. Great.
However, I am not sure why you have removed the upload type. Could you pls explain your thoughts? it can be a good idea, just curious.

**Comment by irina060981** [comment]
>However, I am not sure why you have removed the upload type. Could you pls explain your thoughts? it can be a good idea, just curious. was it suggested in Harry's email?

Yes, there were a discussion about this on the meeting and I created an issue for that - https://github.com/alpheios-project/alignment-editor-new/issues/132
There are some details of discussion there. Would mark it for verification too - thank you for the attenstion to this.

the main arguments to remove upload types:
- we have distinct upload type for each menu - global - csv, tsv: local - txt and xml; this way I could define the type from the extension
- for now we don't have different upload types for the same extension
- in future if we would have different types for the same extension - I could add a header to the uploaded file (when it is downloaded) with details of the file format
- it would reduce amount of incorrect upload transactions

**Comment by irina060981** [comment]
I re-read the issue and now I am not sure - that should do this optimization now :) before interface was discussed.
I did this because I made a lot of mistakes myself when was uploading for tests.

**Comment by monzug** [comment]
@irina060981 , do you want to add anything to be discussed in #149 ?

**Comment by irina060981** [comment]
>@irina060981 , do you want to add anything to be discussed in #149 ?

I think that we could discuss it when we would have additional types of Upload from files - json, csv, tsv, txt and xml, for now we don't have them even in requirements. Let's return to this question when we would have new types of upload.

**Comment by irina060981** [comment]
I believe that as we came to the final decision with upload types - I could close the issue

**Comment by monzug** [comment]
agree. global upload (csv, tsv, json), origin/target upload: csv, tsv, xml, txt
