### ISSUE TITLE
Download button in Origin or Target text does not work

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#136]
I entered texts in both origin and target text, then clicked on Download. This action does not do anything. Note that I am able to download texts only when using the Download button from top menu.

**Comment by irina060981** [comment]
oh, I believe I broke something while working on new download/upload types - will fix

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
it does work now. it downloaded a csv file
