### ISSUE TITLE
test language support in tokenization

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#145]
as we had issue with Chinese (and Irina said also  Russian, Ukrainian, Thai, Vietnamese), let's test all language in Target or Origin texts. so far, I did all languages starting with A, B and C.

**Comment by irina060981** [comment]
Related to the issue https://github.com/alpheios-project/tokenizer/issues/33
and PR - https://github.com/alpheios-project/tokenizer/pull/34

**Comment by monzug** [comment]
@irina060981 I got a 500 error when using a file saved as japanese language

**Comment by irina060981** [comment]
Yes it is right - we have two unsupported languages.
It is described here - https://github.com/alpheios-project/tokenizer/issues/33
And I duplicated this info by email 2 Feburary

**Comment by monzug** [comment]
Sorry, I didn't see Japanese in the email that's why I added it here. will
wait when completed to finish testing all languages

**Comment by monzug** [comment]
Confirm that it's working for russian, ukrainain, thai and vietnamese  but as said  in alpheios-project/tokenizer#33 , I am still getting a 500 error for  japanese and korean languages.

**Comment by monzug** [comment]
Sanskrit also gives a 500 error. see attachment

![Screen Shot 2021-03-15 at 2 43 03 PM](https://user-images.githubusercontent.com/41396793/111162849-d29f9c00-859c-11eb-9027-a1f072d3f4aa.png)

**Comment by monzug** [comment]
in the drop down we have the Ukanian language which I have never heard of. Could it be a spelling error for Ukranian?

**Comment by irina060981** [comment]
@monzug , I have a suggestion -
may be it is worth to create a new issue for each language fail with text samples?
It would be useful for the developer - to investigate and test it with the ready text sample

**Comment by monzug** [comment]
I used this text for Telugu language:
Pratipattisvatvamula visyamuna mānavulellarunu janmataḥ svataṁtrulunu samānulunu naguduru.

Vāru vivēdanāṁtaḥkaraṇa saṁpannulaguṭacaē parasparamu bhrātṛbhāvamutō vartiṁpavalayunu

in English:
All human beings are born free and equal in dignity and rights. 

They are endowed with reason and conscience and should act towards one another in a spirit of brotherhood.

**Comment by monzug** [comment]
and the same text for Sanskrit from https://omniglot.com/writing/sanskrit.htm

Sarvē mānavāḥ svatantrāḥ samutpannāḥ vartantē api ca, gauravadr̥śā adhikāradr̥śā ca samānāḥ ēva vartantē. 

Ētē sarvē cētanā-tarka-śaktibhyāṁ susampannāḥ santi. Api ca, sarvē´pi bandhutva-bhāvanayā parasparaṁ vyavaharantu.

**Comment by monzug** [comment]
created two new issues to report the problem with Telugu and Sanskrit languages and the misspelled error.
