### ISSUE TITLE
Outstanding issues that need input from Bridget and Harry

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#149]
1) see #39 - Monica asked: How do I ungroup a selection in the alignment group when it's only on one side?
Irina's reply: From the requirements we have the following - active alignment group -

if you click on the grouped token that is from the text (origin or target) that was the first - then the group would be finished (if you have tokens from both texts)
if you click on the grouped token that is from the text that was not first - it would be removed from the group
So there is no way to remove tokens from the group from the first text (as in your case).

I could suggest only the following - to select a token from the second text (target in your case), then finish the group by clicking on any grouped token from the origin text. Then activate by clicking on the grouped token from the target text. And this way you would be able to remove tokens from origin part of the group.

Or you could suggest how to expand requirements :)

2) see #39 - Monica asked: is it ok to move all tokens out of a segment till it's empty (I can always move them back in)? I could not find anything in the issue, just wondering. it might be a no-issue at all.

Irina's reply: Oh, I think it is not good, because we have a check on the same amount of segments. And this way - it would be broken. May be we should set a limit?

**Comment by balmas** [comment]
>see #39 - Monica asked: How do I ungroup a selection in the alignment group when it's only on one side?
Irina's reply: From the requirements we have the following - active alignment group -

Per discussion with @abrasax today, could we address this by having a 2nd click on a word in the starting side of an alignment group remove that word, UNTIL the point at which a word on the opposite side is selected?

E.g. 
Click Origin Text Word A -> Alignment Group contains Word A
Click Origin Text Word B -> Alignment Group contains Word A and Word B
Click Origin Text Word B -> Alignment Group contains Word A
Click Target Text Word C > Alignment Group contains Word A, Word B, Word C
Click Origin Text Word A -> Alignment Group is saved.

**Comment by balmas** [comment]
>see #39 - Monica asked: is it ok to move all tokens out of a segment till it's empty (I can always move them back in)? I could not find anything in the issue, just wondering. it might be a no-issue at all.

Per discussion with @abrasax today, let's prevent the user from completely emptying a segment.

**Comment by irina060981** [comment]
@balmas and @abrasax - thank you for decissions - would implement them

**Comment by monzug** [comment]
these issues have been fixed.
