### ISSUE TITLE
Show "tokenization service unavailable" error

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#151]
see #141 for reference
irina said:
error says that the fail is on the step - getConfig, when application starts to upload configuration (tokenization parameters) from the remote tokenizer to use them in text single blocks. So this text of the error is predefined.
Bridget suggestion:
I think maybe in that case it would be better to show an error that is more meaningful to the user (e.g. "tokenization service unavailable") if possible.

@irina060981 , can you investigate if this is easy to implement? Thanks

**Comment by irina060981** [comment]
Updated message to the 
```
Remote service is unavailable - {url} 
```

This message is common for all our services

**Comment by monzug** [comment]
got Remote service is unavailable  few times when uploading the betamasaheft database
