### ISSUE TITLE
Remove line break gets stuck

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#152]
see issue #83 

I did experience this issue few times when testing the remove/add a line break after a token.
if I use undo/redo, the remove line break after the token does not do anything when clicking on it. see attachment
![Screen Shot 2021-02-04 at 3 18 45 PM](https://user-images.githubusercontent.com/41396793/106905844-df5ae580-66fc-11eb-873b-63668f6160da.png)

**Comment by monzug** [comment]
to repro:
1) have a segment with 3 lrows
2) remove line break after a token twice, till you have all words on one row. 
3) then click on undo/redo few times, till you see that Remove line break after a token is active but does not do anything

**Comment by irina060981** [comment]
oh - will check

**Comment by irina060981** [comment]
The bug is located and fixed
Merged and closed

**Comment by monzug** [comment]
tested in About Alpheios
Alpheios Translation Alignment editor 1.0.1 (build development.20210208207)
now it works. Thanks
