### ISSUE TITLE
Remove tokens from the group from the starting text

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#154]
>see #39 - Monica asked: How do I ungroup a selection in the alignment group when it's only on one side?
Irina's reply: From the requirements we have the following - active alignment group -

Per discussion with @abrasax today, could we address this by having a 2nd click on a word in the starting side of an alignment group remove that word, UNTIL the point at which a word on the opposite side is selected?

E.g. 
Click Origin Text Word A -> Alignment Group contains Word A
Click Origin Text Word B -> Alignment Group contains Word A and Word B
Click Origin Text Word B -> Alignment Group contains Word A
Click Target Text Word C > Alignment Group contains Word A, Word B, Word C
Click Origin Text Word A -> Alignment Group is saved.

_Originally posted by @balmas in https://github.com/alpheios-project/alignment-editor-new/issues/149#issuecomment-772971868_

**Comment by irina060981** [comment]
This feature is realized
Merged and closed

**Comment by monzug** [comment]
happy to say that it works. Thanks
