### ISSUE TITLE
Prevent from move all tokens from a segment

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#155]
>see #39 - Monica asked: is it ok to move all tokens out of a segment till it's empty (I can always move them back in)? I could not find anything in the issue, just wondering. it might be a no-issue at all.

Per discussion with @abrasax today, let's prevent the user from completely emptying a segment.

_Originally posted by @balmas in https://github.com/alpheios-project/alignment-editor-new/issues/149#issuecomment-772972130_

**Comment by irina060981** [comment]
This check is realized

Merge and closed

**Comment by monzug** [comment]
this is fixed. However I can still have an empty segment if I move all words to the next segment, except for the last one which I cannot move but I can delete or by deleting all words in a segment. @balmas question for you

**Comment by balmas** [comment]
I think we should not allow an empty segment by any means.

**Comment by irina060981** [comment]
It is easy to fix - I will add a check for empty segment for delete token
It is good to have a testing stage :)
