### ISSUE TITLE
Upload tsv file in origin or target text, text source type changes to TEI

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#157]
I am getting an error on alignment due to TEI checked instead of Text. to repro:
upload an origin and target tsv file, the souce type changes from text to TEI and the alignment fails with an error. if I change back the source type to Text it works fine. 

see attachment
![Screen Shot 2021-02-05 at 2 24 58 PM](https://user-images.githubusercontent.com/41396793/107039668-7c318780-67be-11eb-80d2-8bf556bf1104.png)

**Comment by monzug** [comment]
see content of tsv files
![Screen Shot 2021-02-05 at 2 31 52 PM](https://user-images.githubusercontent.com/41396793/107040006-ef3afe00-67be-11eb-8861-f10a1e7e38c4.png)

**Comment by irina060981** [comment]
This error is because you are sending plain text, but point that it is TEI.
The tokenizer tells you, that he couldn't find tags :)

**Comment by monzug** [comment]
right. but it's the application that switches the Text to TEI not me!

**Comment by monzug** [comment]
interesting, somehow some of the downloaded files with filetype tsv get uploaded as source type TEI.

**Comment by monzug** [comment]
Unfortunately I deleted the ones that I used in the above example and I am not able to reproduce the TEI issue with new ones. Keep trying...

**Comment by monzug** [comment]
I can only think that somehow the TEI field was checked when I downloaded the text files newly created. the question is when is TEI option sticky?????

**Comment by irina060981** [comment]
There are no rules for auto check fpr sourceType.
The only way is change it not manually - is to upload file where sourceType = TEI
For example you sent me a file 
```
HEADER: 1	ltr	eng	tei
Cui  dono  lepidum  novum  libellum  
arido  modo  pumice  expolitum  ?  
Corneli  ,  tibi  ;  namque  tu  solebas  
meas  esse  aliquid  putare  nugas  ,  
iam  tum  cum  ausus  es  unus  Italorum  
omne  aevum  tribus  explicare  chartis  ,  
doctis  ,  Iuppiter  ,  et  laboriosis  !  
quare  habe  tibi  quidquid  hoc  libelli  
qualecumque  ,  quod  ,  o  patrona  virgo  ,  
plus  uno  maneat  perenne  saeclo  .
```

you could see that TEI is defined in the first row

**Comment by irina060981** [comment]
@monzug , do you have anything else unclear here?

**Comment by monzug** [comment]
Thanks Irina. yes, it's all clear but I still need to do some testing. I'll take this one back.

**Comment by monzug** [comment]
I saw again a text file saved as tei. Unfortunately I did not save it.

**Comment by irina060981** [comment]
May be the following could help:
Source type options are saved to browser storage.
For example:
You worked with TEI texts (sourceType = TEI was saved to browser storage) - then reload the page or open it on the next day.
It would have TEI as default (saved from previous session) - you worked with text as sourceType=text and thought that text type is selected, because you didn't reselect. 
Could it be this way?

**Comment by monzug** [comment]
yes, it could be. I have seen it yesterday again but I thought it was a cut
and paste from an other browser window.

**Comment by monzug** [comment]
I found a reproducible scenario. 
1) upload xml file in origin and target text and do an alignment
2) clear text
3) Tei is still checked after clear text. 
4) enter text in origin and target text, then align
5) I'll get the 400 error and "Origin source text was not tokenized due to the errors in tokenization service. All tokenization results were cancelled".

if it's not a big deal (considering all you have in your plate), maybe we should check for text as default after a clear text. super low priority. @irina060981 Irina, what do you think?

**Comment by irina060981** [comment]
It is not very easy task - because I would need to create an exception for the logic - all settings are saved in localStorage.
Let's postpone it for the moment when we would have more time for this

**Comment by monzug** [comment]
agree. postponed.

**Comment by monzug** [comment]
this is not longer reproducible after changes in workflow, including issue #280
