### ISSUE TITLE
Token identification - remove dependency from text type

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#16]
re prefix-id - I think it's not being used anyway, but just to point out that we should not make any assumptions about how the location of the text on the display corresponds to the text identifier. 

We probably need to avoid using location of the token in the text as the identifier, because we need to allow the user to edit the initial tokenization results in case they are incorrect. This would require a renumbering of all the tokens. We need to keep track of the location of the tokens, but that probably needs to be a separate property from the unique identifier of the token.

From https://github.com/alpheios-project/alignment-editor-new/pull/10

**Comment by balmas** [comment]
see alpheios-project/documentation#43 for discussion of PIDs

**Comment by irina060981** [comment]
I have defined tokens the following way:
<№ text>-<№ segment>-<№ token>

Origin is always - 1
Targets are - 2-...

This way each token has a unique ID.

@balmas, do you see here any useful change? Or Token ID would stay as-is?
Should I do anything else within this issue?

**Comment by balmas** [comment]
I think this is fine.
