### ISSUE TITLE
Disable "add line break after the token" for last word in a segment

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#166]
in build Alpheios Translation Alignment editor 1.0.1 (build development.20210208207), the "Add line break after the token" is enable but when I click on it, it does not add a line break as it's last word. it does activate the "Remove line break after the token", which also does not do anything. would it be possible to disable "add line break after the token" when it's the last word of a segment?

**Comment by irina060981** [comment]
Agree - missed this case - will fix

**Comment by irina060981** [comment]
This check is added
Merged and closed

**Comment by monzug** [comment]
fixed in Alpheios Translation Alignment editor 1.0.1 (build development.20210209354)
