### ISSUE TITLE
Prevent from deleting all tokens in a segment

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#168]
this is fixed. However I can still have an empty segment if I move all words to the next segment, except for the last one which I cannot move but I can delete or by deleting all words in a segment. @balmas question for you

_Originally posted by @monzug in https://github.com/alpheios-project/alignment-editor-new/issues/155#issuecomment-775156893_

**Comment by irina060981** [comment]
I think we should not allow an empty segment by any means.

@monzug this might not be critical for the demo though, so it would probably be fine to just make sure there is an issue to fix it at some point.

_Originally posted by @balmas in https://github.com/alpheios-project/alignment-editor-new/issues/155#issuecomment-775461186_

**Comment by irina060981** [comment]
The check is added
merged and closed

**Comment by monzug** [comment]
Thanks Irina. fixed in Alpheios Translation Alignment editor 1.0.1 (build development.20210209354)
