### ISSUE TITLE
Fix bug - tooltips are all upper case

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#171]
>Tooltips are all upper case. any reason why all words upper case? 

It is because of styles mix - would fix it

_Originally posted by @irina060981 in https://github.com/alpheios-project/alignment-editor-new/issues/62#issuecomment-773894926_

**Comment by irina060981** [comment]
Styles are fixed
![image](https://user-images.githubusercontent.com/12377640/107330391-3695f700-6afd-11eb-8b59-99bbfd83dd2d.png)

Merged and closed

**Comment by monzug** [comment]
OK. Alpheios Translation Alignment editor 1.0.1 (build development.20210209354)
