### ISSUE TITLE
Different error when uploading from top menu or from origin text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#175]
Upload a csv file saved from Ugorit app in Origin text. I get the following error:
Json file doesn't have all obligatory fields. Source Text won't be created.
Upload the same file from Upload in top menu, the error is the following:
There is no data in file to upload

Maybe a more generic message in both cases, such as:
The file doesn't have all the required fields. Text won't be created.

![Screen Shot 2021-02-09 at 3 22 53 PM](https://user-images.githubusercontent.com/41396793/107376931-bb2b4a00-6aea-11eb-95e3-9fd3d1cb53fb.png)

**Comment by monzug** [comment]
file is the following
[ugarit-Translation-pairs-1612878769270.csv.zip](https://github.com/alpheios-project/alignment-editor-new/files/5951934/ugarit-Translation-pairs-1612878769270.csv.zip)

**Comment by irina060981** [comment]
Unified the error is done
Merged and closed

**Comment by monzug** [comment]
The file doesn't have all the required fields. Text won't be created.
