### ISSUE TITLE
Add some description/tooltip for multivalued metadata terms

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#177]
After on-line meeting:

We need to add some instructions how to handle with multivalued metadata terms.

**Comment by irina060981** [comment]
Done 
![image](https://user-images.githubusercontent.com/12377640/108468090-f2abaa80-72d1-11eb-9c3c-5004226c1e25.png)

**Comment by monzug** [comment]
Great! just a couple of words that need to be updated for consistency: 
Contributed should be Contributor (same as field name)
"would be saved" maybe will be saved or should be saved
is it single value or single valued?

**Comment by irina060981** [comment]
>Great! just a couple of words that need to be updated for consistency:
Contributed should be Contributor (same as field name)
"would be saved"- how about "will be saved" or "should be saved"?
is it single value or single valued?

thank you, Monica, for the language edits - it is always a strees for me to write instructions in English for persons who's prefession is a language :)
Will update

**Comment by monzug** [comment]
hahaha, same for me!!!! You do a great job, believe me!

**Comment by irina060981** [comment]
The text is updated

**Comment by monzug** [comment]
Irina, sorry to be such a pain but if we say multivalued metadata then it should be single valued metadata (in two location).

**Comment by irina060981** [comment]
ok - would change - thank you for your attentition here :) don't want to be fynny for our users with texts :)

**Comment by irina060981** [comment]
Instructions are fixed

**Comment by monzug** [comment]
Thanks - tested in Alpheios Translation Alignment editor 1.0.2 (build development.20210224195)
