### ISSUE TITLE
sentence view and short view not currently working 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#188]
see #70
in latest build Alpheios Translation Alignment editor 1.0.1 (build development.20210212294), the html output does not work in sentence view and short view when text has segments. Output is visible only in full view.

full view
![Screen Shot 2021-02-12 at 5 09 18 PM](https://user-images.githubusercontent.com/41396793/107792172-1bbdbf80-6d55-11eb-863b-6acec9bc3de6.png)

short view
![Screen Shot 2021-02-12 at 5 09 30 PM](https://user-images.githubusercontent.com/41396793/107792208-25472780-6d55-11eb-8bf6-5c90daa0916c.png)

**Comment by irina060981** [comment]
I found the bug and fixed

**Comment by monzug** [comment]
Irina, Thanks. Now it works!!! However if the sentence is short like in my test file, the language bars in short view are  cropped.
see attachment

![Screen Shot 2021-02-14 at 9 04 31 AM](https://user-images.githubusercontent.com/41396793/107871650-dfe54000-6ea3-11eb-9c19-22636512c735.png)

**Comment by monzug** [comment]
Note that this effects only the origin side of the html output. see attachment
![Screen Shot 2021-02-14 at 9 08 03 AM](https://user-images.githubusercontent.com/41396793/107871711-4ec29900-6ea4-11eb-8cc7-2fc5addcfe92.png)

**Comment by irina060981** [comment]
Fixed style bugs

![image](https://user-images.githubusercontent.com/12377640/107920126-27f58700-6fb8-11eb-9dd4-8821bda179cc.png)

![image](https://user-images.githubusercontent.com/12377640/107920145-2fb52b80-6fb8-11eb-9063-f9df93998c3d.png)

![image](https://user-images.githubusercontent.com/12377640/107920165-3a6fc080-6fb8-11eb-8258-aea51d6d0e0f.png)

**Comment by monzug** [comment]
Irina, would it be possible to rearrange the view to have the origin text in the half page and the translations in the other half, like in Full view? right now both in sentence view and short view, the origin text takes more than half of the view and the translated text have a small portion of it. see screenshot

![Screen Shot 2021-02-15 at 2 47 36 PM](https://user-images.githubusercontent.com/41396793/107955300-e821a600-6f9d-11eb-8e2e-ebea4c8c683f.png)

**Comment by irina060981** [comment]
>Irina, would it be possible to rearrange the view to have the origin text in the half page and the translations in the other half, like in Full view? right now both in sentence view and short view, the origin text takes more than half of the view and the translated text have a small portion of it. see screenshot

Yes, I could if you think, that it would be more consistent. 
And I see on your screen that target part was cropped - I would check it.

**Comment by irina060981** [comment]
I have rearranged the sentence view (50/50), added some scroll improvements

**Comment by monzug** [comment]
uhm, scrolling is not the best. it does jump up and down the text a little. you can test yourself with this file
![Uploading Screen Shot 2021-02-16 at 4.15.03 PM.png…]()

**Comment by monzug** [comment]
uhm, scrolling is not the best. it does jump up and down the text a little. when scrolling in a segment, also the all page slides up or down. try scrolling the 4th sentence.
you can test yourself with this file

**Comment by irina060981** [comment]
@monzug , I found the bug in scrolling when we have several targets and fixed it.
But I din't understand - what do you mean saying jump up/down.

I have made a video with your file json - and record how I see the scrolling.
If you will see it other way - I would need some details - browser, how much tabs did you have - may be it is some lag in browser. I would try to reproduce it.

Here it is the video - https://www.dropbox.com/s/t0d33vewq910o1m/Alignment%20Editor%20scroll%20-%201.mp4?dl=0

**Comment by monzug** [comment]
I am sorry I forgot to mention that it's in Safari/Mac (BigSur). I am doing much of testing on this browser as it's more likely I am going to find problems. I confirm that sentence view and scrolling work ok in Chrome and Firefox on MAC. as per the Safari scrolling, I would keep as is. I do not think we have many users so I would not bother for the moment.
