### ISSUE TITLE
Suggestion for sentence view

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#194]
see issue #70 .
Sentence view gives the ability to display the sentence in which an actual match occurs plus the sentences around.
Right now, we have a drop down with the option 0 equal to current sentence, +1, +2.. sentences up the current word, -1, -2... sentences down the current word.
I haven't been able to test the -1, -2 option yet as it does not work for me, however I was suggesting to simplify the drop down, as follow:
current sentence
1 sentence around (including before and after) and (if  you think it's necessary),
2 sentences around (including before and after) and that's all. if the user wants to see more text, there is always the Full view option.

**Comment by irina060981** [comment]
@monzug , it works as you described.
It shows the amount of sentences before and after.

![image](https://user-images.githubusercontent.com/12377640/108034166-d533d200-7080-11eb-9907-be1323382abc.png)

![image](https://user-images.githubusercontent.com/12377640/108034193-dfee6700-7080-11eb-9edb-08c064357c7b.png)

![image](https://user-images.githubusercontent.com/12377640/108034205-e67cde80-7080-11eb-8496-d0d2cd466102.png)

![image](https://user-images.githubusercontent.com/12377640/108034220-eed51980-7080-11eb-82f4-313abaca1420.png)

![image](https://user-images.githubusercontent.com/12377640/108034243-f4cafa80-7080-11eb-8278-274ac8eb4f7a.png)

Amount of sentence with minus do nothing.
I would limit it to be greater then null always.

**Comment by monzug** [comment]
Great. Can we talk on the call about limiting to only 0 and 1 in which case
it means 1 sentence above and one below the selected word? Thanks

**Comment by irina060981** [comment]
Let's talk on the call - I would set a limit to >= 0 - to avoid uncorrect values.

**Comment by irina060981** [comment]
Limit is set - sentenceCount could be >= 0

**Comment by monzug** [comment]
works as described with no upper limit at the moment.
