### ISSUE TITLE
Metadata is not currently displayed in HTML output, should it be?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#195]
I thought I did enter a comment in some issue or maybe not. anyhow, do we want to support metadata in HTML output or not?
Right now, we have a line in the translated text but not in the origin and not in full view, only in sentence or short view. 
maybe smaller font for metadata?
see screenshot in sentence view

![Screen Shot 2021-02-15 at 3 57 24 PM](https://user-images.githubusercontent.com/41396793/107962791-ac8bd980-6fa7-11eb-8a8a-d9968c9462e0.png)

and in short view

![Screen Shot 2021-02-15 at 4 07 36 PM](https://user-images.githubusercontent.com/41396793/107963188-202de680-6fa8-11eb-85dd-89a2d5973749.png)

**Comment by monzug** [comment]
also, why does sometimes the order of metadata go from date of copyright to publisher? see below

![Screen Shot 2021-02-15 at 5 09 30 PM](https://user-images.githubusercontent.com/41396793/107969966-caaa0780-6fb0-11eb-8814-05a88153692e.png)
![Screen Shot 2021-02-15 at 5 09 44 PM](https://user-images.githubusercontent.com/41396793/107969976-d0075200-6fb0-11eb-93ed-8330016b73ea.png)

**Comment by monzug** [comment]
I think it should be Copyright date, right?

**Comment by irina060981** [comment]
For now I have requirements for showing metadata only in target in short and sentence view.
Let's ask on the call - should I place somewhere (and where) metadata information for origin and target in full view

**Comment by irina060981** [comment]
>also, why does sometimes the order of metadata go from date of copyright to publisher? see below

Oh, I didn't place any order here - it is saved by the order the values were saved.
Would add the order for better consistency.

**Comment by irina060981** [comment]
Sorting for metadata in HTML Output is done

**Comment by monzug** [comment]
Please update Copyright Date too.

**Comment by irina060981** [comment]
>Please update Copyright Date too.

Done

**Comment by irina060981** [comment]
Adding metadata to origi and full view would be tracked via https://github.com/alpheios-project/alignment-editor-new/issues/213

**Comment by monzug** [comment]
tested in FF/Mac and Safari in Alpheios Translation Alignment editor 1.0.2 (build development.20210219298) 
Copyright Date has been updated. Thanks
The order is still confusing to me. Right now, I added a number to each field that was populated from top to bottom, However, I've noticed that in Origin text, the Identifier is displayed as last and  in Target text, the Copyright Date is between the Creator and the Contributor. Question: are you sorting based of importance or by field inputs (e.g. field 1, field 2. field 3 etc)?

![Screen Shot 2021-02-22 at 2 01 29 PM](https://user-images.githubusercontent.com/41396793/108714504-e6b22980-7519-11eb-936c-6b8d312f672e.png)

**Comment by irina060981** [comment]
The sorting is the following:

1 Title
2 Creator 
3 Copyright Date
(this 3 fields was defined as main on the previous meeting)

4 Contributor
5 Publisher
6 Source
7 Description
(this is unchanged - the same order as in metadata panel)

8 Identifier
(this is the last as the most technical one)

**Comment by monzug** [comment]
Could it be a side effect of the fix for #224? Metadata entries are not saved except for Creator and Contributor and these are the only two entries displayed in HTML output out of the eight that I entered. Looking at the json file, I confirm that none of the entries was saved except for Creator and Contributor.

![Screen Shot 2021-02-23 at 3 09 06 PM](https://user-images.githubusercontent.com/41396793/108855296-24ca4e80-75e9-11eb-908b-701b2694434d.png)

**Comment by irina060981** [comment]
Yes, @monzug , you are right - it was a bug afeter my changes, I am sorry.
Now it is fixed.

**Comment by monzug** [comment]
No problem at all. will check asap.

**Comment by monzug** [comment]
Metadata is saved in HTML output. As per discussion, metadata is saved only once at the top of the page and that's what is correctly doing. However, I noticed that we have the block separator with same size as the top which has metadata and Language info. what about shrinking it to a line. Have you tried this?

![Screen Shot 2021-03-04 at 2 23 41 PM](https://user-images.githubusercontent.com/41396793/109970808-c93d4680-7cf5-11eb-9b19-3d6d289705f7.png)

**Comment by irina060981** [comment]
@monzug , I think it is a good idea

- reduced empty lang bar height
- updated paddings

![image](https://user-images.githubusercontent.com/12377640/110081900-59ec5300-7dd8-11eb-814c-dbe00797b4b6.png)

**Comment by monzug** [comment]
Looks great in Alpheios Translation Alignment editor 1.2.0 (build development.20210305347)
