### ISSUE TITLE
Display issue of the Target text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#197]
We had this issue before but it's happening today again in Alpheios Translation Alignment editor 1.0.2 (build development.20210215390).
The Edit tokens in Target texts is not visible . see screenshot

![Screen Shot 2021-02-15 at 4 02 43 PM](https://user-images.githubusercontent.com/41396793/107970685-b9152f80-6fb1-11eb-92da-1de709eb6368.png)

**Comment by monzug** [comment]
this is a sample file 
[alignment-ita-eng.tsv.zip](https://github.com/alpheios-project/alignment-editor-new/files/5983749/alignment-ita-eng.tsv.zip)

**Comment by irina060981** [comment]
I found the bug - it is reproduced after Clear texts.
this bug is fixed now.

**Comment by monzug** [comment]
oh, I do always use clear text. this must have been a new thing.

**Comment by irina060981** [comment]
>oh, I do always use clear text. this must have been a new thing.

yes it is a mixed of clear text and lazy render of tokens editor :)

**Comment by monzug** [comment]
fixed in Alpheios Translation Alignment editor 1.0.2 (build development.20210216353)

**Comment by monzug** [comment]
fixed in Alpheios Translation Alignment editor 1.0.2 (build development.20210216353)
