### ISSUE TITLE
Sentence = 0 shows just a portion of a sentence

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#212]
While testing #188, I come across this scenario: 
have a word in Origin text aligned with its translation in two different sentences.
select sentence view = 0, the sentence view around the second translation does show only a portion of the sentence not the full sentence. see screenshots

full view: Italian word "forse" has two translation "English" and "obvious"

![Screen Shot 2021-02-17 at 3 48 10 PM](https://user-images.githubusercontent.com/41396793/108222050-b55fe500-7138-11eb-9bd5-ca70df5ea7ed.png)

sentence view = 0  (only a portion of the sentence with "obvious" is displayed)

![Screen Shot 2021-02-17 at 3 49 08 PM](https://user-images.githubusercontent.com/41396793/108222647-446cfd00-7139-11eb-8845-600a3395cb31.png)

sentence view =1 (two full sentences are shown)

![Screen Shot 2021-02-17 at 3 47 21 PM](https://user-images.githubusercontent.com/41396793/108221707-61550080-7138-11eb-9751-66d5e32dfbe2.png)

Irina, I was expecting that in case of sentence =0 it would show two sentences: one around the word "English" and one around the word "obvious". In case of sentence =1, the same view as we do only have two sentences in the segment. 

Also, in the same example, there is a truncation of the sentence view in the target text when I switch from "combina" and "combinare" in the last segment. If sentence view is =1, switching from one word to the other, the sentence view for "combinare" is truncated and does not show  "negative  qualities  and  behaviors  ." (which happens to have one of the aligned word).

![Screen Shot 2021-02-17 at 4 16 51 PM](https://user-images.githubusercontent.com/41396793/108224804-96af1d80-713b-11eb-838b-4d82ac5a9582.png)

**Comment by irina060981** [comment]
I didn't care of the case when tokens could be separated to different sentences - would fix it.

**Comment by irina060981** [comment]
The workflow is updated
![image](https://user-images.githubusercontent.com/12377640/108343430-aad04900-7227-11eb-87d0-812870174d1b.png)

![image](https://user-images.githubusercontent.com/12377640/108343462-b4f24780-7227-11eb-86f6-e6c011ed0864.png)

**Comment by monzug** [comment]
Giving second thoughts, it might be a very unlikely user situation. Thanks for taking a look. Anyhow, it doesn't work properly.
sentence = 0 should show the sentence in which each words is in. sentence = 1 should add more sentences around the aligned word. 
Considering that it might not be a real user situation (Harry talked about a word with multiple translation so I tested it but I am not sure what he meant with multiple translations. I might have got all wrong). after all, the meaning of alignment is to arrange in a line. If it is too complicated to fix it, just reverse it as it was before. it was working better than what it is at the moment. ok?

see below, with sentence = 0, I have to many sentences on the target side.

![Screen Shot 2021-02-22 at 4 46 55 PM](https://user-images.githubusercontent.com/41396793/108732971-58946e00-752e-11eb-8cd0-16a38a9552af.png)

**Comment by monzug** [comment]
Giving second thoughts, it might be a very unlikely user situation. Thanks for taking a look. Anyhow, it doesn't work properly.
sentence = 0 should show the sentence in which each words is in. sentence = 1 should add one more sentence around the aligned words. 
Considering that it might not be a real user situation (Harry talked about a word with multiple translation in a sentence so I tested it but I am not sure what he meant with multiple translations. I might have got all wrong.) After all, the meaning of alignment is to arrange in a line. If it is too complicated to fix it, just reverse it as it was before this last fix. It was working better than what it is at the moment. ok?

see below, with sentence = 0, I have too many sentences on the target side. I should only have 2 sentences, one for each translated word.

![Screen Shot 2021-02-22 at 4 46 55 PM](https://user-images.githubusercontent.com/41396793/108732971-58946e00-752e-11eb-8cd0-16a38a9552af.png)

**Comment by irina060981** [comment]
It is rather a difficult question - what should be considered a translation here.
I thought that the whole group is a translation. 
That's why we need the whole context between translation parts.

But from your answer - a user could look at this as several different translations for the one word inside the same text?
Am I right?

**Comment by irina060981** [comment]
May be it is better to discuss this question with Bridget and Harry and come to some final solution - how should context be arranged here (I believe we need sentences as a context here)/
@monzug , what do you think?

**Comment by irina060981** [comment]
it was decided to leave the current workflow on the online meeting:
if a single translation group is spread over several sentences, than all words (sentences) between the first word and the last in the group would be shown in a sentence mode

**Comment by irina060981** [comment]
@monzug , I think you could add verified here?

**Comment by monzug** [comment]
Verified in Alpheios Translation Alignment editor 1.2.1 (build development.20210308383) - we do display the alignment group between the first and the second match as decided in the call-
