### ISSUE TITLE
HTML output should show Metadata for Origin text too

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#213]
see #70 and #195
after last call, we said that HTML output should show Metadata for Origin text too at the top of the page.

**Comment by irina060981** [comment]
Done

![image](https://user-images.githubusercontent.com/12377640/108487216-be90b380-72ea-11eb-9067-deaa03768105.png)

![image](https://user-images.githubusercontent.com/12377640/108487253-c8b2b200-72ea-11eb-8500-197a27f63cfa.png)

![image](https://user-images.githubusercontent.com/12377640/108487289-d2d4b080-72ea-11eb-917d-984f8dfbdc8b.png)

**Comment by monzug** [comment]
tested in FF/Mac 
Metadata info are visible now also for the Origin text. I like the look in short view and sentence view, however, I found it too heavy in the Full view. Shall we discuss it at the call tomorrow? Thanks

![Screen Shot 2021-02-22 at 2 01 29 PM](https://user-images.githubusercontent.com/41396793/108712505-26c3dd00-7517-11eb-9bbd-9a83da18913d.png)

**Comment by irina060981** [comment]
>tested in FF/Mac
Metadata info are visible now also for the Origin text. I like the look in short view and sentence view, however, I found it too heavy in the Full view. Shall we discuss it at the call tomorrow? Thanks

@monzug, as our meeting would be skipped today - would we postpone this discussion to the next week?

**Comment by monzug** [comment]
Absolutely, as it's a visual bug, it's better to get everybody's feedback.
