### ISSUE TITLE
Metadata: words  in Creator or Contributor are saved by clicking on trash bin

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#224]
Just noticed in Alpheios Translation Alignment editor 1.0.2 (build development.20210219298), that when I first enter a word in the Creator and/or Contributor field and then click on the trash bin, the words are saved rather than deleted. if I download as json, the fields are populated at upload.
Note that bin works as expected in the following scenario: save a value under the input field, then click on it and then click on the bin icon, the field is empty.
an other weird behavior: if I move back a saved value to the input field, then I can only delete the value or update the value, but I cannot save it as is.

**Comment by irina060981** [comment]
>when I first enter a word in the Creator and/or Contributor field and then click on the trash bin, the words are saved rather than deleted.

It is a strange funny bug - would check later

**Comment by irina060981** [comment]
>an other weird behavior: if I move back a saved value to the input field, then I can only delete the value or update the value, but I cannot save it as is.

agree, it is weird - would check

**Comment by monzug** [comment]
Thanks

**Comment by irina060981** [comment]
Both bugs are fixed

**Comment by monzug** [comment]
this is fixed in Alpheios Translation Alignment editor 1.0.2 (build i226-sentence-view-bug.20210223418) 
tested in FF/Mac and Safari
