### ISSUE TITLE
Invalid Login: few issues

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#225]
Tested on FF/Mac and Chrome /Mac
1)  can't see the error message

![Screen Shot 2021-02-22 at 2 57 30 PM](https://user-images.githubusercontent.com/41396793/108722359-5b3d9600-7523-11eb-8d28-69c811155e8e.png)

2) if I close the login pop-up and go back to the Login page after the above error, there is a message about waiting while we are logging you in. in FF, I have a java script error

![Screen Shot 2021-02-22 at 2 58 04 PM](https://user-images.githubusercontent.com/41396793/108722288-482ac600-7523-11eb-87d1-2823994f48d5.png)

**Comment by monzug** [comment]
Also we have a Close button on the Login pop-up that we don't have in the release. Is this a new requirement?

**Comment by irina060981** [comment]
>can't see the error message

>Also we have a Close button on the Login pop-up that we don't have in the release. Is this a new requirement?

This window is from Auth0 support, may be there were some bugs with it

>if I close the login pop-up and go back to the Login page after the above error, there is a message about waiting while we are logging you in. in FF, I have a java script error

This error is from Auth0 support in `alpheios-components`

May be latter I would be able to check it

**Comment by monzug** [comment]
Also, we are missing the Sign in as Apple user. see screenshot of release login pop-up vs latest build

![Screen Shot 2021-02-26 at 8 38 06 AM](https://user-images.githubusercontent.com/41396793/109270420-46f0e600-780e-11eb-9672-40ecd50b262e.png)


![Screen Shot 2021-02-26 at 8 37 39 AM](https://user-images.githubusercontent.com/41396793/109270422-48baa980-780e-11eb-8624-64c317197567.png)

**Comment by irina060981** [comment]
on online-meeting was decided to disable login until  https://github.com/alpheios-project/embed-lib/issues/125
I would close this issue as we disable the feature completely for now.
