### ISSUE TITLE
Sentence view: how should it work?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#226]
related to #212 
I did align a Latin and Greek text for testing.
the first Latin line is "odi et amo" which is aligned with the following Greek text:  θεοὺς  μὲν  αἰτῶ  τῶνδ᾽  ἀπαλλαγὴν  πόνων   
I aligned odi with θεοὺς, et with μὲν, amo with αἰτῶ and there are 3 greek words left out.
With sentence view = 0, I would expect to see the sentence around the aligned word (but I could be wrong). in this case there is only one sentence (and no punctuation), so for each of the aligned words "odi", "et", "amo", I should get the same sentence (there is only one). Instead, I get only translated word with the 3 words left out. So, what should the logic be for sentence = 0 ? Not sure if this is broken because of #212 

see attachments:

![Screen Shot 2021-02-22 at 6 09 50 PM](https://user-images.githubusercontent.com/41396793/108745948-ff333b80-753b-11eb-8e41-96357f9b3897.png)

![Screen Shot 2021-02-22 at 6 10 01 PM](https://user-images.githubusercontent.com/41396793/108745978-05c1b300-753c-11eb-8eb4-3fb51ebc8f26.png)

![Screen Shot 2021-02-22 at 6 14 09 PM](https://user-images.githubusercontent.com/41396793/108746015-11ad7500-753c-11eb-8bde-24a143ed978d.png)

![Screen Shot 2021-02-22 at 6 14 20 PM](https://user-images.githubusercontent.com/41396793/108746026-170abf80-753c-11eb-8497-b11a2b88599c.png)

**Comment by irina060981** [comment]
Something is broken - will check

**Comment by monzug** [comment]
Thanks.

**Comment by irina060981** [comment]
The bug is fixed - thank you for catching this case

**Comment by monzug** [comment]
Yes! now it shows the full sentence. Thanks
