### ISSUE TITLE
Text not visible in segment block

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#234]
related to #67 
tested in FF/Mac and Safari in Alpheios Translation Alignment editor 1.0.2 (build development.20210224195) 

I uploaded a poetry file with short sentences of Greek text (Aeschylus, Suppliant Maidens) with English translation. Arrows are visible but I have to click on arrows several times before the text in the segment block is visible. see attachment

![Screen Shot 2021-02-24 at 2 35 08 PM](https://user-images.githubusercontent.com/41396793/109009299-a932d500-76ae-11eb-86fb-e186644a3019.png)

sample of the file that I used for testing 
[alignment-grc-eng.tsv.zip](https://github.com/alpheios-project/alignment-editor-new/files/6036372/alignment-grc-eng.tsv.zip)

**Comment by monzug** [comment]
Tested in Chrome/PC, same as above

**Comment by monzug** [comment]
an other example in FF/PC while testing the language support. see attachments:

1) Origin and Target text

![dutch-english](https://user-images.githubusercontent.com/41396793/109513463-207fb480-7a73-11eb-8d30-dc599cc14ee8.JPG)

2) alignment groups

![FF-PC](https://user-images.githubusercontent.com/41396793/109513510-2f666700-7a73-11eb-8a54-d649f06f15e0.JPG)

**Comment by irina060981** [comment]
The feature was disabled
I would close the issue as this feature would be redeveloped in future

**Comment by monzug** [comment]
retested in latest build Alpheios Translation Alignment editor 1.3.3 (build development.20210519.98) - as you can see, still not pretty

![Screen Shot 2021-05-26 at 4 21 10 PM](https://user-images.githubusercontent.com/41396793/119676825-74b1ef00-be3e-11eb-8217-c29eba33ce6a.png)

**Comment by irina060981** [comment]
@monzug , could you attach the download of such an example here - I will check later

**Comment by monzug** [comment]
an other one with indexDB

![Uploading Screen Shot 2021-06-18 at 2.49.20 PM.png…]()

**Comment by monzug** [comment]
![Screen Shot 2021-06-18 at 2 49 20 PM](https://user-images.githubusercontent.com/41396793/122563608-ad5f7580-d044-11eb-9940-d9dc959a0f0e.png)

**Comment by irina060981** [comment]
I have updated workflow for calculating max-height
Check on several examples.
This is your example http://thelatinlibrary.com/sha/pert.shtml

![image](https://user-images.githubusercontent.com/12377640/122665415-6612e980-d1ea-11eb-9267-e6e20f4be746.png)

**Comment by monzug** [comment]
fantastic. Thanks. will check on Monday

**Comment by monzug** [comment]
tested in FF and Chrome on Mac and PC and Safari. looks good.
texts used for testing http://thelatinlibrary.com/sha/pert.shtml and DTSAPI, Aeschylus, Suppliant Maidens.
