### ISSUE TITLE
DTSAPI: Arabic vocabulary too large, system is unresponsive

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#236]
see #77 
I did try to upload the Miscellaneous Arabic Texts, by selecting the Arabic Reading Lessons  passage 1 and 2. I did not know that passage 1 was the vocabulary. It took quite sometimes to upload and then I started getting the yellow system messages in FF and the tab was not responsive so I had to close it. Can we remove the Vocabulary from the Arabic Reading Lessons  as option to upload?

**Comment by balmas** [comment]
I have removed the arabic texts.

**Comment by irina060981** [comment]
Removed by Bridget
![image](https://user-images.githubusercontent.com/12377640/109236003-81608000-781a-11eb-8a45-060347fc34ec.png)

**Comment by monzug** [comment]
Arabic is all gone in Alpheios Translation Alignment editor 1.0.2 (build development.20210226340)
