### ISSUE TITLE
FF/Mac, the html output override the previously open tabs

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#237]
I have seen this only in FF/Mac, not on PC. When I open a html output file in FF browser, it does override all the previously open tabs of Alpheios. Any idea? a browser oddity?

**Comment by irina060981** [comment]
I think that this is a strange behaviour of FF on MAC, because one page couldn't make other tabs reload (for securiy reasons).
Will look at it with my own eyes :)

**Comment by irina060981** [comment]
I was not able to reproduce it with Firefox 86 + mac OS Catalina 10.15.7.
@monzug, May be it is a bug of your browser version?
Are you able to reproduce it with the laste version of Firefox?

**Comment by monzug** [comment]
I just tried again and had the same behavior: html output override all alpheios tabs. FF 86 + bigSur 11.2.1

![Screen Shot 2021-03-03 at 5 26 50 PM](https://user-images.githubusercontent.com/41396793/109837695-bbc88380-7c45-11eb-86a6-a0875fd7d4f4.png)

**Comment by monzug** [comment]
I just reinstall FF 86 from scratch and now it does open a new browser window, so there is no override. OK to close this one.
