### ISSUE TITLE
Logout clears all content in alignment editor

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#238]
see #72 
 
do an alignment group and then use the tools. Login and save few words in wordlist. At logout, the page is reloaded and the alignment groups and the Origin and Target texts are all gone. I was expecting that Logout would clear my wordlist but not the content in the alignment editor. Any good reason for such implementation?

**Comment by irina060981** [comment]
Yes, it is a well-known behaviour.
I would need to do some workaround about it.
Here are advices from @balmas 

```
As for the Logout, I agree this is less than optimal. This is one of the things that using the other Auth0 library, the SPA library, would probably resolve.  But I don't think I have the time to look into that.

As a workaround, you could try just removing the logout functionality, which I think might happen automatically if you just remove the LOGOUT_URL from the env-embed.js file.

If that doesn't work, then you might want to try to intercept the click handler on the Logout button and at least warn the user that they will lose their data. Or alternatively, disable the element altogether in a post-activation step on the embedded library. (e.g. see how we add extra handlers after activation via the alpheios-embed-support.js library in alpheios_nemo_ui).
```

**Comment by monzug** [comment]
Thanks for the explanation. Glad it has been taking care of.

**Comment by irina060981** [comment]
on online-meeting was decided to disable login until  https://github.com/alpheios-project/embed-lib/issues/125
I would close this issue as we disable the feature completely for now.
