### ISSUE TITLE
Add the Betamasaheft API to the DTS API upload

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#239]
from @balmas 
https://betamasaheft.eu/api/dts

**Comment by irina060981** [comment]
Betamasaheft API - DTS API - support is added:

![image](https://user-images.githubusercontent.com/12377640/109497762-43937e00-7ade-11eb-80ba-cda687af90a9.png)

There are several bugs with it (depends on the remote source):
- it shows totalItems much bigger than API returns
- links for Beta maṣāḥǝft Narrative Units (182) and Beta maṣāḥǝft Manuscripts (217) - are not available

When it would be fixed on the remote side - changes would be uploaded by API to our applications automatically.

**Comment by irina060981** [comment]
There is only one small problem with this API - our remote tokenizer returns empty result for tokens.
Would need changes via - https://github.com/alpheios-project/tokenizer/issues/36

**Comment by monzug** [comment]
I have problem with this API: it takes few minutes to display the first pop-up where I can select the units, then I get an error loading each unit.

![unable-dtsapi](https://user-images.githubusercontent.com/41396793/109503828-c1b53d80-7a68-11eb-81e9-af6b2318aa9b.JPG)

**Comment by monzug** [comment]
Also, can we remove the extra step when selecting  a book? e.g. Alpheios DTS API, then classical latin then Catullus, then Carmina (1) and then I have Carmina one more time.

**Comment by irina060981** [comment]
>one thing left to do: Can we remove the extra step when selecting a book? e.g. Alpheios DTS API, then classical latin then Catullus, then Carmina (1) and then I have Carmina one more time.

I skipped this step before, but this step is needed for Betamasaheft.
So such an upgrade is rather difficult - I would need to do some additional analysis - if I would have time - I woukd try to upgrade the adapter - to do 2 requests instead of one for such cases.

**Comment by irina060981** [comment]
>I have problem with this API: it takes few minutes to display the first pop-up where I can select the units, then I get an error loading each unit (Unable to get data from URL betamasaheft... etc)

This API are really slow and very dependent on traffic

**Comment by irina060981** [comment]
on the online meeting was decided to leave all steps as is

**Comment by irina060981** [comment]
@monzug - I think we could set Verified to the issue?

**Comment by monzug** [comment]
ok
