### ISSUE TITLE
DTSAPI: can we remove the digits after the language, the authors and the books?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#241]
tested in Alpheios Translation Alignment editor 1.0.2 (build development.20210226340) 
We do display now digits after the Greek and Latin Classic, after the authors and after each book. Would it be possible to remove these numbers? Thanks

![Screen Shot 2021-02-26 at 2 23 03 PM](https://user-images.githubusercontent.com/41396793/109305659-5a1baa00-783e-11eb-9a2e-b322c0000c15.png)

![Screen Shot 2021-02-26 at 2 25 14 PM](https://user-images.githubusercontent.com/41396793/109305750-77507880-783e-11eb-9268-abbfb00e2831.png)

**Comment by irina060981** [comment]
This numbers show how much children they have - I easily could remove them, but I decided that it would be useful for the user. @monzug , are you sure that this information is not useful?

**Comment by monzug** [comment]
they were not working properly when I took the screenshots above so I didn't know what these numbers were for. Now they display the correct number of children. Alpheios Translation Alignment editor 1.0.2 (build development.20210301379)  - see attachments

![Screen Shot 2021-03-02 at 12 28 38 PM](https://user-images.githubusercontent.com/41396793/109642336-21881300-7b53-11eb-9338-075e1d693bd8.png)
![Screen Shot 2021-03-02 at 12 28 48 PM](https://user-images.githubusercontent.com/41396793/109642339-22b94000-7b53-11eb-8485-cef73215f013.png)

**Comment by irina060981** [comment]
These digits completely depends on API, I think that Alpheios returns correct amounts but Betamasaheft - not

**Comment by monzug** [comment]
The screenshots above are all from alpheios API and you can see the differences between build development.20210226340 and build development.20210301379. If the numbers are correctly reporting the number of children, I am ok with displaying them. However if the numbers are incorrect, they can only add more confusion and in this case, I would rather see them removed.

**Comment by irina060981** [comment]
removed digits 
![image](https://user-images.githubusercontent.com/12377640/109786069-85483400-7c58-11eb-8214-9143579f85f0.png)

**Comment by monzug** [comment]
Thanks. digits are gone.
