### ISSUE TITLE
Language is sticky in the morphology pop-up

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#242]
Let's say I wrongly select Greek instead of Latin in the Origin text, before the alignment. After alignment, if I double click on a word I get the error that the resource is not found in the Greek database with the option to change the language to Latin. If I chose Latin instead of Greek, in the next double click the language will not change, it will still be Greek. Note that this works fine in the release.

![Screen Shot 2021-02-26 at 2 30 41 PM](https://user-images.githubusercontent.com/41396793/109306753-ea0e2380-783f-11eb-8aac-0a31099ad057.png)

**Comment by irina060981** [comment]
Yes, it is a normal behaviour for Alpheios Reading Tools in embeded library mode.
When you define language and direction for the source - they are saved and used for marking tokens.

Alpheios Reading Tools uses this inline mark up as a prior definition of the language and direction.

**Comment by monzug** [comment]
@balmas, @irina060981 should we do anything here (e.g. disable change language)?

**Comment by balmas** [comment]
I vote for allowing the user to change (correct) the language of a text in the alignment editor after tokenization.  At that point, it doesn't matter if it's different than the language used for tokenization, especially since it was wrong anyway.

**Comment by irina060981** [comment]
> I vote for allowing the user to change (correct) the language of a text in the alignment editor after tokenization. At that point, it doesn't matter if it's different than the language used for tokenization, especially since it was wrong anyway.

For now it is available step. But in future if we connect this to some database - it would lead to inconsistency, because language is an important property for tokenisation. We would need to store languages changes history.

**Comment by irina060981** [comment]
Added ability to change language (in text editor part) - changes would be automaticaly applied to alignment groups creation editor.

**Comment by monzug** [comment]
I did some preliminary testing and it worked. Need to work more on this issue.  @irina060981 pls feel free to assign to me if you are done

**Comment by irina060981** [comment]
Yes, I think that I finished with this issue - would be glad to get your final verification

**Comment by monzug** [comment]
It's not working at all in build Alpheios Translation Alignment editor 1.1.0 (build development.20210304395) - tested with chinese, arabic, latin and greek, language cannot be changed in the pop-up. Is there a problem with the build? I am pretty sure yesterday I saw it fixed but didn't have time to fully test it.

**Comment by irina060981** [comment]
I could change it in both links  (but I updated last changes to production today)
https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/alignment-editor/index.html
https://alignment.alpheios.net/

We have two environments - development and production
All my changes are uploaded to development first - https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/alignment-editor/index.html
And after you, @monzug , verifies - after coping some changes -  I update production - https://alignment.alpheios.net/

So I think you shouldn't check the production - it is already checked via development branch.

**Comment by monzug** [comment]
Got it! Thanks

**Comment by monzug** [comment]
I cannot change the language in the pop-up in Alpheios Translation Alignment editor 1.2.0 (build development.20210305347).

**Comment by irina060981** [comment]
Monica, I think we have some misunderstanding here.
I didn't update Alpheios Reading Tools - it is rather difficult to update priority there.

I realized the following workflow:

For example I set incorrect language for the target - Greek instead of Latin
![image](https://user-images.githubusercontent.com/12377640/110230077-14f02a00-7f5a-11eb-8d0e-36456cc7fcc9.png)

So when I lookup a word there - I get no correct results:
![image](https://user-images.githubusercontent.com/12377640/110230092-38b37000-7f5a-11eb-9648-dad2b0beccdf.png)

I need to update the anguage of the target text, I open Text source editor and change language there:
![image](https://user-images.githubusercontent.com/12377640/110230097-51238a80-7f5a-11eb-91fc-83447841c136.png)

![image](https://user-images.githubusercontent.com/12377640/110230100-57196b80-7f5a-11eb-94ff-2cd3e6ebfae5.png)

![image](https://user-images.githubusercontent.com/12377640/110230108-5d0f4c80-7f5a-11eb-9a89-e6403b148a03.png)

Let's try again to lookup a word:
![image](https://user-images.githubusercontent.com/12377640/110230131-7b754800-7f5a-11eb-9661-5fde9fc9f3a6.png)

@monzug, did you try this workflow?

**Comment by monzug** [comment]
this works. so we are not going to change the pop-up? if not, maybe we should disable the ability to change language from the dropdown. if possible I would "hide" the "Wrong language? Change to: ... "drop-down. do you think it's possibile without much effort to hide this message?

**Comment by irina060981** [comment]
>this works. so we are not going to change the pop-up? if not, maybe we should disable the ability to change language from the dropdown. if possible I would "hide" the "Wrong language? Change to: ... "drop-down. do you think it's possibile without much effort to hide this message?

I think that there is no ability to do it specially for Alignment Editor. 
Alpheios Reading Tools has this feature with Wrong language for a long time. And such a change would need to redefine the whole workflow for the cases when we have wrong language in html markup. This workflow is tested and realeased before.

I couldn't easily estimate how much time it could take - I think we should talk to @balmas first.

**Comment by irina060981** [comment]
@monzug , I created a separate issue for the autodetecting language (that we discussed on the meeting)
https://github.com/alpheios-project/alpheios-core/issues/639

may be we should finish with this one then?
or create additional issue for language workflow in alpheios-core repository?

what do you think?

**Comment by monzug** [comment]
I'll assign to myself to test when the new feature is implemented (alpheios-project/alpheios-core#639). Thanks.

**Comment by irina060981** [comment]
@monzug - this is ready for testing in https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/alignment-editor/index.html

**Comment by monzug** [comment]
tested in Alpheios Translation Alignment editor 1.3.1 (build development.20210319 83) 

I have Greek text that I saved as Latin. in the alignment group, language is latin (as I defined in the Origin language). If I double click on any Greek word, it will give me the option to change language by selecting Greek from drop-down. However, when I double click an other Greek word, I do have to select again Greek language from drop-down. Basically changing the language is not sticky. I am used to Alpheios where changing the language is sticky. see attachment

![Screen Shot 2021-03-26 at 3 17 50 PM](https://user-images.githubusercontent.com/41396793/112645993-5aac5e00-8e47-11eb-92c7-f062787c7277.png)

**Comment by irina060981** [comment]
Yes, changing language is not sticky.
When you change the language - you set the highest priority for once.
We discussed this on the meeting.

If you suggest not to do it once - we should set the rule - how long such priority is set.
Because after this priority is set - no other rules work - html markup or language detection.
@monzug , what do you think?

**Comment by monzug** [comment]
oh, I think I missed that at the meeting. well, in my testing I overuse the lookup so it's annoying to keep changing the language. On the other hand, if the user wants a more permanent solution, there is always the possibility to change the language in the Origin (or Target) language drop-down. Shall we ask Harry at the next meeting, just to make sure he is ok with this implementation? Thanks
otherwise this is verified for me.

**Comment by irina060981** [comment]
it would be solved in https://github.com/alpheios-project/alignment-editor-new/issues/302

**Comment by irina060981** [comment]
>- if defined language is unsupported - use default language (as it was before)
>- if a user chose another language it is used as priority without limitation for the page

@monzug , changes are implemented

**Comment by monzug** [comment]
I have Latin as Original language and Greek as Translation text, no matter what the default language is, Latin and Greek will be automatically detected. tested in Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210420322)
