### ISSUE TITLE
Safari login doesn't work in alignment editor

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#243]
tested in Alpheios Translation Alignment editor 1.0.2 (build development.20210226340)
When I login as an existing user or I sign up as a new user, I'll get the same error message in Safari - Version 14.0.3 (16610.4.3.1.4) BigSur - see attachment

![Screen Shot 2021-02-26 at 2 48 16 PM](https://user-images.githubusercontent.com/41396793/109308138-e54a6f00-7841-11eb-91c3-a5d28e81ab2a.png)

**Comment by irina060981** [comment]
on online-meeting was decided to disable login until  https://github.com/alpheios-project/embed-lib/issues/125
I would close this issue as we disable the feature completely for now.
