### ISSUE TITLE
Display option for HTML output - 3 columns

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#254]
A new display view for HTML output (similiar to Ugarit) - 3 columns,
or may be all targets in columns with ability to show hide additional columns

**Comment by monzug** [comment]
Tested in Alpheios Translation Alignment editor 1.2.2 (build development.20210310373)
color scheme is available also in alignment groups with more than 2 languages. 3 columns option is in. quick one: can we add the line separator between languages as we do in Full view?

![Uploading Screen Shot 2021-03-10 at 2.59.23 PM.png…]()

**Comment by irina060981** [comment]
border is added

**Comment by monzug** [comment]
Looks good. Thanks.

![Screen Shot 2021-03-12 at 3 36 16 PM](https://user-images.githubusercontent.com/41396793/110954667-0c786480-8349-11eb-910a-835b15406586.png)
