### ISSUE TITLE
Display option for HTML output - equivalence

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#255]
Add a new display view.
steps: 
 - left side -  origin text (similiar to all others views); right side is empty (similiar to word, sentence)
 - hover on a grouped word inside origin 
 - on target side shown - all alignment groups from target with groups that includes the same word in origin
 
 for example:
 alignment groups:
 
 |Origin           | Target         |
 | ------------- |:-------------:|
 | test text       | latin test text  |
 | test thing     | latin test thing   |
 | test word     | greek test word   |
 | other word     | greek other word   |
 
 Display view when hover `test` in origin, target would be the following
 |Origin           | Target         |
 | ------------- |:-------------:|
 | `test` text  test thing   test word other word  | latin test text (+metadata)  |
 |     | latin test thing  (+metadata)  |
 |      | greek test word  (+metadata)  |

**Comment by irina060981** [comment]
@monzug , @balmas , @abrasax - hope I understood the case correctly

**Comment by monzug** [comment]
with multiple results in the target text, correct?

**Comment by irina060981** [comment]
I added display view - equivalence (would be glad to feedback)

![image](https://user-images.githubusercontent.com/12377640/109961244-6f5c7100-7d35-11eb-8f65-9435a57116b6.png)

I hope I understood correctly - and view shows all target groups, but not all origin groups with this word.

- removed duplicated metadata and language name
 
![image](https://user-images.githubusercontent.com/12377640/109961298-856a3180-7d35-11eb-991c-06f1fa576962.png)

@monzug , I didn't find the issue where you wrote, that it would be good to make view less heavy without duplicating metadata.
But I remembered about that issue.

**Comment by monzug** [comment]
Thanks for removing the duplicated metadata and language.  now the HTML output is not evenly split in two parts, the origin is bigger than target. Is this intentional? see screenshot

![Screen Shot 2021-03-04 at 2 23 41 PM](https://user-images.githubusercontent.com/41396793/109971490-9e9fbd80-7cf6-11eb-81c4-952aa3157d80.png)

**Comment by monzug** [comment]
Basically it works like in short view but listing all the occurrences of the selected word.

**Comment by irina060981** [comment]
>now the HTML output is not evenly split in two parts, the origin is bigger than target. Is this ok? see screenshot

we have two types of layout:

full view and sentence view - 50% : 50% (many text in the target part)
short view and equivalence view - 70% : 30% (less text on target side)

So it looks as intended

**Comment by irina060981** [comment]
Юquestion 2

How about grouping the same results in one line with number of occurrences in parenthesis?
in the example below:
English
a (2)
Cre tor Big; circa 1324; Con but tor
Italian
questo (2)
questo e' un test; test creator; test 1876; test contributor; test publisher; test

I don't think that counting the same results is really needed, because it could have very similiar, rather similier and so on. I believe that additional analyzing of target here would be redundant from the application.

But I think - that it is worth to sort by target id and group by text.
Would try to do that

**Comment by irina060981** [comment]
>Basically it works like in short view, with the addition of listing all the occurrences of the selected aligned word in the translated text. Looks good to me. Good job, Irina.

thank you, Monica! :)

**Comment by irina060981** [comment]
>>English
a (2)
Cre tor Big; circa 1324; Con but tor
Italian
questo (2)
questo e' un test; test creator; test 1876; test contributor; test publisher; test

>I don't think that counting the same results is really needed, because it could have very similiar, rather similier and so on. I believe that additional analyzing of target here would be redundant from the application.

I looked at Harry's example and thought again - I believe you are right - it would be useful to collapse the same results

**Comment by irina060981** [comment]
Done
added grouping/collapsing for targets

![image](https://user-images.githubusercontent.com/12377640/110109576-5fa66080-7df9-11eb-8fff-2e31c49eb5fe.png)

![image](https://user-images.githubusercontent.com/12377640/110109595-66cd6e80-7df9-11eb-8b03-9dd2a65a8850.png)

![image](https://user-images.githubusercontent.com/12377640/110109640-75b42100-7df9-11eb-9ec6-a373ec17a53e.png)

![image](https://user-images.githubusercontent.com/12377640/110109724-8f556880-7df9-11eb-8787-f66826175620.png)

![image](https://user-images.githubusercontent.com/12377640/110109753-98ded080-7df9-11eb-8a9f-be1fdb6d75c3.png)

**Comment by monzug** [comment]
Fantastic. Thanks

**Comment by monzug** [comment]
Tested in Safari, Chrome and FF in Alpheios Translation Alignment editor 1.2.1 (build development.20210308383). it works as described.

![Screen Shot 2021-03-08 at 2 37 22 PM](https://user-images.githubusercontent.com/41396793/110328681-efc3f000-801b-11eb-855e-fcdfa0e484f1.png)
