### ISSUE TITLE
Unable to upload references as buttons are not visible

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#256]
Tested in Chrome and Safari on  Mac. Note that in FF, the buttons are always visible when scrolling the references page.
Upload DTSAPI text in Ancient Greek Sophocles Ajax Ajax or Hesiod Theogeny. When scrolling down through the 1402 references, to reach the Upload and Cancel buttons, it stops just at the last line of references, so the buttons are not visible.

![Screen Shot 2021-03-03 at 3 04 23 PM](https://user-images.githubusercontent.com/41396793/109823801-8c5f4a00-7c38-11eb-9472-193e338afa4f.png)

**Comment by monzug** [comment]
in Chrome and FF/PC it works fine.

**Comment by irina060981** [comment]
I was not able to reproduce the bug in Safari/Mac and FF/Mac
But I think the problem could be in the case that max-height of the modal window is rather big (600px).

I decreased it to 500px and I hope it should improve the visibility.

**Comment by irina060981** [comment]
<img width="688" alt="Screenshot 2021-03-04 at 10 20 44" src="https://user-images.githubusercontent.com/12377640/109890607-4b684380-7cd3-11eb-89ee-76e4c3930283.png">

<img width="658" alt="Screenshot 2021-03-04 at 10 21 01" src="https://user-images.githubusercontent.com/12377640/109890627-54591500-7cd3-11eb-9431-852aef3c71b6.png">

**Comment by monzug** [comment]
YES, in Safari and Chrome I can see the buttons now. tested in Alpheios Translation Alignment editor 1.1.0 (build development.20210304395)
I am still able to see the issue in alignment.alpheios.net version Alpheios Translation Alignment editor 1.1.0 (build dev.20210303352)

**Comment by irina060981** [comment]
>I am still able to reproduce this issue in alignment.alpheios.net, version Alpheios Translation Alignment editor 1.1.0 (build dev.20210303352). @irina060981 do you have to update this site?

Let's update - I think it is worth to do that
