### ISSUE TITLE
DTSAPI: Text is sticky in the loading pop-up

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#258]
Super minor issue: when uploading references, the sentence "There are two ways to upload passages:" is still visible in the loading pop-up.

see screenshot

![Screen Shot 2021-03-03 at 2 37 08 PM](https://user-images.githubusercontent.com/41396793/109835760-cbdf6380-7c43-11eb-95df-100821280a9e.png)

**Comment by irina060981** [comment]
oh - I missed that - will fix easily

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
fixed in Alpheios Translation Alignment editor 1.1.0 (build development.20210304395). Thanks
