### ISSUE TITLE
Update styles for grouped tokens in HTML Output

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#265]
from @abrasax 
Is not white possible- so that the highlighted box is not visible and any text that is aligned appears in black-  the way it does in the alignment editor after alignment?

**Comment by irina060981** [comment]
Done 
![image](https://user-images.githubusercontent.com/12377640/110088681-e569e200-7de0-11eb-877c-bdf4d32af00c.png)

**Comment by monzug** [comment]
verified.
