### ISSUE TITLE
tokenizing English does weird things with punctuation

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alignment-editor-new#269]
@monzug noticed that when you tokenize the English "can't" you get the unexpected tokens "ca" and "n't".

This is because the English language model for the tokenizer has extensive normalization features for English that we aren't taking into account. This is probably true for other languages as well.

The space token has a "norm" attribute which provides a normalized version of the token.
So for "can't"
it produces tokens:

[
 { text: "ca"
   norm: "can",
 },
 { text: "n't",
   norm: "not"
 }
]

So we have a choice here -- 
(1) we can use the normalized version of the text always, which in some cases will result in the user seeing tokens that are not exactly as the original text
(2) I can have the tokenizer return both the origina text of the token (as it sees it) and the normalized version, and in the alignment editor interface we could show the normalized version to the user somehow  (maybe in a tooltip ?)

It's an easy change to the tokenizer to include the normalized version in the output (of course it will duplicate the size of the response).  Or I could include it only if it differs from the original text. 

@abrasax @monzug and @irina060981 let's discuss on Tuesday.

**Comment by irina060981** [comment]
@balmas , ok - I think it is really a simplest solution :)

**Comment by irina060981** [comment]
Done

**Comment by monzug** [comment]
If I check the "Use language specific tokenizer for English" checkbox, then can't is split in two: ca  n't
see screenshot
![Screen Shot 2021-03-09 at 5 04 49 PM](https://user-images.githubusercontent.com/41396793/110500636-b3ff5800-80f9-11eb-9a77-1ab5f3cf8b80.png)

If I do not check the "Use language specific tokenizer for English" checkbox, then can't is not split: can't
see screenshot
![Screen Shot 2021-03-09 at 5 05 05 PM](https://user-images.githubusercontent.com/41396793/110500739-cf6a6300-80f9-11eb-8db6-0d97b93ad708.png)

**Comment by irina060981** [comment]
Yes, it is an expected behaviour

**Comment by monzug** [comment]
Thanks. Tested also in Latin and English with the option checked and unchecked. It worked as expected.

sample text used for testing (from Ovid):

In nova fert animus mutatas dicere formas
corpora ; di , coeptis (nam vos mutastis et illas)
adspirate meis primaque ab origine mundi
ad mea perpetuum deducite tempora carmen.
Mundi origo.
5
Ante mare et terras et quod tegit omnia caelum
unus erat toto naturae vultus in orbe,
quem dixere chaos : rudis indigestaque moles
nec quicquam nisi pondus iners congestaque eodem
non bene iunctarum discordia semina rerum.
10
nullus adhuc mundo praebebat lumina Titan,
nec nova crescendo reparabat cornua Phoebe,
nec circumfuso pendebat in aere tellus
ponderibus librata suis, nec bracchia longo
margine terrarum porrexerat Amphitrite;
15
utque aer, tellus illic et pontus et aether.
Sic erat instabilis tellus, innabilis unda,
lucis egens aer: nulli sua forma manebat,
obstabatque aliis aliud, quia corpore in uno
frigida pugnabant calidis, umentia siccis,
20
mollia cum duris, sine pondere habentia pondus.
