### ISSUE TITLE
Let the user change the order in which the translations appear and suppress some if necessary

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#274]
from @abrasax, Can we let the user change the order in which the translations appear and suppress some if necessary?

**Comment by irina060981** [comment]
The feature is realized:

- added languages list to the top (shown only if languages are more than 1)
![image](https://user-images.githubusercontent.com/12377640/111295394-0bbc3700-8697-11eb-9f1a-e09f90e9ae86.png)

![image](https://user-images.githubusercontent.com/12377640/111295426-137bdb80-8697-11eb-8a2c-6a5e39358212.png)

- items are draggable - and changes the language's order
- items could be shown/hidden - the languages would be hidden

![image](https://user-images.githubusercontent.com/12377640/111295835-900eba00-8697-11eb-96bf-e94088bcb4aa.png)
![image](https://user-images.githubusercontent.com/12377640/111295972-b2083c80-8697-11eb-8742-6424cb52eafe.png)
![image](https://user-images.githubusercontent.com/12377640/111296499-496d8f80-8698-11eb-94a1-54b756702704.png)
![image](https://user-images.githubusercontent.com/12377640/111296523-50949d80-8698-11eb-9b98-cc49f0c0a778.png)

**Comment by monzug** [comment]
Nice job, well done. will do more testing.

**Comment by monzug** [comment]
tested in Safari, Chrome and FF/Mac build Alpheios Translation Alignment editor 1.3.0 (build i274-translations-order-suppress.20210316359)

1) if I suppress all languages (did try with a html output of 3 and one of 4 languages), then I add them back, only the first two languages are added and shown in the output. the other languages are not visible and the language button is not selectable.
see screenshots

![Screen Shot 2021-03-16 at 3 21 29 PM](https://user-images.githubusercontent.com/41396793/111326493-e3b7de00-866c-11eb-8fa7-0db88ec5c86f.png)

![Screen Shot 2021-03-16 at 3 26 06 PM](https://user-images.githubusercontent.com/41396793/111326503-e4e90b00-866c-11eb-9e2e-97774013004e.png)

![Screen Shot 2021-03-16 at 3 31 02 PM](https://user-images.githubusercontent.com/41396793/111326509-e581a180-866c-11eb-85b1-c4a92f7ecd8c.png)

**Comment by irina060981** [comment]
>if I suppress all languages (did try with a html output of 3 and one of 4 languages), then I add them back, only the first two languages are added and shown in the output. the other languages are not visible and the language button is not clickable.
see screenshots

@monzug , thank you for the catch! Fixed it

**Comment by irina060981** [comment]
>Is there any reason why languages are in alphabetical order in the html output and not in the order that they have been added in the tokenization process? I can move them around to bring back the original order, still is there any good reason to follow the alphabetical order?

First I added for testing during development, and then I decided that it is a good upgrade :)
But you, Monica, and also @zfletch showed me that it is not so useful - I removed it.

**Comment by monzug** [comment]
tested in Chrome and FF/Mac,  build Alpheios Translation Alignment editor 1.3.1 (build development.20210317350) both fixed. Thanks
