### ISSUE TITLE
Tooltips for editor tabs

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#277]
Add tooltips to editor tabs links: language + metadata.
To editors and HTML Output

**Comment by irina060981** [comment]
Added tolltips for tabs links to

- alignment group editor
![image](https://user-images.githubusercontent.com/12377640/110628064-67497900-81ee-11eb-8d38-d54f4de0b796.png)

- tokens group editor
![image](https://user-images.githubusercontent.com/12377640/110628109-75979500-81ee-11eb-8c13-6e4c8e4decb2.png)

- to HTML output to full view
![image](https://user-images.githubusercontent.com/12377640/110628254-8ea04600-81ee-11eb-943c-be844688e6c6.png)

**Comment by monzug** [comment]
Perfect. To be picky, I would suggest to have the Language stand out more. Now it blends into the metadata. Also, we might want to show only the relevant fields of metadata such as  Title, Creator and Copyright Date. 
from issue #195 ,  the 3 most important are:
1 Title
2 Creator
3 Copyright Date

**Comment by irina060981** [comment]
- updated format to `<langname> - <metadata>`
- used short metadata format `<title>;<creator>;<date copyrighted>`

**Comment by monzug** [comment]
Thanks

**Comment by monzug** [comment]
tested in Alpheios Translation Alignment editor 1.2.2 (build development.20210311357). Looks good. Thanks
