### ISSUE TITLE
Align button is still available after tokenization

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#298]
Irina, I am still testing the error messages reported in #153. 
the first error in the list is  ALIGNED_CONTROLLER_NOT_READY_FOR_TOKENIZATION
"Document source texts are not ready for tokenization."
Shown when
 - not all parameters defined for the text (language, sourceType, direction, text)
 -  all texts are already tokenized
Comments:
Should not be ever shown, because Align button should not be available in these conditions.

so, I tested the scenario in which all texts are tokenized and the Align button is still available. so, two questions here:
1) why do we want to have the align button available after tokenization process? we should have it available only after adding new target.
2) if I click on Align, error message is generated in neither the alignment editor nor in the web log. 
see screenshot

![Screen Shot 2021-03-22 at 3 05 57 PM](https://user-images.githubusercontent.com/41396793/112002422-26bbfa80-8b20-11eb-8d46-d0a89201f07a.png)

**Comment by irina060981** [comment]
Yes - you are right it is not a right behaviour for availability definition.
Fixed

**Comment by monzug** [comment]
this is fixed in Alpheios Translation Alignment editor 1.3.1 (build development.20210329350)
