### ISSUE TITLE
Target texts is empty after json upload

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#301]
tested in Alpheios Translation Alignment editor 1.3.1 (build development.20210326330), Chrome and Safari

Upload a json file with 4 languages. The alignment groups and editor are populated with all 4 texts correctly. However the target texts for the second and third languages are empty. Is there any specific reason why we do not display the texts after the first one? space optimization?

see below the empty text for Italian language ( # 3 )
![Screen Shot 2021-03-26 at 2 39 30 PM](https://user-images.githubusercontent.com/41396793/112641727-ee2f6000-8e42-11eb-9ade-0a758dd406d7.png)

see below the alignment group populated by the Italian text ( # 3).
![Screen Shot 2021-03-26 at 2 39 52 PM](https://user-images.githubusercontent.com/41396793/112641763-f6879b00-8e42-11eb-9965-abc50d17b4b7.png)

**Comment by irina060981** [comment]
The bug is fixed

**Comment by monzug** [comment]
I have a question on this one. do you think that for space optimization would be better not to show the text? in this case, we could implement something in the UI.

**Comment by irina060981** [comment]
>I have a question on this one. do you think that for space optimization would be better not to show the text? in this case, we could implement something in the UI.

I have an issue with the following space optimization:

- add left sliding menu
- place there tabs for Text Editor, Alignment Groups Editor, Tokens Editor
- show only one tab at once 

I suggest to look at the results of this optimization and then to think about other ones

**Comment by monzug** [comment]
yes, agree.
