### ISSUE TITLE
Empty box in language pop-up

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#302]
tested in Alpheios Translation Alignment editor 1.3.1 (build development.20210326330) Chrome and Safari

when I double click on an unsupported language word, a pop-up is generated with the selected word and and message that says that ... was not found in our resources. Wrong language? Change to:  with a language drop-down.
there is an empty box below the search word. Was it supposed to be populated by a message such as "Lexical query produced no results"?

see attachment
![Screen Shot 2021-03-26 at 2 35 54 PM](https://user-images.githubusercontent.com/41396793/112643188-60ed0b00-8e44-11eb-8b4e-eb00ac24a750.png)

if I select Latin from drop-down, the following message is generated in the next pop-up:
![Screen Shot 2021-03-26 at 3 04 34 PM](https://user-images.githubusercontent.com/41396793/112643462-b0cbd200-8e44-11eb-9961-fabe01fb774d.png)

**Comment by irina060981** [comment]
There are two issues here:

- empty popup (Lexical query produced no results - is not rendered) - this is a bug - I would check it

- empty language select for unsupported language - it is a common workflow, I didn't change logic here. We need to give an user opportunity to change to any supported language - to set its priority. If you have some suggestions on this pont - feel free to give them to me

**Comment by monzug** [comment]
actually, I thought about it and was thinking to default to Latin. we should ask Harry and Bridget.

**Comment by irina060981** [comment]
>empty popup (Lexical query produced no results - is not rendered) - this is a bug - I would check it

This is fixed both in webextension (use last Release)
And in the Alignment Editor (https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/alignment-editor/index.html)

**Comment by irina060981** [comment]
Decided on the meeting:
 - if defined language is unsupported - use default language  (as it was before)
 - if a user chose another  language it is used as priority without limitation for the page

**Comment by irina060981** [comment]
>- if defined language is unsupported - use default language (as it was before)
- if a user chose another language it is used as priority without limitation for the page

@monzug , changes are implemented

**Comment by monzug** [comment]
Now if defined language is not supported, the default language is taken from Page language in Option

![Screen Shot 2021-04-21 at 2 14 33 PM](https://user-images.githubusercontent.com/41396793/115551921-fba60180-a2ab-11eb-97e3-596a3a21a3a4.png)

**Comment by monzug** [comment]
tested in FF 89 and in the morphological pop-up, the default language is taken from Page language in Option if defined language is not supported.
