### ISSUE TITLE
(TIR 19) Have an ability to add a target text to an existed alignment

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#31]
This is okay for now but note that it will have to change because the uses cases call for the ability to add in a new target text to an existing alignment at any point.

_Originally posted by @balmas in https://github.com/alpheios-project/alignment-editor-new/pull/28#discussion_r481313316_

**Comment by balmas** [comment]
And in this case (per https://github.com/alpheios-project/alignment-editor-new/pull/40#discussion_r503917857) , if the newly added text has the wrong number of segments it shouldn't clear out all of the alignment, just not allow the new text to be added.

**Comment by irina060981** [comment]
19.Must allow for input/upload of new translation texts once alignment has started (i.e. addition of a new target text)

**Comment by irina060981** [comment]
Discussed on the meeting:

if a user decides to add a new targetText when other texts are already tokenized, then the workflow would be the following:

- a user should go to the TextEditors block
- click add Target Text - at this moment Align Editors should be frozen
- upload a new Target Text
- click Align successfully (should go through checks - an equal amount of segments)
- at this moment a new TextEditorSingle should be frozen
- new tokenized segments should be added to align-editor

**Comment by irina060981** [comment]
Merged and closed
