### ISSUE TITLE
Download Full to json as only option

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#315]
I just noticed this in latest build with slide menu but it's reproducible in previous builds too.
The download option has only Full to json, when I add an empty target text.
is there any reason why we are missing the HTML output?

![Screen Shot 2021-04-06 at 3 39 40 PM](https://user-images.githubusercontent.com/41396793/113720087-94565200-96ee-11eb-9891-c41d060ffb7d.png)

**Comment by irina060981** [comment]
We have two download options - 
- full to json - is available before and after tokenization was done
- HTML - is available only after texts were tokenized

I believe in your case, texts were not tokenized ?

**Comment by monzug** [comment]
when I upload a json file with source texts, segments and alignment groups and I add a target text without tokenization. I can browse through the alignment groups or token groups and the download option will only have the Full to json available.  that's what I am puzzled with.

**Comment by irina060981** [comment]
I think that both points separately make sense :)

- there are reasons to prevent a user from downloading not fully tokenized text;
- there are reasons to allow users to continue to create alignment groups even if additional target is added but not tokenized;

But I see you think that it is incosistent behaviour.
@monzug , do you suggest to add some limits here? or otherewise to allow a user to download not fully tokenized text?

**Comment by monzug** [comment]
well, there is an inconsistency and I pointed that out. Let's think about
when a user would like to have an html output with the above scenario.

**Comment by irina060981** [comment]
>when a user would like to have an html output with the above scenario.

We download tokenized texts and alignment groups in HTML Output and don't use source texts there.
If I will add an ability to download HTML output with not-tokenized translations text then I would need to add a filter in the code to exclude it.

So from my point of view it is incorrect to allow to download HTML Output with untokenized parts.
A user should first tokenize all texts and then he/she could get a consistent HTML Output.
@monzug , what do you think?

**Comment by monzug** [comment]
There is something not quite right so let me spend more time testing this one. the point is that I have only full to json with alignment group editor.

**Comment by monzug** [comment]
After thinking and rethinking, I come to the same conclusion as Irina did, long before me.  From the user's point of view, it's ok to save a json file with an incomplete target language (in this case with empty text) to be completed later on. On the contrary the html output would not be of any use for the user.
