### ISSUE TITLE
Add Initial screen to the application

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#316]
from @abrasax 
We need to show first initial screen with the choice
- start new alignment (go to text input screen)
- resume previous alignment  [browse to upload]  (go directly to populated alignment screen)

Also it would be good to add embed video with some tutorial for Alignment Editor

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/113881747-0e2a3080-9800-11eb-849e-e273ae18b65c.png)

**Comment by monzug** [comment]
Super fast Irina! How can I see the video?

**Comment by irina060981** [comment]
It is implemented here - https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/alignment-editor/index.html
as usual

Video is not about the Alignment Editor for now - I would create it later

**Comment by monzug** [comment]
ok, so what am I supposed to see/test in the latest build?

**Comment by monzug** [comment]
ok, I cleared my cache and now I can see the new splashscreen!

**Comment by monzug** [comment]
if I choose the option resume previous alignment with a test file that works in previous versions (see file below), I am still left at the splash screen without any notification/error. Next, if if I click on Start new alignment, I can see the previous file been uploaded. Note that with an other sample file all went well. see the file that I used for the above scenario.

[06-04_14-59-full-alignment-ara-eng-Chinese-Azer-Burn.json.zip](https://github.com/alpheios-project/alignment-editor-new/files/6273176/06-04_14-59-full-alignment-ara-eng-Chinese-Azer-Burn.json.zip)

**Comment by irina060981** [comment]
Bug is fixed

**Comment by monzug** [comment]
fixed. Thanks

**Comment by irina060981** [comment]
>question: as the screen is meant as initial screen, is there a way to get rid of it after the initial use? if I clear text or reload the page I do always end up to the initial screen again (which I find annoying after a while). 

I could do this easily, but I am not sure that @abrasax meant this workflow. Let's ask him

> also, the tool menu is visible there after doing any alignment. see screenshot

Yes, it is visible - because after Alpheios Reading Tools are activated - we could see the toolbar. And I believe that we should not deactivate it each time texts are cleared. I think we already discussed it. @monzug , do you want to discuss it again on the meeting?

**Comment by monzug** [comment]
> > question: as the screen is meant as initial screen, is there a way to get rid of it after the initial use? if I clear text or reload the page I do always end up to the initial screen again (which I find annoying after a while).
> 
> I could do this easily, but I am not sure that @abrasax meant this workflow. Let's ask him.
> I asked in an email
> 
> > also, the tool menu is visible there after doing any alignment. see screenshot
> 
> Yes, it is visible - because after Alpheios Reading Tools are activated - we could see the toolbar. And I believe that we should not deactivate it each time texts are cleared. I think we already discussed it. @monzug , do you want to discuss it again on the meeting?

Absolutely not reason to bring that up again. it was just to say that there is an other reason not go back to the splash screen. I agree with Bridget that Clear Text should open the Text editor.

**Comment by irina060981** [comment]
from @balmas 
My votes:

1) Always have ClearText open TextEditor

2) Rename "Clear Text" to "New Alignment"

3) Remove the slide-in menu from the initial screen
4) Until we have the ability to save a user's work in between browser sessions (e.g. via indexdb and/or a connection to a remote db/system), then the initial screen should always be shown upon reload of the application in the browser.

**Comment by irina060981** [comment]
from @abrasax 

> 1. Always have ClearText open TextEditor
agreed

> 2. Rename "Clear Text" to "New Alignment"
agreed

> 3. Remove the slide-in menu from the initial screen
doesn't agree

> 4. Until we have the ability to save a user's work in between browser sessions (e.g. via indexdb and/or a connection to a remote db/system), then the initial screen should always be shown upon reload of the application in the browser.
agreed


I agree with Harry about saving menu on initial screen - it is not very attractive, but could be useful for advanced users

**Comment by irina060981** [comment]
Final changes are done:

> 1. Always have ClearText open TextEditor
> 2. Rename "Clear Text" to "New Alignment"

**Comment by monzug** [comment]
I do not see the changes in Alpheios Translation Alignment editor 1.3.2 (build development.20210412239), both in Chrome and Safari/Mac.

**Comment by irina060981** [comment]
@monzug , I am sorry - I didn't push the changes to the development branch - now they are pushed

**Comment by monzug** [comment]
yes, I can see it now in Alpheios Translation Alignment editor 1.3.2 (build
development.20210412682)
