### ISSUE TITLE
Rename origin to original and target to translation texts

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#321]
from @abrasax

**Comment by irina060981** [comment]
done

**Comment by monzug** [comment]
Irina, would it be possible to run a search for all the occurrences of origin and target texts and substitute with original and translation?
I found a couple of instances on this screenshot (Origin Language and Target Language)
![Screen Shot 2021-04-08 at 3 13 40 PM](https://user-images.githubusercontent.com/41396793/114033552-a9adb680-987d-11eb-89ae-148603af869e.png)

**Comment by irina060981** [comment]
>Irina, would it be possible to run a search for all the occurrences of origin and target texts and substitute with original and translation?

Everything that could be found with such search was already fixed. But some titles are made by calculations from textType variable (that is still origin/target). I tried to fix all such places, but this was missed. I am sorry.

**Comment by irina060981** [comment]
Fixed again

**Comment by monzug** [comment]
Thanks! haven't seen any other occurrences.
