### ISSUE TITLE
the token editor menu is overlapping the slide menu

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#322]
tested in Safari and Chrome/Mac. see screenshot

![Screen Shot 2021-04-08 at 3 41 52 PM](https://user-images.githubusercontent.com/41396793/114045508-5c831200-9888-11eb-831f-80b5ddf55321.png)

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
fixed. see screenshot

![Screen Shot 2021-04-09 at 4 46 10 PM](https://user-images.githubusercontent.com/41396793/114198147-4a21da80-9953-11eb-9062-21fea84db93b.png)
