### ISSUE TITLE
Update TextEditor to a new workflow

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#327]
from @abrasax 
[from Start a New Alignment button on initial screen]

    ENTER NEW TEXT

              paste in

              upload file [browse to choose file]

  (and then, depending on their choice, the rest of the screen displays either)

---------------------------------

(paste in)

        ORIGINAL TEXT                   [FIRST] TRANSLATION       
     
 
          [box]                             [box]
       paste original text               paste translation here
             here

     
      (after first translation box is filled the system asks) 

       Do you wish to add another translation?  or [FINISHED]

      (after "FINISHED"- system says)

      Alpheios thinks your original text is in x , and your translations
      are in y and z. If this is not the case, please correct them here:
      [(dropdowns) ]   

      When the languages are correct, press [ALIGN]

-------------------

(upload)

     ORIGINAL                                   TRANSLATION

     choose text  DTS                           choose text  DTS

    (initially no boxes appear,
    (filled box appears when text is chosen 
     - without need for upload arrow)

    (after first translation box is filled the system asks)

       Do you wish to add another translation? or [FINISHED]

      (after "FINISHED"- system says)

      Alpheios thinks your original text is in x , and your translations
      are in y and z. If this is not the case, please correct them here:
      [ ]

      When the languages are correct, press [ALIGN]

**Comment by irina060981** [comment]
from @abrasax 
I think we should probably make it possible for the usr to make a different text entry choice for original and translation. That suggests

ENTER TEXT

Original Text                                                                       Translation

-----box--------                                                                  ------box-------

type or paste in                                                               type or paste in

upload                                                                              upload

---------------------                                                               --------------------

where the choices of paste in or upload would appear in the boxes themselves or immediately below them. If they choose "type..." the box is simply cleared for input with the cursor inside and if they choose upload the "choose file" appears.

**Comment by irina060981** [comment]
from @irina060981 
I understood it the same way - original and each translation has its own choice:

- type/paste
- upload from file
- upload from DTS API

Next we try to define language, direction and texttype (text or tei) automatically and shows selects for them with defined choices. A user could correct.
And we show advanced tokenization options for each text.

**Comment by irina060981** [comment]
Workflow is updated

Now text editor screen has the following steps:

![image](https://user-images.githubusercontent.com/12377640/115013900-fdab4180-9ef4-11eb-9ab9-dbe778c9bd64.png)

**After clicking type/paste in** 
![image](https://user-images.githubusercontent.com/12377640/115013935-09970380-9ef5-11eb-82b6-92aa637354fd.png)

After inserting text (more than 5 characters) and loosing focus (click any other point on the screen out of the textarea) 
it will detect sourceType (text or tei), language and text direction (if sourceType === text)

![image](https://user-images.githubusercontent.com/12377640/115014430-a9ed2800-9ef5-11eb-89b9-2ae238328512.png)


**After clicking upload**
![image](https://user-images.githubusercontent.com/12377640/115014576-def97a80-9ef5-11eb-83ff-2ea9bc677cc1.png)

![image](https://user-images.githubusercontent.com/12377640/115014637-f0428700-9ef5-11eb-9ae5-2675b743c7b7.png)

**After clicking New Alignment**
![image](https://user-images.githubusercontent.com/12377640/115014754-16682700-9ef6-11eb-8c7f-17515455846f.png)

**Comment by irina060981** [comment]
Updated labels from @abrasax feedback

![image](https://user-images.githubusercontent.com/12377640/115019288-58946700-9efc-11eb-98f0-4171a9bb8eaa.png)

**Comment by abrasax** [comment]
ps- thanks for getting this up this week so we can discuss it next week.
It's a big help to see a concrete example.  I do think you can go ahead and
make the text changes I just sent. They are not controversial.

**Comment by abrasax** [comment]
getting close-   Now drop the word "text" after translation
and the the words "a text" after "upload" and "type/paste in"
and lets say ENTER TEXT rather than ENTER TEXTS

**Comment by monzug** [comment]
tested in FF and Safari, Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210416351)
I do not like the workflow for Upload a Text. 
1) When I first click on it, the button moves from right to left and it's renamed Upload text, and two more buttons are displayed: DTSAPI and Show Metadata. I have to click one more time to Upload text to be able to Browse a file to upload. so we have an extra step in comparison with previous builds. 
2) next, if I click on Upload a text in Translation text but then I realized that I want to type in a text instead, I need to start a New alignment (or delete it when there are more than one translations). In previous builds I could just enter the text in the text editor.
3) Last, step 1) is always reproducible when I reload the page. For any subsequent new alignment, when I click on Upload a text, the Browse a file to upload is always visible so I do not need to click one more time on Upload text to generate it.

![Screen Shot 2021-04-16 at 3 12 26 PM](https://user-images.githubusercontent.com/41396793/115029663-8068d800-9ec6-11eb-92fa-53f9c87b7976.png)

**Comment by monzug** [comment]
As per the Type/paste in a text:

1) when I paste in a text in previous builds, all the relevant info (TEI, text direction, language) are visible. In latest build, I copied a text in the empty box without knowing that the previous alignment was in Arabic, so the text was copied right to left. 
2) I have issues with first translation text withType/paste in a text. The first translation language does not show Metadata, language, direction etc. even when I click  outside the box. see screenshots

![Screen Shot 2021-04-16 at 3 38 19 PM](https://user-images.githubusercontent.com/41396793/115033710-07b84a80-9ecb-11eb-8fca-57d4eaabdae0.png)
![Screen Shot 2021-04-16 at 3 37 26 PM](https://user-images.githubusercontent.com/41396793/115033713-0850e100-9ecb-11eb-8192-b62cb276c9af.png)

**Comment by irina060981** [comment]
>ps- thanks for getting this up this week so we can discuss it next week.
It's a big help to see a concrete example.  I do think you can go ahead and
make the text changes I just sent. They are not controversial.

Done

![image](https://user-images.githubusercontent.com/12377640/115134049-59d6a880-a050-11eb-8799-f3cd112dd4d2.png)

**Comment by irina060981** [comment]
>When I first click on it, the button moves from right to left and it's renamed Upload text, and two more buttons are displayed: DTSAPI and Show Metadata. I have to click one more time to Upload text to be able to Browse a file to upload. so we have an extra step in comparison with previous builds.

additional step is removed:

![image](https://user-images.githubusercontent.com/12377640/115232812-7ced7f00-a15a-11eb-9b54-7f2e8f60bdce.png)

![image](https://user-images.githubusercontent.com/12377640/115232838-82e36000-a15a-11eb-9531-eba47445a28a.png)

**Comment by irina060981** [comment]
>Last, step 1) is always reproducible when I reload the page. For any subsequent new alignment, when I click on Upload a text, the Browse a file to upload is always visible so I do not need to click one more time on Upload text to generate it. so there is an inconsistency here that should be fixed.

fixed

**Comment by irina060981** [comment]
>when I paste in a text in previous builds, all the relevant info (TEI, text direction, language) are visible. In latest build, I copied a text in the empty box without knowing that the previous alignment was in Arabic, so the text was copied right to left and it was not meant for it.

I believe that this means that we should not try to save previous optins of the text in a new workflow - would fix

**Comment by irina060981** [comment]
>next, if I click on Upload a text in Translation text but then I realized that I want to type in a text instead, I need to start a New alignment (or delete it when there are more than one translations). In previous builds I could just enter the text in the text editor. Note that in Type/paste in a text, I do still have the option to "Browse" to upload.

I would add an aditional button

**Comment by irina060981** [comment]
>I have issues with first translation text with Type/paste in a text. The first translation language does not show Metadata, language, direction etc. even when I click outside the box. Sometimes I have the Show Metadata button but not the other info, such as direction, language, type.

I fixed the bug

**Comment by irina060981** [comment]
>>when I paste in a text in previous builds, all the relevant info (TEI, text direction, language) are visible. In latest build, I copied a text in the empty box without knowing that the previous alignment was in Arabic, so the text was copied right to left and it was not meant for it.

>I believe that this means that we should not try to save previous options of the text in a new workflow - would fix

done

**Comment by irina060981** [comment]
>>next, if I click on Upload a text in Translation text but then I realized that I want to type in a text instead, I need to start a New alignment (or delete it when there are more than one translations). In previous builds I could just enter the text in the text editor. Note that in Type/paste in a text, I do still have the option to "Browse" to upload.

>I would add an additional button

Button is added
![image](https://user-images.githubusercontent.com/12377640/115361962-6f8ccf00-a204-11eb-9fc7-022b92080424.png)

**Comment by irina060981** [comment]
@monzug - all your points in the issue are fixed

**Comment by monzug** [comment]
Clear Text button has some glitches. 
1) Click on Clear Text in both Original and Translated text after uploading a file on each. then, upload again a file in the Original text, at this point the Translation will be automatically populated with previous uploaded file. Somehow Clear text keeps the latest file in memory
![Screen Shot 2021-04-20 at 6 25 34 PM](https://user-images.githubusercontent.com/41396793/115432671-edea7080-a206-11eb-98c9-33767e7a13f8.png)

**Comment by irina060981** [comment]
>Click on Clear Text in both Original and Translated text after uploading a file on each. then, upload again a file (it can be the same or a new one) in the Original text, at this point the Translation will be automatically populated with previous uploaded file. Somehow Clear text keeps the latest file in memory. in the below screenshot, see the result of the text editor after clicking upload only on the Original text.

Thank you for catching this bug, @monzug 
Now it is fixed

**Comment by irina060981** [comment]
>After Clear Text and upload again, in several occasion I only have the Show Metadata button, all the others are missing. see screenshots

After the previous changes - I could not reproduce it

**Comment by monzug** [comment]
Fixed in Alpheios Translation Alignment editor 1.3.3 (build development.20210426.95) 

I could not longer reproduce both issues described above.

**Comment by monzug** [comment]
Actually, I changed back the status of this issue as I found a reproducible scenario:
1) have text in both Original and Translation
2) delete Translation text
3) clear text in Original text
4) see that the text in translation is populated.

**Comment by monzug** [comment]
Not longer reproducible in Alpheios Translation Alignment editor 1.3.3 (build development.20210518.51)
