### ISSUE TITLE
Lost the ability to display other languages

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#331]
In latest build Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210416351), we lost the ability to display the Other language. I uploaded a file 16-04_16-12-full-alignment-ara-eng-Chinese-Azer-Burn.json with other languages saved as Burn, Azer, Chinese etc. The translation languages of the uploaded json are displayed as English, so we lost the information regarding Chinese, Azer and Burn.

same file in previous build  Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210416351)

![Screen Shot 2021-04-16 at 4 16 01 PM](https://user-images.githubusercontent.com/41396793/115039262-95e2ff80-9ed0-11eb-8c1d-ed12f320b1b1.png)

same file in latest build Alpheios Translation Alignment editor 1.3.2 (build development.20210415332)

![Screen Shot 2021-04-16 at 4 15 32 PM](https://user-images.githubusercontent.com/41396793/115039272-97acc300-9ed0-11eb-8760-499c026964aa.png)

**Comment by monzug** [comment]
this is still reproducible in build Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210419378)

**Comment by irina060981** [comment]
@monzug - I could not reproduce it
![image](https://user-images.githubusercontent.com/12377640/115383996-d799e000-a219-11eb-8aa7-928487a40392.png)

could you attach your HTML (inside archive) to check it and it would be great if you also could attach json?

**Comment by monzug** [comment]
oh, it's not HTML, it's in the alignment editor

**Comment by irina060981** [comment]
Oh, now I see the problem - will fix

**Comment by irina060981** [comment]
fixed

**Comment by monzug** [comment]
this is fixed in Alpheios Translation Alignment editor 1.3.3 (build development.20210422393) 
Thanks.
