### ISSUE TITLE
Uploaded text is not displayed in latest build

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#332]
tested in FF and Safari Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210416351)

when I upload a file with 4 languages, none of the texts is displayed. I have to click on Type/paste in a text to see the source text.
1) this was not happening in previous build Alpheios Translation Alignment editor 1.3.2 (build development.20210415332)
2) if we want to keep this workflow, we should rename the button "Type/paste in a text" with Display text or similar.  The first time I was honestly confused and didn't know what to do and that I have to click on Type/paste in a text. If user clicks on upload a text instead, then there is no way to display the previously uploaded text, user has to start over with a New Alignment.

**Comment by irina060981** [comment]
@monzug , it is a bug - I fixed it - 
it shows correct text areas after upload json now

**Comment by monzug** [comment]
Thanks. this is fix in Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210419378)
