### ISSUE TITLE
Alignment with one word

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#334]
tested in Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210419378) 

when I align a text and a translation with 1 word (or few), the alignment is successful but I cannot see the relevant info such as Language, direction, Text source type. (very similar to issue reported in #337)
if 1 word or just few words are not allowed (I am not aware if we set a minimum lately), the align button should be grayed out, not selectable.

![Screen Shot 2021-04-19 at 3 26 29 PM](https://user-images.githubusercontent.com/41396793/115244618-60365480-a124-11eb-8dd7-c2a82ebce742.png)

**Comment by irina060981** [comment]
It was set a minimum for language detection (min 5 characters).
Now if information is not enough - default text settings would be shown

this is fixed

**Comment by monzug** [comment]
Thanks Irina. This is fixed in Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210420322)
