### ISSUE TITLE
Original or Translated language different from language in filename

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#336]
tested in build Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210419378)  and previous

I noticed that in the latest builds, the origin and target languages are sometimes different from the uploaded file name (e.g. deu for german in the filename then shown as slovak after upload) or are frequently saved as Romanian or Slovak, specially when I type not existing words. This is new as I have been testing using these files for the last 2 months and I have never noticed the discrepancy between the language saved in the filename and the Origin or Target language after uploading the file. Could it be that it's trying to detect the language?

![Screen Shot 2021-04-19 at 3 21 13 PM](https://user-images.githubusercontent.com/41396793/115248895-60d0ea00-a128-11eb-9c9b-5f29e291cbb9.png)

**Comment by irina060981** [comment]
Yes, @monzug , you are right there was a bug with additional language detection for uploaded texts.
Now it is fixed

**Comment by monzug** [comment]
yes, this is fixed in Alpheios Translation Alignment editor 1.3.3 (build development.20210422393)
