### ISSUE TITLE
Browse or Choose File

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#337]
Tested in Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210419378) in FF and Safari

When I click on Upload in FF, I have the Choose File button, in Safari I have Browse instead. Why such a difference?

![Screen Shot 2021-04-19 at 4 05 26 PM](https://user-images.githubusercontent.com/41396793/115249982-70046780-a129-11eb-82aa-a644bc6fd644.png)

![Screen Shot 2021-04-19 at 4 04 45 PM](https://user-images.githubusercontent.com/41396793/115250006-772b7580-a129-11eb-86be-9629fb805fdd.png)

**Comment by irina060981** [comment]
>When I click on Upload in FF, I have the Choose File button, in Safari I have Browse instead. Why such a difference?

this labels are generated by browser - it is predefined by browser developers.

**Comment by monzug** [comment]
Ok. Thanks. in Chrome it's also Choose File
