### ISSUE TITLE
Undo/Redo in slide menu

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#338]
Monica's question to Harry: We have two locations for Undo/Redo: one is in the slide menu and it's for the alignment editor and the other is in the tokens editor. Should we rename the Undo/redo in the slide menu to Undo alignment/Redo alignment or it's ok for you as is?
Harry said: My initial reaction is that undo/redo would intuitively apply to the current context.  But I'll have to look more closely at it to be sure it is as intuitive as i think.

My suggestion based on Harry's answer: let's disable (greyout) the Undo/Redo in slide menu when not in the alignment editor.
This can be a usability issue, when you have both tokens editor and alignment editor with activated undo/redo. If you click on Undo from slide menu when in Token editor, you cannot see what's happening in the alignment editor.
see screenshot

![Screen Shot 2021-04-19 at 4 19 09 PM](https://user-images.githubusercontent.com/41396793/115251653-038a6800-a12b-11eb-9dc6-57160c5e5644.png)

**Comment by monzug** [comment]
Basically we have 3 options here:
1) rename Undo/Redo to Undo alignment/Redo alignment
2) grey out undo redo when NOT in alignment editor
3) move the Undo/Redo buttons from the slide meno to to Alignment editor as in Tokens editor

**Comment by abrasax** [comment]
What are you doing working on a Saturday morning?  But if you happen to
feel like chatting about interface options I am also on deck, with a couple
of questions about which I should be interested in your response.

**Comment by abrasax** [comment]
What are you doing working on a Saturday morning? But if you happen to feel
like chatting about interface questions I have a couple of issues I should
like your opinion about.

**Comment by irina060981** [comment]
I deleted a duplicated comment

**Comment by monzug** [comment]
based on a conversation with Harry (@abrasax) he agreed to move the Undo/Redo buttons from the slide menu to the relevant page which is the Alignment Groups Editor.

**Comment by irina060981** [comment]
Done here https://github.com/alpheios-project/alignment-editor-new/issues/380

**Comment by monzug** [comment]
verified in Alpheios Translation Alignment editor 1.3.3 (build development.20210518.51)
