### ISSUE TITLE
Change Delete button action

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#339]
from on-line meeting with @abrasax 

- add delete button to original and first translation text, it should be visible when there is some text in the box
- for original and first translation text it should simply clear the text box
- for translations text after the first - it should delete translation text (as it is now)
- delete button is available only before text is tokenized

**Comment by irina060981** [comment]
done

**Comment by monzug** [comment]
tested in build Alpheios Translation Alignment editor 1.3.3 (build development.20210423396) 

Clear Text removes (delete) the Translation language box while the garbage bin clears the text. This happens only for Original and first Translation Text. This is not so intuitive as Clear Text is meant to do what it says, while Garbage Bin is widely recognized as Trash or Delete action. For the subsequent Translation Languages (Language 2 and above), the Garbage bin deletes the correspondent Translation language entry. For usability, this is confusing. A button should have a consistent behavior and this is expected, instead bin has two meanings here: clear text from entry box and delete the Translation language entry.

**Comment by irina060981** [comment]
>also, there are some glitches that I have reported in #327 about automatically populated text areas.

This is fixed

**Comment by irina060981** [comment]
>A button should have a consistent behavior and this is expected, instead bin has two meanings here: clear text from entry box and delete the Translation language entry.

Yes, it has different behaviour by request.
And I agree - that having garbage icon and Clear text button at once - is rather confusing.

I also has a request to return empty text area back from @abrasax - let's see - how it woukd be in full changes

**Comment by irina060981** [comment]
The behaviour is changed here - https://github.com/alpheios-project/alignment-editor-new/issues/366
