### ISSUE TITLE
language in csv file is different than in filename

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#340]
related to issue #336
I uploaded two csv files, one Greek and one Latin. in build Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210418129), in both uploaded files, the Original and Translation language showed the correct language as per filename. in latest build Alpheios Translation Alignment editor 1.3.3 (build development.20210422393), in both uploaded files the Original and Translation language is set to English. see attachments

latest build - Alpheios Translation Alignment editor 1.3.3 (build development.20210422393)

![Screen Shot 2021-04-23 at 2 30 41 PM](https://user-images.githubusercontent.com/41396793/115871283-a0f1de80-a440-11eb-8800-3ed56ee3e1c2.png)

old build - Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210418129)

![Screen Shot 2021-04-23 at 2 32 46 PM](https://user-images.githubusercontent.com/41396793/115871455-de566c00-a440-11eb-9114-93d03f61b72a.png)

**Comment by irina060981** [comment]
@monzug , could you attach csv files? From screenshots I could see that they are not standard - and there are a lot of english (latin letters) there 
So these Greek and Latin was not detected in previous biuld but was to be uploaded from contents.
But format is not native for the Alignment Editor

**Comment by monzug** [comment]
what is the difference between build i327-new-text-editor-screen.20210418129 with the language specified and the current build with English as default language? does it have something to do with the language detection? I looked at issue https://github.com/alpheios-project/alpheios-core/issues/639, and that was implemented already in build i327-new-text-editor-screen.20210418129. so, which change causes such a difference in behavior? 
as per the two csv files, they are saved wordlist, one saved as greek and one saved as latin.
[wordlist-lat-6.csv.zip](https://github.com/alpheios-project/alignment-editor-new/files/6377688/wordlist-lat-6.csv.zip)
[wordlist-grc.csv.zip](https://github.com/alpheios-project/alignment-editor-new/files/6377689/wordlist-grc.csv.zip)

**Comment by irina060981** [comment]
@monzug , I believe I could not understand the problem.
Attached file - is a download csv from wordlist. When you upload it as a single text file - it is uploaded as a solid text.
So that's why no language is defined inside a file.
Then langauge would be defined by the follwoing steps:

- language is set to default for the start (to English)
- text is uploaded from file 
- if text is longer than 5 characters, then it would be sent to Language Detection 
- if detection returned langCode - it would be set, otherwise text would still have English language

May be you mean changes - that application is always set to default from the start?

Anyway I don't see any error here.
And Language detection service couldn't return any other language before.
May be you defined it manually before?

**Comment by monzug** [comment]
No, I didn’t change the language myself. I uploaded the two csv files (filename has latin and greek accordingly) and the build from April 18 (I believe this is the correct date but I cannot check at the moment) detected the language from the filename. Just asking why now it’s not longer detecting the language.

**Comment by irina060981** [comment]
Monica. it detects language and detects as English - results look like this

for `wordlist-lat-6`
![image](https://user-images.githubusercontent.com/12377640/116540559-a9a94f80-a92d-11eb-9c50-48a50ee23bde.png)

for `wordlist-grc`
![image](https://user-images.githubusercontent.com/12377640/116540629-c3e32d80-a92d-11eb-9287-7ee394cc6cc1.png)

And it couldn't detect it before as the other language.
And there is no defined language inside.

I don't know - how it could define anything other then English.

I uploaded this file in old version - https://alignment.alpheios.net/ (without auto detection) - it is still English

**Comment by monzug** [comment]
glad it's a no issues. if it does appear again then we should dig into change in that specific build that made this possible. Thanks
