### ISSUE TITLE
Add summary popup before starting tokenization

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#344]
from online meeting from @abrasax 
After clicking button - Prepare texts for alignment (tooltip: tokenizing) - before it was called Align

"Alpheios believes your texts are in the following languages. Please
    review and correct if necessary"

    original text:                            translations:

     (corrections would be available after clicking Cancel button under text areas)

                              "ALL OK"                  "CANCEL"

         (which takes the user to the following screen:)
    
    ------------------------------------------------------------------
    "Please describe your texts"

    Original Text                              Translation 1

Title                                          Title
Author                                         Author
Date                                           Date
Edition
Other                                          (scroll successive translations)

                                               Translation 2 etc

                      "you can modify this later"
                               "SKIP"

   -------------------------------------------------------------------

                   ---  "Preparing Texts"  ---
           
                   (turning wheel of some sort)

                   (and then open the alignment screen with no further
                    messages)
 

-----------------------------------------------------------

**Comment by irina060981** [comment]
On the last meeting there was decided to have only screen with languages check
![image](https://user-images.githubusercontent.com/12377640/116386635-5071eb00-a85d-11eb-9729-031db3547c81.png)

`All ok` - button - starts tokenization process
`Cancel` - closes the modal and let user to update languages

**Comment by monzug** [comment]
tested in Alpheios Translation Alignment editor 1.3.3 (build development.20210430.74)

1) pls, change Original in Translation in the pop-up
![Screen Shot 2021-04-30 at 3 26 23 PM](https://user-images.githubusercontent.com/41396793/116701936-c5156880-a9c8-11eb-9c48-736c0d74151c.png)

2) All OK button should be just OK or Harry (@abrasax) might have something else in mind.

3) When I Cancel the pop-up and also uncheck the option to display it again, the pop-up is still generated briefly with the loading wheel after clicking on alignment. This does happen also when "Show language check before text would be prepared" option is unchecked.

4) related to the above issue, please confirm that we want the option "Show language check before text would be prepared" checked by default.

**Comment by irina060981** [comment]
>pls, change Original in Translation in the pop-up 

Thank you for the catch - fixed

**Comment by irina060981** [comment]
>All OK button should be just OK or Harry (@abrasax) might have something else in mind.

Yes, Harry defined it as All Ok - because it means that all languages in the popup are ok.

**Comment by irina060981** [comment]
>When I Cancel the pop-up and also uncheck the option to display it again, the pop-up is still generated briefly with the loading wheel after clicking on alignment. This does happen also when "Show language check before text would be prepared" option is unchecked.

Yes it is designed behaviour - it shows a wheel during tokenization is going. (I removed notifications - Tokenization is started/Tokenization is finished.
It seems that I need to remove heading - it is confusing eithout languages list.

**Comment by irina060981** [comment]
Now it looks like this
- no language check
![image](https://user-images.githubusercontent.com/12377640/116838277-216ac900-ac11-11eb-9901-3ba7df6542ea.png)

- with language check
![image](https://user-images.githubusercontent.com/12377640/116838309-3f382e00-ac11-11eb-9cff-30135073fa4f.png)

**Comment by monzug** [comment]
verified in Alpheios Translation Alignment editor 1.3.3 (build development.20210503268)
