### ISSUE TITLE
Add no metadata icon

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#347]
from on-line meeting with @abrasax

Add an icon that shows that a text doesn't have metadata

![image](https://user-images.githubusercontent.com/12377640/116387825-8cf21680-a85e-11eb-91f7-ebf309b78405.png)

**Comment by monzug** [comment]
tested in Alpheios Translation Alignment editor 1.3.3 (build development.20210430.74). verified
