### ISSUE TITLE
apply colors from v1 editor 

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alignment-editor-new#35]
we need to have the ability to apply the colors used in V1 of the alignment editor (https://github.com/alpheios-project/alignment-editor/blob/master/db/css/alph-align-edit.css)

Maybe we could make it possible to have different themes ?

**Comment by irina060981** [comment]
Theme could be defined according to the following priority:

a) A theme is defined in url GET parameters - theme -
https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/alignment-editor/index.html?theme=standard-theme
https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/alignment-editor/index.html?theme=v1-theme

b) A theme is defined in application code - theme
        document.addEventListener("DOMContentLoaded", function(event) {
          new window.AlignmentEditor.AppController({
            appId: 'alpheios-alignment-editor',
            theme: 'v1-theme' //,
            // theme: 'standard-theme'
          }).init()
        });

c) Default theme - standard

**Comment by irina060981** [comment]
Merged and closed
