### ISSUE TITLE
Add align button to the Text Enter Screen

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#350]
From the on-line meeting with @abrasax

Add `Prepare texts for alignment` to the Text Enter Screen - after tokenization starts to be available

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/116390588-8fa23b00-a861-11eb-8549-187075d7aafd.png)

**Comment by monzug** [comment]
tested in Alpheios Translation Alignment editor 1.3.3 (build development.20210430.74) - Harry suggested to move the button at the bottom of the text area. if text is too long, it should go on top and bottom + on slide menu. I'll mark as verified and if Harry wants those changes we should reopen this issue.
