### ISSUE TITLE
Add IndexDB support

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#353]
Add ability to save and upload alignments from local IndexedDB;
Add ability to work with big texts using partly upload/save to IndexedDB;

**Comment by irina060981** [comment]
Resuming is available on Initial screen for now - under Choose file button

![image](https://user-images.githubusercontent.com/12377640/119826801-c3917e80-bf3b-11eb-939a-b6611a322be8.png)

**Comment by irina060981** [comment]
Added feature to upload tokens by part (prev/next)
![image](https://user-images.githubusercontent.com/12377640/121684724-70562900-cb02-11eb-8bb4-e90f0497ea05.png)

![image](https://user-images.githubusercontent.com/12377640/121684773-819f3580-cb02-11eb-825b-9b35240df4c6.png)

![image](https://user-images.githubusercontent.com/12377640/121684790-89f77080-cb02-11eb-8bd5-de4e43bd582b.png)

Parts size are defined in options.

Parts are divided by the following workflow:
- if part has more than charMax (from settings) and there are more than 5 tokens left in the segment (for another part):
    - if next token is from the other sentence (this token is last in the current sentence) - then part is saved and new part is started to be created
    - if part has more than charMax *2 (from settings) and next token and next next token are still in the same sentence - then part is saved and new part is started to be created
    
So this way an algorithm divides to parts.

**Comment by monzug** [comment]
question: I upload less than 50000 char - Characters count - 49495 (max - 50000) - 
 from the following text:  http://thelatinlibrary.com/suetonius/suet.nero.html which is split in segments. Unfortunately I had problem to display the align text. Then I resume the alignment and the word count was Characters count - 4618 (max - 
50000) text in indexDB 

does indexDB truncate

**Comment by irina060981** [comment]
I believe it was a problem with dividing to parts
Now it is not reproducable
