### ISSUE TITLE
Text is visible after delete translation

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#354]
Tested in Alpheios Translation Alignment editor 1.3.3 (build development.20210430.74) 
steps to repro:
1) enter text in Original and Translation
2) click on delete (garbage bin) for the translation and for the Original text.
3) click on Restart button on the Original text. Original section goes into starting point for entering text or upload file.
4) At the same time, the translation is populated by the last text that was entered and deleted.

![Screen Shot 2021-04-30 at 4 35 03 PM](https://user-images.githubusercontent.com/41396793/116711172-e3806180-a9d2-11eb-9653-660a528c3251.png)

**Comment by irina060981** [comment]
@monzug , thank you for paying attention to such bugs :)
I fixed it.
But I think you don't need to spend time to verify it - because Harry changed the workflow with clear action for text enter screen.
I would realize it later.

**Comment by monzug** [comment]
Thanks.
