### ISSUE TITLE
Navigation after clicking on Restart (Source Text Editor)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#355]
tested in Alpheios Translation Alignment editor 1.3.3 (build development.20210430.74) 

After editing text in Original and Translation and then click on restart (and repeating these steps a couple of times), I do not get the option to upload text but just restart and show metadata button. I was expecting to get back to the same step as in Original in the screenshot below:

![Screen Shot 2021-04-30 at 5 24 09 PM](https://user-images.githubusercontent.com/41396793/116717256-fac24d80-a9d8-11eb-9758-2335be79ed94.png)

**Comment by irina060981** [comment]
Monica, I didn't understand the issue - you faced with the situation - you clicked Restart and it didn't do anything?

Each time I click restart it returns to the following
![image](https://user-images.githubusercontent.com/12377640/116869763-a7f4ca00-ac54-11eb-8d1a-d704b98a3a91.png)

Could you give me exact steps to reproduce?

**Comment by monzug** [comment]
right. again it's a weird scenario that I have experienced few times. I'll take it back to see if I am able to repro in the new build. I'll keep at testcase.

**Comment by monzug** [comment]
workflow has changed so this scenario is not longer reproducible
