### ISSUE TITLE
direction right to left does reverse the words after alignment

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#357]
tested on alignment editor on latest build Alpheios Translation Alignment editor 1.3.3 (build development.20210430.74) 
see the differences in source text editor and in alignment editor. why such a difference? Note that this does not happen with the Arabic language which is automatically displayed right to left and both text editor and alignment editor have same direction.

![Screen Shot 2021-05-01 at 3 00 38 PM](https://user-images.githubusercontent.com/41396793/116783296-3834e280-aa8e-11eb-97e3-5279c5533843.png)

![Screen Shot 2021-05-01 at 2 59 06 PM](https://user-images.githubusercontent.com/41396793/116783340-821dc880-aa8e-11eb-8cb0-cf6a787edf06.png)

**Comment by irina060981** [comment]
Oh it is an interesting issue - but we don't control it.

It is rendered by browser this way.

In Text Enter Screen we have texts in `textarea` tag. Direction is placed here via attribute:
![image](https://user-images.githubusercontent.com/12377640/116871874-4c2c4000-ac58-11eb-8cd1-863f607e64b5.png)

`dir="rtl"`

**Comment by monzug** [comment]
yep, I see. Let's ask Bridget if we should do anything here.
