### ISSUE TITLE
Alignment fails after invalid integer error condition is removed

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#361]
tested in Alpheios Translation Alignment editor 1.3.3 (build development.20210503268) and previous build too.
I uploaded a xml file (downloaded from Alpheios) in both Original and Translation. text is aligned successfully. then I start a new alignment, this time using the same file but editing the "If this text is aligned with a treebank, specify the starting segment index" with garbage text and numbers. the following error is generated: "Request doesn't return data - 400: {'tbsegstart': ['Not a valid integer.']} (tokenizationGroup.alpheios.getTokens)"  in combination with "Original source text was not tokenized due to the errors in tokenization service. All tokenization results were cancelled." error. 
When I delete the entry in the "If this text is aligned with a treebank, specify the starting segment index" field, the alignment fails again. it's like the field is still not cleared after deleting the entries.

![Screen Shot 2021-05-03 at 5 33 32 PM](https://user-images.githubusercontent.com/41396793/116897636-c5ff0200-ac35-11eb-8dd2-fffbbcf08981.png)

**Comment by irina060981** [comment]
This property is hidden in https://github.com/alpheios-project/alignment-editor-new/issues/381

**Comment by monzug** [comment]
this is still reproducible in Alpheios Translation Alignment editor 1.3.3 (build development.20210518.51) as this option is still available in TEI.

**Comment by irina060981** [comment]
oh, I missed it there.
Deleted it from tei fieldset too.

**Comment by monzug** [comment]
property not longer displayed in TEI options

![Screen Shot 2021-05-19 at 2 21 26 PM](https://user-images.githubusercontent.com/41396793/118811949-e376d180-b8ad-11eb-8929-f6f49b71404e.png)
