### ISSUE TITLE
Failed to detect latin language from xml file

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#362]
Related to #361 
I uploaded a xml file downloaded from Vergilius in Alpheios (see file attached). in the xml, it says that lang is Latin. 
See below
<TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:py="http://codespeak.net/lxml/objectify/pytype" py:pytype="TREE"><text xml:lang="lat"><body><div type="edition" xml:lang="lat" ....

The source text editor fails to identify the language as Latin. see attachment

![Screen Shot 2021-05-03 at 5 36 25 PM](https://user-images.githubusercontent.com/41396793/116898228-6b19da80-ac36-11eb-9472-f7c65a1c2f62.png)

[cts-virgilio.xml.zip](https://github.com/alpheios-project/alignment-editor-new/files/6415922/cts-virgilio.xml.zip)

**Comment by irina060981** [comment]
Yes, an application detects language only for plain texts.
It is not available to detect language for XML, because we don't parse XML inside Text Enter Screen.

So it is correct behaviour

**Comment by monzug** [comment]
based on the above explanation, it should detect the language when I paste a TEI text, but it does not. see screenshot below:
on the left, there is the uploaded TEI with grc as language, on the right same TEI text not uploaded but copied with eng as language
![Screen Shot 2021-06-13 at 4 30 11 PM](https://user-images.githubusercontent.com/41396793/121890327-80e0ec00-cd1a-11eb-83e2-8a0a98c21a18.png)

**Comment by irina060981** [comment]
@monzug , as I explained at the previous comment - we don't have an ability to detect language for TEI texts - it should be defined manually by the user.
The only exception - DTS API links - I defined language for each link's group.
Alpheios Greek - grc
Alpheio Latin - lat
Betamasaheft - gez

That's why you got described result

**Comment by monzug** [comment]
ok, so the difference between XML and TEI with correct language detected, is the source: Alpheios TEI. correct?

**Comment by irina060981** [comment]
yes - application knows that from the given DTA API links upload defined languages.

But Application knows nothing about other TEI/XML texts.

**Comment by monzug** [comment]
got it! Thanks
