### ISSUE TITLE
Remove full from filename when downloaded from Source text editor

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#363]
Just noticed that when I download a file from Source Text Editor and the text has not been tokenized yet, the filename does say full-alignment-xx-xx.json
I think it should say just alignment-xx-xx.json as for tsv files. In this way it's easier to find a json file with full alignment from one that has not been aligned yet.

![Screen Shot 2021-05-04 at 2 30 48 PM](https://user-images.githubusercontent.com/41396793/117003949-c7880300-ace5-11eb-88a9-2b14b80fe306.png)

**Comment by irina060981** [comment]
Done

**Comment by monzug** [comment]
Thanks! verified in Alpheios Translation Alignment editor 1.3.3 (build development.20210518.51)
