### ISSUE TITLE
Add an ex-icon to the text block

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#366]
From the online meeting with @abrasax 

Add ex-icon to th text box - that should work similiar to delete/restart button:

- if it is original text or a single translation (no other translations are defined) - it clears text and inits language data
- if it is a single translation - but not the last - it would delete a translation

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/117560484-96d30f80-b0d1-11eb-9ae7-0935d47f9ba2.png)

**Comment by monzug** [comment]
X does clear text
