### ISSUE TITLE
Make metadata icon clickable

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#368]
From the online meeting with @abrasax 

Update metadata workflow:

- at the starting point - we don't have any additional icons
- when text is defined - we got no-metadata icon - red
- when there is some metadata defined - we got has-metadata icon - green
- has-metadata and no-metadata icons are clickable - should open metadata block

**Comment by irina060981** [comment]
First 
![image](https://user-images.githubusercontent.com/12377640/117560495-a7838580-b0d1-11eb-9c15-523df129aa6b.png)

Created some text
![image](https://user-images.githubusercontent.com/12377640/117560504-b833fb80-b0d1-11eb-88e1-b710219e8e7f.png)

Added some metadata
![image](https://user-images.githubusercontent.com/12377640/117560517-c7b34480-b0d1-11eb-9ed8-d9c317e3de19.png)

After icon clicked
![image](https://user-images.githubusercontent.com/12377640/117560520-d3067000-b0d1-11eb-83eb-0468f04aef4c.png)

**Comment by monzug** [comment]
question about the font used in the metadata fields. In Enter Text, fonts are in black with green icons, in align text fonts are in red with green icons. any reason for this difference?

![Screen Shot 2021-05-18 at 2 40 46 PM](https://user-images.githubusercontent.com/41396793/118665360-89fd9c80-b7f2-11eb-90a9-699a5480379a.png)

**Comment by irina060981** [comment]
@monzug , thank you for the catch :) It is bug with styles -

**Comment by monzug** [comment]
@irina060981 if I edit a field, the metadata icon turns green. When I delete the entry, the metadata is still green as the entry cannot be deleted. Basically the metadata icon cannot turn into a red one again. Did we plan for such a scenario?

**Comment by irina060981** [comment]
No, it was a bug - I faced with it - while was working with IndexedDB - now it is fixed.

**Comment by monzug** [comment]
This is fixed in Alpheios Translation Alignment editor 1.4.1 (build development.20210528289)
