### ISSUE TITLE
Make lang icon clickable

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#369]
From the online meeting with @abrasax 

- make language icon clickable
- show language/direction choice inside modal window

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/117560861-e36c1a00-b0d4-11eb-8f70-414c8baac699.png)

**Comment by monzug** [comment]
Can you make the icon just a little bit larger to match the size of TXT/TEI? I am still not so convinced that it's obviously a clickable icon except when mouse over.

**Comment by irina060981** [comment]
I added the min-width for the lang icon - it would be the same as tei/text.

>Also, I am still not so convinced that it's so obvious that it's a clickable icon except when mouse over.

Do you have any proposals how to do it better?

**Comment by irina060981** [comment]
They are not real buttons - because they have two roles:
- show data (language, source type) as icon
- be clickable 

Icons could be clickable - that's why I rendered them this way.
We have another clickable icon - add a new target text - and it doesn't look like the button

If I change styles - it would be this way

![image](https://user-images.githubusercontent.com/12377640/119923961-1445bd80-bfb6-11eb-9851-047dbf52ffb9.png)

**Comment by irina060981** [comment]
@monzug, do you like it? Do you anyway think that it is a good change?
If it is so - I would change it

**Comment by monzug** [comment]
I would definitely remove the language detected icon as among all of them it's the only one who is not clickable. having all small green buttons, it's more Alpheios style. we should discuss it with Harry on the next call. Thanks for putting up an example.

**Comment by irina060981** [comment]
>I would definitely remove the language detected icon as among all of them it's the only one who is not clickable. 

I don't agree with it.
This icon tells a user, that language is not detected and user should select language manually.
From my point of view - it is an important information.

**Comment by monzug** [comment]
I hear you but my concern is mainly to the fact that it does not work properly (see #351 and #405) and for consistency as 3 out of 4 icons are clickable. we should discuss this on next call

**Comment by monzug** [comment]
![Screen Shot 2021-06-02 at 2 40 59 PM](https://user-images.githubusercontent.com/41396793/120498718-bc48f580-c3bf-11eb-9f1c-f1e917617a55.png)

**Comment by monzug** [comment]
I have noticed the improvement of this functionality recently. Basically the language icon is less 'invasive'. see screenshot from Alpheios Translation Alignment editor 1.3.3 (build dev.20210610374), with full_alignment eng-ita.json
![Screen Shot 2021-07-07 at 4 59 54 PM](https://user-images.githubusercontent.com/41396793/124784562-56173b80-df46-11eb-8c2a-9c4eab7e225f.png)

and this is screenshot from Alpheios Translation Alignment editor 1.4.1 (build development.20210706320) with full-alignment eng-ita.json
![Screen Shot 2021-07-07 at 5 00 31 PM](https://user-images.githubusercontent.com/41396793/124784803-8eb71500-df46-11eb-9f14-38473962682a.png)

as you can see the language icon is not generated in latest version of the alignment with the same file

**Comment by monzug** [comment]
I think we can close this one as language icon is not longer generated as before, see previous comment.
