### ISSUE TITLE
Update language summary modal window

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#371]
From online meeting with @abrasax 

Add check - if a text is TEI format
Show what texts are already tokenized

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/117562806-10c0c400-b0e5-11eb-8786-62e2b35e7645.png)

![image](https://user-images.githubusercontent.com/12377640/117562816-22a26700-b0e5-11eb-9bd1-d9103afb93a7.png)

**Comment by irina060981** [comment]
This check only shows that a text is defined as TEI.
it shows the same as clickable icon.
If there is some bugs here - I need an example.
What exact file did you upload, was it defined as TEI in properties (icon)

**Comment by irina060981** [comment]
> also, I do not think Is Tei is a good field name, maybe just TEI?
if you think so, I would change

**Comment by monzug** [comment]
Thanks. Now I do get the check for TEI

![Screen Shot 2021-05-19 at 2 03 06 PM](https://user-images.githubusercontent.com/41396793/118809670-3438fb00-b8ab-11eb-9edc-ce0dfb8e169f.png)
