### ISSUE TITLE
Add navigation links to the top of the screen

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#372]
From the online meeting with @abrasax 
Add navigation links to the

Text Enter Screen - ENTER TEXT [ALIGN] [EDIT]  
Create Alignment Groups Screen - [ENTER] ALIGN TEXT [EDIT]  
Edit Tokens Screen - [ENTER] [ALIGN] EDIT TEXT

This links should do navigation between screens according to their availability.

**Comment by irina060981** [comment]
added
![image](https://user-images.githubusercontent.com/12377640/117604787-9e5deb80-b199-11eb-8c4f-a4b01ad56a96.png)

![image](https://user-images.githubusercontent.com/12377640/117604796-a3bb3600-b199-11eb-82ea-d7d35a6e37c7.png)

![image](https://user-images.githubusercontent.com/12377640/117604806-a9b11700-b199-11eb-99a3-103da939db1f.png)

**Comment by monzug** [comment]
ENTER TEXT is the only available navigation when no alignment has been created yet.
tested in Alpheios Translation Alignment editor 1.3.3 (build development.20210519.98)
