### ISSUE TITLE
Add Options button to the header

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#377]
From the on-line meeting with @abrasax 

- Add Options button to the header of Text Enter Screen, Align Text Screen, Text Edit Screen
- Place specific optios to each Options popup
- A single global option (theme) should be placed inside Options on Text Enter Screen

Remove Options from main menu

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/118113727-fca0fd80-b429-11eb-8ed2-44ecdf50ac83.png)

**Comment by monzug** [comment]
Verified in Alpheios Translation Alignment editor 1.3.3 (build development.20210519.98)
