### ISSUE TITLE
Add undo/redo to the Align Text Screen

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#380]
from the online meeting with @abrasax 

- place UNDO/REDO to the Align Text Screen
- update styles - UNDO/REDO buttons should be near the tabs

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/118123645-e7cb6680-b437-11eb-9319-e9b7e7f29ac9.png)

![image](https://user-images.githubusercontent.com/12377640/118123671-eef27480-b437-11eb-9ddd-647a36063df3.png)

**Comment by monzug** [comment]
Verified in Alpheios Translation Alignment editor 1.3.3 (build development.20210518.51)
