### ISSUE TITLE
Hide tokenizer option - tbsegstart

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#381]
From online meeting with @abrasax and @balmas 

Hide a tokenizer option (used for plain text) - `tbsegstart` (If this text is aligned with a treebank, specify the starting segment index)

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/118125422-47c30c80-b43a-11eb-94aa-f9185c2c907c.png)

**Comment by monzug** [comment]
this option is not longer available for TEXT, only for TEI. tested in Alpheios Translation Alignment editor 1.3.3 (build development.20210518.51)

**Comment by monzug** [comment]
maybe it should be removed also from TEI as issue #361 is still reproducible. Please confirm if this was the original intention.

**Comment by irina060981** [comment]
Fixed in https://github.com/alpheios-project/alignment-editor-new/issues/361

**Comment by monzug** [comment]
fixed, see #381
