### ISSUE TITLE
Add describe button to Text Enter Screen

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#383]
from the online meeting with @abrasax 

- add Describe button to each text box on Text Enter Screen , that opens Metadata template

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/118236337-4a287380-b4d9-11eb-867f-b89ced449554.png)

**Comment by monzug** [comment]
Verified in Alpheios Translation Alignment editor 1.3.3 (build development.20210519.98)
