### ISSUE TITLE
Add an information row to the texts in Align Text Screen

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#385]
from online meeting with @abrasax 

- add an information row to each text on Align Text Screen
- place there language name - not clickable (similiar to HTML display view)
- place there no-metadata/has-metadata icon (https://github.com/alpheios-project/alignment-editor-new/issues/368)

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/118263274-64724980-b4f9-11eb-8ed9-c7724b3f90cd.png)
![image](https://user-images.githubusercontent.com/12377640/118263310-6c31ee00-b4f9-11eb-8f19-6d4b51a75f9c.png)

**Comment by monzug** [comment]
Verified in Alpheios Translation Alignment editor 1.3.3 (build development.20210518.51)
