### ISSUE TITLE
Add clickable tei/text icon

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#387]
From the online meeting with @abrasax 

- add text/tei clickable icon for each text box on Text Enter Screen
- show popup with sourceType and tokenize options

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/118345141-f4ee6f80-b575-11eb-975b-cc1c1a0af282.png)

![image](https://user-images.githubusercontent.com/12377640/118345146-fcae1400-b575-11eb-905f-bdf180586771.png)

**Comment by monzug** [comment]
icon is clickable and pop-up is generated
