### ISSUE TITLE
Help and Options pop-ups are truncated in Enter Text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#389]
Tested on MAC 13.3-inch (1440 × 900) BigSur 11.3,  Safari, Chrome and FF

the Help and Options pop-up are truncated. see screenshots

![Screen Shot 2021-05-17 at 2 42 29 PM](https://user-images.githubusercontent.com/41396793/118490857-b47e2580-b71e-11eb-974b-fba5897f7a3f.png)
![Screen Shot 2021-05-17 at 2 42 12 PM](https://user-images.githubusercontent.com/41396793/118490860-b516bc00-b71e-11eb-8ef3-9b5739c9f353.png)
![Screen Shot 2021-05-17 at 2 41 38 PM](https://user-images.githubusercontent.com/41396793/118490861-b5af5280-b71e-11eb-86d1-c01c682415d5.png)
![Screen Shot 2021-05-17 at 2 41 08 PM](https://user-images.githubusercontent.com/41396793/118490862-b647e900-b71e-11eb-88a9-040d6eea99e0.png)

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
Options looks good but the help is still truncated in all browsers.

![Screen Shot 2021-05-18 at 2 36 03 PM](https://user-images.githubusercontent.com/41396793/118653059-77319a80-b7e7-11eb-897d-0cc890fd5ca0.png)

**Comment by irina060981** [comment]
I believe that clientHeight is too small of the browser on your Mac.
I will decrease max-height of the window then.

**Comment by irina060981** [comment]
fixed

**Comment by monzug** [comment]
yes. looks good. will test on other MAC and PC

**Comment by monzug** [comment]
on Chrome and FF/PC looks good

**Comment by monzug** [comment]
and so does on Catalina 10.15.6 13.3 inch 1440x900
