### ISSUE TITLE
Create an edit aligned text mode - visual editor 

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#39]
We need to a specific edit mode for aligned texts:

- it should give an ability to merge, separate tokens, update tokens metadata
- it should have a visual way of editing
- it should save a history
- may be we would need undo/redo here

**Comment by balmas** [comment]
it should also offer the option to apply a tokenization change (i.e. a split or a merge) globally across the entire text.

**Comment by irina060981** [comment]
16.Must allow user to edit tokenization results before they start aligning a text (because supporting editing words once alignment is started is not in scope)
17.Must allow user to edit line breaks at any point during alignment
18.May allow user to append words to the beginning or end of the source and translation texts once alignment has started

**Comment by balmas** [comment]
this issue should be for the mode switch. #63 cover the actual edit requirements #81  #82 #83

**Comment by irina060981** [comment]
Comments from @balmas to the approved the first step:
>>
I like the way it looks. It's simple and easy to understand. I don't know how much of the underlying code you intend to be working at this point, so I didn't review it closely. I will add a few comments on the requirements:

1. as we discussed in the check-in, if it's not too much work, I would like to make the possibility to edit the text of a token a configurable option.  With the current UI design, this would mean restricting the edit to insertion of a space for the split token functionality.  

2. I am not sure of the best way to deal with the restriction on editing tokens which have already been aligned. This is something we will need to get user feedback on. But, going with the approach you have taken for now, I think we should visually identify those tokens that cannot be edited by not outlining them, and having a popup help which says that they need to be un-aligned before they can be edited.

3. For the token ids,I see that you have a `freeIdWord` getter on segment that isn't used yet.  I would like for us to be able to differentiate the ids of tokens which have been created or changed via the editor from tokens that were part of the original tokenization, and if possible, retain some sort of history. What do you think about the following approach:
 tokens which are merged get new Ids in the format <segment-id>-<original-token-id>-m-<increment>
 tokens which are split each get new ids in the format   <segment-id>-<original-token-id>-s-<increment>
 tokens which are edited each get new ids in the format   <segment-id>-<original-token-id>-e-<increment>

 tokens which are added at the beginning or end of a segment get ids in the format   <segment-id>-x-<increment>

so as an example, take the following segment of words "Bella per Emathios plus quam ciuilia" 

It has the following tokens (pseudo-code):

```
[ { text: 'Bella',
    id: '1-1',
    index: 0
  },
  { text: 'per',
     id '1-2',
    index: 1
  },
  { text: 'Emathios',
    id: '1-3',
    index: 2
  },
  { text: 'plus',
    id: '1-4',
    index: 3
  },
  { text: 'quam',
    id: '1-5',
    index: 4
  },
  { text: 'ciuilia',
    id: '1-6',
    index: 5
  }
]
```

Use merges 'plus' and 'quam', and we then have:


```
[ { text: 'Bella',
    id: '1-1',
    index: 0,
  },
  { text: 'per',
     id '1-2',
    index: 1,
  },
  { text: 'Emathios',
    id: '1-3',
    index: 2,
  },
  { text: 'plusquam',
    id: '1-4-m-1',
    index: 3,
  },
  { text: 'ciuilia',
    id: '1-6',
    index: 4,
  }
]
```

Use splits 'Emathios' after 'Em' and we then have:


```
[ { text: 'Bella',
    id: '1-1',
    index: 0
  },
  { text: 'per',
     id '1-2',
    index: 1
  },
  { text: 'Em',
    id: '1-3-s1',
    index: 2
  },
  { text: 'athios',
    id: '1-3-s2',
    index: 3
  },
  { text: 'plusquam',
    id: '1-4-m1',
    index: 4
  },
  { text: 'ciuilia',
    id: '1-6',
    index: 5
  }
]
```

User changes their mind and merges 'Em' and 'athios' back together, so we have:


```
[ { text: 'Bella',
    id: '1-1',
    index: 0
  },
  { text: 'per',
     id '1-2',
    index: 1
  },
  { text: 'Emathios',
    id: '1-3-s-1-m-1',
    index: 2,
  },
  { text: 'plusquam',
    id: '1-4-m-1',
    index: 3,
  },
  { text: 'ciuilia',
    id: '1-6',
    index: 4
  }
]
```

And so on. what do you think?

**Comment by irina060981** [comment]
>as we discussed in the check-in, if it's not too much work, I would like to make the possibility to edit the text of a token a configurable option. With the current UI design, this would mean restricting the edit to insertion of a space for the split token functionality.

Will add it in a new PR

**Comment by irina060981** [comment]
>I am not sure of the best way to deal with the restriction on editing tokens which have already been aligned. This is something we will need to get user feedback on. But, going with the approach you have taken for now, I think we should visually identify those tokens that cannot be edited by not outlining them, and having a popup help which says that they need to be un-aligned before they can be edited.

Oh, I think it should be useful, I could guess it myself.
will add it in a new PR

**Comment by irina060981** [comment]
>For the token ids,I see that you have a freeIdWord getter on segment that isn't used yet. I would like for us to be able to differentiate the ids of tokens which have been created or changed via the editor from tokens that were part of the original tokenization, and if possible, retain some sort of history. What do you think about the following approach:

I have forgotten to remove `freeIdWord ` from the segment.
A new `idWord` is defined inside `AlignedText.getNewIdWord`:

```
  getNewIdWord (segment) {
    const getNextIdWordMethod = TokenizeController.getNextTokenIdWordMethod(this.tokenization.tokenizer)
    return getNextIdWordMethod(segment.lastTokenWordId)
  }
```

So finally `idWord` is defined inside `TokenizeController`  depending on the current `tokenizer`

**Comment by irina060981** [comment]
> What do you think about the following approach:
tokens which are merged get new Ids in the format --m-
tokens which are split each get new ids in the format --s-
tokens which are edited each get new ids in the format --e-
tokens which are added at the beginning or end of a segment get ids in the format -x-

I am not sure that it would be useful for any purposes, because such idWord stores ver less information for interpreting.
And I don't know who would use the information, that this token was splitted to some unknown parts for example, and then merged with something unknown. But if you know benefits from this solution - I could do this :)

**Comment by balmas** [comment]
> > What do you think about the following approach:
> > tokens which are merged get new Ids in the format --m-
> > tokens which are split each get new ids in the format --s-
> > tokens which are edited each get new ids in the format --e-
> > tokens which are added at the beginning or end of a segment get ids in the format -x-
> 
> I am not sure that it would be useful for any purposes, because such idWord stores ver less information for interpreting.
> And I don't know who would use the information, that this token was splitted to some unknown parts for example, and then merged with something unknown. But if you know benefits from this solution - I could do this :)

the main reason is for documentation of the alignment process. I think we might also report this information in the exported alignment.  I'd like to try it.

**Comment by irina060981** [comment]
@balmas , I have some questions about requirements:
>it should give an ability to merge, separate tokens, update tokens metadata

what properties of a token do you mena here saying `update tokens metadata`, is it enough to edit a `word`? or we should give an ability to update `idWord` and check its unique after?

>it should also offer the option to apply a tokenization change (i.e. a split or a merge) globally across the entire text.

what do you mean here? do you mean to add an additional form with inputs, and then search for such words and update without limiting to a segment?

or the following:
> additional requirement:
> when merging or splitting tokens, the user should be offered the option to apply the action to all like tokens in the aligned text

should it be limitted to the text instance?

**Comment by irina060981** [comment]
@balmas , I suggest to close this issue after merging.

All requirements are realised besides the following:
>it should also offer the option to apply a tokenization change (i.e. a split or a merge) globally across the entire text.

And this requirement is defined inside #82

**Comment by irina060981** [comment]
Merged and closed

**Comment by irina060981** [comment]
Realized features to be checked:

Tokens Editor
1. becomes available after source texts were tokenized; 
2. if a new targetText was added after texts were already tokenized, a user should tokenize a new target text; it should appear in both editors - alignment groups and tokens edit
3. there are several features that are available in the editor:
    - **insert new tokens** at the begininng of the first segment and to the end of the last segment;
       to do this - a user should type words in the empty text inputs and press Enter, they would be divided to tokens by spaces;
       
4. other features become available after a user click on the token's input

![image](https://user-images.githubusercontent.com/12377640/105653925-ace50780-5f08-11eb-8369-c4d543f28830.png)

   - **update a token**; 
      **availability** - it is available if the global option in the options **Allow update token word** is checked
      **workflow** - click on the input, type anything, click on the first icon  ![image](https://user-images.githubusercontent.com/12377640/105654155-22e96e80-5f09-11eb-9cf3-df0340c747be.png)
      
   - **merge with a left token**; 
      **availability** - it is available if there is a left token in the segment
      **workflow** - click on the second icon  ![image](https://user-images.githubusercontent.com/12377640/105654181-2ed53080-5f09-11eb-994a-3689bdb07e7c.png)

**Comment by irina060981** [comment]
@monzug , I described all final features that were agreed with @balmas.
Also I would be glad to have your feedback about styles - margins, fonts, colors for the editor and your comments about errors texts and tooltips, would update them upon your check.

**Comment by monzug** [comment]
@irina060981 , will look into all options step by step. at the moment I have one question:
What does "Words would be separated to tokens by spaces. Click Enter to insert tokens." mean? Could it be: words would be separated from the tokens by spaces.   or     words would be separated into tokens...?

**Comment by irina060981** [comment]
@monzug , oh, my english fails sometimes :)
then I think it would be correct - 
"Words would be separated into tokens by spaces"

for example,

A user types to the input - 
`test starting text`
would be divided to 
'test' 'starting' 'text'

![image](https://user-images.githubusercontent.com/12377640/105819577-13028500-6004-11eb-8923-764140912162.png)

![image](https://user-images.githubusercontent.com/12377640/105819607-1dbd1a00-6004-11eb-9f58-ae4e27c73d81.png)

**Comment by monzug** [comment]
@irina060981  Thanks for the explanation. will try asap, then we will double check with Harry for the best terminology.

a super minor thing. Can we remove the dots from tooltip? see what happens in arabic when also dots move from left to right!!!

![Screen Shot 2021-01-26 at 3 57 05 PM](https://user-images.githubusercontent.com/41396793/105862465-1429b700-5ff0-11eb-93d4-ccfb31fb2749.png)


![Screen Shot 2021-01-26 at 3 56 53 PM](https://user-images.githubusercontent.com/41396793/105862468-14c24d80-5ff0-11eb-9f1c-a75d49c4909f.png)

**Comment by monzug** [comment]
maybe, just: "Each token needs to be separated by space. Click Enter to insert tokens." or. "Each token has to be separated by space. Click Enter to insert tokens."

**Comment by irina060981** [comment]
oh, will check it and remove dots

**Comment by irina060981** [comment]
@monzug, 
1. I remove dots and removed right aligning for tooltip
![image](https://user-images.githubusercontent.com/12377640/105989550-04dc6380-60ed-11eb-9739-9d186f10e167.png)

2. Updated description to "Each token needs to be separated by space. Click Enter to insert tokens."

**Comment by monzug** [comment]
Thanks!

**Comment by monzug** [comment]
need to finish testing all the options.

@Irina, questions:
1) How do I ungroup a selection in the alignment group when it's only on one side?
see attachment
![Screen Shot 2021-02-02 at 5 10 51 PM](https://user-images.githubusercontent.com/41396793/106628007-a2b2b100-6579-11eb-8949-3db285c3c98f.png)

2) is it ok to move all tokens out of a segment till it's empty (I can always move them back in)? I could not find anything in the issue, just wondering. it might be a no-issue at all.
see attachment
![Screen Shot 2021-02-02 at 5 13 39 PM](https://user-images.githubusercontent.com/41396793/106628381-089f3880-657a-11eb-8e60-b478f131c394.png)

**Comment by irina060981** [comment]
> How do I ungroup a selection in the alignment group when it's only on one side?
see attachment

From the requirements we have the following - active alignment group - 
 - if you click on the grouped token that is from the text (origin or target) that was the first - then the group would be finished (if you have tokens from both texts)
 - if you click on the grouped token that is from the text that was not first - it would be removed from the group
 
 So there is no way to remove tokens from the group from the first text (as in your case). 
 
 I could suggest only the folowing - to select a token from the second text (target in your case), then finish the group by clicking on any grouped token from the origin text. Then activate by clicking on the grouped token from the target text. And this way you would be able to remove tokens from origin part of the group.
 
 Or you could suggest how to expand requirements :)

**Comment by irina060981** [comment]
>is it ok to move all tokens out of a segment till it's empty (I can always move them back in)? I could not find anything in the issue, just wondering. it might be a no-issue at all.

Oh, I think it is not good, because we have a check on the same amount of segments. And this way - it would be broken.
May be we should set a limit?
Monica, what do you think?

Should I writre a letter to all - Bridgit and Harry with this question?

**Comment by monzug** [comment]
we should create a list of outstanding issues and then ask for their help.
this could be added to the list.

**Comment by irina060981** [comment]
Ok Will create this list - thank you :)

**Comment by monzug** [comment]
let's do a new issue with the two above questions. #149

**Comment by monzug** [comment]
This is fully tested. If I see problems, I will enter as new issues. Thanks.
