### ISSUE TITLE
Change the title of Options for Edit Text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#390]
Right now, the title for Options for Enter text is Options for Text Align. Pls change into Options for Edit Text or Text Edit

![Screen Shot 2021-05-17 at 5 11 04 PM](https://user-images.githubusercontent.com/41396793/118512539-311aff00-b733-11eb-8426-98dde1743cff.png)

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
Thanks
