### ISSUE TITLE
Clear text via X takes two steps

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#392]
Enter one letter in Original text to enable the X in the edit box. Click on the X, the interface remove the top navigation but does not clear the single letter entered. Click one more time on the X, this time the text is cleared. see screenshots

![Screen Shot 2021-05-18 at 4 07 12 PM](https://user-images.githubusercontent.com/41396793/118666437-7a328800-b7f3-11eb-8b2b-cb89bd323d64.png)

![Screen Shot 2021-05-18 at 4 07 21 PM](https://user-images.githubusercontent.com/41396793/118666474-80c0ff80-b7f3-11eb-8219-70924f1ceb9d.png)

**Comment by irina060981** [comment]
it is not an easy problem:
there are two oposite actions 
  - save a text on unfocus (click on the ex - is unfocus) and hide upload button
  - clear text on x-click and show upload button
  
  on show button - the place of the ex-button is changed and click doesn't have enough time to execute
  
  I added a small delay to resolve it

**Comment by monzug** [comment]
I marked  it fixed as it does happen always when the box is still highlighted and the Type or paste in text or Choose text to upload are still visible.
