### ISSUE TITLE
Chinese is repeated twice in drop-down languages

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#393]
we have two Chinese in drop-down language, one with ZH code and the other has ZHO code. We should remove one or rename it with a more significant name.
see screenshot

![Screen Shot 2021-05-18 at 6 21 18 PM](https://user-images.githubusercontent.com/41396793/118688170-1796b780-b806-11eb-8cf5-57f0da458063.png)

**Comment by irina060981** [comment]
Removed with zh code - as we support 3 chars in language code

**Comment by monzug** [comment]
Thanks. Fixed in Alpheios Translation Alignment editor 1.3.3 (build development.20210519.98)
