### ISSUE TITLE
Change Options titles

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#396]
We use Align Text, Edit Text, Enter Text in the interface, but in the Options we use Text Align, Text Edit, Text Enter. We should be consistent and use Options for Align Text, Options for Edit Text, Options for Enter Text.

**Comment by irina060981** [comment]
Agree completely - fixed

**Comment by monzug** [comment]
this is fixed in Alpheios Translation Alignment editor 1.4.1 (build development.20210528289)
