### ISSUE TITLE
Can we clear the file name  from the interface after uploading a json file from the menu?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#399]
I uploaded a file from the Resume previous alignment from the slide menu. I noticed that in the Original Choose File, the file name is populated by a previous attempt to upload a json from choose file. Can we clear the file name from the interface after uploading a json file from the menu?

see screenshot

![Screen Shot 2021-05-21 at 11 28 11 AM](https://user-images.githubusercontent.com/41396793/119116475-92d7b380-ba28-11eb-9dcb-5e406ab29bb3.png)

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
now I am getting no file 

![Screen Shot 2021-05-28 at 5 55 16 PM](https://user-images.githubusercontent.com/41396793/120010934-07d55b00-bfde-11eb-8633-e6bfbfe133ba.png)

**Comment by irina060981** [comment]
I think that it is fixed with https://github.com/alpheios-project/alignment-editor-new/issues/400

**Comment by monzug** [comment]
regarding the file type after the error, I think this is ok
![Screen Shot 2021-10-12 at 3 00 49 PM](https://user-images.githubusercontent.com/41396793/136961448-91795b84-d644-4760-8a2a-16d21c97a814.png)
