### ISSUE TITLE
Upload is still available after alignment

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#400]
It's possible to upload a file in Original after the alignment has occurred. I ended up in a situation in which I cannot delete any texts in Enter text or redo an alignment. We should prevent this from happening.
in the old version the upload is disabled as soon as an alignment is created.
See related issue #399 

steps to repro:
1) upload a json file from the interface in Original, an error is generated and the filename is printed next to Choose File.
2) go to Resume previous alignment and choose a json file.
3) go to Enter Text, and see that the Choose File is still available (and also DTSAPI) and that I can upload a new file in Original. see screenshot

![Screen Shot 2021-05-21 at 11 52 14 AM](https://user-images.githubusercontent.com/41396793/119118963-05e22980-ba2b-11eb-9084-a693970ba2c7.png)

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
fixed.
