### ISSUE TITLE
Cannot select any tokens in Align Text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#401]
This is a scenario that I have experienced few times. After Undo/Redo grouping of tokens, the selection of tokens is not longer possible. It does sort of freeze the alignment editor after the message Choose an other token from the same segment is generated.
to repro, links few tokens, then use the Undo button. Then click on a token that cannot be link to an other token so that the message "Choose an other token from the same segment" is generated. Now if you click on any tokens, it's not possible to do any grouping. if the text is split in segments,  it's only possible to group the tokens only in one segment. when that grouping is done then it is possible to do groupings in other segments.

![Screen Shot 2021-05-21 at 10 24 26 AM](https://user-images.githubusercontent.com/41396793/119140648-b6105c00-ba44-11eb-99c3-c98f00b613a8.png)

**Comment by irina060981** [comment]
Tried several scenarios similiar to what you described.
I could not reproduce it.
May be it was solved .
Waiting for your verification.

**Comment by monzug** [comment]
I was able to reproduce on first try in build Alpheios Translation Alignment editor 1.4.1 (build development.20210622.39) 
I followed the steps above: aligned few words, undo all the alignments then try to align one word from segment e.g. B to a word from different segment e.g. A, the message is generated and I cannot do any other alignment on the segment A.

**Comment by irina060981** [comment]
I checked this issue with a new undo/redo workflow - I was not able to reproduce
May be you will have time to check it again?

**Comment by monzug** [comment]
I cannot reproduce the scenario any longer after message "Choose another token please - from the same segment, translation text." is generated.
