### ISSUE TITLE
The DTSAPI pop-up for uploading texts selection is truncated

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#402]
Tested in Alpheios Translation Alignment editor 1.3.3 (build development.20210519.98) in both Mac and PC.

the pop-up is truncated so I cannot see the Upload and Cancel buttons. this was working in Alpheios Translation Alignment editor 1.3.1 (build i153-update-messages.20210331618), the old version on Irina's environment.

![Screen Shot 2021-05-21 at 2 58 44 PM](https://user-images.githubusercontent.com/41396793/119141925-28ce0700-ba46-11eb-9c06-00cd6f04e649.png)

**Comment by monzug** [comment]
tested in Alpheios Translation Alignment editor 1.4.1 (build development.20210528289)
buttons are now visible but sometimes are overlapping with the pop-up border - tested in FF and Safari
(prometeus, Libation, Thebes, Agamemnon, Suppliant Women)

![Screen Shot 2021-05-28 at 3 48 01 PM](https://user-images.githubusercontent.com/41396793/119994563-fdf72c00-bfcc-11eb-8661-16fe16881918.png)

**Comment by irina060981** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/12377640/122666630-e0933780-d1f1-11eb-92d3-78336e2013cd.png)

**Comment by monzug** [comment]
tested in Chrome and FF on Mac and PC and Safari. all looking good.
