### ISSUE TITLE
in case of Arabic, direction is right to left for the header too

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#406]
Just noticed that when the direction changes from left to right to right to left as for Arabic language, also the header of the box changes direction. I do not think it should, but pls confirm if this was a requirement. Thanks

![Screen Shot 2021-05-22 at 10 24 13 PM](https://user-images.githubusercontent.com/41396793/119497149-84f59b80-bd64-11eb-93a2-1a339d675efc.png)

**Comment by monzug** [comment]
I asked Harry and he thinks it's a bug too.

**Comment by irina060981** [comment]
Thank you, @monzug !
Yes it is a bug after some interface changes - fixed

**Comment by monzug** [comment]
this is fixed in Alpheios Translation Alignment editor 1.4.1 (build development.20210528289)
