### ISSUE TITLE
Can we highlight in red the characters count when it does exceed the max number as it was before?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#408]
I think that it can be difficult to understand that the Prepare texts for alignment button is not active because the characters count has exceeded the max number. 

current version
![Screen Shot 2021-05-26 at 3 15 45 PM](https://user-images.githubusercontent.com/41396793/119666145-61e6ec80-be35-11eb-97cf-f9b35bf7477d.png)

previous version
![Screen Shot 2021-05-26 at 3 22 35 PM](https://user-images.githubusercontent.com/41396793/119667159-4e885100-be36-11eb-91fd-c3e9b485cdd4.png)

**Comment by irina060981** [comment]
Thank you for the catch - fixed
![image](https://user-images.githubusercontent.com/12377640/119955857-d2cc0700-bfe3-11eb-8413-b83faad1ab0f.png)

**Comment by monzug** [comment]
this is fixed in Alpheios Translation Alignment editor 1.4.1 (build development.20210528289)
