### ISSUE TITLE
Html output header for Arabic goes right to left

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#412]
tested in FF 89
similar to #406 
the header of the html box changes direction too.

see screenshot
this is the case in which direction hasn't changed 
![Screen Shot 2021-06-01 at 2 46 52 PM](https://user-images.githubusercontent.com/41396793/120326256-d5cb3e00-c2e8-11eb-8e47-11a85f658075.png)

if direction is right to left, the header goes right to left too
![Screen Shot 2021-06-01 at 2 42 50 PM](https://user-images.githubusercontent.com/41396793/120326739-5722d080-c2e9-11eb-9ccc-3c0ecb74ac76.png)

**Comment by irina060981** [comment]
Fixed
![image](https://user-images.githubusercontent.com/12377640/122666377-2818c400-d1f0-11eb-8d49-696a873ddcc8.png)

**Comment by monzug** [comment]
tested in FF and Chrome, Mac. fixed.

![Screen Shot 2021-06-21 at 3 09 06 PM](https://user-images.githubusercontent.com/41396793/122767213-b2216500-d2a2-11eb-9467-ee2b746ed3b8.png)

![Screen Shot 2021-06-21 at 3 14 57 PM](https://user-images.githubusercontent.com/41396793/122768578-06791480-d2a4-11eb-8859-c958b363d9be.png)
