### ISSUE TITLE
Upload options not available for Translation

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#413]
tested in FF and Chrome in Mac and PC
Upload a text file in original and a tei file in Translation. The error message that the lines do not match is generated. Click on the X in the Translation box to clear the text. The options to upload a text file or to choose a file are shown. If I click on the enter text box and then again outside the box, the options to upload are all gone. The only way to proceed with the alignment is to copy or edit text or to choose to start a new alignment.

![missing-text-to-upload](https://user-images.githubusercontent.com/41396793/120356384-4a46b280-c2d2-11eb-8ee7-8a164317538b.JPG)

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
tested in Chrome on PC, Safari and FF on Mac. works fine now. Thanks
