### ISSUE TITLE
A minimum and max  in Max characters per part 

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#423]
Set a minimum and max  in Max characters per part (recommended for performance)? default is 1000 but you can also set it to 0

**Comment by irina060981** [comment]
There are two checks now:
1) min/max by input field (when you change value using input buttons)
2) a check on change option event:
    if a user set a value less than min - min value would be applied
    if a user set a value more than max - max value would be applied

**Comment by monzug** [comment]
range is 1-50000

set to 50000, I had some memory issue on the 3rd part. see screenshot

![unresponsive](https://user-images.githubusercontent.com/41396793/122234027-83625380-ce8a-11eb-8d65-d5e9e529c739.JPG)

**Comment by irina060981** [comment]
>range is 1-50000. shall we revisit the limits?
set to 50000, I had some memory issue on the 3rd part. see screenshot

It is dependent on the computer resources

Anyway - I don't have aby preferances for these limits - would put any values you like

**Comment by monzug** [comment]
let's discuss with Harry

**Comment by monzug** [comment]
it seems that we are all ok with the range so I am going to close this one.
