### ISSUE TITLE
IndexDB: text is repeated in both Original and Translation for DTSAPI upload

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#425]
Upload the first two sections of Metamorphoses by Ovid and do the alignment.  I did try this few times as the next button was not working properly, then I realized that actually it was a combination of the next button and the uploaded text acting funny. After lines 30, the words are repeated several times in both Original and Translation texts. it looks like a memory problem. see screenshots:

![Screen Shot 2021-06-14 at 4 19 36 PM](https://user-images.githubusercontent.com/41396793/121907546-70d20800-cd2c-11eb-93f5-2a972c2aca76.png)

![Screen Shot 2021-06-14 at 4 19 54 PM](https://user-images.githubusercontent.com/41396793/121907541-6fa0db00-cd2c-11eb-9fbb-d6b1b757ba54.png)

**Comment by monzug** [comment]
an other example
![Screen Shot 2021-06-15 at 12 30 13 PM](https://user-images.githubusercontent.com/41396793/122039209-b814d300-cdd6-11eb-84f6-e343946021e5.png)

**Comment by monzug** [comment]
tested on Chrome/PC after clearing all alignments, still reproducible

![memory-latin-text](https://user-images.githubusercontent.com/41396793/122228463-dc7bb880-ce85-11eb-9f1f-62b06ee6f66c.JPG)

**Comment by irina060981** [comment]
@monzug, could you record a video from the screen with opened console, this way I would probably see some information - for now I don't have idea - what is the problem here, as I could not reproduce it.

**Comment by monzug** [comment]
I could not longer reproduce this scenario in build Alpheios Translation Alignment editor 1.4.1 (build development.20210622.39) - tested in Chrome/PC and FF/Mac
