### ISSUE TITLE
Add feature - Clear IndexedDB

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#427]
- add ability to remove all alignments from IndexedDB
- add ability to remove a single alignment from IndexedDB

**Comment by irina060981** [comment]
Features are added
![image](https://user-images.githubusercontent.com/12377640/122152903-4d7e9880-cea5-11eb-8d4f-1bc570121f1e.png)

**Comment by monzug** [comment]
I cannot reach the Clear Alignments button on Chrome/Mac as I have a list longer than the 2 alignments in the example. I think we should make it scrollable.

![Screen Shot 2021-06-16 at 2 37 44 PM](https://user-images.githubusercontent.com/41396793/122220528-b0c1f800-ceb0-11eb-9bbc-96d02ef32224.png)

**Comment by irina060981** [comment]
The layout is fixed - scrolling is enabled

**Comment by irina060981** [comment]
@monzug, @abrasax  , I tried to reproduce freeze Safari on Mac deleting alignment by one, but was not able.
May be you had much more information in IndexedDB. It is dependent on its capacity.

That's why I added printing specific logs to console:

![image](https://user-images.githubusercontent.com/12377640/122320830-39e73680-cf66-11eb-96ea-13283c6db457.png)

So if you face with such freeze behaviour again - you will be able to send me logs from console and we could try to estimate - what ObjectStore / what amount of items in it make IndexedDB hang on.
But I hope if we define some clear workflow - users would be able to avoid it.

IndexedDB is not the same as big Databases that are placed to server. It is used for a limited amount of cases. So we should be careful working with it.

**Comment by monzug** [comment]
Now the page os scrollable so I can see the Clear alignments button.

as per delete of an alignment (or clear alignments), as you said, it depends on the size of the file. If I have relatively small files (30 to 155KB) all goes smoothly. if I have a bigger file (such as 5MB) the delete action takes a long time to perform.

**Comment by monzug** [comment]
scrolling through the files. FIXED. Thanks

![Screen Shot 2021-06-17 at 3 32 03 PM](https://user-images.githubusercontent.com/41396793/122406765-6492b880-cf81-11eb-9d8a-a0f5416e7700.png)

**Comment by irina060981** [comment]
It is a normal behaviour that browser needs several minutes to delete data from the IndexedDB - when it is very big (5 Mb) - 27422 tokens - it is really very big.
I wouldn't delete logs for now - lets track them.

**Comment by monzug** [comment]
ok. I'll verify the scrolling feature. feel free to close this one
