### ISSUE TITLE
Move Max characters per part to Text Edit screen

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#429]
Move Max characters per part option to Text Edit screen Options.
This way we would prevent user from redefining parts after text was already divided to parts.

If texts are already aligned and divided to part, and user will go to the text enter screen and chnage this option - text won't be redivided. The only way to redefine parts - change option, download to json, upload from json - parts would be redivided.

**Comment by irina060981** [comment]
Done

**Comment by monzug** [comment]
max chars has been moved to Enter Text. however,  see below two issues:
1) it's not so obvious to make the connection that this option is used in Align Text. we should add that Max characters per part (recommended for performance)  is  "to be used in Align Text"
2) the other point is that after alignment I cannot change the parts but I have to start over, as you have very well explained above. In the previous version, the parts could be changed in Align Text, although causing loading problems.

**Comment by irina060981** [comment]
>it's not so obvious to make the connection that this option is used in Align Text. we should add that Max characters per part (recommended for performance) is "to be used in Align Text"

I could add this text to the label of the option

**Comment by irina060981** [comment]
>the other point is that after alignment I cannot change the parts but I have to start over, as you have very well explained above. In the previous version, the parts could be changed in Align Text, although causing loading problems.

yes, it was the aim of these change. Do you have any question at this point?

**Comment by irina060981** [comment]
Label is updated

![image](https://user-images.githubusercontent.com/12377640/124339448-e45f8a80-dbf1-11eb-9c58-b38452b4a347.png)

**Comment by monzug** [comment]
"to be used in Align text" has been added
