### ISSUE TITLE
IndexDB: few questions/issues

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#432]
related to #427 

1)  I think the indexDB files in the Resume previous alignment should be order by date of creation. right now, I am not sure what the order is. could it be by size?

2) IndexDB files are only selectable from splash screen. is this a permanent implementation?

3) from IndexDB file type I cannot distinguish the full alignment from the alignment saved in enter text only. 

![Screen Shot 2021-06-16 at 2 37 44 PM](https://user-images.githubusercontent.com/41396793/122225111-0ef0da00-ceb5-11eb-85b6-f24a74af56b5.png)

**Comment by irina060981** [comment]
>I think the indexDB files in the Resume previous alignment should be order by date of creation. right now, I am not sure what the order is. could it be by size?

there is no default ordering in IndexedDB - so if we want to order it - I need to add sorting after data is retrieved from the IndexedDB. I haven't done it.

**Comment by irina060981** [comment]
>IndexDB files are only selectable from splash screen. is this a permanent implementation?

Yes, it was done for the first version.
After there would be requirements where to put it besides initial screen - I would do that

**Comment by irina060981** [comment]
>from IndexDB file type I cannot distinguish the full alignment from the alignment saved in enter text only.

Yes, this data is not available on this step - when I retrieve only common information from the DB.
If we want to show the state of the alignment - I would need to do additional development.

**Comment by monzug** [comment]
let's move to discussion then

**Comment by monzug** [comment]
1) and 3) have been implemented.

**Comment by irina060981** [comment]
>IndexDB files are only selectable from splash screen. is this a permanent implementation?

Decided on the meeting to leave as is
