### ISSUE TITLE
redo not active until 2nd undo

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alignment-editor-new#44]
to reproduce:

click word A in the origin text
click word B in the translation text
click word A in the origin text (to save the alignment group)
click Undo
see that Redo is NOT active
click Undo again
see that Redo is active

shouldn't Redo be available with the first Undo?

**Comment by irina060981** [comment]
It was from the question - how we track finishAlignmentGroup as a step (we were talked about it before).
I suggest a simple solution on the PR.

**Comment by irina060981** [comment]
Merged and closed
