### ISSUE TITLE
Missing tools in resume previous alignment

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#446]
Tested in FF and Safari on Mac and Chrome on PC, build Alpheios Translation Alignment editor 1.4.1 (build development.20210622.39) 

When I choose a file from the list of previous alignments, the align text screen does not show the tools. I would expect the same behavior as when I edit or upload a file in enter text. I do not see any reason why it should not be the same.  see attachment

![Screen Shot 2021-06-24 at 3 30 09 PM](https://user-images.githubusercontent.com/41396793/123271424-19d4eb80-d501-11eb-9610-34079bc894ce.png)

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
tested in Alpheios Translation Alignment editor 1.4.1 (build development.20210705250)
Chrome, Safari and FF on MAC. this is fixed, thanks
