### ISSUE TITLE
make it more obvious that align requires selection of origin text language

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alignment-editor-new#45]
When creating a new alignment, the Align button isn't active until the language of the origin text is explicitly selected. 

We need to make this more visually obvious to the user

**Comment by irina060981** [comment]
The problem here is the following - alignmentUpdate flag changes on blur event.
So I simply check in another textarea and Align button is activated (alignmentUpdate flag is updated).

I am glad to get feedback about it - then I should change event on key press.

**Comment by irina060981** [comment]
I decided that to add a simple check with watch would be better - it would reduce transactions for the data.
Because when you click a button, `blur` event would be emitted first and then `click` event button would be emitted .

**Comment by irina060981** [comment]
Merged and closed
