### ISSUE TITLE
Edit text in indexDB shows only the first part

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#453]
It looks like I can only see the first part in Edit text. When I go to next part (or 3rd  or 4th part), the part display in Edit text does not get updated. it does show the first part only. see screenshots
Align text is on 6th/7th part

![Screen Shot 2021-07-09 at 5 48 07 PM](https://user-images.githubusercontent.com/41396793/125104624-e20f9b80-e0dd-11eb-8335-2d01da3f3905.png)

edit text does still show the first part

![Screen Shot 2021-07-09 at 5 49 17 PM](https://user-images.githubusercontent.com/41396793/125104741-010e2d80-e0de-11eb-8686-a7506a567afe.png)

Is there a way to sync the parts in Edit text and Align text?

**Comment by irina060981** [comment]
I still need to work on this screen. 
Thank you for raising it - because I forget about this issue.

**Comment by irina060981** [comment]
- added visual navigation by parts on Edit Text Screen
- added updated uploaded parts from navigation on Align Text Screen
- added check for enterning tokens to the start nad to the end of the text

![image](https://user-images.githubusercontent.com/12377640/125151000-5e11ee00-e187-11eb-8827-22abdaa4deeb.png)

All navigation is done only on Align Text Screen.

I didn't realize a feature to navigate on Edit Text Screen (it needs much bigger development).
We discussed this with @abrasax before IndexedDB development.

**Comment by irina060981** [comment]
Also I need to check and fix saving undo/redo to IndexedDB.

**Comment by irina060981** [comment]
Undo/redo for tokens editor is updated for saving results to IndexedDB

**Comment by irina060981** [comment]
Also I need to check and update undo/redo with saving to IndexedDB on Align text screen.

**Comment by monzug** [comment]
as you are looking into edit text, could you pls fix the merge with right or left token?

**Comment by irina060981** [comment]
>as you are looking into edit text, could you pls fix the merge with right or left token?

what issue do you mean?

**Comment by monzug** [comment]
it does not work. when you merge the right or left it does not merge the
tokens.

**Comment by monzug** [comment]
I noticed this yesterday when I briefly looked at the above fix for Edit
text

**Comment by irina060981** [comment]
>it does not work. when you merge the right or left it does not merge the
tokens.

How could I reproduce it? it works properly in tests and I see how it works manually.

**Comment by monzug** [comment]
Ok. Will add more info tomorrow. Thanks

**Comment by irina060981** [comment]
this issue is fixed

**Comment by monzug** [comment]
Tested in Alpheios Translation Alignment editor 1.4.1 (build development.20210715259) with a big alignment of Characters count - 29086 (max - 50000)
Tokens can be insert at the beginning and end of the alignment. Edit text is in sync with align text. I checked with initial part, middle part and last part of the big file above.
