### ISSUE TITLE
Save undo/redo in Tokens Editor to IndexedDB

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#457]
I need to check how undo/redo works in Tokens Editor and how it is saved to IndexedDB

**Comment by irina060981** [comment]
Checked, updated
Unit tests are made

**Comment by monzug** [comment]
I just realized that undo/redo in the edit text does also undo/redo aligned tokens. see screenshots below

<img width="1366" alt="Screenshot 2021-07-26 at 11 21 56" src="https://user-images.githubusercontent.com/41396793/127015281-efffd725-be68-4ff2-9c48-00e105251591.png">

<img width="1377" alt="Screenshot 2021-07-26 at 11 22 11" src="https://user-images.githubusercontent.com/41396793/127015298-aaee29f0-646e-4e20-a59b-89d7bfe972d7.png">

<img width="1378" alt="Screenshot 2021-07-26 at 11 22 22" src="https://user-images.githubusercontent.com/41396793/127015321-dc003089-6131-44df-8e36-2149314c8cb3.png">

**Comment by irina060981** [comment]
Such an interesting bug - will investigate

**Comment by irina060981** [comment]
Workflow is refactored - bug is fixed

**Comment by monzug** [comment]
works fine in build 9/22. the undo in edit text will undo only the editing done in edit text even if the word I merged is inside a created alignment group. I think this is ok.

**Comment by irina060981** [comment]
if I understood you right , you point to the following case:
- we edit a token
- then created an alignment group with it
- then undo on EDIT screen and this way re-edit grouped token

This histories are quite independent from each other. If we want to prevent from such editing - then we need to add a rule:
- if any edited token was grouped -> clear edit history (and then we prevent from editing using undo/redo)

I decided not to do it.

The other way is to create a single workflow for both - creating groups and editing tokens - I could do it, but I decided that it would be confusing in the current design.

So finally - it is not pretty, but this behaviour is designed.
If we want to change it using one of described methods (or may be any other way), I think we weould need to create a new issue for it.
That's why I suggest to end with this issue and verify according to this desctiption.
Monica, what do you think?

**Comment by monzug** [comment]
Irina, I will enter a new one. I believe that any grouped token should not be edited but ungroup first then edit. The problem is mainly in the left over grouped token that in align editor is still grouped and you cannot ungroup by mouse over or undo. a little ugly.
