### ISSUE TITLE
Save undo/redo in Align Editor to IndexedDB

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#458]
I need to check how undo/redo works in Align Editor and how it is saved to IndexedDB

**Comment by irina060981** [comment]
Checked, updated
Unit tests are made

**Comment by monzug** [comment]
few issues with undo/redo

1) undo (and redo) action takes 3 steps to complete: both words highlighted, then undo the translation, next undo the original. However in indexedDB, the actual steps of Undo are two: the aligned word in the Original is still highlight. see screenshot below

![Screen Shot 2021-07-16 at 2 25 07 PM](https://user-images.githubusercontent.com/41396793/125992913-ff2f0a77-db5c-4ca4-bb88-050d57c4a560.png)

**Comment by irina060981** [comment]
>1. undo (and redo) action takes 3 steps to complete: both words highlighted, then undo the translation, next undo the original. However in indexedDB, the actual steps of Undo are two: see screenshot below where the aligned word in the Original is still highlight but Undo button is not clickable. to repro this scenario, you have to do 2 alignments and then click on Undo the last alignment. This needs to be fixed as the highlighted word can go unnoticed and then create issue when doing alignment with other translated languages (such as Choose another token please - from the same segment, translation text.)

you are talking about the state of the Undo button. Now I undestood.
Agree it should be fixed.

**Comment by irina060981** [comment]
>Undo (and Redo) works only for one alignment. Please confirm that this is due to the nature of indexedDB

What do you call alignment in this context? And are you asking about creating alignment groups? Or about saving to IndexedDB?

**Comment by irina060981** [comment]
>It's unstable when you scroll through parts and undo/redo few alignments. The Undo/Redo are both selectable but it's not clear what they are undoing/redoing. You keep clicking on undo but nothing happens. Could not see any error in the log related to this issue. basically when you get to the situation in the screenshot, Undo/Redo are not longer working.

Yes it is a limit for now - I didn't realise a feature about scrolling (also thrrough parts) on undo/redo clicking.
It is rather difficult.

**Comment by monzug** [comment]
> > Undo (and Redo) works only for one alignment. Please confirm that this is due to the nature of indexedDB
> 
> What do you call alignment in this context? And are you asking about creating alignment groups? Or about saving to IndexedDB?
> I didn't understand the question, I am sorry.

see video of alignments and how Undo works in build Alpheios Translation Alignment editor 1.3.3 (build dev.20210610374) 

https://user-images.githubusercontent.com/41396793/126174197-13276955-d538-41c5-a77d-19a8a0579735.mov

**Comment by monzug** [comment]
> > It's unstable when you scroll through parts and undo/redo few alignments. The Undo/Redo are both selectable but it's not clear what they are undoing/redoing. You keep clicking on undo but nothing happens. Could not see any error in the log related to this issue. basically when you get to the situation in the screenshot, Undo/Redo are not longer working.
> 
> Yes it is a limit for now - I didn't realise a feature about scrolling (also thrrough parts) on undo/redo clicking.
> It is rather difficult.

actually I was able to reproduce this error in the following scenario:
1) do some alignments
2) then resume previous alignment and upload the file with these alignments in it
3) undo each alignment by mouse over each aligned word, one by one. you'll see that the state of Undo/Redo is active (clickable) but they don't do anything.

![Screen Shot 2021-07-19 at 10 31 53 AM](https://user-images.githubusercontent.com/41396793/126177831-cecd77eb-b202-47e3-a52d-ce90d27ac220.png)

**Comment by monzug** [comment]
I was able to reproduce step 3 above in Chrome/PC build of  20/8. undo and redo just stopped working and they are both active clickable)

**Comment by irina060981** [comment]
Workflow is refactored - bug is fixed

**Comment by monzug** [comment]
tested in Safari (and Chrome and FF) on Mac. looks good. I was not able to reproduce the above errors with undo/redo.
