### ISSUE TITLE
Add ability to turn on/off indexeddb support

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#460]
Decided to implement on the on-line meeting

**Comment by irina060981** [comment]
added an option to Enter text options

![image](https://user-images.githubusercontent.com/12377640/125755123-f3813d17-5527-4a63-b976-b99edb01c8a4.png)

**Comment by monzug** [comment]
The Option is available in latest build Alpheios Translation Alignment editor 1.4.1 (build development.20210715259)
