### ISSUE TITLE
Add annotations to tokens

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#462]
Add a new feature - annotations to tokens:
- annotation could be one of the following type:
   - common comments
   - notes referenced to lemma ID
   - notes referenced to morphology data
- annotation could be added to any token
- available annotation's type are defined in options (or inside embedding code)
- each annotation has a heading and a textarea
- annotations should be exported to json
- annotations should be saved to IndexedDB

**Comment by irina060981** [comment]
from @balmas email :
about defining settings 

I think the simplest way to implement the annotation fields right now
would be to just extend the default app settings to include a setting
that contains a multi-select list of possible token-level annotation
fields to make available. It could just be a simple list of field names,
e.g. maybe just these to start:

* lemma

* morphology

* comments

Each field would just name a separate string-based annotation field, and
we wouldn't for now enforce any validation that what they have entered
is actually what the name of the field is.  So, if they put something in
the lemma field that isn't a lemma, that's their problem.

The user could select as many (or none) to include in the annotation
interface.  It would apply to all alignments they create, until they
change it.  If their selections don't match what is actually in data,
then the data would just be carried forward the way it is, but not be
editable by the user.

And maybe we could prevent them from making changes to this option while
they have an active alignment loaded, so that they can't change
mid-stream.  Then, when you are loading an existing alignment, if you
find annotation fields in it that don't match the list they have
selected, you could warn the user that they have fields that don't match
their selections and that they will be retained as-is but not be
available for editing.

**Comment by irina060981** [comment]
- added annotation mode switch on the Align Text Screen:  
![image](https://user-images.githubusercontent.com/12377640/128344274-7f6374c2-5fae-494a-86ba-066bf81b5958.png)
   - when it is not checked - click on the token updates alignment group
   - when it is checked - click on the token opens annotation modal
   
- if a token has no annotations - the following modal will open on the click - for a new annotation     
![image](https://user-images.githubusercontent.com/12377640/128345406-09801713-4bbe-48ad-9d7a-18fcc63fa12d.png)

- if a token already has annotations - a modal will look like the following:
![image](https://user-images.githubusercontent.com/12377640/128345841-322d21fc-ef79-421e-b12e-766dd0b80438.png)

- available types are defined in settings on Enter Screen
![image](https://user-images.githubusercontent.com/12377640/128345959-5e1e57f5-cc8e-412b-bce1-aaac5f5a7ae6.png)

when annotations are already created - this setting is not editable,
otherwise it would look like this
![image](https://user-images.githubusercontent.com/12377640/128346087-9d3aa522-d9c8-4556-9ca0-63d65e2453fe.png)

- as in our  case only lemmaId type is available that's why in the annotations modal:
![image](https://user-images.githubusercontent.com/12377640/128345841-322d21fc-ef79-421e-b12e-766dd0b80438.png)

the first annotation (comment type) is not editable - only visible,
the second annotation (lemmaId type) - has edit and delete icons

- if annotation text is too long - it would betruncated to the row in the list
![image](https://user-images.githubusercontent.com/12377640/128346440-9f1b942c-3a05-43ea-8ca1-2e5d45a1bc56.png)

if you click on it - it would be expanded
![image](https://user-images.githubusercontent.com/12377640/128346485-b52b0a16-f70a-496e-87a0-dc580518348d.png)

- annotations are saved to JSON and IndexedDB

**Comment by irina060981** [comment]
Added ability not to close popup on click away

**Comment by monzug** [comment]
Few questions:
1) any reason why we do not save to html?
2) the annotation 

Comments:
1) I believe it should be "Annotation Types" and not "annotation's type" in Options. 
2) the style of the above setting is awkward: the color, the font and the size of the arrows do not match the other settings
![Screen Shot 2021-08-10 at 3 24 18 PM](https://user-images.githubusercontent.com/41396793/128878734-0a2ee9a1-5047-440f-a7b5-e94aa1385f2d.png)

**Comment by irina060981** [comment]
>any reason why we do not save to html?

It is out of scope of requirements. If you and Harry will define to do it - I would spend time for this implementation :)

**Comment by irina060981** [comment]
>the check for annotation is under align text. I think it should be moved to Options (we do not have any settings there) but I do understand that this is a setting that can be turned on and off frequently. Honestly I am not so convinced about this location at the moment.

I don't agree with placing it to Options - because it is not an option and has very different workflow not similiar to options.
I think that such inconsistency is a bad choice - that will worsen the structure.

But I agree that it is difficult to find place for it. I didn't find a good one in the interface - that's why i placed it to the mostly visible part of the screen.

**Comment by irina060981** [comment]
> what's the max chars allowed in annotations? I was able to save successfully a full page from the latin library site as a comment.

Yes, there is no limits for annotations. Do you think I should place such a check? What max should I place?

**Comment by irina060981** [comment]
>I believe it should be "Annotation Types" and not "annotation's type" in Options.

Oh, thank you - will rename it.

**Comment by irina060981** [comment]
>The style of the setting below is awkward: the color, the font and the size of the arrows do not match the other settings

Agree - will adapt

**Comment by irina060981** [comment]
>The annotation mode when on, is not saved in indexedDB while it is in the json file. Any reason why such a difference?

I am not sure - what do you mean here - will check

**Comment by irina060981** [comment]
>If I have more than one comment (or morphology or lemmaID) would it be possible to add a number next to the comment such as comment 1, comment 2 etc?

Agree with this - will add

**Comment by monzug** [comment]
1) Irina, did you also make the change to save to html?

2) how to repro following comment: The annotation mode when on, is not saved in indexedDB while it is in the json file. Any reason why such a difference?
- have annotation mode checked, then save a file to indexedDB and next save as json file. When I resume previous alignment from slash screen so from indexedDB, the annotation is not checked. when I resume previous alignment from side menu and select the file that I just saved, the annotation mode is checked.


3) an other question, why do we have show annotations in pop-up after enable annotation mode on indexeddb file , but not in any other annotations? see below

![Screen Shot 2021-08-18 at 4 47 37 PM](https://user-images.githubusercontent.com/41396793/129921959-80903d45-d707-4600-9d11-df5b84a10f2c.png)

![Screen Shot 2021-08-18 at 4 52 38 PM](https://user-images.githubusercontent.com/41396793/129922005-b9ea1dff-f069-4398-8490-cfed46c095e4.png)

**Comment by irina060981** [comment]
>Irina, did you also make the change to save to html?

No, it is a big change - it would be done within a new issue

**Comment by irina060981** [comment]
>an other question, why do we have 'Show annotations' in pop-up after enable annotation mode on indexedDB file, but just 'Add annotation' button with list of existing annotations everywhere else? see below the two buttons.

I didn't fully understand your question.
**Show annotations** - shows a list of saved annotations
**Add annotation** - adds a new annotation

When you click on a token that doesn't have annotations - it would be open in a new annotation mode.
![image](https://user-images.githubusercontent.com/12377640/129978896-d39ff6ca-179a-4615-be1d-75b7ce0e1e84.png)

When you click on a token that has annotations - it would be open in a list mode.
![image](https://user-images.githubusercontent.com/12377640/129978923-8b3ca45d-87ef-41ba-aad8-f412712887cf.png)

What exactly do you see as incorrect?

**Comment by irina060981** [comment]
>how to repro following comment: The annotation mode when on, is not saved in indexedDB while it is in the json file. Any reason why such a difference?

Oh I see, thank you for the catch - will fix.

**Comment by monzug** [comment]
> > an other question, why do we have 'Show annotations' in pop-up after enable annotation mode on indexedDB file, but just 'Add annotation' button with list of existing annotations everywhere else? see below the two buttons.
> 
> I didn't fully understand your question.
> **Show annotations** - shows a list of saved annotations
> **Add annotation** - adds a new annotation
> 
> When you click on a token that doesn't have annotations - it would be open in a new annotation mode.
> ![image](https://user-images.githubusercontent.com/12377640/129978896-d39ff6ca-179a-4615-be1d-75b7ce0e1e84.png)
> 
> When you click on a token that has annotations - it would be open in a list mode.
> ![image](https://user-images.githubusercontent.com/12377640/129978923-8b3ca45d-87ef-41ba-aad8-f412712887cf.png)
> 
> What exactly do you see as incorrect?

Here is the inconsistency:
1) pop-up for first comment to be added (new alignment)
![Screen Shot 2021-08-20 at 2 18 26 PM](https://user-images.githubusercontent.com/41396793/130232167-cbf0f8d9-93b2-4e18-943f-f08c707a0b5b.png)
2) pop-up for any subsequent annotation (new alignment)
![Screen Shot 2021-08-20 at 2 19 30 PM](https://user-images.githubusercontent.com/41396793/130232264-20f6e8dd-3465-4649-a7d9-70db87052e24.png)
3) pop-up with Show annotations - see screenshot above. However I am not able to generate Show annotations anymore in  build development.20210820241

**Comment by monzug** [comment]
as per above issue: I can save an empty field for annotation (create a comment then go to edit and delete everything), I am still able to reproduce this in build development.20210820241

![Screen Shot 2021-08-20 at 2 45 13 PM](https://user-images.githubusercontent.com/41396793/130235834-8032e69f-4115-4a9a-a14d-373a2b857b8d.png)

**Comment by monzug** [comment]
2 the lemmaid and morphology are missing the pencil to edit and the bin to delete when I remove the related annotations type from Options. Not sure how it should work, actually. it might be the right way to implement this, just not sure. 

this is fixed by making all 3 types as default values, #474

**Comment by irina060981** [comment]
>as reported above in this issue: " I can save an empty field for annotation (create a comment then go to edit and delete everything)" I am still able to reproduce this in build development.20210820241

It is not a bug - there are no requirements what to do with empty text - should I delete an annotation if a user deletes the text?

**Comment by irina060981** [comment]
>ok, this is how it works:

And I didn't understand - do you see anything incorrect here? could you point on the ecxact bug if it is here

**Comment by irina060981** [comment]
>2 the lemmaid and morphology are missing the pencil to edit and the bin to delete when I remove the related annotations type from Options. Not sure how it should work, actually. it might be the right way to implement this, just not sure.

It is a designed behaviour as it was described in requirements

**Comment by irina060981** [comment]
@monzug , finally - is only a decision about what to do with empty text fields - is the last unsolved question here? 

Empty text field should be defined as a new issue with exact requirements for thw orkflow from my point of view, because there are no requirements in this issue.

If it is the last - I suggest to verify this issue.

**Comment by monzug** [comment]
yes, there are no other outstanding issues. will enter a new one for empty text field.

> @monzug , finally - is only a decision about what to do with empty text fields - is the last unsolved question here?
> 
> Empty text field should be defined as a new issue with exact requirements for thw orkflow from my point of view, because there are no requirements in this issue.
> 
> If it is the last - I suggest to verify this issue.

#486

**Comment by irina060981** [comment]
great - thank you!
