### ISSUE TITLE
Clear all alignments takes a long time

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#464]
Irina, I had only two files in the list and both pretty small. when I click on Clear Alignments, it loaded for really a long time so I had to manually remove each of them. see screenshots of loading and errors in log.
I am not sure if they are related but the time was the same in error log and on screen: 10:46am.

![Screen Shot 2021-07-19 at 10 46 40 AM](https://user-images.githubusercontent.com/41396793/126179911-53a9a355-dfd6-4051-bd61-da10c18b023e.png)

![Screen Shot 2021-07-19 at 10 46 57 AM](https://user-images.githubusercontent.com/41396793/126179930-282cee01-285d-4941-ab0f-01e8f967f7c1.png)

**Comment by monzug** [comment]
I did run an other test with two short files in the alignments list. I clicked on Clear alignments at 11.24am. from screenshot, you can see the time at 11.28am. I closed the pop-up at 11.30am. then manually removed each of them in no time.

![Screen Shot 2021-07-19 at 11 28 24 AM](https://user-images.githubusercontent.com/41396793/126186183-b23c8d4b-0026-481e-9c73-ce0a5ef461f0.png)

**Comment by irina060981** [comment]
These operations depend on the browser and how it gets an access to the hardware to delete all the data.
You could have some operations in the background that could make it to be slowly.
I faced with it a couple of times. I believe that such operations for OS have the lowest priority.

When you delete only a part of the data - it uses another workflow - and it handle with memory the other way.

I could not do anything with it

**Comment by monzug** [comment]
I'll reassign to me to test on PC again (both Chrome and FF) and again on Mac all 3 browser.

**Comment by monzug** [comment]
tested again in two other computers: my husband's PC and my daughter's MAC. Clear all alignments does not delete the files in the log and I got the same error in the console log. Irina, I believe there is a problem with this button. see attachment

<img width="1440" alt="Screenshot 2021-07-26 at 10 53 11" src="https://user-images.githubusercontent.com/41396793/127011147-b79ee3b2-d49d-41ca-a44d-22fb4f470a99.png">

**Comment by irina060981** [comment]
oh, @monzug - thank you for the console printscreen - it shows an error - after this error appered - the process was stopped.
Will investigate it

**Comment by irina060981** [comment]
Bug is fixed, it is cleared quick now in my environment.

**Comment by monzug** [comment]
Tested in Safari, FF and Chrome on Mac and Chrome/PC. Now Clear all alignments deletes all the saved indexedDB files from splash screen.
