### ISSUE TITLE
annotation type Option is not editable in start a new alignment

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#468]
if I add 2 or more annotations type and do an alignment with annotations, the next start a new alignment will have the annotation type field not editable.
see attachments:
at the starting a new alignment (Reset all will only apply the default setting but not make the annotation field editable)
![Screen Shot 2021-08-11 at 2 23 07 PM](https://user-images.githubusercontent.com/41396793/129028237-ea3031a0-92c3-4514-911e-8418e21c0582.png)

after reloading the page
![Screen Shot 2021-08-11 at 2 23 31 PM](https://user-images.githubusercontent.com/41396793/129028269-87102457-9519-4e05-8993-c52d3fa9b9ea.png)

**Comment by irina060981** [comment]
Bug is fixed

**Comment by monzug** [comment]
Fixed. Tested in FF and Safari/Mac
