### ISSUE TITLE
show message when alignment group is completed

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alignment-editor-new#47]
suggestion from @monzug it would be good to show a message confirming that an alignment group is completed.

**Comment by irina060981** [comment]
I just finished to work on a notifications workflow, would add this easily.

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/96451636-3bd3eb00-125b-11eb-9050-165de1803507.png)

![image](https://user-images.githubusercontent.com/12377640/96451678-4e4e2480-125b-11eb-93b5-549023093481.png)

![image](https://user-images.githubusercontent.com/12377640/96451717-5ad27d00-125b-11eb-86c8-8281e2f5104a.png)

**Comment by irina060981** [comment]
Merged and closed
