### ISSUE TITLE
Duplicate text in Align text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#471]
I noticed that in build  Alpheios Translation Alignment editor 1.4.1 (build development.20210806356) and in latest build Alpheios Translation Alignment editor 1.4.1 (build development.20210813302), the latin text is duplicated. I entered a latin text with 9500 chars after increasing Max characters per text (recommended for performance) to 50000 in Options. in Align text, the Latin text is repeated below the first segment. tested in Safari, Chrome and FF on MAC. see screenshot

![Screen Shot 2021-08-13 at 3 01 10 PM](https://user-images.githubusercontent.com/41396793/129360973-3d0c63ec-872f-4b50-91ab-ce7ffc52ed91.png)

**Comment by irina060981** [comment]
@monzug, I was not able to reproduce - could you describe steps in more details please.

**Comment by monzug** [comment]
Got it! it's a non-issue. the Latin word is consider as a section on its own as it is separated by double line, that's what confused me. the text is duplicated in enter text.

**Comment by irina060981** [comment]
I am happy with it :)
