### ISSUE TITLE
Make modal draggable and close on clickaway

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#473]
Add ability to drag modal (options, help, annotations, save, upload, summary, waiting, metadata, language, sourceType)
Add ability to close modal on clickaway

**Comment by irina060981** [comment]
Done

**Comment by monzug** [comment]
Wouldn't mind if this was an option. 
anyhow, tested in Chrome/Mac in Options & Help in all 3 mode, annotations, save locally, upload texts from DTS API, summary, waiting, metadata, language and sourcetype.

**Comment by irina060981** [comment]
>anyhow, Add ability to close modal on clickaway hasn't been implemented, correct?

It is done - and I easily close modals in alignment editor by clickaway.
If you have problems - I need details .

**Comment by monzug** [comment]
tested also in Chroma and FF/PC.
There are no problems at all, just a question: when I upload text from DTSAPI and I close on clickaway the upload modal, the text is still loading. the clickaway closes the modal but not the action behind it. I think it should abort the upload. what do you think?

**Comment by irina060981** [comment]
yes - you are right - closing modal is not aborting the process - and if to be honest - there is no way to stop uploading data if the process is started.
I could try only not to render it on the screen - but it would be uploaded in the background anyway.

**Comment by irina060981** [comment]
I suggest to turn off clickaway behaviour for upload window - it is the easiest and mostly logic behaviour in this case.
@monzug - what do you think?

**Comment by monzug** [comment]
yes, please. just to avoid conflict behaviors

**Comment by irina060981** [comment]
Done

**Comment by monzug** [comment]
this is fixed.however I realized that the cancel button does not cancel the process either. will enter a new issue for this.
