### ISSUE TITLE
Convert Annotation Mode checkbox to toggle

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#477]
Defined on the meeting

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/130052681-4dc7444e-89ab-47ae-a5bd-344e0e0f6acc.png)
Done

**Comment by monzug** [comment]
can we have it slightly smaller?

**Comment by irina060981** [comment]
Yes - it is a standard size for being comfortable for mouse click.
To what percents do you suggest to reduce - make it 80% of the current?

**Comment by monzug** [comment]
I would say yes

**Comment by irina060981** [comment]
Done

![image](https://user-images.githubusercontent.com/12377640/130767671-7668e274-b3b9-4740-bf56-0a87c6dc53f3.png)
