### ISSUE TITLE
Add a max characters setting for annotations text field

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#480]
Defined on the meeting

- add a setting to the Enter Text Options - max characters of a annotation text field
- set limits - 1-50000
- set default - 500

**Comment by irina060981** [comment]
Done

![image](https://user-images.githubusercontent.com/12377640/130200889-e75ec058-9f32-49c6-910f-2d61fb1b933d.png)

![image](https://user-images.githubusercontent.com/12377640/130200968-5866c5d4-e268-4892-8cb2-2b1a9a26570b.png)

![image](https://user-images.githubusercontent.com/12377640/130200992-bbf0af0a-ee07-4f96-bd85-d5a30f966975.png)

**Comment by monzug** [comment]
max char is 500. if max char is reached, text cannot be saved. the issue related to edit an annotation and delete all entry is reported in #462
