### ISSUE TITLE
Add annotations to HTML output

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#482]
Defined on the meeting

- download and render annotations to HTML Output

**Comment by monzug** [comment]
related to issue #462

**Comment by irina060981** [comment]
- annotations are underlined
- annotations modal is opened by a single click on the token
- annotation modal is draggable and clickaway is available

![image](https://user-images.githubusercontent.com/12377640/130558046-b33330fa-c1bc-49d3-8b57-e0be6f63e65f.png)

**Comment by monzug** [comment]
tested in build 24/8
1) can we add "Annotation for xxx" in the title of the annotation pop-up in html output?

![origine](https://user-images.githubusercontent.com/41396793/130628958-edc65d93-f7fc-4011-a0cd-394f0bb68cb7.JPG)

2) why am I missing the # of the comment, morphology and lemmaID for the annotations saved before latest build?

![origine-2](https://user-images.githubusercontent.com/41396793/130629432-e7e6d36a-da6b-44f4-8b5b-22442cd37f9b.JPG)

3) Is there any reason why I cannot upload old html output files any longer in latest build?

**Comment by irina060981** [comment]
>can we add "Annotation for xxx" in the title of the annotation pop-up in html output?

Will fix

**Comment by irina060981** [comment]
>why am I missing the # of the comment, morphology and lemmaID for the annotations saved before latest build?

I believe you saved them before I created an ability to have index

**Comment by irina060981** [comment]
>Is there any reason why I cannot upload old html output files any longer in latest build?

Yes, I was to change the way it is created to use annotations modals.
Will try to make changes to support both

**Comment by monzug** [comment]
verified in build 8/25
tested in all browsers/PC and MAC
