### ISSUE TITLE
I can have 2 annotations with some comment #

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#484]
if I delete a comment then add a new one, I can have 2 comments with same comment #. see screenshot

![Screen Shot 2021-08-20 at 3 09 56 PM](https://user-images.githubusercontent.com/41396793/130238379-0e246fb9-bfc2-4eb1-8923-45a60e8acd60.png)

![Screen Shot 2021-08-20 at 3 12 24 PM](https://user-images.githubusercontent.com/41396793/130238494-19222730-f1b9-49c7-84ee-b19f121e668f.png)

**Comment by irina060981** [comment]
oh, thank you for the catch - will check

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
fixed in build 8/25
