### ISSUE TITLE
Can we make tokens with annotations more visible in Ge'ez?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#485]
I just added few annotations in Ge'ez and noticed that the line that indicates the token with annotation is not so visible. Can we make the underline more visible? see screenshot

![Screen Shot 2021-08-20 at 4 03 25 PM](https://user-images.githubusercontent.com/41396793/130245867-e56113b3-bb1a-4ef7-bce6-bb1a59373ead.png)

**Comment by irina060981** [comment]
oh - it is a specific for Geez font - will do it another way then

**Comment by irina060981** [comment]
Done

![image](https://user-images.githubusercontent.com/12377640/130604460-87cbba3d-4872-47c4-8d7c-af0d2fff50d4.png)

![image](https://user-images.githubusercontent.com/12377640/130607507-ad263656-7112-473e-8bde-357e5cf7bf17.png)

**Comment by monzug** [comment]
Thanks, it looks much better. I just realized that if I do an alignment, the underline for annotation is lost. will enter a new issue.
see screenshot
![Screen Shot 2021-08-24 at 3 11 10 PM](https://user-images.githubusercontent.com/41396793/130622764-2b7a9fd3-b659-4882-8543-c636ba26d984.png)
