### ISSUE TITLE
Able to save an empty entry field after editing

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#486]
reported in issue #462 

" I can save an empty field for annotation (create a comment then go to edit and delete everything)" I am still able to reproduce this in build development.20210820241

Irina's comments:
It is not a bug - there are no requirements what to do with empty text - should I delete an annotation if a user deletes the text?
Empty text field should be defined as a new issue with exact requirements for the workflow from my point of view, because there are no requirements in this issue.

I would do like in creating a comment: if there is no text then we can print 'There is not enough information for editing (or saving) an annotation'

**Comment by irina060981** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/12377640/130775389-a9064487-b0e2-44b3-8fb9-19fa1be58794.png)

**Comment by monzug** [comment]
tested in build 8/25
when saving an empty annotation, the following message is generated: There is not enough information for saving an annotation and annotation cannot be saved.
