### ISSUE TITLE
Undo/redo not working after few clicks

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#491]
related to #458 which is for indexedDB text.
undo and redo are still active (selectable) but stopped working as clicking on each button does not produce any result. I entered a simple sentence in Enter Text, then did the alignment, then aligned one token and added an annotation. Checked in Edit text if token with annotation can be edited. Then I did an alignment with the token with the annotation. I used undo, redo few times till it was not longer working. see error in the console (Chrome/Mac)
![Screen Shot 2021-08-25 at 9 24 14 AM](https://user-images.githubusercontent.com/41396793/130746395-1e777531-3197-45bb-b9ab-52ab5e0ffa28.png)

I did also have problems with undo/redo in chrome/PC with no error in console

**Comment by monzug** [comment]
I might have a reproducible scenario (Chrome/PC):
align two tokens, then undo the alignment and repeat the steps with redo, till you have the token highlighted but Undo is not active. at this point mouse over the token to deselect it. Note the undo/redo are active now but not working.

![first-step-undo](https://user-images.githubusercontent.com/41396793/130770111-6b1aca90-01e2-474c-b6c6-df20c950f20e.JPG)

![second step-undo](https://user-images.githubusercontent.com/41396793/130770151-6a2fa3cf-982e-48a1-83df-3b1044165ca6.JPG)

![step 3 - undo](https://user-images.githubusercontent.com/41396793/130770175-eea018d2-f5bf-4df0-a0f4-3c69239a53fe.JPG)

**Comment by monzug** [comment]
an other error with Undo active but not working. see screenshot below

![Screen Shot 2021-09-17 at 2 35 12 PM](https://user-images.githubusercontent.com/41396793/133783750-724b15ce-edaf-40f4-8310-d1aae0fb6fe4.png)

**Comment by irina060981** [comment]
I am working on undo/redo issue - I need to change workflow here to solve this bugs

**Comment by irina060981** [comment]
Workflow is refactored - bug is fixed

**Comment by monzug** [comment]
it works fine on FF/Mac. Thanks for fixing it.
