### ISSUE TITLE
Third target language text is not  displayed in Define Alignment Groups 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#50]
My scenario: I have Latin as origin language and 3 target languages  (2 English and Greek). When I do the alignment, the third language (Greek) has no text displayed.  see screenshot

![third-language-empty](https://user-images.githubusercontent.com/41396793/97186779-1756a200-1778-11eb-8c45-9e47e0b4293c.JPG)

Also, I am a little confused by the navigation between the groups icons.  When all language are displayed, the 1, 2 and 3 icons are blue. When I click on 1,  the icon is grayed out and only the 2nd and 3rd target language are displayed. if I want to see only the target language associated with icon 1, I have to grayed out the icons 2 and 3 first.  I am thinking of a situation in which I have several target languages and in order to see only one specific language, I have to grayed out all the others. just a thought.

**Comment by irina060981** [comment]
> My scenario: I have Latin as origin language and 3 target languages (2 English and Greek). When I do the alignment, the third language (Greek) has no text displayed. see screenshot

I checked we get 500 Error for Greek chars from tokenization service. 
I updated the code - to print the error to notification bar.

For now if one text is not tokenized - all tokenization is cancelled
![image](https://user-images.githubusercontent.com/12377640/97667419-8c550f00-1acb-11eb-92d0-0a4c5d5db266.png)

**Comment by irina060981** [comment]
>Also, I am a little confused by the navigation between the groups icons. When all language are displayed, the 1, 2 and 3 icons are blue. When I click on 1, the icon is grayed out and only the 2nd and 3rd target language are displayed. if I want to see only the target language associated with icon 1, I have to grayed out the icons 2 and 3 first.

Tabs workflow is the following:
- a tab could be active or not (click changes its status to the opposite)
- if only one tab is active - creation of alignment groups is available on it
- if several tabs active - only view mode is available
- at least one tab should be active

>I am thinking of a situation in which I have several target languages and in order to see only one specific language, I have to grayed out all the others. just a thought.

if you want to create groups you should deactivate other tabs.

**Comment by irina060981** [comment]
The bug is solved

**Comment by monzug** [comment]
I got the messages of the failed tokenization process. Note that I also got the tokenization process has finished below the failed tokenization error messages. we should review these messages with #51 

![too-many-messages](https://user-images.githubusercontent.com/41396793/97717361-15a01d80-1a9b-11eb-83cb-2d73c656b9d5.JPG)
