### ISSUE TITLE
I cannot save an annotation without any annotation type

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#500]
We should not allow to deselect all annotation types from Options. If I uncheck all of them, then I cannot enter an annotation because I get the message that "There is not enough information for saving an annotation".
If annotation type is a request field to save an annotation, we should prevent users from unchecking all annotation types in Options.
![Screen Shot 2021-08-30 at 3 35 34 PM](https://user-images.githubusercontent.com/41396793/131348174-b47dafce-8bee-4df5-ae5f-c0a8dfa6dd19.png)

**Comment by irina060981** [comment]
Monica, I could not reproduce this bug and I don't understand, how can you make type select empty?

I tested in Chrome and Safari - I couldnot deselect all values. This select doesn't contain an empty value by design.

Monica could you give me some detailed steps?

**Comment by monzug** [comment]
you can deselect all annotation types in Options in Enter Text screen. if we want to support this, then we should allow an empty field for annotation type in align text screen. Or we should not allow to have an empty field for annotation types in Options in order to prevent the issue that I cannot save with an empty annotation type field in align text screen.

![Screen Shot 2021-09-02 at 2 10 39 PM](https://user-images.githubusercontent.com/41396793/131841185-6c04dd9f-1dba-49ed-b572-8f24c5666903.png)


![Screen Shot 2021-09-02 at 2 06 09 PM](https://user-images.githubusercontent.com/41396793/131841181-3c845ec1-87d1-40ca-8e31-b4998505a84f.png)

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
Hahaha, I know... it's me!
