### ISSUE TITLE
Standard Theme: options for save locally are not visible

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#501]
tested in Safari and FF/Mac and FF/PC - also the annotations from the texts in the back bleed in
see attachment
![Screen Shot 2021-08-30 at 4 43 14 PM](https://user-images.githubusercontent.com/41396793/131357957-eb49eaca-2686-458e-95f2-9ac696575e28.png)

**Comment by irina060981** [comment]
Done 
![image](https://user-images.githubusercontent.com/12377640/131841103-764504be-e7ba-455a-a0fe-842ed1b3483a.png)

**Comment by monzug** [comment]
fixed

![Uploading fix-save-locally.JPG…]()
