### ISSUE TITLE
Error message should be updated

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#502]
I just got the following error message in edit text that I haven't seen it before:
The token that is the translation of merging is inside a created alignment group, you should ungroup it first.

Should it be the usual error message: The merging token is inside a created alignment group, you should ungroup it first. or The token you are merging with is inside a created......

![Screen Shot 2021-08-31 at 2 09 14 PM](https://user-images.githubusercontent.com/41396793/131500099-5bf9d400-9695-4ac5-8efa-953bca52ea8b.png)

**Comment by irina060981** [comment]
Fixed

 ![image](https://user-images.githubusercontent.com/12377640/131836640-547164aa-6038-4e20-a205-85c03b76ae60.png)

**Comment by monzug** [comment]
Thanks.
