### ISSUE TITLE
Edit text has been changed to display only a segment: few issues 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#503]
I am not sure when the split of edit text has been implemented but it created some problems.
tested in Chrome and FF/mac and Chrome and FF/PC in build 8/27
1) first issue is related to scrolling. if only a portion of the text is now available in edit screen, then I should be able to go to the next or prev part of the text. If we do not want to allow navigation among segments, then this should be more obvious for the user to understand. At the moment we do only show the tiles where the text is available. I think that's what we all agreed in the call. However I do think we need to make it more understandable for the user, maybe by adding some explanation under the tiles? e.g. portion of visible segment in align text ???
2) Because of the new change, by doing any editing in the available segment the align text is truncated to the available segment. e.g. if I had 4 tiles initially, after editing the original text, I am left with 2 tiles so texts is truncated.
3) also, there is the possibility that I can insert tokens to the start and end of the segment, even if it is not the real start or end of the original text. see screenshots below

I tested this scenario with the same original and translation texts against the build available in the alignment online and this was not reproducible.

![Screen Shot 2021-08-31 at 3 30 23 PM](https://user-images.githubusercontent.com/41396793/131513102-09098390-4a9b-4ee6-b37f-45efa0c5d105.png)

![Screen Shot 2021-08-31 at 3 30 52 PM](https://user-images.githubusercontent.com/41396793/131513090-db8ca042-19e6-40db-aca4-f816deaeb48c.png)

**Comment by irina060981** [comment]
>first issue is related to scrolling. if only a portion of the text is now available in edit screen, then I should be able to go to the next or prev part of the text. If we do not want to allow navigation among segments, then this should be more obvious for the user to understand. At the moment we do only show the tiles where the text is available. I think that's what we all agreed in the call. However I do think we need to make it more understandable for the user, maybe by adding some explanation under the tiles? e.g. portion of visible segment in align text ???

This functionality is limited.
All navigation through parts are done only on Align Text screen, because we divide to parts to limit amount of text rendered to the screen. Edit Text screen is more heavy. 
So for performance optimization Application gives an ability to edit only visible parts, and doesn't allow to upload additional parts separately from Align Text screen.
Logic is the following 
  - a user saw some moments to fix - he/she goes to Edit Text screen and fixes it.
  - a user don't want to fix the text that he doesn't see
  
  Yes we discussed it on the meeting.
  What exactly do you suggest to add?
  Add information to the Help?
  I don't think that we have a good place for some instructions near panels as we try to use as much visible space for tokens as we could

**Comment by irina060981** [comment]
>Because of the new change, by doing any editing in the available segment the align text is truncated to the available segment. e.g. if I had 4 tiles initially, after editing the original text, I am left with 2 tiles so texts is truncated.

I didn't understand the problem. What exactly disappears from screen after editing? Could you give a detailed example?

**Comment by irina060981** [comment]
>also, there is the possibility that I can insert tokens to the start and end of the segment, even if it is not the real start or end of the original text. see screenshots below

Oh, I would update checks

**Comment by irina060981** [comment]
>I tested this scenario with the same original and translation texts against the build available in the alignment online and this was not reproducible.

I didn't understand this information. What exactly is not reproducible?

**Comment by monzug** [comment]
comment from Harry:
when I went back to the align screen all the remaining portions and tiles were gone. Definitely a bug. Definitely has to be addressed before we give it to anyone.


> > I tested this scenario with the same original and translation texts against the build available in the alignment online and this was not reproducible.
> 
> I didn't understand this information. What exactly is not reproducible?

Irina, I promptly replied to this but all my changes were not saved!!!! I just realized it. 

the above scenario was not reproducible in the old build which did not include the changes to display only segments of the text in Edit text screen.

To reproduce the scenario, all you have to do is to align a text with about 5000 chars (4 tiles more or less) in both the original and translation texts. Then go to edit text screen and edit the available portion of the text by merging two words or by inserting a token or by editing a word. Then go back to align text screen. you'll notice that the # of tiles is now reduced to 2 from 4 tiles. Basically in align text screen the original text is now reduced to same size of the segment in Edit text screen.
if you are still having problem reproducing this issue we can have a call together tomorrow.

**Comment by monzug** [comment]
> > I tested this scenario with the same original and translation texts against the build available in the alignment online and this was not reproducible.
> 
> I didn't understand this information. What exactly is not reproducible?

al of the above 'issues' are related to the change in edit text screen to display only the current segment available in align text.

to repro the segment issue:
have a long text with about 5000 chars. 4 tiles are visible in the align text screen in both original and translation text. go to edit text screen. Do any type of editing: merge two words, insert text at beg or at end of segments, edit a word etc. you'll see that the tiles are reduced to only the visible part in both edit text screen and align text screen. 
pls let me know if it is still not clear and we can have a call and show it to you.

**Comment by irina060981** [comment]
Oh - I understand finally and was able to reproduce easily
Will add screenshot for my investigation

Before
![image](https://user-images.githubusercontent.com/12377640/131930495-248add59-134b-4e2d-aa79-35ecf4fd2944.png)

![image](https://user-images.githubusercontent.com/12377640/131930514-b5f6c863-7f53-4ca2-9bb0-478db41731eb.png)

After merging
![image](https://user-images.githubusercontent.com/12377640/131930538-89750ee0-51f9-4828-bf02-9e92f7e8cc03.png)

![image](https://user-images.githubusercontent.com/12377640/131930551-334360e3-f317-455d-b942-06b9c69b6da1.png)

**Comment by monzug** [comment]
yes. Thanks

**Comment by monzug** [comment]
regarding the problem of inserting token at the beg and the end of the segment, if you do some editing and the go back to align text and then back to edit text, you will notice that I have the ability to insert text at beg and the end of the segment because this is what it's left from the original text
![Screen Shot 2021-09-03 at 3 19 01 PM](https://user-images.githubusercontent.com/41396793/132011899-a6a49aea-ac24-4c21-8c72-2772df714596.png)
![Screen Shot 2021-09-03 at 3 18 52 PM](https://user-images.githubusercontent.com/41396793/132011905-d06e52e9-799f-4342-b213-d5abaefa3920.png)

**Comment by monzug** [comment]
also note that the html output is also truncated.

**Comment by irina060981** [comment]
>also note that the html output is also truncated.

It is a separate bug

**Comment by irina060981** [comment]
the bug with truncated parts after text was edited - is fixed

**Comment by monzug** [comment]
this is fixed now. let's leave the scrolling in edit text as is for the moment.
