### ISSUE TITLE
IndexedDB in error message when uploading an unsupported file extension

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#507]
The error message generated when uploading an unsupported file extension does also list indexedDB in the supported files. Do we want to add indexedDB to this list? indexedDB file are uploaded only from splash screen not from Resume previous alignment from the menu.
see attachment

![Screen Shot 2021-09-01 at 2 44 18 PM](https://user-images.githubusercontent.com/41396793/131673559-c452e57f-a228-4da1-9dac-92a85ca17be4.png)

**Comment by irina060981** [comment]
oh, thank you for the catch - I misse to remove it from the list

**Comment by irina060981** [comment]
Fixed
![image](https://user-images.githubusercontent.com/12377640/131813903-df4b1e55-d127-49b7-bc2b-e8caf7661994.png)

**Comment by monzug** [comment]
thanks
