### ISSUE TITLE
Messages are sticky, should they be?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#51]
The message "Alignment group is finished and saved."  is sticky.  I undid the alignment and message was still there. I do have the option to close the message myself, though.
also, the "Choose an other token please from target text" message is sticky. After I undid the alignment, message was still there. and the target and origin tokens were all highlighted in yellow on mouse over and not able to align again. see photo from iphone. question: am I doing something wrong with Undo button?

![token to choose](https://user-images.githubusercontent.com/41396793/97190534-348d6f80-177c-11eb-901e-f110df845191.JPG)

![IMG_4884](https://user-images.githubusercontent.com/41396793/97192682-83d49f80-177e-11eb-8518-70462cabb358.jpg)

**Comment by irina060981** [comment]
@monzug , this notification bar has only two actions:
- some events adds info notifications or error notifications;
- each event could be closed manually.

That's all. We could add non-manual closes:
- by timeout (we should define time amount)
- by other event (we should define the event for each event that adds it to the bar).

**Comment by monzug** [comment]
Thanks @irina060981 - I am still getting familiar with the alignment editor and reporting my impressions as first time users.

**Comment by monzug** [comment]
here is an other example of sticky messages:

![several-messages](https://user-images.githubusercontent.com/41396793/97432941-1eee8600-18f3-11eb-8d68-4e1472d01aff.JPG)

**Comment by balmas** [comment]
per discussion with @irina060981 on 10/28 we will probably need different rules for different classes of notifications (e.g. timeout, dismiss after next action, etc).  To be implemented before release but wait to work on until most major features are implemented.
