### ISSUE TITLE
Place back max per part to Enter Text Options

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#511]
from the on-line meeting with @abrasax

**Comment by irina060981** [comment]
Done

![image](https://user-images.githubusercontent.com/12377640/131830425-1a2da5dd-8f06-42fd-a3c1-f4d4e2fc9366.png)

**Comment by monzug** [comment]
can you add some description here, pls? I do not have these changes in my environment

**Comment by irina060981** [comment]
>max chars in annotation set at 500

This is the max characters that is allowed for a text of an annotation

>max chars per part set at 1000

This the amount of characters that will be used to divide segments to part.
By default it is 1000 - it means that application will divide a segment to parts (near 1 thousand characters) and show one part at a time. Next/prev is for navigating.

Division to parts is stored to IndexedDB and could be redivided only on application reload (this setting doesn't change on the fly).

>max chars per text

This is max ammount of characters that are allowed for a single text (original or translation)

**Comment by monzug** [comment]
I tested with 1, then 50000 (max allowed) and the default. 
I uploaded the Odyssey from chapter 1 to 12.  with 50000 it was painfully slow to go to the next page.  I noticed several errors in the log. also I needed to reload the page. see screenshots
Max part set to 1 with short text
![Screen Shot 2021-09-20 at 4 22 35 PM](https://user-images.githubusercontent.com/41396793/134022094-75bd32d1-a85a-463c-ae12-840e9fa82812.png)

![Screen Shot 2021-09-20 at 4 28 35 PM](https://user-images.githubusercontent.com/41396793/134021941-aa1eb655-071f-4c23-974e-47d1897cef92.png)
![Screen Shot 2021-09-20 at 4 29 41 PM](https://user-images.githubusercontent.com/41396793/134021953-48b145c3-5df2-4048-85c3-74f823e0bd8d.png)
![Screen Shot 2021-09-20 at 4 30 36 PM](https://user-images.githubusercontent.com/41396793/134021957-5f182be6-b72c-49e1-b867-73ceaba54e29.png)

**Comment by monzug** [comment]
in Safari with a smaller section of the Odyssey (from chapter 1 to 6), I got the following error (part is set to max 50000):
![Screen Shot 2021-09-20 at 5 16 32 PM](https://user-images.githubusercontent.com/41396793/134027735-e117c082-3ac7-457c-9c14-4a3c00f96811.png)
