### ISSUE TITLE
what if the token is not from the same segment?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#52]
"die" and "giorno" are not on the same segment, they can't be aligned. I made up the translation for testing. see screenshot
how can I readjust the origin and target text when it has been already aligned in segments (e.g. move "die" on same segment as "giorno")? do I need to start over? 

![two lines](https://user-images.githubusercontent.com/41396793/97325980-e6df3880-1849-11eb-9b93-1c23b306fe7e.JPG)

**Comment by monzug** [comment]
In this scenario,  I only have one big segment and I can do the alignment on different rows

![more-lines](https://user-images.githubusercontent.com/41396793/97328477-6f5ed880-184c-11eb-895c-7f3b4a1295ed.JPG)

**Comment by irina060981** [comment]
>"die" and "giorno" are not on the same segment, they can't be aligned. I made up the translation for testing. see screenshot
how can I readjust the origin and target text when it has been already aligned in segments (e.g. move "die" on same segment as "giorno")? do I need to start over?

For now the definition of the segments are made by the tokenization service based on its parameters after Align button is clicked. 
Default options - divide to segments by a line break (singleline mode), 
also we would support division to segments by double line breaks (to save line breaks inside the segment), but for now it doesn't work - https://github.com/alpheios-project/tokenizer/issues/17

So For now you should start over by reloading the page

**Comment by balmas** [comment]
Our requirements include supporting an ability to edit the segments once created (i.e to move words from one segment to the other). That should address this once implemented.

**Comment by balmas** [comment]
see #81

**Comment by irina060981** [comment]
@monzug, as #81 is done let's check this issue too

**Comment by irina060981** [comment]
closed with this one - https://github.com/alpheios-project/alignment-editor-new/issues/39

**Comment by monzug** [comment]
as per #81  we should be able to "Move tokens from the end of 1 segment to the beginning of the next segment".
In the above example, I was able to move "giorno" (last word of the segment) to the next segment in the target text to do the alignment with "die", using the option 'Move the token to the next segment'.

in Safari, I cannot activate the options for giorno (it does work in Chrome and FF). Any idea?
see screenshot

![Screen Shot 2021-01-25 at 4 12 54 PM](https://user-images.githubusercontent.com/41396793/105724628-5687c100-5f28-11eb-9897-28eb4126bea6.png)

**Comment by monzug** [comment]
@irina060981 actually, it does happen on FF and Chrome too when I clear text and start the align over. if I reload the page and enter the origin and target texts again, then I am able to move the last word to the next segment. If I use clear text, then the options are greyed out (or I have only edit available if I checked 'Allow update token word'). see screenshot in Chrome/Mac
![Screen Shot 2021-01-25 at 4 38 17 PM](https://user-images.githubusercontent.com/41396793/105727853-c9df0200-5f2b-11eb-8cf7-9ea93d4cc0d2.png)

**Comment by irina060981** [comment]
oh, thank you Monica for the catch - I would fix the bugs (I could reproduce both)

**Comment by irina060981** [comment]
@monzug , 
Fixed styles for showing icons in Safari.
Fixed clear text feature - (it didn't properly cleared all previous work)

Now this bugs should be solved.

**Comment by monzug** [comment]
Both fixed. Thanks
