### ISSUE TITLE
with indexedDB turned off, I cannot save locally some files

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#521]
I am not so sure if it is indexedDB the culprit but it works when I tried to save a file that would not save successfully when indexedDB was turned off.
tested in Safari and Chrome
I uploaded the chinese and english text from Christoph and tokenized the texts successfully by removing some extra blank lines in the english version (in section 2 and section 9). then when I tried to save locally I got the error below in the screenshots. when I turned indexedDB on, save locally worked as expected.
Note that I tried the same scenario with one line file and it worked.

![Screen Shot 2021-09-07 at 2 30 29 PM](https://user-images.githubusercontent.com/41396793/132348301-28fb37b8-500b-43ae-8535-167a056f18e2.png)

![Screen Shot 2021-09-07 at 2 38 05 PM](https://user-images.githubusercontent.com/41396793/132348291-6d2ee537-e78d-4b6e-b4a5-3316c93898da.png)

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
this is fixed in build 9/8 tested in chrome on PC and Mac
