### ISSUE TITLE
Resume alignment, file is corrupted

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#523]
tested in latest build 8/9 in FF and Safari/Mac
enter latin text that is less than 5000 chars in both the original and translation
do some alignments and some editing (merge two words, editing a couple of words) then save locally
when I uploaded the file, I noticed that the second segment was corrupted. see screenshots

enter text:
![Screen Shot 2021-09-08 at 2 47 36 PM](https://user-images.githubusercontent.com/41396793/132511931-19278658-45b6-496f-adc5-29bf72849cab.png)

resume saved file:
![Screen Shot 2021-09-08 at 2 47 03 PM](https://user-images.githubusercontent.com/41396793/132511935-e3af36a6-00f5-41ec-a170-f04d84a7108f.png)

**Comment by monzug** [comment]
also, the html output is corrupted 
![Screen Shot 2021-09-08 at 2 50 51 PM](https://user-images.githubusercontent.com/41396793/132512409-1b26376c-ec0d-489c-84ae-6729c6cb7da1.png)

**Comment by monzug** [comment]
and Christoph's file with chinese and english texts

**Comment by irina060981** [comment]
It should be fixed with https://github.com/alpheios-project/alignment-editor-new/issues/530

**Comment by monzug** [comment]
tested in FF and Safari/Mac in build 09/14, json, indexedDB and HTML output looked good.
