### ISSUE TITLE
Should we print the error message with an active screen?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#524]
I got an error message when trying to resume an alignment with from file type (html file). the error is barely visible because it's in the background. The side menu is active over the screen where the error is displayed. Should we make the screen active when printing an error? See screenshot

![wrong-extension](https://user-images.githubusercontent.com/41396793/132532879-0226298a-c3ad-4e96-83e2-c4594464a976.JPG)

**Comment by irina060981** [comment]
Fixed - menu is closed on the file extension error

**Comment by monzug** [comment]
beautiful. Tested in chrome, FF and Safari/Mac and FF and Chrome/PC
