### ISSUE TITLE
SourceType modal is empty

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#526]
from @monzug email
Irina,
this issue has drove me nut.... I cleared cache, close browser, reopen browser, load and reload
the alignment editor but the text pop-up is empty in Chrome on Mac only. see attachment

any ideas? it started after I switched from double line to single line (not reproducible in FF or safari/Mac) and no errors on log
![image](https://user-images.githubusercontent.com/12377640/132612125-99b31ca4-8b3c-460b-a997-8eefa2707723.png)

**Comment by irina060981** [comment]
I was not able to reproduce but I have made some investigations.
The options for this modal are uploaded from the remote tokenizer with a separate request on first application load.
And when they are uploaded we could render this modal.

So I could suppose that there are some problems occasionally happens with this request when you or Harry used it.
I don't have any access to the remote tokenizer and could not check the log.
But we could try to collect more information.

As I could not reproduce it I would need your help, Monica:
if there is again this problem, I would need 
   - screenshot of the console log (I placed additional log there)
   - screenshot from the network tab (it it at the same place as console)
   
![image](https://user-images.githubusercontent.com/12377640/132616779-70f49018-c90d-4f55-aad3-32f7acc7d767.png)

   - screenshot with the request
    you could find it on the Network tab with the header tokenizer (pay attention that it tracks only if it was already opened on page reload)
  
![image](https://user-images.githubusercontent.com/12377640/132616673-47f35f7f-da1e-4216-8aa2-807798e7af18.png)

    Select the row with tokenizer header, click on the Preview (at the right tabs)
    
![image](https://user-images.githubusercontent.com/12377640/132617007-833ec181-34e5-4bf2-b46c-ab9e3b841016.png)

click right button of the mouse on the first line in the preview and copy 

And paste all this information here

**Comment by irina060981** [comment]
Hope it will give me some more information

**Comment by monzug** [comment]
interesting that when I turned on disable cache I could see the modal populated.
see screenshots
![Screen Shot 2021-09-09 at 11 33 01 AM](https://user-images.githubusercontent.com/41396793/132661710-995d62c1-0b16-486a-bb7f-6db08ab4c972.png)

![Screen Shot 2021-09-09 at 11 32 04 AM](https://user-images.githubusercontent.com/41396793/132661723-63cec169-6045-4bb4-94d4-f6f221b01f61.png)

**Comment by monzug** [comment]
let me know if you need more info. Obviously the sourcetype modal is still empty... I could only see it the first time I clicked on the disable cache. Thanks

**Comment by irina060981** [comment]
Oh, I always use disabled cache.
It is strange - because - there are information from the source

Will add some more logs then

**Comment by irina060981** [comment]
@monzug , your screenshots are perfect

I added more logs and I would need screenshot with full console (use Console tab instead of Network) if you would reproduce empty modal. I still could not do this.

**Comment by monzug** [comment]
here is the console
![Screen Shot 2021-09-09 at 2 01 21 PM](https://user-images.githubusercontent.com/41396793/132682140-420ba3c2-67be-4556-a17d-da1e8a694d6c.png)

**Comment by irina060981** [comment]
@monzug , console log tells that you have simpleLocalTokenizer as a tokenizer.
I chose it and text/tei modals became empty - because local tokenizer is very simple text parser and doesn't have any options for parsing text and didn't support tei at all.

I think that It is better to disable this icon if a user chose

**Comment by monzug** [comment]
YES. that was it!!!! Thanks so much. I thought I used reset all but obviously I hadn't.so happy

**Comment by monzug** [comment]
@irina060981  I closed this one as problem is solved. In order to prevent the user to end up in a similar scenario, feel free to enter a separate issue. Great.
