### ISSUE TITLE
Singleline text separator causes issues in the indexedDB file and json file

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#529]
tested in production site and latest build in test environment (Chrome and Safari/Mac)
I uploaded the same file in original and translation site with indexedDB checked and double line as text separator. the align text looked good, then I saved it locally and also as indexedDB file.
Resume the json file, all looked good and so did the indexedDB file.
Start a new alignment with the same file for original and translation but this time I switched to single line text separator. the align text looked good, so I saved locally and as indexedDB file. When I resume the alignment as json or as indexedDB, the align text had a missing line separator, the first line displayed on the bottom and an other line was misplaced. see attachments

align text with single line
![Screen Shot 2021-09-09 at 1 56 45 PM](https://user-images.githubusercontent.com/41396793/132683280-e6f2c1af-e54a-4b69-9e97-c64c056fe91b.png)

align text with double line
![Screen Shot 2021-09-09 at 5 20 17 PM](https://user-images.githubusercontent.com/41396793/132714459-50c733fa-e3a8-40eb-97ef-393374dac01f.png)

the console log from test environment
![Screen Shot 2021-09-09 at 2 43 21 PM](https://user-images.githubusercontent.com/41396793/132687996-a007ccd1-11b0-4545-a6e9-07c6e304177a.png)

the json file from test environemt
[09-09_14-40-full-alignment-ara-eng.json.zip](https://github.com/alpheios-project/alignment-editor-new/files/7136561/09-09_14-40-full-alignment-ara-eng.json.zip)

**Comment by irina060981** [comment]
Yes, there are some problems with segment sorting - will fix it

**Comment by monzug** [comment]
Thanks

**Comment by irina060981** [comment]
Sorting of segments are fixed

**Comment by monzug** [comment]
this is fixed in build 9/13
