### ISSUE TITLE
Editing a token with annotations

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#538]
related to the scenario listed in issue #537.

I realized that by merging and editing a token with annotations, we can end up with a token in align text which keeps all the annotations. see screenshot below

![Screen Shot 2021-09-17 at 3 25 23 PM](https://user-images.githubusercontent.com/41396793/133790633-ab4628b7-e765-4b08-af15-2c401a09f984.png)

two considerations here:
1) there is something wrong but I haven't been able to isolate the issue
2) morphology type has the number 1 repeated 3 times (due to the editing and merging of the token)

**Comment by irina060981** [comment]
>there is something wrong but I haven't been able to isolate the issue

@monzug , I don't know how to reflect to this :)

**Comment by irina060981** [comment]
>morphology type has the number 1 repeated 3 times (due to the editing and merging of the token)

@monzug - may be we should change adding a number workflow?
instead of simple order num we could add - token Id - orderNum ? then it would be always unique
What do you think?

**Comment by monzug** [comment]
how complicated it would be? can we wait to implement this after Pietro's release? also, let's retest when the clean-up of editing annotation is done.

**Comment by irina060981** [comment]
No, it is not complicated - but of course would ned some testing.
I think that we could do it after Pietro release.

>let's retest when the clean-up of editing annotation is done

do you mean this issue?
https://github.com/alpheios-project/alignment-editor-new/issues/537#issuecomment-926730735

**Comment by monzug** [comment]
yes. let's do after Pietro's release

**Comment by irina060981** [comment]
- annotation type index now contains token.idWord
- added sorting for annotations

![image](https://user-images.githubusercontent.com/12377640/135077969-9f92be4c-d004-43f3-ae90-981776941afb.png)

Fixed

**Comment by irina060981** [comment]
>we can end up with weird token ids by annotating and merging token that were previously annotated and merged. see below.

I could remove this change, but we need to be sure - that we won't have duplicate indexes for types.

>problems again with undo/redo. I ended up with undo/redo not doing anything. need to reproduce this.

Oh, it is not good news.
May be there are some errors in the console?
Anyway I will wait for reproducable steps or console errors

Thank you for your attentiveness

**Comment by monzug** [comment]
Glad you saw the bug too. it's really weird, isn't it???? I will also need
more testing to understand  what's wrong here.

**Comment by irina060981** [comment]
I will create a bunch of unit tests for different complex undo/redo scenario.
There is a strange problem in the coding language - it could loose references when there are many iterations - I could add additional check for it.
Will do it later. Thank you for your attention to such tiny bugs.
