### ISSUE TITLE
suppress chars count in TEI text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#539]
We had a problem when uploading text from DTSAPI and exceeding the max chars allowed as the editor counted also the tags and this is really annoying specially with Geez language. Said so, are we ok by suppressing the chars count in TEI texts? see below an example of the same text, upload from DTSAPI vs plain text.

![Screen Shot 2021-09-20 at 5 30 18 PM](https://user-images.githubusercontent.com/41396793/134030643-7a3fedee-a5f8-4a51-8822-019f5a1c5781.png)

**Comment by irina060981** [comment]
Yes, check for TEI for max char count was switched off in some previous issue.
Finally I didn't understand, what exact problem do you see here?
As I could see - it is a desired behaviour - we check plain text for max char and don't check TEI.

**Comment by monzug** [comment]
not a problem, just a question as I was able to upload several chapters of the Odyssey without any warning of possible performance issues. Unfortunately I did come across memory problems.

**Comment by irina060981** [comment]
Oh, great 
Then I think I could close the issue.
