### ISSUE TITLE
Tokenization process has started

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#54]
In Chrome, I have a Latin origin text and 2 targets (English and Italian).  I got the notification that Tokenization process has started, but it has been sitting there for quite sometimes.  it worked with two languages.  are we supporting the 3 languages or not yet?

![tokenization process has started](https://user-images.githubusercontent.com/41396793/97433527-0b8fea80-18f4-11eb-885a-8295f687c02e.JPG)

**Comment by irina060981** [comment]
I would check the issues with tokenization for different languages

**Comment by monzug** [comment]
I was able to have the alignment with the same origin text and the two target languages in Chrome/Mac

**Comment by irina060981** [comment]
It is because of the same problem:
> My scenario: I have Latin as origin language and 3 target languages (2 English and Greek). When I do the alignment, the third language (Greek) has no text displayed. see screenshot

I checked we get 500 Error for Greek chars from tokenization service. 
I updated the code - to print the error to notification bar.

For now if one text is not tokenized - all tokenization is cancelled
![image](https://user-images.githubusercontent.com/12377640/97667419-8c550f00-1acb-11eb-92d0-0a4c5d5db266.png)

_Originally posted by @irina060981 in https://github.com/alpheios-project/alignment-editor-new/issues/50#issuecomment-719262998_

**Comment by irina060981** [comment]
The bug is closed

**Comment by balmas** [comment]
> It is because of the same problem:
> 
> > My scenario: I have Latin as origin language and 3 target languages (2 English and Greek). When I do the alignment, the third language (Greek) has no text displayed. see screenshot
> 
> I checked we get 500 Error for Greek chars from tokenization service.
> I updated the code - to print the error to notification bar.
> 
> For now if one text is not tokenized - all tokenization is cancelled
> ![image](https://user-images.githubusercontent.com/12377640/97667419-8c550f00-1acb-11eb-92d0-0a4c5d5db266.png)
> 
> _Originally posted by @irina060981 in [#50 (comment)](https://github.com/alpheios-project/alignment-editor-new/issues/50#issuecomment-719262998)_

Greek chars should work.  Are they being encoded as utf-8?

**Comment by monzug** [comment]
no longer an issue with the new workflow
