### ISSUE TITLE
if LocalTokenizer is selected, sourcetype modal is empty

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#540]
see issue #526  
with LocalTokenizer selected, the SourceType modal is empty.

**Comment by irina060981** [comment]
disabled sourceType options on Enter Text Screen  for simpleLocalTokenizer

![image](https://user-images.githubusercontent.com/12377640/134653219-2c9302c6-e6db-419e-a49c-58735f7de641.png)

**Comment by monzug** [comment]
Irina, I don't see this change implemented in build 9/24. see screenshot below

![Screen Shot 2021-09-24 at 5 21 49 PM](https://user-images.githubusercontent.com/41396793/134700280-e56b846c-d237-4051-857f-4192e521d102.png)

**Comment by irina060981** [comment]
I am sorry, @monzug, I didn't upload changes for this issue.
Now it is uploaded.

**Comment by monzug** [comment]
verified in build 9/27. tested in Chrome and FF/PC
