### ISSUE TITLE
Set update token word option to true by default and hide from Edit Options

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#544]
From the on-line meeting

**Comment by irina060981** [comment]
- set updateTokenWord to true by default
- hide updateTokenWord  setting for Edit Screen Tokens
- disable Options on Edit Token Screen because there is no options there now

**Comment by monzug** [comment]
tested in Chrome, FF and Safari/Mac. Options button is greyed out and the pencil icon to edit is turned on by default.
