### ISSUE TITLE
Undo is still active on resume an alignment

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#545]
tested in latest build 9/24 with annotation token.
I edited a token in Edit text and then saved to json. when I resumed the alignment, the Undo button in Edit Text is still active but if I click on it, it says nothing to undo.

see error in console log

![Screen Shot 2021-09-24 at 8 31 33 AM](https://user-images.githubusercontent.com/41396793/134629316-0b0eb7dd-4730-4589-81b4-970185f4c155.png)

**Comment by irina060981** [comment]
Fixed this bug

**Comment by monzug** [comment]
verified. no error in the log and undo is not active on resume an alignment
