### ISSUE TITLE
Base token loose its annotation after splitting

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#548]
from issue #537
A token's annotation is kept also when the token is merged with an other word to create a different token and new annotations are added to the newly created token. However the base token looses its annotation after merging, editing and splitting the newly created token - this is what this issue is about.
step by step:
1) add annotation to "patrocinium"
2) then go to edit and merge "patrocinium" with me and add an annotation to the newly merged token
3) then go to edit and split the token. the annotation is saved only for "me" and when I open the annotation pop-up, I still have all annotations, also for "patrocinium" that is not longer annotated.

This is really an awkward scenario and note that UNDO works fine. We might want to consider fixing the situation in which by splitting the two tokens with annotation, each token will keep its annotation. Basically replicate the behavior of UNDO.
for screenshots, see issue #537

**Comment by irina060981** [comment]
And I don't agree that it is a bug.
You want that application should be more expert and understand that these splitted tokens are equal to tokens that existed some step before 
it is enhancment :)

**Comment by monzug** [comment]
Thanks for the explanation. I did not know that after splitting the annotation would go to the first word by design.  I might have missed this piece of information. Where can I find the workflow? Thanks

**Comment by irina060981** [comment]
>Thanks for the explanation. I did not know that after splitting the annotation would go to the first word by design. I might have missed this piece of information. Where can I find the workflow? Thanks

We don't have documentation anywhere - always less time for that.
As I was creating this workflow not based on the issue - I made it up myself.
I decided to implement the following simple workflow:

- merging -> all annotations are saved to the merged token
- splitting -> all annotations are saved on the first

That's are all rules

**Comment by irina060981** [comment]
Decided on the meeting - delete annotations on splitting/merging

**Comment by irina060981** [comment]
Done

- delete annotations after merging/splitting
- restore annotations on undo merging/splitting
- delete new annotations (created for edited token) on undo
- restore new annotations (created for edited token) on redo

**Comment by irina060981** [comment]
Also updated styles for annotated token in Edit Token Screen - red border

![image](https://user-images.githubusercontent.com/12377640/136200653-08b961ee-b67b-4fb0-8ff1-8f8c2d31e253.png)

**Comment by irina060981** [comment]
>resume previos alignment for a ita-eng indexedDB file could not load because of 'token is undefined' error. I do not know what's going on here

It tells that there are some problems with saved alignment, and it has some inconsistency in the data - may be it is a result of incorrect saving of splitting/merging/undo results - I didn't see it myself.

If I would face with it - I would solve, but now I could suggest only to add some handling with it - like adding a notice - Alignment is corrupted and could not be uploaded.

What do you think?

**Comment by monzug** [comment]
to retest all the issues reported above in Chrome, FF (PC and MAC). There were several bug fixes lately.

**Comment by monzug** [comment]
this is a super long id for an annotation!!!

![Screen Shot 2021-11-11 at 4 55 29 PM](https://user-images.githubusercontent.com/41396793/141328592-03cb561c-c1fb-4297-bae6-aec0b8f19587.png)

**Comment by monzug** [comment]
there is a scenario that I am still trying to reproduce in which undo/redo are not active so I cannot undo/redo a split. see screenshot (need more time to try to find a reproducible scenario). no errors in the log
in edit text split a token, then go to align text and add an annotation on a portion of the token, go to edit text again: undo/redo not active.
![Screen Shot 2021-11-11 at 5 13 08 PM](https://user-images.githubusercontent.com/41396793/141332056-4bac84c9-d5ff-4d07-8f38-315f72664337.png)
![Screen Shot 2021-11-11 at 5 13 50 PM](https://user-images.githubusercontent.com/41396793/141332058-c28d623b-77f0-4b01-931b-2cf62328bee6.png)
![Screen Shot 2021-11-11 at 5 15 05 PM](https://user-images.githubusercontent.com/41396793/141332059-3fd9676e-8c52-41e7-9e96-b220c7b16132.png)
![Screen Shot 2021-11-11 at 5 15 20 PM](https://user-images.githubusercontent.com/41396793/141332062-0fd5d6ec-6f18-443e-992a-9e1e9dc1a07b.png)

**Comment by irina060981** [comment]
>found the reproducible scenario: in align text if I highlight the token and then deselect it (it does happen frequently thinking that I am in annotation mode), then in edit text the undo/redo are not active as if the token is in an alignment group.

The reason is the following:

When you select a token at the first time - it is added to a group.
At the moment when token is grouped - appliction clears history.
And we don't have a feature to restore history if a user changes his mins and deselect the token.

So there is no bug here - it is a result of clearing history workflow

**Comment by irina060981** [comment]
>this is a super long id for an annotation!!!

If to be honest - I think that such many edits is a an edge test case and won't happy often in the real life.
From code perspective there is no reason how long is the id - it should be unique - and it is the only limit.

May be later - it is worth to invest time to it - but this long id - is the id of the token that has the annotation.
It is our workflow of creating ids to save id unique.

So from my point of biew it is not worth now to invest time in changing annotation id workflow.

**Comment by monzug** [comment]
> > this is a super long id for an annotation!!!
> 
> If to be honest - I think that such many edits is a an edge test case and won't happy often in the real life. From code perspective there is no reason how long is the id - it should be unique - and it is the only limit.
> 
> May be later - it is worth to invest time to it - but this long id - is the id of the token that has the annotation. It is our workflow of creating ids to save id unique.
> 
> So from my point of biew it is not worth now to invest time in changing annotation id workflow.

yes, I agree that those many edits are an unlike scenario... I just reported here as a comment. I come up with that id by resuming an existing alignment rather than starting from scratch (which I did afterwords).
