### ISSUE TITLE
Tooltips for Save locally are truncated

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#550]
Tooltips for Save locally are truncated - see screenshot. tested in safari/Mac and FF/PC

![Screen Shot 2021-09-27 at 4 05 49 PM](https://user-images.githubusercontent.com/41396793/134924659-4d9f9e60-8c46-474e-b05e-0348f2389811.png)

**Comment by irina060981** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/12377640/135014735-463a4a21-65c8-43cb-87d8-d69b5a4afc3a.png)
