### ISSUE TITLE
Safari: missing color in buttons

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#57]
see FF/Mac vs Safari

![Screen Shot 2020-10-29 at 4 57 00 PM](https://user-images.githubusercontent.com/41396793/97599582-72062d00-1a08-11eb-8837-403c1b2b0884.png)

**Comment by irina060981** [comment]
It is really an interesting issue :)
alpheios-components specific safari css styles that we define with !important flag (for button.alpheios-button-tertiary) overwrite my styles for buttons.

**Comment by irina060981** [comment]
I think I would need to clear from alpheios styles to prevent this rules to be overwritten

**Comment by irina060981** [comment]
Fixed in https://github.com/alpheios-project/alignment-editor-new/pull/85

**Comment by monzug** [comment]
looks good. Thanks
![Screen Shot 2020-12-28 at 2 49 03 PM](https://user-images.githubusercontent.com/41396793/103218657-e92e4380-491b-11eb-8e0c-582de820c797.png)
