### ISSUE TITLE
TEI source type: Onesegment and body

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#570]
I noticed that when I upload a TEI file from DTSAPI, the default option for Supply a comma-separated list of TEI elements in the text which group segments of tokens is onesegment. However the same option when I copy a TEI text in the alignment editor is body. why such a difference?
see screenshots:
body
![Screen Shot 2021-10-12 at 3 17 29 PM](https://user-images.githubusercontent.com/41396793/136967008-0dd798f9-2d04-45c2-99f6-bece096bd345.png)
onesegment
![Screen Shot 2021-10-12 at 3 43 04 PM](https://user-images.githubusercontent.com/41396793/136967531-f954e641-bfab-47ba-b8aa-f91fe30cc47c.png)

**Comment by irina060981** [comment]
great job, Monica!
Thank you - you find a very tiny bug - but it could bring much problems in future.
I fixed it

**Comment by irina060981** [comment]
The correct variant (default that is defined in the remote tokenizer)

text -> tokenization -> segments -> 'onesegment'
tei -> tokenization -> segments -> 'body'
