### ISSUE TITLE
Add ability to remove/insert token at any place inside a segment

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#576]
Decided on the on-line meeting

- remove specific inputs for adding tokens to the start and to the end of the text
- add specific icon for insert
- on clicking on insert icon - modal window is shown, where user could define place to insert token (next/previous to the active) and text in the text area (it would be splitted similiar to insert to start and end)
- allow deleting tokens (by click icon) at any place in the text

**Comment by irina060981** [comment]
- added ability to delete tokens in any place inside a segment (the only limit we could not delete all tokens from a segment)
- added ability to insert tokens in any place inside a segment with the following steps:

![image](https://user-images.githubusercontent.com/12377640/140043012-6f2f4b7b-873a-4f16-a9a1-d512d78ef947.png)

   - select token and click + icon
   - insert tokens modal window is opened

![image](https://user-images.githubusercontent.com/12377640/140043164-07139cb4-388a-4352-8dd8-3faaad5b04b5.png)

   - select - before or after active token words should be inserted
   - enter words to be entered
   - click Insert

- added suport for undo/redo with/without annotations

**Comment by monzug** [comment]
tested in Safari and FF/MAC so far looks good.
Two comments:
1) I was able to insert and save 80 words (364 chars). Is there a limit? if not, could we set a limit of few words? I believe the intention of this enhancement is to let user enter a word or just few words. Am I correct?
2) I deleted all words from the original text and I was left with two words that I could not delete (this is well described by Irina above in the enhancement: the only limit we could not delete all tokens from a segment). The message that I am getting is the usual one: the token is inside an alignment group..... However when I go back to align text these two last words are not part of any groups. Would it be possible to add a more meaningful message for this case? see screenshots
![Screen Shot 2021-11-03 at 3 14 44 PM](https://user-images.githubusercontent.com/41396793/140077271-8fade759-b6c0-48da-b3aa-b5b863e5f6d0.png)
![Screen Shot 2021-11-03 at 3 08 04 PM](https://user-images.githubusercontent.com/41396793/140077276-0a1359d4-c4c1-4cce-ac1d-9a7b5fff4add.png)
![Screen Shot 2021-11-03 at 3 07 53 PM](https://user-images.githubusercontent.com/41396793/140077280-9b06482e-bbc9-45b7-a9b3-77aefdd7a72d.png)

**Comment by irina060981** [comment]
>I was able to insert and save 80 words (364 chars). Is there a limit? if not, could we set a limit of few words? I believe the intention of this enhancement is to let user enter a word or just few words. Am I correct?

We talked about this limit with Harry - and he said that he could expect inserting many words.
That's why I didn't add a limit.

But if you discussed this question again with Harry - I will be glad to add such limits.

**Comment by irina060981** [comment]
>I deleted all words from the original text and I was left with two words that I could not delete (this is well described by Irina above in the enhancement: the only limit we could not delete all tokens from a segment). The message that I am getting is the usual one: the token is inside an alignment group..... However when I go back to align text these two last words are not part of any groups. Would it be possible to add a more meaningful message for this case? see screenshots
message in Edit Text

I didn't understand the problem if to be honest.
There are two different workflows:

1. Delete icon will become unavailable if there is only one token in a segment (no additional printed errors or tooltips)

2. Grouped tokens does not have action menu with icons and show only tooltip (that you have on the screenshot)

If you have got a case when not grouped tokens are shown as grouped on the Edit tokens screen - I need steps to reproduce - because I could not imagine how it could be. 

Or may be I didn't understand your description correct?

**Comment by monzug** [comment]
1) I am waiting for Harry's input. I strongly suggested to set a limit from 1 to ?

**Comment by irina060981** [comment]
It should be fixed with https://github.com/alpheios-project/alignment-editor-new/issues/592

**Comment by monzug** [comment]
Not longer reproducible. However there is a very minor 'issue'. if in edit text I mouse over a token and then I go in align text and do an alignment with the same token, when back in edit text the token has both the message that is part of an alignment group and the small icons to edit/merge/detete etc. When I click in one of these icons, I get the message that the token is inside an alignment group... the only action I can do is to insert a token before or after.

![Screen Shot 2021-11-05 at 2 51 47 PM](https://user-images.githubusercontent.com/41396793/140522257-5aa6657e-30d4-4c9b-b3cf-38e49d0bf778.png)

**Comment by monzug** [comment]
@abrasax do we want to set a limit to # of tokens to insert?

**Comment by abrasax** [comment]
Not unless we absolutely have to.

**Comment by irina060981** [comment]
then I think we can close this issue
