### ISSUE TITLE
spaces added in alignment segments

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#58]
why do tokenization add extra space  in the alignment segments ( e.g. i d ) that are not shown in origin or target texts?
see screenshot

![tokenization](https://user-images.githubusercontent.com/41396793/97718960-eb4f5f80-1a9c-11eb-864a-412559c1a538.JPG)

**Comment by balmas** [comment]
the particular case of "id" is probably a bug in the latin language model of the tokenizer.

The tokenizer does currently try to separate enclytics (e.g Nisi -> Ni si , Neque -> Ne que) but it in an early state and will not catch everything.  We may also need to make that a preference the user can specify.  But separating "id" is clearly wrong and is probably English defaults bleeding through (i'd -> i [woul]d) so i'll register that as a bug against the tokenizer.

**Comment by monzug** [comment]
Actually, I was testing without selecting the language. in this case it was English in both origin and target language to see if the selection matter. as a matter of fact it does. If I specify latin, id is not separated. so it works fine. will close this one.

**Comment by balmas** [comment]
oh, great!

**Comment by monzug** [comment]
retest in Chrome and Safari. id is shown correctly if language is Latin.
