### ISSUE TITLE
Greek and Arabic alignment

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#59]
with Greek origin text  or  Greek target text, I have a failed tokenization process (see screenshot).
In Arabic language, the characters are not displayed correctly in the alignment groups (see screenshot)
tested in FF/PC

![greek-alignment](https://user-images.githubusercontent.com/41396793/97725011-096c8e00-1aa4-11eb-8539-1391c607a56c.JPG)

![arabic-alignment with text](https://user-images.githubusercontent.com/41396793/97725027-0f626f00-1aa4-11eb-9fe0-38df64f3fb2e.JPG)

**Comment by irina060981** [comment]
> It is because of the same problem:
> 
> > My scenario: I have Latin as origin language and 3 target languages (2 English and Greek). When I do the alignment, the third language (Greek) has no text displayed. see screenshot
> 
> I checked we get 500 Error for Greek chars from tokenization service.
> I updated the code - to print the error to notification bar.
> 
> For now if one text is not tokenized - all tokenization is cancelled
> ![image](https://user-images.githubusercontent.com/12377640/97667419-8c550f00-1acb-11eb-92d0-0a4c5d5db266.png)
> 
> _Originally posted by @irina060981 in [#50 (comment)](https://github.com/alpheios-project/alignment-editor-new/issues/50#issuecomment-719262998)_

Greek chars should work.  Are they being encoded as utf-8?

_Originally posted by @balmas in https://github.com/alpheios-project/alignment-editor-new/issues/54#issuecomment-719551278_

would check it

**Comment by monzug** [comment]
How about the Arabic? Thanks

**Comment by irina060981** [comment]
Would be fixed with the PR

**Comment by irina060981** [comment]
Merged and closed
