### ISSUE TITLE
Undo an alignment group

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#590]
Related to #576 
while testing the above enhancement, I come across the ability to undo (or redo) an alignment group. see screenshots below:

'ina' is inside a created alignment group so I cannot merge, delete, edit, ecc. this token
![Screen Shot 2021-11-03 at 2 16 03 PM](https://user-images.githubusercontent.com/41396793/140080309-08871b11-fa5f-4000-91ec-8864e5b0f4d4.png)

however, by clicking on undo I can go back to previous state, despite its current status of alignment group
![Screen Shot 2021-11-03 at 2 17 28 PM](https://user-images.githubusercontent.com/41396793/140080306-7ab5c6c5-6c38-40ac-9360-6544b3ee0d25.png)

I don't recall if we did discuss this in the past. I just want to be sure that this is the expected behavior.

**Comment by irina060981** [comment]
@monzug , could you describe steps - that I could reproduce it?
I didn't fully understand what scenario was used.

**Comment by irina060981** [comment]
I believe it is from this bug (if I understood correct your description) - https://github.com/alpheios-project/alignment-editor-new/issues/592

It is fixed

**Comment by monzug** [comment]
Nope, it's not related to issue #592 .
Let's do an alignment group and then remove all the tokens in the original, I can also 
![Screen Shot 2021-11-04 at 2 39 05 PM](https://user-images.githubusercontent.com/41396793/140323632-f4df5f1c-588e-48d5-9967-9839fed89063.png)
![Screen Shot 2021-11-04 at 2 38 27 PM](https://user-images.githubusercontent.com/41396793/140323639-e1fb9513-f98f-481c-925a-d296d053d5f4.png)

**Comment by irina060981** [comment]
it is almost the same as for insert - but for delete :)
I added a fix for clear history

**Comment by monzug** [comment]
fix is working. I cannot reproduce the above scenario any longer. Thanks!
