### ISSUE TITLE
Empty token in HTML output and one more

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#591]
Related to #576 
1) I added a new token and then created an alignment group with the new token. When I undo in edit text, the second part of the alignment group (in this case the token in the translation) is still part of the alignment group and I cannot change its status

![Screen Shot 2021-11-03 at 4 24 27 PM](https://user-images.githubusercontent.com/41396793/140090358-4906d4c1-6e68-4b98-9e94-cfc18a1f956d.png)

2) I really don't know how I ended up with an empty token in original and still a token in translation in the html output. see screenshot

![Screen Shot 2021-11-03 at 4 08 14 PM](https://user-images.githubusercontent.com/41396793/140087841-0f83fdf9-b79f-41d4-a756-4d59c7eebfe3.png)

**Comment by irina060981** [comment]
I believe it is from this bug - https://github.com/alpheios-project/alignment-editor-new/issues/592

It is fixed

**Comment by monzug** [comment]
part 2 is actually fixed. the original was removed by a undo/redo action described in #590

**Comment by monzug** [comment]
part 1 is still reproducible as reported in issue #576 too.
