### ISSUE TITLE
We should not allow to delete all tokens from a segment

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#595]
related to issue #576 
I was able to delete all tokens from a segment. As said in the enhancement, we should not be able to delete all  tokens from a segment: "the only limit we could not delete all tokens from a segment". see below

"logs" is the last token in the segment. as you can see the trash icon is active
![Screen Shot 2021-11-04 at 2 27 20 PM](https://user-images.githubusercontent.com/41396793/140331079-1b997982-e0ad-475e-8ef0-600046b23a5f.png)

if I click on the Trash icon, the last token of the segment is gone with no error in the log.
![Screen Shot 2021-11-04 at 2 26 56 PM](https://user-images.githubusercontent.com/41396793/140331081-571afeda-f7c7-47f3-aae0-9d9bcda841f4.png)

Steps to repro:
1) create a segment with few tokens
2) delete all tokens in edit text, except the last one (e.g. logs) for which the trash icon is not active.
3) click on undo, till you see that the trash icon in logs is active again (or go to the next token and then back to logs). 
4) now you can delete one by one all the tokens by redo.

**Comment by irina060981** [comment]
>now you can delete one by one all the tokens by redo.

I didn't understand - how did you get this result?
Could you list exact steps after deleting all tokens except one?

**Comment by monzug** [comment]
it's basically a lot of undo/redo. see screenshots
![Screen Shot 2021-11-05 at 2 34 45 PM](https://user-images.githubusercontent.com/41396793/140518928-6bdefe9c-9d79-42ed-8998-d2dec2d4509c.png)
![Screen Shot 2021-11-05 at 2 35 05 PM](https://user-images.githubusercontent.com/41396793/140518931-4e6a721e-94d4-4834-bdf3-7249e27eaeaa.png)
![Screen Shot 2021-11-05 at 2 35 13 PM](https://user-images.githubusercontent.com/41396793/140518932-55aa1f10-2201-4c02-b950-581f399ced45.png)
![Screen Shot 2021-11-05 at 2 35 20 PM](https://user-images.githubusercontent.com/41396793/140518933-e686c506-8d97-436a-bd33-ca60ddc63148.png)
![Screen Shot 2021-11-05 at 2 35 29 PM](https://user-images.githubusercontent.com/41396793/140518937-ede33e86-f36a-4920-ba5c-a4ba35adc421.png)
![Screen Shot 2021-11-05 at 2 35 36 PM](https://user-images.githubusercontent.com/41396793/140518940-41881b8d-00ec-4295-b936-9727d5278fdc.png)

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
this is definitely fixed in build 11/8. Thanks
