### ISSUE TITLE
insert token before and after a token in alignment group 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#599]
from #576 
There is a very minor 'issue'. If in edit text, I mouse over a token and then I go in align text and do an alignment with the same token, when back in edit text the token has both the message that is part of an alignment group and also the small icons to edit/merge/detete etc. When I click in one of the icons, I get the message that the token is inside an alignment group suggesting to ungroup first, the only action I can do is to insert a token before or after.

![Screen Shot 2021-11-05 at 2 51 47 PM](https://user-images.githubusercontent.com/41396793/140523245-ad534b11-6d45-46f5-8878-c28047112061.png)

an other example
![Screen Shot 2021-11-05 at 3 07 38 PM](https://user-images.githubusercontent.com/41396793/140523456-759f88af-e59e-4207-9551-422f998acb64.png)

![Screen Shot 2021-11-05 at 3 07 46 PM](https://user-images.githubusercontent.com/41396793/140523474-4d3906fb-1eaa-424c-abb4-2a4f8bb8ce0f.png)

**Comment by irina060981** [comment]
It is a bug with removing active status from token on going to another screen.
I am happy that we are working together and you catch such bugs!

Fixed

**Comment by monzug** [comment]
Not longer reproducible. Thanks.
