### ISSUE TITLE
(TIR 1a, 5, 6) Support Plain Text Input

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#60]
1.Must accept input of source and translation text in either plain text and TEI XML
4.Must support creation of a new alignment via upload of a file adhering to the Alpheios XML alignment schema
5.Must support creation of a new alignment via upload of a set of plain text matched segments
6.Should be extensible to easily support creation of new alignments from other automatic alignment output formats
7.May support retrieval of input text from a [DTS API document endpoint URL](https://distributed-text-services.github.io/specifications/)

From https://github.com/alpheios-project/documentation/blob/master/development/alignment-editor.md

The first part - input plain text is done (besides some problems with greek, arabic and line breaks) - #59, #55

Tei input:
- from manual input (textarea)
- from xml file, Alpheios XML alignment schema
- from link

(may be it is worth to do the same for plain text for each source text individually)

**Comment by balmas** [comment]
I'm going to split this one into multiple issues as the pieces will be in different milestones

**Comment by balmas** [comment]
This issue now covers:
(1a)
* Plain text input of origin and source text(s) via direct input (textarea)
* Plain text input of origin and source text(s) via file upload

(5)
* support for segments to be defined (via double blank lines) in the direct input and uploaded text files

**Comment by balmas** [comment]
implicitly included is also the code design requirement

(6) Should be extensible to easily support creation of new alignments from other automatic alignment output formats

**Comment by irina060981** [comment]
>(1a)
Plain text input of origin and source text(s) via direct input (textarea)
Plain text input of origin and source text(s) via file upload

Done

>support for segments to be defined (via double blank lines) in the direct input and uploaded text files

would be checked

**Comment by irina060981** [comment]
>(6) Should be extensible to easily support creation of new alignments from other automatic alignment output formats

@balmas, what exactly should be done here in Milestone 1?

**Comment by balmas** [comment]
>> (6) Should be extensible to easily support creation of new alignments from other automatic alignment output formats

> @balmas, what exactly should be done here in Milestone 1?

Here's my understanding of how the code as currently designed supports this:

The  `uploadType` is set in the `TextsController`
The `UploadController` defines upload methods per `uploadType`
The `SourceText` defines a `convertFromJson` method which handles the details of converting the uploaded data to text that can be used to create an `AlignedText` (including definition of the tokenization method)

So to add a new supported upload type we would

1. Add a new `convertFrom...` method to `SourceText` to support the specific type of input 
2. Add a method to handle the new uploadType in the `UploadController` (this method would determine which convert method on `SourceText` to call) 
3. If in the the format of the new type is already tokenized, create a new tokenization class to convert those tokens into the token structure of the alignment editor.
4. Add the new type to a list of supported upload types in the `TextsController`
5. Present the list of types in a select box to the user in the `text-editor-single-block.vue` component
6. Have the `TextsController` pass the selected `uploadType` to the `UploadController`

I think this works, but I'm wondering if it makes sense to move the conversion methods out of `SourceText` and into `UploadController`. I think it reduces the places the code needs to be touched to add a new upload type. What do you think @irina060981 ?

As I look at the code, I also just realized that I  missed explicitly stating the following requirement:

8. Must accept *upload* of source and translation text in either plain text and TEI XML

**Comment by irina060981** [comment]
> support for segments to be defined (via double blank lines) in the direct input and uploaded text files 
would be fixed with https://github.com/alpheios-project/alignment-editor-new/pull/87

**Comment by balmas** [comment]
@irina060981 should we make the upload of plain text a new issue?

**Comment by irina060981** [comment]
>@irina060981 should we make the upload of plain text a new issue?

I think it is a good idea - this way it would be easier to track it :)
Will do that

**Comment by irina060981** [comment]
Ok now I could close it
