### ISSUE TITLE
Insert tokens twice, gives errors in the web console

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#600]
Chrome/Mac, latest build of 11/05.
I inserted few tokens before the word novum and all went well, then I inserted again other tokens before the same word, and I found a bunch of warning in the web console of duplicate keys. As a matter of fact, I noticed two things:
1) the inserted words got mixed up
2) if I do an annotation for one token, it does add automatically to an other token.
I tested by adding same words and different words.

![Screen Shot 2021-11-05 at 3 30 26 PM](https://user-images.githubusercontent.com/41396793/140528372-f1b84e8d-28b9-4b21-8fac-7ad6dc2d3bf2.png)

I inserted two sentences before aliquid. words got mixed up and also annotation is repeated
![Screen Shot 2021-11-05 at 3 45 08 PM](https://user-images.githubusercontent.com/41396793/140529342-33dacfff-6211-4f50-a4ea-ff4e96ddcc25.png)

**Comment by irina060981** [comment]
Yes, application doesn't expect that the token would be editted twice, but its id is not changed.
I didn't think about it.

**Comment by irina060981** [comment]
This bug is fixed

**Comment by monzug** [comment]
tested in latest build 11/8 and all looks good: no errors in log and no mixed up words in align text. Thanks
