### ISSUE TITLE
(TIR 8) May impose restrictions on the length of allowed input text if necessary.

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#61]
From https://github.com/alpheios-project/documentation/blob/master/development/alignment-editor.md

**Comment by irina060981** [comment]
After on-line meeting:

First try to optimize rendering of layout - scroll-bar, flextbox
Then add an option for max characters with spaces - 5000 (each text)

**Comment by irina060981** [comment]
I did some optimization for layout:

- tokens editor renders only after first show
- added max-height and scroll for alignment groups editor

**Comment by irina060981** [comment]
Added the following workflow

- added a global option for setting max characters per text (default 5000)
![image](https://user-images.githubusercontent.com/12377640/109800033-6ea9d900-7c68-11eb-862c-ce05584cebfa.png)

- added updated characters count with showing max
![image](https://user-images.githubusercontent.com/12377640/109800107-84b79980-7c68-11eb-8dfa-937593c3a13f.png)

- until any text has length greater than maximum - align button is disabled
![image](https://user-images.githubusercontent.com/12377640/109800172-99942d00-7c68-11eb-8960-4d91221fa728.png)

![image](https://user-images.githubusercontent.com/12377640/109800199-a022a480-7c68-11eb-848d-ff09ffe4a4df.png)

**Comment by monzug** [comment]
More testing is needed. 
A couple of suggestions:
1) Max characters per text -> I would add that is (recommended for performance) or similar
2) I would set the field limit from 1 (right now 0 is allowed) to a max number (not sure what it could be) - with 1000000 I got a performance error

**Comment by irina060981** [comment]
- updated label for max characters option
- added min/max for the field

![image](https://user-images.githubusercontent.com/12377640/109925311-5049e900-7d0d-11eb-8970-464dde37e6ff.png)

**Comment by monzug** [comment]
tested in Chrome/PC and safari, FF and Chrome/Mac. works fine.
