### ISSUE TITLE
Undo not active after splitting a token

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#610]
from #548 
there is a scenario that I am still trying to reproduce in which undo/redo are not active so I cannot undo/redo a split. see screenshot (need more time to try to find a reproducible scenario). no errors in the log
in edit text split a token, then go to align text and add an annotation on a portion of the token, go to edit text again: undo/redo not active. (tornano was split in torn and ano, then add annotation to torn only)

![Screen Shot 2021-11-11 at 5 13 08 PM](https://user-images.githubusercontent.com/41396793/141332056-4bac84c9-d5ff-4d07-8f38-315f72664337.png)

found the reproducible scenario: in align text if I highlight the token and then deselect it (it does happen frequently thinking that I am in annotation mode), then in edit text the undo/redo are not active as if the token is in an alignment group.

steps to repro:
in edit text, split a token in two.
in align text, highlight one portion of the split token then deselect, add an annotation on this portion of the token.
go to edit text again, see that undo and redo are not active

**Comment by irina060981** [comment]
>found the reproducible scenario: in align text if I highlight the token and then deselect it (it does happen frequently thinking that I am in annotation mode), then in edit text the undo/redo are not active as if the token is in an alignment group.

The reason is the following:

When you select a token at the first time - it is added to a group.
At the moment when token is grouped - appliction clears history.
And we don't have a feature to restore history if a user changes his mins and deselect the token.

So there is no bug here - it is a result of clearing history workflow

_Originally posted by @irina060981 in https://github.com/alpheios-project/alignment-editor-new/issues/548#issuecomment-966688799_

**Comment by irina060981** [comment]
So it is not a bug

**Comment by monzug** [comment]
@irina060981 I think deselecting the token should be considered as an ungrouping action. the problem here is that I do not have any token 'highlighted' or 'part of a group'. see below
![Screen Shot 2021-11-12 at 7 43 08 AM](https://user-images.githubusercontent.com/41396793/141422412-8ba03dbb-8bc6-450f-a080-d2611246e9c6.png)
![Screen Shot 2021-11-12 at 7 43 17 AM](https://user-images.githubusercontent.com/41396793/141422419-1b814141-368d-423d-8e50-f8d86d797dec.png)
![Screen Shot 2021-11-12 at 7 43 30 AM](https://user-images.githubusercontent.com/41396793/141422420-010c3119-7b5b-463f-a2a4-1fef26d089d2.png)
![Screen Shot 2021-11-12 at 7 43 38 AM](https://user-images.githubusercontent.com/41396793/141422423-443f4459-9acf-440c-a06b-a53a8c7db921.png)
![Screen Shot 2021-11-12 at 7 43 54 AM](https://user-images.githubusercontent.com/41396793/141422426-2521c267-d7c0-48b9-b826-d4fe23fd5ee5.png)
![Screen Shot 2021-11-12 at 7 44 05 AM](https://user-images.githubusercontent.com/41396793/141422430-c81a76c1-96c4-4888-9edc-110e70efdd8e.png)

**Comment by irina060981** [comment]
As I could see on the second screenshot - you add favore to a group, and then removed it.
I agree it is a unselect action.
But anyway - we don't have restore history workflow as I described before.

What exactly do you see here as a minor bug?
What should be changed?

**Comment by irina060981** [comment]
Yes, when you add an annotation - there is no clear history action.
As an application could not know that a user will consider his adding to alignment group as a mistake on the next step, application could not decide clear history on this adding, but not clear history on other adding - they have no difference on this step.

What exactly do you suggest?

**Comment by monzug** [comment]
to keep it open for future consideration.

**Comment by irina060981** [comment]
Restore history is a rather heavy feature.
Then I will change tags for this issue

**Comment by monzug** [comment]
we have a list of issues to discuss and this is not a priority so I'll change tags
