### ISSUE TITLE
after tokenization, I can still change Text/TEI option in Enter text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#616]
Just noticed but it has been there for a while.
let's have latin text in original and English text in Translation (for convenience I used the same Latin text in my example below). After tokenization, go back to enter text and click on the Text icon. I am able to change Text to TEI. Once done, I cannot change it back to Text, not I cannot change Text/TEI in the Translation screen.
see below.

1) go back to Enter text after tokenization and click on Text icon. see that Text and TEI are editable.
![Screen Shot 2021-12-18 at 2 28 41 PM](https://user-images.githubusercontent.com/41396793/146642786-4a696555-0c9c-4edd-96c6-9786849d4489.png)

2) after changing Text to TEI, the fields are greyed out.
![Screen Shot 2021-12-18 at 2 28 53 PM](https://user-images.githubusercontent.com/41396793/146642783-0206cf47-c2aa-4bdb-a698-e9055fa9f976.png)

3) Text is greyed out in the Translation screen.
![Screen Shot 2021-12-18 at 2 29 11 PM](https://user-images.githubusercontent.com/41396793/146642781-5aa76f2e-d6fa-484f-a347-a3670db6ac0c.png)

I was not expecting to be able to change this setting after tokenization and I do not se the reason to do it.

**Comment by irina060981** [comment]
oh, it is a small bug - will fix it later

**Comment by monzug** [comment]
Thanks!!!!

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
fixed. Thanks
