### ISSUE TITLE
Add a feature - dtsAPI upload available

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#617]
From on-line meeting with @abrasax 
When in standard mode (the default mode) the user would go directly into his local file system if he chooses upload
to get the current system that shows also the DTS option he would have to go into the OPTIONS on the text enter screen and choose ACADEMIC mode-  then we he clicked on upload he would see the current two options- DTS or the local file system.

**Comment by irina060981** [comment]
Added a new feature

![image](https://user-images.githubusercontent.com/12377640/149446496-52dd85eb-6403-445d-b374-9e002f2728d7.png)

It controls the way DTS API Upload is available.

If it is equal false (Standard mode)

![image](https://user-images.githubusercontent.com/12377640/149446605-85d658fe-3e7b-4156-9b74-4705ea66bb3e.png)

If it is equal true (Academic mode)

![image](https://user-images.githubusercontent.com/12377640/149446630-0c004f91-98fe-42f9-81f1-c66f7b574f2e.png)

**Comment by monzug** [comment]
looks good. just a couple of comments:
1) can we move the enable DTSAPI above use language specific tokenizer? the checkboxes look alike so it would fit better there (esthetically).
2) when I click on Reset all in custom options, the checkboxes are back on default only when I close the custom pop-up and reopen again. Note that the selection of any checkbox takes effect immediately on the background. see screenshots
![Screen Shot 2022-01-14 at 2 31 06 PM](https://user-images.githubusercontent.com/41396793/149523170-2aead936-39af-46ae-b7ed-e8b2a329e46d.png)
![Screen Shot 2022-01-14 at 2 30 55 PM](https://user-images.githubusercontent.com/41396793/149523176-8fb2a410-797f-46ec-a3e0-f8ca1e339587.png)
![Screen Shot 2022-01-14 at 2 30 45 PM](https://user-images.githubusercontent.com/41396793/149523181-9237903a-6f21-43da-ba24-7d5081a3c59e.png)
![Screen Shot 2022-01-14 at 2 30 35 PM](https://user-images.githubusercontent.com/41396793/149523187-bcf304ea-473c-4bc7-8f64-77a71f9be1af.png)

**Comment by irina060981** [comment]
>1. can we move the enable DTSAPI above use language specific tokenizer? the checkboxes look alike so it would fit better there (esthetically).

Yes, I could move - I place it here to be more visible outside all other checkboxes

**Comment by irina060981** [comment]
>2. Can we remove No file selected? I do not see any advantages on having it.

No, I could not remove it without full redesign of the file input - it is a standard dile input rendered by browser, so you could notice - that browsers could print different text here

**Comment by irina060981** [comment]
>3. when I click on Reset all in custom options, the checkboxes are back on default only when I close the custom pop-up and reopen again. Note that the selection of any checkbox takes effect immediately on the background. see screenshots

Oh, I see, thank you for the catch - I will check it

**Comment by monzug** [comment]
> > 2. Can we remove No file selected? I do not see any advantages on having it.
> 
> No, I could not remove it without full redesign of the file input - it is a standard dile input rendered by browser, so you could notice - that browsers could print different text here

I just noticed the different behavior of current version versus an old version from about a year ago 
in the old version, after selecting a file to upload, the Choose file button (with No file selected) is not longer displayed on screen. see screenshots
![Screen Shot 2022-01-18 at 2 58 20 PM](https://user-images.githubusercontent.com/41396793/149952121-a07cac04-fb7e-40c9-9754-937b37c5f65e.png)
![Screen Shot 2022-01-18 at 2 56 40 PM](https://user-images.githubusercontent.com/41396793/149952125-6a3856bc-2cb4-4fd9-ab93-4110b71a9f27.png)
![Screen Shot 2022-01-18 at 2 55 59 PM](https://user-images.githubusercontent.com/41396793/149952129-91bfbd48-4faf-42cf-8409-f6f587c1b91d.png)
![Screen Shot 2022-01-18 at 2 55 47 PM](https://user-images.githubusercontent.com/41396793/149952134-4ed0146f-ac8d-4647-872b-107214f1c276.png)
![Screen Shot 2022-01-18 at 2 55 13 PM](https://user-images.githubusercontent.com/41396793/149952135-39e6adc0-e0df-4c6d-be87-482eb7fbe5d8.png)

**Comment by irina060981** [comment]
@monzug , I didn't understand your suggestion.
An application hides file input if a file was uploaded without errors, it is visible only if there are some errors.

If you see it after you upload a correct text/file - then please give me exact steps with screenshots.
For now I could not reproduce it

**Comment by irina060981** [comment]
Oh, I understood what are you talking about - will check

**Comment by irina060981** [comment]
Fixed (hope, I underxtood correct your concerns :) )

**Comment by monzug** [comment]
yes, Thanks. issue 2 is fixed. Great.

**Comment by irina060981** [comment]
I didn't solve these 1 and 3 issues, will solve today :)

**Comment by irina060981** [comment]
- "Enable upload from DTS API" option is moved
![image](https://user-images.githubusercontent.com/12377640/151289723-c749ba33-9975-4836-9c41-022b8cc41202.png)

**Comment by irina060981** [comment]
The 3 I will do later - it is more complex than I expected

**Comment by irina060981** [comment]
It is outdated for new design - https://github.com/alpheios-project/alignment-editor-new/issues/634
