### ISSUE TITLE
Update metadata (book) icon

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#618]
From on-line meeting with @abrasax 

It is too small for having so much details.
Let's leave book's pages empty.

**Comment by irina060981** [comment]
Done 
![image](https://user-images.githubusercontent.com/12377640/149431938-2ee9fa6c-86e4-4867-ae65-47948373cebf.png)

**Comment by abrasax** [comment]
perfect

**Comment by monzug** [comment]
looks good.
![Screen Shot 2022-01-14 at 2 48 04 PM](https://user-images.githubusercontent.com/41396793/149525518-e2253ca3-be82-41a7-848b-0b88ad3a5d6a.png)
