### ISSUE TITLE
(TIR 9-10) Support add/update/upload metadata for source texts

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#62]
9.Must allow user to add identifying bibliographic metadata about source and translation texts (e.g. author, title, edition, etc.)
10.May support automatic detection of metadata provided in Dublin Core, Schema.org or other standard in the source input text (in the case of TEI input)

From https://github.com/alpheios-project/documentation/blob/master/development/alignment-editor.md

**Comment by balmas** [comment]
See also #4

**Comment by balmas** [comment]
I would like the interface to offer the following fields to the user for each aligned text:

|fieldname|fieldtype|multivalued|
|---|---|---|
|identifier|URI|No|
title|string|No|
|creator|string|Yes|
|contributor|string|Yes|
|publisher|string|No|
|date copyrighted|date|No|
|source|URI|No|
|description|string|No|

These map directly to the corresponding vocabulary items in the DCMI Terms vocabulary (https://www.dublincore.org/specifications/dublin-core/dcmi-terms/) and the fieldnames stored in the data object should use the corresponding URIs

At this point, I don't think we will *require* any of the metadata fields to be supplied for an aligned text, but I'd like to reserve the possibility to change that decision so the implementation should account for the possibility that one or more of the fields may be required.

The tokenizer service also has a requirement to be able to parse this metadata from the supplied file and return it along with the tokens. See alpheios-project/tokenizer#14.

**Comment by irina060981** [comment]
We should support metadata provided in at least the following ways:

* within elements in the teiHeader of the TEI XML document 
* for texts retrieved from a DTS API, in the dts:dublincore and dts:extensions properties from a [DTS API collections endoint](https://distributed-text-services.github.io/specifications/Collections-Endpoint.html)
* as user entered name/value pairs

In the first two cases, we need to allow the user to edit any metadata that was automatically extracted from the XML or DTS API as it's unlikely we will be able to get this 100% correct.  Internally, it can probably be modeled as key/value store. But note that we will want to support full URIs for metadata properties,  and probably should offer users the option to select terms from the Dublin Core controlled vocabulary (https://www.dublincore.org/specifications/dublin-core/dcmi-terms/)

_Originally posted by @balmas in https://github.com/alpheios-project/alignment-editor-new/issues/2#issuecomment-657513196_

**Comment by irina060981** [comment]
Published PR for the first step:
For the issue #62 

- created `Metadata` and `MetadataTerm` classes to handle with metadata, attached to `SourceText`
- created `MetadataBlock` and `MetadataTermBlock` components, attached to `text-editor-single-block`
- added Metadata button to text-editor-single-block menu - it works as toggle

![image](https://user-images.githubusercontent.com/12377640/103215789-1ac8fe00-4960-11eb-8715-7709ecdf5b1f.png)

![image](https://user-images.githubusercontent.com/12377640/103215727-f2d99a80-495f-11eb-99b8-10033d3aef3a.png)

- defined workflow for inputs:
   - single value metadata - add/update/clear inside its one input
   - multivalued metadata: to add - simply type a value and blur/press Enter - it would be printed under the input
   
![image](https://user-images.githubusercontent.com/12377640/103215669-c291fc00-495f-11eb-984e-8dc69a86037a.png)

   - edit/delete - click on the value - it would be activated for editing inside input

 - metadata inside text-editor-single-block could be edited at any time

**Comment by irina060981** [comment]
The next step (getting metadata from the tokenizer service) would be postponed until this feature (parsing metadata from TEI) would be ready inside tokenizer service

**Comment by irina060981** [comment]
Postponed feature was saved to a separate issue - https://github.com/alpheios-project/alignment-editor-new/issues/123

**Comment by irina060981** [comment]
@monzug 
this feature was realized here

9.Must allow user to add identifying bibliographic metadata about source and translation texts (e.g. author, title, edition, etc.)

The detailed explanation in the upper comments

**Comment by monzug** [comment]
questions/issues:
1) I can download and upload the metadata in json. when I download from origin as tsv and upload again the show metadata fields are empty. why does not the download show metadata work for origin or target text?
2) I don't see any restriction in any fieldtype such as date copyrighted (I can enter any character). I guess this is ok, just checking.
3) when I edit Creator and Contributor fields, the entry goes below the entry field, field is back empty,  then I can reselect it and add to the field. is this step necessary?
4) I believe that for the above reason, Creator and Contributor do not get populated when I upload the json file. see attachment

![Screen Shot 2021-02-04 at 4 12 31 PM](https://user-images.githubusercontent.com/41396793/106912993-da4d6480-6703-11eb-9853-5acf78071123.png)

5) Tooltips are all upper case. any reason why all words upper case?

**Comment by monzug** [comment]
tested in Chrome/PC and Safari/Mac

**Comment by irina060981** [comment]
>Tooltips are all upper case. any reason why all words upper case? 
It is because of styles mix - would fix it

**Comment by irina060981** [comment]
>I can download and upload the metadata in json. when I download from origin as tsv and upload again the show metadata fields are empty. why does not the download show metadata work for origin or target text?

Download/upload of metadata is available only for json
Csv/tsv download/upload - was a simple first iteration for source text (it is out of requirements),
it includes text, language, direction and sourceType

**Comment by irina060981** [comment]
>I don't see any restriction in any fieldtype such as date copyrighted (I can enter any character). I guess this is ok, just checking.

I believe it is ok for now - I don'y have specific requirements for it fo this stage

**Comment by irina060981** [comment]
>when I edit Creator and Contributor fields, the entry goes below the entry field, field is back empty, then I can reselect it and add to the field. is this step necessary? wouldn't it be easier to separate each contributor by comma , or ; ?

It works the following way - you enter any text, click enter - and it is saved as a value inside a multivalue property, then you could edit it by selecting or delete after selecting.

I don't think that it is a good practice to set a "clever" dividing to the creators or contributors by some specific characters, that could be used inside the value.

From my point of view - just type aned enter is easier.
@monzug , do you think that defining separator is better?

**Comment by irina060981** [comment]
>I believe that for the above reason, Creator and Contributor do not get populated when I upload the json file. tested in Safari/MAC and Chrome/PC - see attachment

They would be downloaded to json and uploaded after if they were saved to values.
![image](https://user-images.githubusercontent.com/12377640/107013685-659f2680-67e6-11eb-9e87-03aa8b063028.png)

But I could not reproduce the case when they left in the field and was not saved

Could you point me steps - how you are able to print creator / contributor to the field, download - then upload and the fields are empty.
Could you also attach json file of that case

**Comment by monzug** [comment]
4) I would prefer the easy way: enter a word that is saved automatically and each name should be separated by a ; 
5) see below the steps and the empty fields in Contributor and Creator

a) enter a word in both fields, reselect from below the entry field in order to populate it

![Screen Shot 2021-02-05 at 4 07 00 PM](https://user-images.githubusercontent.com/41396793/107051909-4c3db080-67cd-11eb-9595-5988f24bd988.png)

b) align and save as json. upload the json file. note that Contributor and Creator are empty. will email you the related json file.

![Screen Shot 2021-02-05 at 4 07 47 PM](https://user-images.githubusercontent.com/41396793/107052050-7c854f00-67cd-11eb-8562-3fa58d57b602.png)

**Comment by irina060981** [comment]
>I would prefer the easy way: enter a word that is saved automatically and each name should be separated by a ; (we can check with @balmas if there are specific requirements)

Then how would the application know - when you finished to type the first value and started to enter the next value?
Checking if you entered ; ?
----------
You described the workflow - when the values for multivalu fields were not saved, because you didn't press Enter

**Comment by monzug** [comment]
got it! I have to say that it's not so obvious that the word is saved when it is under the field and it is not saved when it populates the field.

**Comment by balmas** [comment]
> 1. I would prefer the easy way: enter a word that is saved automatically and each name should be separated by a ;  (we can check with @balmas if there are specific requirements)

With regard to multi-valued fields:  in the underlying data, we should  have each field value stored separately.  This does not necessarily mean that is how the UI has to represent it (i.e. the UI could join and split on ; for purposes of display and easy of user input). For the moment, I would suggest we go with what @irina060981 has coded since it accurately reflects how the data should be stored, and make an issue for further refining the user interface for this later.

**Comment by irina060981** [comment]
>I don't see any restriction in any fieldtype such as date copyrighted (I can enter any character). I guess this is ok, just checking.

This is placed in a new issue for later devopment

**Comment by irina060981** [comment]
>>Tooltips are all upper case. any reason why all words upper case?

>It is because of styles mix - would fix it

It is fixed in a separate issue

**Comment by irina060981** [comment]
@monzug , do you have other questions or notes here?

**Comment by monzug** [comment]
all good.
