### ISSUE TITLE
TEI is detected in old version but not in latest one

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#624]
related to #622 which is about copying content with TEI tags.
while checking the above github item, I come across the following change in detecting TEI versus text. I downloaded a file from perseus which I called perseus.xml.
When I upload the file in alignment version available in http://alpheios-alignment-editor.irina-sklyarova.ru/, the TEI icon is checked (from text goes to TEI), see screenshot

![Screen Shot 2022-01-18 at 2 56 40 PM](https://user-images.githubusercontent.com/41396793/149956596-9bd2f6f0-7c62-4bc0-a48c-78d7270c3669.png)

If I upload the same file in the alignment version from 17/01, the text icon is checked - see below

![Screen Shot 2022-01-18 at 2 58 20 PM](https://user-images.githubusercontent.com/41396793/149957010-966a262a-ec4b-471d-b4b6-8755cc58142e.png)

why such a difference?
this is the file in question 
[perseus.xml.zip](https://github.com/alpheios-project/alignment-editor-new/files/7889816/perseus.xml.zip)

**Comment by irina060981** [comment]
@monzug, thank you for the attachment!

I am sorry, but it is broken and I could not test - I see it this way (after unzip)
![image](https://user-images.githubusercontent.com/12377640/150030336-3007857e-95f1-4ea1-9624-1c14ea890b7c.png)


And I could not open it even in a text editor

Could you attach it again please

**Comment by irina060981** [comment]
I tested on my xml files - they are detected by extension - correctly

**Comment by irina060981** [comment]
[t2fromperseus.zip](https://github.com/alpheios-project/alignment-editor-new/files/7894124/t2fromperseus.zip)
I was able to reproduce with @abrasax file

It was because of double check and failing because of it https://github.com/alpheios-project/alignment-editor-new/issues/622 on text check (that was not designed it is a bug)

Now it is fixed

**Comment by monzug** [comment]
this is fixed in the alignment editor version from 19/1
