### ISSUE TITLE
scaife or perseus .xml files failed to upload 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#627]
this is due to the fix for issue #176. it seems like only xml file in AlpheiosV1 format are allowed. why is that? it's a big limitation compare with previous build in which we supported xml files from Perseus, Scaife and Alpheios reading tools.

see error message
![Screen Shot 2022-01-26 at 3 40 18 PM](https://user-images.githubusercontent.com/41396793/151183881-87393585-f23d-4a32-9f78-b0f76e617491.png)

**Comment by irina060981** [comment]
Monica, if we want to support an upload of some new file format - I need to develop an upload workflow.

For now we have 
- JSON format - that is created by me
- XML format that is used by Ugarit (and this was said in #176) -  I believe that it is equal to Alpheios V1 format.

If we want to support more - I need to create a specific workflow for each. 
It could not understand it without additional developing.

If you suggest to support more - let's create specific issues with attached examples and exact url where I could create more examples.
And put them in to my task's query - amd I will spend time for it.

**Comment by monzug** [comment]
Irina, I was not able to upload any xml files successfully yesterday. I tried xml files from Perseus, Scaife or Alpheios. The only format was ugorit files. today everything works perfectly. did you change anything in between?

**Comment by monzug** [comment]
Actually I see what's happening. if I upload an Ugorit file first, next I do a resume previous alignment of a scaife (or perseus file), then the upload fails with the error message that is not an Alpheios v1 files. The error in console is TypeError: w.isActive is not a function, not sure if this could be related to the xml upload failure.

**Comment by irina060981** [comment]
@monzug , I didn't change anything that is referenced to this feature.

I have realized only one feature - uploading from Ugarit xml (as it was defined in the issue #176 ).
If you think that other xml should have the same format and should be uploaded without any additional development - then I could check. 
There is no any exact criterias inside XML that it is Ugarit or any else - that's why I check some structures that are obligatory for the current xml upload.

Could you attach some examples - if you think that they are the same as Ugarit?
If you think that Error text is incorrect - let's change it - that we don't support such xml formats.

If they are not the same as Ugarit - they could fail with any error in the console.
And I need to do additional development to upload other formats.

Finally - what exactly I should do with this issue?

**Comment by irina060981** [comment]
And @monzug , why do you think that it is a bug? 

If a feature is not realized - from my point of view - it is not a bug.
If you agree with me - let's remove bug label.

**Comment by monzug** [comment]
well, I cannot resume a xml file after an ugorit file upload so that's a problem.

**Comment by irina060981** [comment]
Could you upload ugarit xml after ugarit xml? Or you could upload ugarit file only once?

**Comment by monzug** [comment]
see this sequence below (I have to go out so I do not have tome now, will talk at the noon call for me - I usually work in the afternoon).
![Screen Shot 2022-01-27 at 9 49 58 AM](https://user-images.githubusercontent.com/41396793/151324526-29098fcd-4797-4e51-b747-79e99f4f1b91.png)
![Screen Shot 2022-01-27 at 9 50 10 AM](https://user-images.githubusercontent.com/41396793/151324535-e10c4073-e86d-4280-91eb-64de81b68247.png)
![Screen Shot 2022-01-27 at 9 50 25 AM](https://user-images.githubusercontent.com/41396793/151324538-a5df36cf-927e-4384-bd98-f5bb1c935984.png)
![Screen Shot 2022-01-27 at 9 50 37 AM](https://user-images.githubusercontent.com/41396793/151324540-8836bec7-1d3f-4919-9fa7-13f167e03497.png)
![Screen Shot 2022-01-27 at 9 50 51 AM](https://user-images.githubusercontent.com/41396793/151324544-992f9c04-f7c4-4e6c-bcc1-94702964fa59.png)

**Comment by irina060981** [comment]
Could you attach scafie.xml?

I should check - why do you think it should be uploaded.
From my point of view if it is not the same as Ugarit - then it should not be uploaded, because I didn't developed this feature.
And didn't test it, and it is not described in the issue #176 .

**Comment by monzug** [comment]
as per the call, we are not expecting to upload xml file in resume previous alignment, only Ugarit xml files
