### ISSUE TITLE
(TIR 12-13) Support input, display of line breaks

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#63]
12.Must preserve line breaks in plain text input
13.Should support user identification of TEI elements representing line breaks in TEI input

From https://github.com/alpheios-project/documentation/blob/master/development/alignment-editor.md

**Comment by balmas** [comment]
Also 

17. Must allow user to edit line breaks at any point during alignment

**Comment by balmas** [comment]
Note that responsibility for preserving line breaks in the input is shared by the alignment editor and the tokenizer service. 

Alignment editor must provide the user with:

1) an interface for defining how line breaks are identified in the input text 
2) an interface for inserting or removing line breaks after the alignment process has started

(1) must be driven by the API options made available by the tokenization service for both plain text and TEI input

**Comment by balmas** [comment]
editing to be handled via #83

**Comment by balmas** [comment]
@irina060981 Note that the line break information can be found in the tokenizer output in the `line_break_before` property of the token object.  This needs to be read and used to set the `Token.hasLineBreak` property by `AlpheiosRemoteTokenizer.formatToken` when parsing the tokenizer results.

**Comment by irina060981** [comment]
Need to check it with doubleline segmentation

**Comment by balmas** [comment]
@irina060981 this line in AlpheiosRemoteTokenizer is normalizing double-lines to single before the text gets sent to the tokenizer

https://github.com/alpheios-project/alignment-editor-new/blob/20b255228ca85c6d990e2217a23f728065c62515/src/lib/tokenizers/alpheios-remote-tokenizer.js#L12

**Comment by irina060981** [comment]
@balmas , I would fix small bugs with doubleline segmentation and line_break_before with the following PR
https://github.com/alpheios-project/alignment-editor-new/pull/87

**Comment by irina060981** [comment]
About the following requierement:

>2. an interface for inserting or removing line breaks after the alignment process has started

@balmas , do you mean here - 
 - a user could add/insert line breaks only inside one segment?
 - a user would change line breaks after alignment has started in a special edit mode (where we also could split/join tokens)

am I right?

**Comment by irina060981** [comment]
I tested the case when we have more than two new lines
![image](https://user-images.githubusercontent.com/12377640/101619611-3d51b080-3a5f-11eb-9531-b12ab0beaba9.png)

And defined `doubleline` segmentation
It will return a single segment

![image](https://user-images.githubusercontent.com/12377640/101619797-78ec7a80-3a5f-11eb-9001-084b93769e50.png)

Does it a tokenization service bug?

Should we save such additional new lines? 
Are such cases (to use more than one new line in a row inside a segment) the part of the requirement:

> 2. an interface for inserting or removing line breaks after the alignment process has started

**Comment by irina060981** [comment]
May be this last requirement is similiar to this - https://github.com/alpheios-project/alignment-editor-new/issues/83

**Comment by balmas** [comment]
yes I think #83 covers the last requirement.

**Comment by balmas** [comment]
> I tested the case when we have more than two new lines
> ![image](https://user-images.githubusercontent.com/12377640/101619611-3d51b080-3a5f-11eb-9531-b12ab0beaba9.png)
> 
> And defined `doubleline` segmentation
> It will return a single segment
> 
> ![image](https://user-images.githubusercontent.com/12377640/101619797-78ec7a80-3a5f-11eb-9001-084b93769e50.png)
> 
> Does it a tokenization service bug?
> 
> Should we save such additional new lines?
> Are such cases (to use more than one new line in a row inside a segment) the part of the requirement:
> 

we do not have a requirement to support more than one new line in a row inside a segment.

the tokenization service should probably ignore any newlines above 2 in a row. I'll make this an issue there.

**Comment by balmas** [comment]
ready for testing (although TEI testing dependent on #78)

**Comment by monzug** [comment]
@balmas - question: an empty line is still counted as a segment. is this ok?

**Comment by balmas** [comment]
@monzug it depends upon what is selected as the segment identifier in the options:

![eb327742-b805-4d78-910a-52f9a993bad1](https://user-images.githubusercontent.com/644870/102101339-7dff5000-3df8-11eb-8673-c630214e0d80.png)

For plain text:
If doubleline is selected, then single lines should equal line breaks but not segments.  Doublelines should equal segments.

If singleline is selected then single lines should equal segments.

**Comment by monzug** [comment]
interesting. let me try that next.
an other one:  I used xml text as origin (tei gives an error so I kept  the text  source type  and plain text as target. the line are different (24 vs 21) but I didn't get an error. see attachment

![segments are different](https://user-images.githubusercontent.com/41396793/102104397-2531b680-3dfc-11eb-9f0c-467936beda5e.JPG)

**Comment by monzug** [comment]
@balmas, I kept doubleline as segment separator and had a origin text with both single line and double line.  in the alignment groups, the single line has a segment while the double line is a line break, so the opposite of what it should be.

![double-single-segment](https://user-images.githubusercontent.com/41396793/102110405-1c90ae80-3e03-11eb-9432-33f913248f55.JPG)

**Comment by balmas** [comment]
oh that screenshot is really confusing...

I think it is working mostly as expected. See below

![e066d6d3-13fa-4426-8430-eaaf9b6dda71](https://user-images.githubusercontent.com/644870/102130095-633fd200-3e1e-11eb-8da2-fee42f01a239.png)
![d56a0678-daef-40db-b6d8-ecae3bfceddb](https://user-images.githubusercontent.com/644870/102130139-7488de80-3e1e-11eb-8d4e-abb0e5654dce.png)

![28cc02d9-fba6-4d48-b021-f42df3028f8b](https://user-images.githubusercontent.com/644870/102130205-8f5b5300-3e1e-11eb-847a-e50dd0f18b40.png)
![67d6bd36-bbd5-4577-9fda-edd46caef373](https://user-images.githubusercontent.com/644870/102130208-8ff3e980-3e1e-11eb-8628-faa7b154763d.png)

![3a00338b-bfbf-452a-8987-51ba6da9a304](https://user-images.githubusercontent.com/644870/102130249-9e420580-3e1e-11eb-8e15-47d2da213e6d.png)
![e945519b-676e-4af4-a199-d39b0d42722f](https://user-images.githubusercontent.com/644870/102130251-9e420580-3e1e-11eb-971e-b013e9c1d394.png)

**Comment by balmas** [comment]
Note however, if you have > 2 lines in between segments, it messes up. This is to be addressed via alpheios-project/tokenizer#22

**Comment by monzug** [comment]
Yes, I had more than 2 lines.  as you said, it works as expected. I have a question on the details on the Text source type. Why do we have in both origin and target text, the option to specify how segments are separated in the text? if origin is doubleline and target singleline,  it's not so obvious how to count the segments  in order to avoid getting the  "The tokenization process was cancelled because origin and target texts don't have the same amount of segments." error.

**Comment by balmas** [comment]
> Yes, I had more than 2 lines. as you said, it works as expected. I have a question on the details on the Text source type. Why do we have in both origin and target text, the option to specify how segments are separated in the text? if origin is doubleline and target singleline, it's not so obvious how to count the segments in order to avoid getting the "The tokenization process was cancelled because origin and target texts don't have the same amount of segments." error.

Because it's possible these come from different sources, and are uploaded at different times.

The most likely use case is certainly that both will have the same type of segmentation (i.e. single or double line). But particularly for the case where a translation is added after the original alignment is created, we cannot assume that is the case.

I think it could be a good enhancement however to default the translation to the same options as the origin, if the origin has changed. This might not be the easiest thing to do however.

**Comment by monzug** [comment]
tested in poetry too. will update issue  alpheios-project/tokenizer#22  with an example of more than 2 lines

**Comment by monzug** [comment]
Tested in safari too with double and single line for text and TEI. most of the testing has been done with same origin and target text (or TEI) and same options.
