### ISSUE TITLE
Use icons for Help and Options buttons

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#630]
From on-line meeting with @abrasax 

Use icons instead of text inside buttons for Help (?) and Options (gear)

**Comment by irina060981** [comment]
Done 
![image](https://user-images.githubusercontent.com/12377640/151342778-5a1ade2e-f169-4a5f-a513-3144ef44749f.png)

**Comment by monzug** [comment]
They look good. Harry asked to add more space between the two icons and to add the tooltips. Thanks

**Comment by irina060981** [comment]
>They look good. Harry asked to add more space between the two icons and to add the tooltips. Thanks

Done

**Comment by monzug** [comment]
Thanks
