### ISSUE TITLE
Ugarit file in indexedDB

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#631]
related to #176 
I can successfully upload an Ugarit file with 2 or 3 languages. However, when I resume the related indexedDB file from the splash screen, the text from Ugarit is empty. see example with 3 languages
![Screen Shot 2022-01-27 at 2 38 46 PM](https://user-images.githubusercontent.com/41396793/151370286-f5a3a4f5-13eb-4d7a-bfeb-b765a0181c8e.png)

**Comment by monzug** [comment]
after this empty file is generated, any subsequent ugarit files uploaded from resume previous alignment is empty too.

**Comment by irina060981** [comment]
Yes, I saw this problem - will check after Options

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
tested in FF and Chrome, PC and Mac. this is fixed. Thanks
