### ISSUE TITLE
cannot do an alignment in Ugarit file

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#632]
related to #176 
if I upload any Ugarit file and then do an alignment, the following error is generated: Choose another token please - from the same segment, translation text. 
I have to save the file locally and then re-upload to be able to do an alignment
![Screen Shot 2022-01-27 at 2 54 26 PM](https://user-images.githubusercontent.com/41396793/151373813-b7bc65a5-7802-4819-89e6-daa2bb2a78ae.png)

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
tested in FF and Chrome (Mac and PC). This is fixed now. Thanks
