### ISSUE TITLE
Remove option's presets

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#634]
From online meeting with @abrasax and @monzug 

[RESET ALL to standard options]

Enable annotations - true/false (NEW - not realized)
       If true - Available Annotation Types

Enable Tokens Editor Screen - true/false

Enable Metadata - true/false  (NEW - not realized)

[SET ALL TO ADVANCED] 
(If click on it - then previous is hidden besides RESET ALL button, and the following is shown )

Enable annotations - true/false (NEW - not realized)
       If true - Available Annotation Types

Enable Tokens Editor Screen - true/false
        if true - choose icons  (NEW - not realized)

Tokenizer - choose remote/local 

Enable  DTS API

Enable IndexedDB check

**Comment by abrasax** [comment]
What are you doing working on Saturday ?  To the best of my knowledge you
will have plenty of time for these changes.
But perhaps we could speak Monday at 10 to try ensure that we keep further
iterations as few as possible.

**Comment by irina060981** [comment]
Done 
from the start

![image](https://user-images.githubusercontent.com/12377640/151659553-38366cd8-c05b-4514-a733-bc53d434d932.png)

after clicking on set to advanced

![image](https://user-images.githubusercontent.com/12377640/151659572-5074c22b-19a8-4f31-859c-40e72bcf6636.png)
![image](https://user-images.githubusercontent.com/12377640/151659576-ece05ef3-79ef-442f-a8fd-3a78d249f864.png)
![image](https://user-images.githubusercontent.com/12377640/151659579-a5b48844-aa33-4096-84ec-9bcab9f5621f.png)

and if click on the reset all

![image](https://user-images.githubusercontent.com/12377640/151659603-424ee3f6-6866-4b1a-bae1-2ef725b22335.png)

**Comment by monzug** [comment]
looks good. question on max chars per text (recommended for performance) - did you & Harry decide to drop it for good?

see screenshot from alignment.alpheios.net
![Screen Shot 2022-01-31 at 3 22 33 PM](https://user-images.githubusercontent.com/41396793/151810716-0160ddcf-7d2e-4842-a7a2-29f9e059f6a2.png)

**Comment by abrasax** [comment]
would that not only become relevant when the user had turned off indexedDB?

**Comment by monzug** [comment]
> would that not only become relevant when the user had turned off indexedDB?

yes, it does. it's the way to get there that is not so obvious. indexedDB is on by default, but you can see this option only when selecting Set all to advanced which seems to imply that you are turning on options.

**Comment by irina060981** [comment]
We talked about it on meetings - 
 - if we have IndexedDB - than we don't need limits by text size (by sense of this option)
 - otherwise this option becomes available
 
And if we have IndexedDB support - than text limits are defined in textarea

![image](https://user-images.githubusercontent.com/12377640/151884478-21c8f74a-44ba-4d87-8878-9d4e4627cf15.png)
So this is working according to requirements.

I believe that it is a design question? Should be IndexedDB support in the first part?

**Comment by monzug** [comment]
yes, it's a design question for sure.
also, about enable metadata check, it shows or hides the metadata icon. How about the Describe button? the latest is always on.

**Comment by irina060981** [comment]
Oh, thank you - forgot about describe button

**Comment by monzug** [comment]
waiting for the Describe button to be removed in sync with metadata check

**Comment by irina060981** [comment]
>waiting for the Describe button to be removed in sync with metadata check.
as per the design fault regarding indexedDB will enter a separate issue

Done
