### ISSUE TITLE
(TIR 14-15) Segments could be defined in source input

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#64]
14.If input does not provide aligned segments, then input source and translation text is to be initially identified as a single segment of text to be aligned (no automatic segmentation)
15.If input identifies aligned segments, then this information must be preserved with the alignment.

From https://github.com/alpheios-project/documentation/blob/master/development/alignment-editor.md

@balmas - I believe these requirements are for the tokenization service?
Client side application doesn't define segments on any step.

**Comment by balmas** [comment]
yes - the requirement for the client side application is to make it possible for the user to supply the correct tokenizer parameter values for their content

**Comment by balmas** [comment]
oops I entered a dupe of this. Closing - let's use #80 instead.
