### ISSUE TITLE
Reset all to default options removes the related languages from the Align text screen

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#642]
Reset all to default options removed the Language header from Align text, see below

![Screen Shot 2022-02-04 at 3 13 15 PM](https://user-images.githubusercontent.com/41396793/152543606-0d078ebb-67be-425f-aea2-2e14031db0ae.png)

to repro:
set Options to advanced and do an alignment. then change to default by clicking on Reset all to default options. you'll see that the language header is gone in both the translation and the original text in align text screen.

if this is by design, I honestly prefer if we keep showing the languages.

**Comment by irina060981** [comment]
No, it is a bug - will check

**Comment by irina060981** [comment]
Bug is fixed

**Comment by monzug** [comment]
Not longer reproducible
