### ISSUE TITLE
Language and Text icons not shown in Original

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#643]
This is a specific scenario. I click on start new alignment and then choose text to upload. at this point if I enter text directly in the text area (without using DTSAPI or uploading a file), the language icon and text icon are not shown in the Original. If I repeat the same steps in the Translation, both icons are still generated.

![Screen Shot 2022-02-04 at 3 42 45 PM](https://user-images.githubusercontent.com/41396793/152549173-9cdc6422-e595-4cea-896e-c7bab9d0b4dd.png)

see steps for translation where it works as expected

1) select choose text to upload.
![Screen Shot 2022-02-04 at 3 51 45 PM](https://user-images.githubusercontent.com/41396793/152549978-1d2fb696-3283-40fe-b300-47432e70de5c.png)
2) instead copy text in the text area
![Screen Shot 2022-02-04 at 3 51 56 PM](https://user-images.githubusercontent.com/41396793/152549973-411c6287-82b8-42a8-b6d5-93ed7bc6ce3b.png)
3) click outside the text area. the language and text icons are generated
![Screen Shot 2022-02-04 at 3 52 04 PM](https://user-images.githubusercontent.com/41396793/152549970-17b8dd3d-e644-4802-980d-b73693b4fd66.png)

**Comment by irina060981** [comment]
Thank you for detailed description - will check

**Comment by irina060981** [comment]
Fixed
