### ISSUE TITLE
Minimum one icon's group should be enabled for Tokens Editor Screen

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#644]
Looks good. if Enable Tokens Editor Screen is on but all the edit options are not checked, I cannot do anything with the tokens in edit text. I am ok with this. We could also required to have minimum one option checked but I do not think it's necessary.

_Originally posted by @monzug in https://github.com/alpheios-project/alignment-editor-new/issues/613#issuecomment-1029994668_

**Comment by abrasax** [comment]
yes certainly desirable. We should also have the icon choices under Options on the Edit Text screen.  They are not absolutely essential here.  If they are not checked here but subsequently checked there they should obviously be enabled. If it is simpler for the system, we could just enable the choice there.

**Comment by irina060981** [comment]
Decided on the on-line meeting to set all to ON by default

**Comment by abrasax** [comment]
yep

**Comment by monzug** [comment]
@irina060981 Irina, what is this fix supposed to do? I do not see the edit options in edit screen and I can still deselect all edit options.
I do only see that the all ON by default has been implemented. if the other two issues mentioned here are out of scope, we should update this github.

**Comment by irina060981** [comment]
Finally, it was decided to implement only one feature:
- all edit icons are ON by default 

It was done

**Comment by monzug** [comment]
done.
