### ISSUE TITLE
Add an option - Show/hide Alpheios Reading Tools

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#645]
From on-line meeting with @abrasax 

Would do using css styles

**Comment by irina060981** [comment]
Done

![image](https://user-images.githubusercontent.com/12377640/152929368-0caaad52-4d98-495a-b1eb-bf167c5d6ebe.png)

Pay attention - that Alpheios Reading Tools tollbar is rendered only after all application was attached. And we still attach Reading Tools only after texts were tokenized. 
So this option starts to work and could make any changes to visibility only after it was attached and rendered - after texts were tokenized.

**Comment by monzug** [comment]
it works as described. I have a question on the default status of this Option which is turned off. When I click on Set all to advanced button, this option is still turned off. is this by design? if this is the case, we might consider grouping this option with the indexedDB and tokenizer (and possibly metadata when we will support the ability to choose from Dublin Core metadata and Alpheios standard definitions)

![Screen Shot 2022-02-08 at 8 01 56 AM](https://user-images.githubusercontent.com/41396793/152994927-82e292bd-9c98-42bc-a53b-9b7fcb501ddd.png)

**Comment by irina060981** [comment]
>I have a question on the default status of this Option which is turned off. When I click on Set all to advanced button, this option is still turned off. is this by design? if this is the case, we might consider grouping this option with the indexedDB and tokenizer (and possibly metadata when we will support the ability to choose from Dublin Core metadata and Alpheios standard definitions)

Yes, it is by design
From the last requirements from @abrasax 

>
[reset all to standard options]

              [?] is link to specific help- otherwise brackets are buttons
                                         
ANNOTATING [?]      OFF   [on]   (XXX radio buttons)  (clicking ON opens the choices below)
                 (When off no toggle switch appears on alignment page) XXX
                 maximum number of characters: 500, _____    XXX (user can modify)
                 available categories: ______   XXX (user can modify- add as well as delete)
                 enable shortcuts as well as current switch  XXX  ??? TO DISCUSS

EDITING  [?]        OFF   [on]   (XXX radio buttons?) (When off EDIT does not appear in menus)
                 [enable all icons]  XXX
                 [enable only] _add newline, delete newline
                               _add tokens, delete tokens
                               _change text within token
                               _merge tokens, split tokens - probably move these options to EDIT SCREEN OPTIONS)


READING-TOOLS [?]   OFF   [on]    (XXX radio buttons)  or make option on ALIGNMENT page ?? 
                                  (Perhaps we can do it now. see note from Bridget)

[DESCRIPTION] [?]    (opens choices)                                                       
                     ___ Dublin Core metadata
                      x  Alpheios standard definitions   XXX
                     ____user choice of short name
                     ____user choices  XXX

**Comment by monzug** [comment]
I am lost with all the changes happening in Options. Hopefully this will be taken care somehow in sync with tokenizer, indexedDb (and metadata?).

**Comment by abrasax** [comment]
Yes, I do think we found a plausible integration of them all today, but it
makes me wonder whether we should consider an alternative to simplifying
the user experience at the expense of complicating the code-- I am getting
worried that all the cute devices we are developing to keep all the user's
options open with a minimally distracting interface are increasing its
fragility and at the least the time required to check everything.
I am beginning to wonder whether it might be safer to leave the current app
pretty much as it is as the Academic option and offer a Plain Text Only
option that evades all the various points of failure that our more
ambitious comprehensive solution suffers from.  Whether it could be easily
implemented at this point of time would depend on architectural details
that I do not know. I will copy you on a note I am about to send to Irina
with just that question. It could also be a post beta release project. I
think I will copy her on this note too.

**Comment by monzug** [comment]
Note that the first time I enable the toolbar in Options, the toolbar is shown in the align text. any subsequent turn on/off takes effect immediately, including in enter text screen. see screenshots below

enter screen with enable toolbar off and text still not tokenized
![Screen Shot 2022-02-10 at 2 51 19 PM](https://user-images.githubusercontent.com/41396793/153421521-964c33ef-3b29-42b2-bf30-6362f753b442.png)

enter screen with enable toolbar turned on and text still not tokenized
![Screen Shot 2022-02-10 at 2 51 27 PM](https://user-images.githubusercontent.com/41396793/153421623-bc0bc4d1-e970-40a5-8dce-80035d90a9d0.png)

**Comment by irina060981** [comment]
@monzug , Alpheios Reading Tools are rendered only once - after the first tokenization happened.
After you start over - it is not deleted. 

This option as I described before doesn't influence on rendering (creating) a toolbar - it is done as described https://github.com/alpheios-project/alignment-editor-new/issues/68

This option only hides and shows it, makes it visible/unvisible.

**Comment by monzug** [comment]
yes. as said my comment was meant to clarify your explanation.
