### ISSUE TITLE
A bug with tokenization options when upload from XML file

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#650]
from issue https://github.com/alpheios-project/tokenizer/issues/46

noticed that the in TEI options the Supply a comma-separated list of TEI elements in the text which group segments of tokens has onesegment and not body. I believe this has changed due to the last tokenizer update. there was a similar bug entered last Oct.  -  see  https://github.com/alpheios-project/alignment-editor-new/issues/570

![Screen Shot 2022-02-07 at 2 31 36 PM](https://user-images.githubusercontent.com/41396793/152798887-a0699cbd-3c08-4ad3-af92-ad3f0ec6ea33.png)

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
verified

![Screen Shot 2022-02-10 at 2 41 47 PM](https://user-images.githubusercontent.com/41396793/153420300-073884aa-54c6-401b-b2d2-a13eb2e04779.png)
