### ISSUE TITLE
Options update

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#652]
Final requirements for Options from email with @abrasax 

OPTIONS for ENTER TEXT screen
____________________________

[reset all to standard options]

              [?] is link to specific help- otherwise brackets are buttons
                                         
ANNOTATING [?]      OFF   [on] 

EDITING  [?]        OFF   [on]  

READING-TOOLS [?]   OFF   [on]   MOVE TO ALIGNMENT OPTIONS PAGE 

[ACADEMIC OPTIONS] [?]*   --------------------------------------- ----------------                                                                                      |
          DTS API       OFF, [on]       (displays DTS icon)                       |

          XML modification      OFF [on]        (Required to adjust markup elements)      | 
                                  (hides the TEI elements when off; shows them when on)
          TEXT modification     OFF [on]        (Required to define segmentation)
                                  (hides the Segmentation options when off; shows them when on)

    ------------------------------------------------------------------------

[ADVANCED OPTIONS:] [?] 

   LANGUAGE icon   ON, [off]  

   FINAL check     ON, [off]   (for both language and xml together or separately?)                        

   [TOKENIZER SERVICE] [?]
                  x remote
                    local
                    english only [?]

   INDEXED DB [?]  ON  [off]  (radio buttons)
          (When ON, shows)  maximum alignment window size _________   (user adjustable)
          (When OFF, shows) maximum total text size __________   (user adjustable)

**Comment by irina060981** [comment]
@monzug @abrasax 

Update is uploaded

![image](https://user-images.githubusercontent.com/12377640/153557077-a9964b25-57a3-4f50-abbf-8bec06795799.png)

![image](https://user-images.githubusercontent.com/12377640/153557153-5755840b-935d-4e62-b427-66bb6be2ab39.png)

![image](https://user-images.githubusercontent.com/12377640/153557200-866b098e-1533-4617-b0ee-38074de2f4a7.png)

![image](https://user-images.githubusercontent.com/12377640/153557238-9b62ebfe-78af-4531-9750-be56319ae149.png)

New options:

- Language icon
- XML modification
- TEXT modification

Some options was renamed according to description (may be it is worth to recheck labels)

**Comment by monzug** [comment]
Few comments:
1) advanced options button in Option for Enter text - what is it supposed to do?
2) if I have xml options checked and academic off, xml is sticky so it's still available in the TEI pop-up. to me, if the academic is off, all the other nested under should be off
3) options vs mode: we say academic options in the checkbox and the tooltip says enable academic mode - we say advanced options in the button and the related tooltip says enable advanced options. I would suggest to use mode also for the latest or change mode to options in academic too.

**Comment by irina060981** [comment]
>advanced options button in Options for Enter text - what is it supposed to do when I have already opened the advanced options? see below

According to the reqirements - advanced options button does the only thing - shows additional options. This button does not do any changes to options values.

**Comment by irina060981** [comment]
>if I have xml options checked and academic off, xml is sticky so it's still available in the TEI pop-up. to me, if the academic is off, all the other nested under should be off

According to the reqirements - it is the same as advanced - academic option  changes only visibility of several options, but does not change there values

**Comment by irina060981** [comment]
>options vs mode: we say academic options in the checkbox and the tooltip says enable academic mode - we say advanced options in the button and the related tooltip says enable advanced options. I would suggest to change mode to options in academic too.

Oh, thank you for the catch - completely agree

**Comment by irina060981** [comment]
> as you can see from the above attachment, the ? is not rendered properly in FF/Mac

I checked on my FF/Mac - it's ok
<img width="1157" alt="Screenshot 2022-02-14 at 10 35 54" src="https://user-images.githubusercontent.com/12377640/153782815-8e2c7a54-ddcf-4874-872b-f6f82c7f4858.png">

May be it is a specific issue for some FF versions? My is - 94.0.2 (64-bit)

**Comment by monzug** [comment]
will try in all browser PC and MAC

![Screen Shot 2022-02-14 at 9 47 01 AM](https://user-images.githubusercontent.com/41396793/153830189-12622996-9b7f-4b8e-a0a8-50bf7a63e60c.png)

**Comment by monzug** [comment]
> > if I have xml options checked and academic off, xml is sticky so it's still available in the TEI pop-up. to me, if the academic is off, all the other nested under should be off
> 
> According to the reqirements - it is the same as advanced - academic option changes only visibility of several options, but does not change there values

I see what you mean. academic is only expanding so we should use an expander rather than a checkbox because when I check the box it does only show the XML, Text and DTSAPI options, it does not do any action like annotating or editing that turn on annotation or edit.

**Comment by monzug** [comment]
> > advanced options button in Options for Enter text - what is it supposed to do when I have already opened the advanced options? see below
> 
> According to the reqirements - advanced options button does the only thing - shows additional options. This button does not do any changes to options values.

We can improve the look of these two buttons  ("set to default options" and "advanced options"). when not in use, both buttons should be greyed out (not selectable)

**Comment by irina060981** [comment]
>I see what you mean. academic is only expanding so we should use an expander rather than a checkbox because when I check the box it does only show the XML, Text and DTSAPI options, it does not do any action like annotating or editing that turn on annotation or edit.

what do you mean saying expander? It is an option, and it is saved - if you click and make these options visible, next time you open - they still would be visible

**Comment by irina060981** [comment]
>We can improve the look of these two buttons ("set to default options" and "advanced options"). when not in use, both buttons should be greyed out (not selectable)

Set to default is always available - what exact situation could happen when it is disabled? It works similiar to Reset all in Alpheios Readng Tools.

About advanced - do you mean that it should become unavailable in some cases? It is always available for now

It seems to me that we are discussing not my implementation - but the workflow that was required by @abrasax .
If you suggest to do new cnahges to it (new version again :) ), may be it is better to discuss with him?
I do not have pereferances here except situations when someone wants to do too big changes :)

**Comment by monzug** [comment]
> > I see what you mean. academic is only expanding so we should use an expander rather than a checkbox because when I check the box it does only show the XML, Text and DTSAPI options, it does not do any action like annotating or editing that turn on annotation or edit.
> 
> what do you mean saying expander? It is an option, and it is saved - if you click and make these options visible, next time you open - they still would be visible

using expand/collapse arrows

**Comment by monzug** [comment]
@abrasax you should take a look at my comments and then if you want we can have a call.

**Comment by irina060981** [comment]
>Could you pls fix the tooltip truncated in align text options? reproducible in Chrome and FF/PC, Safari and FF/Mac

ok, thank you for the catch

**Comment by irina060981** [comment]
>I see what you mean. academic is only expanding so we should use an expander rather than a checkbox because when I check the box it does only show the XML, Text and DTSAPI options, it does not do any action like annotating or editing that turn on annotation or edit.

Decided that we should save Academic options as a checkbox, because we want to save the state - is it visible or not. So if a user checks it - inner options are visible. On the next open we want to see it the same way - opened. That's why checkbox.As for advanced Harry does not want to save it opened if it was opened before, but wants to give an user an ability to close/open it. So here I would convert to expander as you suggested (without saving previous state of visibility)

**Comment by irina060981** [comment]
- converted Advanced to expander
![image](https://user-images.githubusercontent.com/12377640/154057983-caff0c52-91a1-475e-93ae-39b479594ea3.png)

![image](https://user-images.githubusercontent.com/12377640/154057963-070e4777-5786-445f-8fbf-546101f198b5.png)

**Comment by irina060981** [comment]
- fixed tooltip rendering on Align Text Screen

**Comment by monzug** [comment]
big step ahead! Thanks Irina.
here are few points that I discussed with Harry
1) please change tooltips to use the same verbal form. right now we have show, apply but also allows, adds, etc. We should use allow and add instead of the 3rd person. Also, Harry needs to review the language specific tokenizer tooltip.
2) Harry agreed that both the Academic mode and Advanced mode should be expanders, so pls remove the checkbox from Academic. it should look like Advanced mode.
3) Is it possible to move the focus to the expanded area when I click on the expander arrow? right now when I expand the advanced options, the focus stays on the top of the pop-up and I need to scroll down to see the expanded area. would it be possible to move the focus to the expanded area?
4) Harry will be thinking on the Reset all to standard options button.

**Comment by irina060981** [comment]
>please change tooltips to use the same verbal form. right now we have show, apply but also allows, adds, etc. We should use allow and add instead of the 3rd person.

Thank you for the pointing to it - fixed

**Comment by irina060981** [comment]
>2. Harry agreed that both the Academic mode and Advanced mode should be expanders, so pls remove the checkbox from Academic. it should look like Advanced mode.

Done

**Comment by monzug** [comment]
@irina060981  Looks really good. I like the use of the expanders, very clean look.

**Comment by irina060981** [comment]
>@irina060981 Looks really good. I like the use of the expanders, very clean look.

I am very pleased to get such a feedback - thank you :)

**Comment by irina060981** [comment]
>4. in align and edit screen options, we should add something about the enabling/disabling icons that are duplicated. "For convenience, you can enable/disable the same icons in Edit Text Options" in Align Text and "For convenience, you can enable/disable the same icons in Align Text Options" in Edit Text.

Done

**Comment by irina060981** [comment]
@monzug, I suggest to verify updates in this issue and create new issues for new updates 
(it is easier to navigate through issues this way)

**Comment by monzug** [comment]
> > 3. Is it possible to move the focus to the expanded area when I click on the expander arrow? right now when I expand the advanced options, the focus stays on the top of the pop-up and I need to scroll down to see the expanded area. would it be possible to move the focus to the expanded area?
> 
> There is no any easy way to do focusing on div, so I did with a small workaround. That's why it is not very smooth. But it is working - if you don't like, I would need more time for developing animation here. I did it the most easiest way - and it is no

I am happy with it. it's a little funky but it does do the job. @abrasax ?

**Comment by monzug** [comment]
> > 4. in align and edit screen options, we should add something about the enabling/disabling icons that are duplicated. "For convenience, you can enable/disable the same icons in Edit Text Options" in Align Text and "For convenience, you can enable/disable the same icons in Align Text Options" in Edit Text.
> 
> Done

Would it be possible to use smaller font to fit in one line?

![Screen Shot 2022-02-18 at 2 22 38 PM](https://user-images.githubusercontent.com/41396793/154691144-f2e0a75d-9a85-407d-a1ce-30442a3db322.png)

**Comment by monzug** [comment]
> @monzug, I suggest to verify updates in this issue and create new issues for new updates (it is easier to navigate through issues this way)

verified. feel free to enter a new github for the font size if necessary.

**Comment by irina060981** [comment]
>@irina060981 Would it be possible to use smaller font to fit in one line?

There is no need to change font size - I made that it was in two lines. I removed this division:

![image](https://user-images.githubusercontent.com/12377640/154692258-5c6cfe28-2a43-422e-9b57-405c641dff2b.png)

> verified. feel free to enter a new github for the font size if necessary.

As I fix it right away - there is no need in a new issue in this case :)

**Comment by monzug** [comment]
> > @irina060981 Would it be possible to use smaller font to fit in one line?
> 
> There is no need to change font size - I made that it was in two lines. I removed this division:
> 
> ![image](https://user-images.githubusercontent.com/12377640/154692258-5c6cfe28-2a43-422e-9b57-405c641dff2b.png)
> 
> > verified. feel free to enter a new github for the font size if necessary.
> 
> As I fix it right away - there is no need in a new issue in this case :)

Brilliant! Super fast Irina!!!!! Thanks
