### ISSUE TITLE
Reset all to standard options in Align text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#654]
related to #652
Enable toolbar has been moved to Options in Align text. The popup with the checkbox to enable the toolbar has also the Reset all to standard options button. When I click on it, it does reset to standard ALL options as said. Two issues here:
1) What is the reason for this button to be in align text? logically it should only uncheck the available option in the pop-up (that is enable the toolbar)
2)  the Reset all to standard options takes effect primarily in the enter text Options screen which is in Enter screen and we are currently in Align screen. this is confusing. a workaround to this design would be two buttons: reset and reset all to standard options, still not pretty.

I understand that the button is doing what's supposed to do but it does not make much sense to me.
see below:

let's say that I want to reset only the enable toolbar, so I click on reset all to standard options
![Screen Shot 2022-02-14 at 1 48 36 PM](https://user-images.githubusercontent.com/41396793/153867198-e844bf0e-1624-49a9-a1b8-3c37b47144c7.png)

edit screen is gone after clicking on Reset all to standard options
![Screen Shot 2022-02-14 at 1 48 50 PM](https://user-images.githubusercontent.com/41396793/153867255-f03cc698-74ed-463f-8fca-84c4eef30207.png)

**Comment by irina060981** [comment]
>What is the reason for this button to be in align text? logically it should only uncheck the available option in the pop-up (that is enable the toolbar)

It was here previously when we had some options in this popup.

Was decided to have only one reset all options button - on the Text Enter screen

**Comment by irina060981** [comment]
>It was here previously when we had some options in this popup.
Was decided to have only one reset all options button - on the Text Enter screen

Done

**Comment by monzug** [comment]
see https://github.com/alpheios-project/alignment-editor-new/issues/652 for comments. will close this on as reset button has been removed from Align text
