### ISSUE TITLE
Add help button to HTML page (output)

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#659]
From @abrasax email

Add a little help box to it- saying something minimal like

Mouse over words in the orignal to see what words in the translation have been aligned with them. You have several display options: two column, three column, interlinear, just the aligned words, all the different words in a single translation that the translator used as equivalent to the same ones in the original, and the sentences in which alignments occurred. You cannot edit this document. Make changes in the json version.

**Comment by irina060981** [comment]
- added help button
![image](https://user-images.githubusercontent.com/12377640/154915122-6cb6af71-13fa-442b-8d8a-a75b42173b7d.png)

![image](https://user-images.githubusercontent.com/12377640/154915163-e6cc45b6-3d9b-4e70-8e9e-20218ee4332e.png)

**Comment by abrasax** [comment]
splendid Irina. I think we will go with this implementation. We only have
to correct my misspelling of original, which Monica pointed out.  should be
"original".

**Comment by irina060981** [comment]
Fixed

Pay attention, that you don't need to download HTML again - it is updated automatically in all HTML outputs.

**Comment by monzug** [comment]
tested in all browsers in Mac and PC. looks good. I would prefer a smaller Help button... this one looks gigantic to me.

**Comment by abrasax** [comment]
I agree that it would be nice to make the help button a bit smaller if
possible.

**Comment by irina060981** [comment]
I made the help button smaller

![image](https://user-images.githubusercontent.com/12377640/155518988-1cd5be05-f3bc-4e5c-a45b-4e685aad7501.png)
