### ISSUE TITLE
Add left side menu to HTML Output

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#666]
from on-line meeting with @abrasax 

Add left slide menu and place there filter bar with languages/identification

![image](https://user-images.githubusercontent.com/12377640/155450136-1898a4f6-11b8-49fe-986b-d4af581a70a5.png)

**Comment by irina060981** [comment]
Done

![image](https://user-images.githubusercontent.com/12377640/155517534-8572d877-9892-4488-97ff-c7fe3256207b.png)

**Comment by monzug** [comment]
for the design, I leave the final approval to @abrasax 

as per the functionality, I did not like the following:
have 3 languages in the HTML output, see screenshot below
![parte1](https://user-images.githubusercontent.com/41396793/155540706-b8164375-93a4-4b4c-9fc3-d43ea3bc5df2.JPG)

deselect one language from the side menu. I was expecting to have still 2 language icons in full view, instead I have only one and the other greyed out. why?
see below
![parte2](https://user-images.githubusercontent.com/41396793/155541034-d7e0f2fc-454a-4ac6-b249-43a41d2073b4.JPG)

**Comment by monzug** [comment]
an other scenario that confuses me:

![Screen Shot 2022-02-24 at 2 19 48 PM](https://user-images.githubusercontent.com/41396793/155560291-8e0d5c4d-349a-465a-a637-aa35f0851439.png)

![Screen Shot 2022-02-24 at 2 20 03 PM](https://user-images.githubusercontent.com/41396793/155560300-0cec66e5-91ab-437d-b959-5043d539a184.png)

**Comment by irina060981** [comment]
>in both cases, we have the same html output in full view limited to two languages but we get there in different ways. I believe that in the previous version if we deselect one language from full view by clicking on the icon, also the correspondent large language button would be turned off, correct? I believe that previously the icons and large buttons were in sync. am I right?
would it be possible to compare with previous version?

No it is not correct - this behaviour was the same - I did only UI changes

**Comment by irina060981** [comment]
Some explanations:

Filtering bar (that is now in left menu) has a feature:
 - it filters, changes order in the whole output - in all views
 
 Numbers in circles feature:
 - it operates visibility only in a full view and does not do any changes in others views
 - it is used only to define what texts are visible at once in a full view (similiar to alignment editor application)

We discussed your concerns with @abrasax and that it makes things confusing to have them both.
Harry noticed it before.

I could remind that first we have full view with numbers and short view without numbers;
then it was decided to add filters and new views;
but we don't even discuss that numbers have similiar features in a full view

As a result we have both - and it confuses.

Finally Harry suggested to remove numbers and see would it be more useful

**Comment by abrasax** [comment]
but in interlinear view the numbered icons do add and subtract translations

**Comment by irina060981** [comment]
>but in interlinear view the numbered icons do add and subtract translations

I checked they working incorrect 

These numbers are diffrent - full view has its own, interlinear has its own
They should work the same way as in full view:
 - if number is colored - then this text (translation from the this text) is visible
 - if number is greyed - then this text (translation from the this text) is invisible
 
 But there are some problems with them -

**Comment by irina060981** [comment]
Number tabs are hidden from a full view

**Comment by abrasax** [comment]
At the moment they seem to provide a more convenient way to choose which
translations to show in the interlinear display than I can manage to do
from the menu. I should of course prefer to be able to use the menu alone.

**Comment by abrasax** [comment]
You mean we might leave them on just for the interlinear display ?

**Comment by irina060981** [comment]
>You mean we might leave them on just for the interlinear display ?

No, we don't need

I need to fix the bug that prevent from using filters correctly, and I will remove numbers from the interlinear
I am working on it

**Comment by abrasax** [comment]
oh ok. I misunderstood. Don't stay up over this.

**Comment by irina060981** [comment]
It was suggested by @abrasax to move select view panel to the left side panel too

Done
![image](https://user-images.githubusercontent.com/12377640/155708018-120e911f-61d7-4bf4-9aa4-3e81d80e71bd.png)

**Comment by irina060981** [comment]
- number tabs was removed from interlinear view, now it is filtered only by buttons from the left slide menu

**Comment by irina060981** [comment]
- left menu became partly transparent

![image](https://user-images.githubusercontent.com/12377640/155715739-e43e4b25-14ee-43c5-a793-e7a9c4627248.png)

**Comment by irina060981** [comment]
@monzug and @abrasax ,

Done changes shortly:

- Number tabs are hidden from a full view and interlinear view; now ordering and filtering are done only using buttons in the left side menu

-  Select view radio buttons are moved to left side menu

-  Left side menu was made partly transparent

**Comment by abrasax** [comment]
Well, I'm not sure that packing everything into the left column is
optimal...

**Comment by abrasax** [comment]
Depending on how many languages you have you might have to scroll down more
often

**Comment by abrasax** [comment]
but the functionality does now appear to be correct.  (have to spend a bit
more time verifying)

**Comment by monzug** [comment]
issue 1) - with two translations (1 original and 1 translation), I do not have the side menu so I can only see the full view.
see below
![Screen Shot 2022-02-25 at 2 10 54 PM](https://user-images.githubusercontent.com/41396793/155722192-c88aca2e-a973-4054-8636-26e30c6e0a65.png)

question 1 ) - why when only English is selected  as the only translated language in full view, the side menu removed the eye on the side? see below
menu with English and the eye
![Screen Shot 2022-02-25 at 2 09 19 PM](https://user-images.githubusercontent.com/41396793/155722495-81021e22-49b0-4566-a7df-60167d6fb44a.png)
menu with only English language available and no eye
![Screen Shot 2022-02-25 at 2 10 54 PM](https://user-images.githubusercontent.com/41396793/155722519-1940cea7-d1fa-4478-806e-5cb9fcd28736.png)

**Comment by monzug** [comment]
> for the design, I leave the final approval to @abrasax
> 
> as per the functionality, I did not like the following: have 3 languages in the HTML output, see screenshot below ![parte1](https://user-images.githubusercontent.com/41396793/155540706-b8164375-93a4-4b4c-9fc3-d43ea3bc5df2.JPG)
> 
> deselect one language from the side menu. I was expecting to have still 2 language icons in full view, instead I have only one and the other greyed out. why? see below ![parte2](https://user-images.githubusercontent.com/41396793/155541034-d7e0f2fc-454a-4ac6-b249-43a41d2073b4.JPG)

this one is fixed in latest version with side menu and no icons. Thanks

**Comment by irina060981** [comment]
>issue 1) - with two translations (1 original and 1 translation), I do not have the side menu so I can only see the full view.
see below

I missed it - will fix

**Comment by irina060981** [comment]
>question 1 ) - why when only English is selected as the only translated language in full view, the side menu removed the eye on the side? see below
menu with English and the eye

Because we could not hide all translations
We should have one at least

**Comment by irina060981** [comment]
> > issue 1) - with two translations (1 original and 1 translation), I do not have the side menu so I can only see the full view.
see below

> I missed it - will fix

Decided on on-line meeting with @abrasax to do the following:

the first step: move the select view bar to the page header

![image](https://user-images.githubusercontent.com/12377640/155922719-a2374ea2-3d8f-4299-975f-b234c81d4d54.png)

this step is done

**Comment by irina060981** [comment]
The second step:
- would create a responsive behaviour: 
   - on wide screen - select views bar in the page top, 
   - when there is not enough space to place it in one line - move select views bar to left side menu
   
  Would do later - registered in a separate issue -

**Comment by irina060981** [comment]
>the first step: move the select view bar to the page header

now view selection is available for one translation

I suggest to close this issue and track changes in new ones - to have more clear history
