### ISSUE TITLE
(AIR 8) Must support scrolling of source text and translation text separately

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#67]
From https://github.com/alpheios-project/documentation/blob/master/development/alignment-editor.md

**Comment by irina060981** [comment]
From the email

We have a requirement for the output self-contained HTML - to have independent scroll for each text part
    For now I realized it through setting the max-height of each text segment (otherwise we won't have an independent scroll)
    The rule is the following
     - if we have one segment - max-height -  would get all available height of the page
     - if we have more segments - max-height would be set as all available height / amount of segments but not less than 400px

     Does this rule is good for the expected UI?

**Comment by irina060981** [comment]
from @balmas 
> That seems like a reasonable default. Is there a way to allow the user to increase or shrink the segment size?

**Comment by irina060981** [comment]
After on-line meeting:

it would be good to add buttons (up/down) to adapt height of the segment.

**Comment by irina060981** [comment]
Added max-height, independent scroll and autoscroll for alignment groups editor.

**Comment by irina060981** [comment]
- added buttons for reduce/increase height of a segment block
- buttons are invisible if scroll is not needed
- height is adapted cross segments origin and target

![image](https://user-images.githubusercontent.com/12377640/108458104-a8b9c900-72bf-11eb-8fb9-e1bfbf890078.png)

![image](https://user-images.githubusercontent.com/12377640/108458007-6f815900-72bf-11eb-9161-64b7cd54ec09.png)

![image](https://user-images.githubusercontent.com/12377640/108458154-c5560100-72bf-11eb-88db-4a20b201fa91.png)

There are some small problems with the solution:
- buttons appears after browser would calculate scrollHeight (for big texts it could give some delays)
- as we need to align origin and target segments there could be some non-recalculating

**Comment by irina060981** [comment]
There are a lot of moments that can be improved in this solution, but I decided to have a balance between comfortable usability and time needed for development, because such UI adapting tasks could get much time for minor improvements.

@monzug , @balmas , @abrasax - if you would like this solution - I could add the same to the HTML output.
I suggest you to try it first here and decide.

**Comment by monzug** [comment]
Scrolling can be difficult in short sentences. also, when I use the up arrow, it goes up line by line.

see attachment

![Screen Shot 2021-02-22 at 1 57 05 PM](https://user-images.githubusercontent.com/41396793/108761020-a9b45a00-754e-11eb-8e89-cf20e780ecff.png)

**Comment by monzug** [comment]
Navigating up and down, arrows can disappear
![Screen Shot 2021-02-22 at 9 55 49 PM](https://user-images.githubusercontent.com/41396793/108769062-c6ee2600-7558-11eb-886f-18668024e2b0.png)

**Comment by irina060981** [comment]
>Navigating up and down, arrows can disappear
They are disappeared - when the text has the height that fits its 100% height.
I believe that I could add disappearaing of only one button for - max height and for min height.

**Comment by irina060981** [comment]
>Scrolling can be difficult in short sentences. also, when I use the up arrow, it goes up line by line.

Yes, it is not perfect
I am not sure how I could improve this better

**Comment by monzug** [comment]
Let me test more extensively and will get back to you.

**Comment by monzug** [comment]
basically, these are screenshots of the icons that got my attention

1) I can shrink the second translated text and only parts of the icons are visible

![Screen Shot 2021-02-23 at 6 15 11 PM](https://user-images.githubusercontent.com/41396793/108881583-be9ef500-7603-11eb-80a8-1fda87d1e3f3.png)

2) first alignment group view

![Screen Shot 2021-02-23 at 6 16 22 PM](https://user-images.githubusercontent.com/41396793/108881865-1178ac80-7604-11eb-867e-563b5db97288.png)

3) alignment group view with both translated texts

![Screen Shot 2021-02-23 at 6 23 50 PM](https://user-images.githubusercontent.com/41396793/108882154-5ef51980-7604-11eb-9b06-9735a1a040cf.png)

**Comment by monzug** [comment]
tested also with 4 languages and it's similar to 3 languages scenario. see attachment

![Screen Shot 2021-02-24 at 3 52 08 PM](https://user-images.githubusercontent.com/41396793/109018403-6118b000-76b8-11eb-8754-eab67bc675b3.png)

**Comment by monzug** [comment]
tested with long text, short sentences (poetry style), medium size sentences, long sentences, with 2 and 3 translated languages, xml short and xml long text.

**Comment by irina060981** [comment]
On the online-meeting decided to turn off the feature with buttons for adapting height.
The feature is disabled.

**Comment by irina060981** [comment]
@monzug , I think we could close this issue and I will create a separate issue for arrows for future development

**Comment by monzug** [comment]
yes. there is still something quite not right , see #234
