### ISSUE TITLE
(AIR 9) Must support option to enable the Alpheios Reading Tools on the source and translation text

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#68]
From https://github.com/alpheios-project/documentation/blob/master/development/alignment-editor.md

**Comment by irina060981** [comment]
Added Alpheios Reading tools to the Alignment Editor

Reading tools are enabled inside alignment groups editor
![image](https://user-images.githubusercontent.com/12377640/107902672-d8e92b00-6f92-11eb-84b3-cc3f742ebaa8.png)

Auth0 support is turned off (login/logout)

Trigger event - `Ctrl + Click`

**Comment by monzug** [comment]
Auth0 support is turned off (login/logout) is greyed out but if I click on it, it will take to an empty page, see attachment

![Screen Shot 2021-02-15 at 2 14 06 PM](https://user-images.githubusercontent.com/41396793/107951230-4e0b2f00-6f98-11eb-8d0e-fca47acbf1d2.png)


also, is there anything that can be done to improve the style of the tooltips in Safari?
see attachment
![Screen Shot 2021-02-15 at 2 03 23 PM](https://user-images.githubusercontent.com/41396793/107951354-801c9100-6f98-11eb-8b51-40cd91e5d8fa.png)

**Comment by monzug** [comment]
questions: 
1) How do I lookup for a word? I tried ctrl and click on PC but not much luck. does lookup work for origin and target text as well as for alignment groups?
2) Can you confirm that login/logout should turn off?

**Comment by irina060981** [comment]
>How do I lookup for a word? I tried ctrl and click on PC but not much luck. does lookup work for origin and target text as well as for alignment groups?

Alpheios Reading tools are activated only for the editor part where we create alignment groups - both for origin and target texts.
Press Ctrl (stay pressed) and click a token - lookup would start. It works both for grouped tokens and not grouped tokens.

![image](https://user-images.githubusercontent.com/12377640/108002759-5157f680-703c-11eb-8f33-a7b8cebc5a3b.png)

![image](https://user-images.githubusercontent.com/12377640/108002792-6af93e00-703c-11eb-8659-f7e0c6d067b2.png)


Lookup does not work for textareas (part where a user edits source texts) and does not work for inputs (the part where we edit tokens). For now it is not available for such type of visible data (it is limits from allpheios tools).

Reading Tools are not available for HTML Output (because of limits inside alpheios tools)

Lookup is working for me with these limits well.
@monzug, do you use **press Ctrl + click** inside the middle editor and it doesn't work?

**Comment by irina060981** [comment]
>Can you confirm that login/logout should turn off?

Authentication is turned off. To be turned on - it needs additional registration and settings from AUTH0 server.
I don't have an access to it. Would ask Bridgit on the meeting.

**Comment by irina060981** [comment]
>Auth0 support is turned off (login/logout) is greyed out but if I click on it, it will take to an empty page

I would check it in Alpheios Reading tools, why it is shown, it shouldn't

**Comment by irina060981** [comment]
>also, is there anything that can be done to improve the style of the tooltips in Safari?
see attachment

I don't have this bug in Chrome with the same theme

![image](https://user-images.githubusercontent.com/12377640/108003272-fa532100-703d-11eb-9ae3-d315283e9e46.png)

@monzug, In what browser do you have this bug?

**Comment by monzug** [comment]
Safari/BigSur. I tested in Chrome and FF in bigsur and it was fine.

**Comment by monzug** [comment]
in the html output, if I activate Alpheios installed previously, lookup works well. see attachment
![Screen Shot 2021-02-16 at 9 07 04 AM](https://user-images.githubusercontent.com/41396793/108034974-9711c080-7036-11eb-8d9a-2b96fa272698.png)

**Comment by monzug** [comment]
as per activating the tools, see Safari/Mac

![Screen Shot 2021-02-16 at 9 07 04 AM](https://user-images.githubusercontent.com/41396793/108035379-2919c900-7037-11eb-8b0c-651f7eb1a8e0.png)

and FF/Mac

![Screen Shot 2021-02-16 at 9 12 19 AM](https://user-images.githubusercontent.com/41396793/108035418-33d45e00-7037-11eb-9020-7ff2433efd49.png)

**Comment by irina060981** [comment]
You should not activate it inside Alignment Editor - it is activated inside Alignment Editor itself (not HTML output).

We could not use previously installed Alignment editor  - because we create alignment groups on click.
That's why it is integrated with another event - ctrl + click.

**Comment by irina060981** [comment]
It works for me in Chrome/Windows and Firefox/Windows.
Don't activate anything - simply use Ctrl+Click instead of double click in Windows.

Will check on mac

**Comment by irina060981** [comment]
Ok - I found the problem on Mac and fixed - Ctrl was not detected there properly.
Finally - you should use **Command + Click** on MAC and **Ctrl + Click** on Windows - for lookup

**Comment by irina060981** [comment]
@monzug , finally I found  that with my last optimization we could use doubleClick for Alpheios Reading tools for lookup as usual.
So I set doubleClick as a trigger event.
Tested in Chrome/Windows, Firfox/Windows, Safari/Mac - it works

**Comment by monzug** [comment]
Great!!!! Thanks

**Comment by monzug** [comment]
double click works in safari/mac !!! still have to figure out in FF...
questions:
1) I am still not able to use the tools in the Origin and Target text. double click works only in the alignment groups. on the call, Bridget said that it should work. Am I missing something?
2) when I click on the login , it does take me to an empty tab. I would suggest to fix this even if we plan to add the login feature as you never know if it's going to work!!!!!

**Comment by irina060981** [comment]
>I am still not able to use the tools in the Origin and Target text. double click works only in the alignment groups. on the call, Bridget said that it should work. Am I missing something?

Let me describe the limits with more details:

**In this part Double click doesn't work**
![image](https://user-images.githubusercontent.com/12377640/108190890-3a112a00-715e-11eb-8aaf-e334716274f8.png)

**In this part Double Click works on any token (grouped or not)**
![image](https://user-images.githubusercontent.com/12377640/108190949-48f7dc80-715e-11eb-91ed-34ec34a3a002.png)

Here it is a video how I do clicks
https://www.dropbox.com/s/11n4mes2crjafsj/Alignment%20Editor%20scroll%20-%2011.mp4?dl=0

**In this part Double click doesn't work**
![image](https://user-images.githubusercontent.com/12377640/108191109-7fcdf280-715e-11eb-8d11-a35af83ba3ea.png)

**Comment by irina060981** [comment]
>when I click on the login , it does take me to an empty tab. I would suggest to fix this even if we plan to add the login feature as you never know if it's going to work!!!!! unless you have the login ready for testing pretty soon so we don't forget about this one.

would do that - I need some time to work on it inside Alpheios Reading Tools repository

**Comment by monzug** [comment]
My understanding from the call is that tools should work also in Origin and Target texts. I saw that it was one of your questions for the meeting above:
- Should I spend time trying to activate reading tools on other parts of editor (texareas with source text and tokens editor) ?
so let's wait for feedback from @balmas and @abrasax.
if we decide to go with the current environment (tools are activated only in the alignment groups), I suggest to remove the tools till we have an alignment groups:
e.g. tools not available when editing Origin and Target texts, tools available when alignment groups are generated
e.g. tools not available on upload of tsv file, tools available when uploading a json file

**Comment by abrasax** [comment]
One of the major uses of the tools would be during alignment- to help
choose what to align.  For example, I was hoping to use them when aligning
Greek and Chinese- which ideally would mean activating them for Chinese on
one side and for Greek on the other. (Chinese alone would certainly be
helpful and there may not be that many cases where we will have
dictionaries for more than one of the languages being aligned, so the
priority of supporting different languages on opposite sides of the
alignment could be questioned, and I would want Bridget to participate in
that discussion.)

**Comment by irina060981** [comment]
Login is available inside Alpheios reading Tools

There are some problems with logout still (the page is reloaded on logout) - to fix it - it would need changes to embed-library to support proper logout.

**Comment by irina060981** [comment]
Github secrets are used for client_id - updated during build process

**Comment by irina060981** [comment]
>One of the major uses of the tools would be during alignment- to help
choose what to align.  For example, I was hoping to use them when aligning
Greek and Chinese- which ideally would mean activating them for Chinese on
one side and for Greek on the other. 

Multiple popups task needs serious update inside Alpheios Reading Tools, it is out of scope of Alignment Editor.

**Comment by irina060981** [comment]
>if we decide to go with the current environment (tools are activated only in the alignment groups), I suggest to remove the tools till we have an alignment groups:
e.g. tools not available when editing Origin and Target texts, tools available when alignment groups are generated
e.g. tools not available on upload of tsv file, tools available when uploading a json file

I could add a specific event, dispatch it when texts are tokenized and activate Alpheios Reading Tools on this event.
I tried - it works, but Alpheios Reading Tools need some time for activating - so it appears rather suddenly.

I would add this feature to get feedback from you. And we could stay with this feature - or I could remove it.

**Comment by abrasax** [comment]
It would be interesting to see it working

**Comment by irina060981** [comment]
The feature is added - Tools are activated after texts were tokenized

**Comment by abrasax** [comment]
might it be possible to retain the user's choice of languages on the
original and translation panes so that they don't have to keep changing
them when moving from one to the other?

**Comment by irina060981** [comment]
>might it be possible to retain the user's choice of languages on the
original and translation panes so that they don't have to keep changing
them when moving from one to the other?

The language is defined for each tokenized text.
For example:
![image](https://user-images.githubusercontent.com/12377640/108622635-d94b5f80-7485-11eb-9d32-2c2ed57fd80b.png)

here Greek and Latin are defined.
These languages would be used for lookup by double click whiout additional choosing of the language:
![image](https://user-images.githubusercontent.com/12377640/108622659-01d35980-7486-11eb-88aa-13f7f2865d54.png)

![image](https://user-images.githubusercontent.com/12377640/108622663-0b5cc180-7486-11eb-907b-90a9c8c12514.png)

So I believe that you request is already a realized feature.

**Comment by abrasax** [comment]
splendid. splendid. I must have failed to specify them. I'll check it today
with Greek and Chinese.

**Comment by monzug** [comment]
Confirm that double click worked for Arabic and latin, Arabic and Greek languages without the need to specify the language in lookup. Excellent. I haven't tried with Chinese, though.

**Comment by irina060981** [comment]
>If I click on Clear Text, the tools are still active. I think this is ok. Right?

Yes it is ok, because we don't have events for deactivating Alpheios Reading Tools in this case.

**Comment by monzug** [comment]
Tested with Chinese language from the following site https://ctext.org/mozi/befriending-the-learned. Double click works fine on Chinese words.

**Comment by abrasax** [comment]
I have been most interested to see that during the alignment process in
the Chrome browser Google Translate can supply definitions for all the
languages that we do not ourselves support. This is most convenient and I
hope we retain this capability in all future versions. Indeed, it might be
worth considering turning off our popup in the alignment editor when we do
not have explicit information that the language is one that we support- the
error message is distracting- and in theory we should have this information
from the user much more reliably than from any markup in the text itself.
It also reminds of the value of trying to automatically identify the
language in the tools as a whole ...

**Comment by irina060981** [comment]
>I have been most interested to see that during the alignment process in
the Chrome browser Google Translate can supply definitions for all the
languages that we do not ourselves support. This is most convenient and I
hope we retain this capability in all future versions.

>Indeed, it might be
worth considering turning off our popup in the alignment editor when we do
not have explicit information that the language is one that we support- the
error message is distracting- and in theory we should have this information
from the user much more reliably than from any markup in the text itself.

>It also reminds of the value of trying to automatically identify the
language in the tools as a whole ...

These are interesting ideas - they will need upgrade for Alpheios Reading Tools in future releases.
It is great when there are so much challenges for the application - it seems for me that there are a lot of field to grow for it :)

**Comment by monzug** [comment]
it does work also with Persian and Ge'ez.

**Comment by monzug** [comment]
tested with Syriac in Alpheios Translation Alignment editor 1.0.2 (build development.20210226340)  - tested also the download of a Syriac wordlist
