### ISSUE TITLE
Update TEI check in TEXT Enter screen

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#684]
from online meeting with @abrasax 

Change check
   - now - if a text has `< tei` , then it is tei, otherwise it is text
   - new - if a text has opening bracket at the start and closing bracket at the end

**Comment by irina060981** [comment]
Check is updated
Did the following checks

![image](https://user-images.githubusercontent.com/12377640/156352041-41e1bb23-a076-41af-9674-788f5dcb341f.png)

![image](https://user-images.githubusercontent.com/12377640/156352060-eb7e55ec-8d0c-48d5-9855-dcf1b983c857.png)

![image](https://user-images.githubusercontent.com/12377640/156352090-b1d1c1e0-dd6b-44ed-a29e-0f6a31628ce8.png)

**Comment by abrasax** [comment]
remember to change tei to xml

**Comment by irina060981** [comment]
I updated icon name

![image](https://user-images.githubusercontent.com/12377640/156358336-5ce74842-ad83-4aab-b30b-f1e436b7076f.png)

But notice that inside we still have TEI inside popup

![image](https://user-images.githubusercontent.com/12377640/156358507-ae0123b5-8e12-4312-a829-eb4115dd1c67.png)

This is taken from options and tokenizer.
If we need to change this too - I will need to update it in this sources in a separate issues.
