### ISSUE TITLE
Tokenization service error when I cut and paste then edit the origin and target text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#74]
This used to work. Now I am getting a 500 internal error, see screenshot

I cut and paste a poem from Catullus, then I have to break the line from the origin and target text. when I click on Align I get the 500 error.
the English text is in one 'segment' : 
Let's live, my Lesbia, and let's love,and value all the gossip of stricterold men at a single as1! Suns can set and rise again:for us when once our brief light sets,there is one eternal night to be slept. Give me a thousand kisses, and then a hundred,then another thousand, then a second hundred,and then yet another thousand, then a hundred. Then, when we've made many thousands,let's stir them all up so that we won't knowand neither could any malicious watcherwork out just how many kisses there are.

After inserting the line break, it looks like this:
Let's live, my Lesbia, and let's love,
and value all the gossip of stricter
old men at a single as!
Suns can set and rise again:
for us when once our brief light sets,
there is one eternal night to be slept.
Give me a thousand kisses, and then a hundred,
then another thousand, then a second hundred,
and then yet another thousand, then a hundred. 
Then, when we've made many thousands,
let's stir them all up so that we won't know
and neither could any malicious watcher
work out just how many kisses there are.

same for Italian or Latin:
Viviamo, mia Lesbia, ed amiamo,e ogni mormorio perfido dei vecchivalga per noi la più vile moneta.Il giorno può morire e poi risorgere,ma quando muore il nostro breve giorno,una notte infinita dormiremo.Tu dammi mille baci, e quindi cento,poi dammene altri mille, e quindi cento,quindi mille continui, e quindi cento.E quando poi saranno mille e mille,nasconderemo il loro vero numero,che non getti il malocchio l’invidiosoper un numero di baci così alto.

and with line breaks
Viviamo, mia Lesbia, ed amiamo,
e ogni mormorio perfido dei vecchi
valga per noi la più vile moneta.
Il giorno può morire e poi risorgere,
ma quando muore il nostro breve giorno,
una notte infinita dormiremo.
Tu dammi mille baci, e quindi cento,
poi dammene altri mille, e quindi cento,
quindi mille continui, e quindi cento.
E quando poi saranno mille e mille,
nasconderemo il loro vero numero,
che non getti il malocchio l’invidioso
per un numero di baci così alto.

![error-alignment](https://user-images.githubusercontent.com/41396793/97881648-a91e5c00-1cf0-11eb-9edc-012c4ada83cc.JPG)

This used to work. Any idea what happened?

**Comment by irina060981** [comment]
Would be fixed with the PR

**Comment by irina060981** [comment]
Merged and closed
