### ISSUE TITLE
Define keystrokes for Reading Tools Lookup and Annotations Creation

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#746]
From on-line meeting with @abrasax 

- define for lookup via Alpheios Reading Tools - Ctrl + Click

- define for annotations creation - Shift + Click

**Comment by irina060981** [comment]
Done

**Comment by abrasax** [comment]
works perfectly on Windows 10 Pro in both Chrome and Firefox
doesn't work at all on my Macs - as per attached file-

**Comment by irina060981** [comment]
I tested om my MAC 
  Annotations:
  - (Safari and Chrome) - both work - Shift + Click - opens annotation for me (don't forget to turn on Annotations mode in Options)
  @abrasax did you Annotation mode is checked?
  
  Reading Tools:
   - (Chrome) - Command + Click is working as Ctrl + Click
   - (Safari) - Command + Click and Ctrl + Click - both are not working
-

**Comment by irina060981** [comment]
I found the problem with Ctrl/Command on MAC
- Ctrl+Click - on MAc opens context menu , so it could be reserved
- Command + Click now is working on MAC, the problem was not with keyCode. While developing - I set  a rule, not to select text inside tokens (to prevent from multiple selection), and Chrome works fine with it. But on MAC Alpheios Reading tools could not get a targetWord without visible selection. I removed this prevention - now Command + Click works fine for me on MAC (Chrome + Firefox)

Shift + Click works well on both Safari and Mac - check annotation mode please

**Comment by abrasax** [comment]
Ah,  but can we not now get rid of making annotation an option?   As
keystrokes it would be safe to make it available by default

**Comment by irina060981** [comment]
Yes, I could hide it and set ON by default

**Comment by irina060981** [comment]
> Ah,  but can we not now get rid of making annotation an option?   As
> keystrokes it would be safe to make it available by default

- set enableAnnotations option to true by default 
- remove enableAnnotations option from Options

![image](https://user-images.githubusercontent.com/12377640/164235554-f3353fce-b75d-498c-8d64-b9d397540c11.png)

**Comment by irina060981** [comment]
from @abrasax  email
>Ah I see that we have options for annotations. Better leave it then.
