### ISSUE TITLE
(TIR 7) support retrieval of input text from a DTS API document endpoint URL

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alignment-editor-new#77]
7. support retrieval of input text from a DTS API document endpoint URL

**Comment by balmas** [comment]
Some links for reference:

The DTS API Specification:
https://distributed-text-services.github.io/specifications/

The Alpheios DTS Endpoint (which might be a slightly out of date version of the specification):
https://dts.alpheios.net/api/dts/collections

The Betamasaheft DTS Endpoint (Ancient Ethiopic texts:
http://betamasaheft.eu/

For the demo, the idea here would be to create add the following features to the Alignment Editor UI
1) The ability to specify the base URL of a DTS API Endpoint 
2) The ability to browse the collections served by the DTS API Collections endpoint
3) The ability to browse the passage references  available for a selected Resource from the DTS API Navigation endpoint
4) The ability to select a passage (or range of passages) from the DTS API Document endpoint

the Passage will be returned as TEI XML , and that can be then used as an Origin or Target text.

For a sample of how this was done previously , using the CTS API (which DTS evolved from) see the Perseids Translation Alignment entry form:
https://pca.perseids.org/apps/alignment?

**Comment by irina060981** [comment]
Retrieving data from DTS API is reasilized:

- added modal window for browsing DTS API links
- modal has breadcrumbs
- refs could be selected - sinlgle or several
- selected passages are uploaded to origin/target

![image](https://user-images.githubusercontent.com/12377640/109149791-c4d3d380-77b3-11eb-960b-35da967bb8b1.png)

![image](https://user-images.githubusercontent.com/12377640/109150185-3f045800-77b4-11eb-8273-4310c7a1febf.png)

![image](https://user-images.githubusercontent.com/12377640/109150200-462b6600-77b4-11eb-8a90-8c4b9e29453f.png)

![image](https://user-images.githubusercontent.com/12377640/109150221-4c214700-77b4-11eb-80d6-0b823e242cc2.png)

![image](https://user-images.githubusercontent.com/12377640/109150251-54798200-77b4-11eb-8f06-cb62923cc3fd.png)

![image](https://user-images.githubusercontent.com/12377640/109150262-5a6f6300-77b4-11eb-8ecb-242b3ff2c932.png)

![image](https://user-images.githubusercontent.com/12377640/109150284-622f0780-77b4-11eb-9ea2-e8998b30098c.png)

![image](https://user-images.githubusercontent.com/12377640/109150302-6a874280-77b4-11eb-899a-48957c72c967.png)

**Comment by monzug** [comment]
I followed the above instructions and I was able to upload Greek and latin text. Few issues/question below:

1) Why do we have french text in Alpheios DTS API e.g. Latin Classique or Arabe Classique or Grec Ancien?

2) Can we clear the checkmarks after an upload? see attachment

![Screen Shot 2021-02-25 at 2 20 56 PM](https://user-images.githubusercontent.com/41396793/109159427-e2ce1380-7774-11eb-80b0-a088b8df3ee5.png)

3) I noticed that when I select few passages from a book (e.g. Carmina, 2-92-102 or 2-3-4) only one passage out of three is uploaded. I did also upload Ovid text, passages 8 and 15, but only passage 8 was uploaded. In case of Ovid, it could be because of the size, but in Catullus, the passages are only few lines long. see attachment of the uploaded Carmina text for passage 4 (27 lines) and missing passage 2 and passage 3.

![Screen Shot 2021-02-25 at 2 44 40 PM](https://user-images.githubusercontent.com/41396793/109162397-735a2300-7778-11eb-80f5-41fc99c81f26.png)

**Comment by balmas** [comment]
I removed the French labels

**Comment by irina060981** [comment]
>I removed the French labels

Thank you, @balmas

**Comment by irina060981** [comment]
>Can we clear the checkmarks after an upload or after clicking on Cancel? see attachment
done

**Comment by irina060981** [comment]
>I noticed that when I select few passages from a book (e.g. Carmina, 2-92-102 or 2-3-4) only one passage out of three is uploaded. I did also upload Ovid text, passages 8 and 15, but only passage 8 was uploaded. In case of Ovid, it could be because of the size, but in Catullus, the passages are only few lines long. see attachment of the uploaded Carmina text for passage 4 (27 lines) and missing passage 2 and passage 3.

The big is fixed - thank you, @monzug, for your attentive check !

**Comment by monzug** [comment]
Thanks for clearing the checkmarks.

as per passages selection, it does not work as expected. Now it does select the range of passages, not the selected passages. For example,  Alpheios DTS API - Ancient Greek - Sophocles - Ajax, if I select 2, 4 and 6 passages, I am expecting 3 lines (as each line is a passage in this case), instead it does generated the range from 2 to 6, so 5 lines totally. I did also try with other authors and it does always select the range, not the single passages.

![Screen Shot 2021-02-26 at 3 42 39 PM](https://user-images.githubusercontent.com/41396793/109314221-60635380-7849-11eb-9f5a-21a537c035e8.png)

**Comment by irina060981** [comment]
>as per passages selection, it does not work as expected. Now it does select the range of passages, not the selected passages. For example, Alpheios DTS API - Ancient Greek - Sophocles - Ajax, if I select 2, 4 and 6 passages, I am expecting 3 lines (as each line is a passage in this case), instead it does generated the range from 2 to 6, so 5 lines totally. I did also try with other authors and it does always select the range, not the single passages.

It works according to the available support of DTS API.
It supports selection a single refrence - then it would be one passage.
Or it supports a range selection - start to end; if a user selects more then one passage - the application would use a range from the min passage to max range; in the described case - 2,3,4,5,6.

**Comment by monzug** [comment]
let's add a comment on top with instructions on range vs single passage. if
I select the first and the last passage (e.g. to check the beg and the end
sentences of a book) it loads the whole book which can be heavy to upload.

**Comment by irina060981** [comment]
>let's add a comment on top with instructions on range vs single passage.

Instructions are added:
![image](https://user-images.githubusercontent.com/12377640/109497329-a0daff80-7add-11eb-9f84-a616d03b85ea.png)

![image](https://user-images.githubusercontent.com/12377640/109497310-991b5b00-7add-11eb-8e95-730f2d09132e.png)

**Comment by irina060981** [comment]
>I select the first and the last passage (e.g. to check the beg and the end
sentences of a book) it loads the whole book which can be heavy to upload.

I believe that we should set some check - but an application does know nothing about size of passages.
So we could set a limit here only by amount of passages without any depending how big they are (one line or several lines).
Will add this for the discussion

**Comment by monzug** [comment]
Thanks for adding the instruction. Yes, let's talk tomorrow. also, some rework on the text is needed.

**Comment by irina060981** [comment]
>Thanks for adding the instruction. Yes, let's talk tomorrow. also, some rework on the text is needed.

I always think that some rework is needed for my texts :)

**Comment by irina060981** [comment]
on on-line meeting was decided to leave as is (not to add additional limits for selecting passages).
@monzug - I would be glad to get updated instructions for display from you :)

**Comment by monzug** [comment]
how about:
- Select one reference that you want to upload.
- Select multiple references to upload as a range from the minimum to the maximum number. For example, if you choose 2, 5 and 8, the range from 2 to 8 references will be uploaded.

**Comment by irina060981** [comment]
Instructions are fixed

**Comment by monzug** [comment]
yep. Thanks
