### ISSUE TITLE
Offline usage

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#770]
from online meeting with @abrasax 

Create ability to upload folder/files to use Alignment Editor and Html output completely offline

**Comment by irina060981** [comment]
Was done 1 step:

   - HTML output now is completely independent from internet connection (libraries, fonts, images, data)
  You could compare the same files
     - with remote links - 652 Kb
     - with embeded data - 3024 Kb
     
   Pay attention that now to update changes you always need to download HTML again

**Comment by irina060981** [comment]
Was done 2 step :

- updated SimpleLocalTokenizer
    - changed word division workflow
    - simplified punctuation extract
    - defined oneSegment property for usage in application (and divide to segment in texts)
    - checked for several languages (eng, rus, vie, kor, heb, ara)

**Comment by irina060981** [comment]
Was done 3 step :
  - check alpheios remote tokenizer availability on startup
     - if available and Simple local tokenizer is set - upgrade to remote
     - if not available and remote is set - downgrade to local

**Comment by irina060981** [comment]
Was the last 4th step:

- on development update we publish (later I will move to updates to production only) a folder with full application code, that could be used offline

- it is placed to Release tab inside github repository
https://github.com/alpheios-project/alignment-editor-new/releases

- a user could download an archive (alpheios-alignment-editor) with a folder
![image](https://user-images.githubusercontent.com/12377640/167561334-ee2e2e10-cf7b-4fdb-a99a-93f256f0159b.png)

- then extract and launch index.html

**Comment by abrasax** [comment]
Each one of the four steps is really a very significant advance in
functionality by itself. You had a busy day, not to mention the fonts.
