### ISSUE TITLE
(TIR 1b) Support TEI XML input

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alignment-editor-new#78]
From #1 

Alignment editor is responsible for presenting the user with a choice to upload TEI and to select from the various parameters for identifying segments, line breaks and metadata in the TEI input as supported by the tokenizer.

**Comment by balmas** [comment]
This issue is for upload of TEI XML input.

Support for retrieval of TEI from a DTS endpoint  is covered by #77

**Comment by irina060981** [comment]
@balmas , there is a problem with sending TEI text to the tokenization service.
Request:
![image](https://user-images.githubusercontent.com/12377640/102079541-a028ba80-3e58-11eb-8ce5-cd513d439e54.png)

I took TEI example in your examples inside tokenizer repository.

And Browser returns me the following error:
![image](https://user-images.githubusercontent.com/12377640/102079673-db2aee00-3e58-11eb-8d84-673ea9938aaa.png)

The same example works well through unit tests and Postman.

**Comment by irina060981** [comment]
May be it is worth to add some additional settings to the web server on tokenization servser side?

**Comment by balmas** [comment]
are you sure you're setting the Content-Type=application/xml header?

**Comment by balmas** [comment]
oh, wait, nevermind, I see, it's a CORS issue. I'll update the server to allow that Header.

**Comment by balmas** [comment]
Or actually, no, I don't know how that could be it since the header is allowed for plain text.

**Comment by balmas** [comment]
Well, I don't understand why it wasn't a problem for the plain text content type but I've added the Access-Control-Allow-Headers * to the server now. @irina060981 can you try again?

**Comment by irina060981** [comment]
Yes, it works well now :)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
ok, this can be tested now. 

You can get data to test with from either Perseus or the texts at texts.alpheios.net

If you use Perseus, you can use the XML button at the bottom of a passage to download TEI xml that should work as input

![9f3933d0-703e-4311-95e5-9e48ef5b2a20](https://user-images.githubusercontent.com/644870/102391790-2e5d8780-3fa4-11eb-8bb2-fcc7950c0745.png)

I think make testing easy to start you should just use the same text in the source and target, because that way you don't have to worry about segment number mismatches.

Note though that apparently the xml declaration 
```
<?xml version="1.0" encoding="utf-8"?>
``` 
will cause the tokenizer to fail. That needs to be fixed (I've entered alpheios-project/tokenizer#23 for it)

So you need to remove that from the downloaded XML before you paste it into the Alignment Editor.

If you use the texts at texts.alpheios.net, you can click on the little citation icon and then click the Passage link to download the XML for the passage

![f06545ac-3ffe-430c-9a0e-89d94e7b8ec5](https://user-images.githubusercontent.com/644870/102392339-ed19a780-3fa4-11eb-9c07-26d8038a7ce2.png)

For this, you should copy just the contents of the `<passage></passage>` element in the response -- that contains the TEI document (this uncovered another bug, if you use the entire contents, the outer text gets tokenized, it should be thrown away instead. This is alpheios-project/tokenizer#24

You can try experimenting with changing the TEI input options:

**Supply a comma-separated list of elements in the text that represent visual blocks**

If this is set to "l" for example, then each bit of text in the TEI that is enclosed in `<l></l>` tags should show up with line breaks after them in the alignment editor.

**Supply a comma-separated list of TEI elements in the text which group segments of tokens.**

If this is set to "p", for example, then each bit of text in the TEI that is enclosed in `<p></p>` tags should show up as a separate segment.

**Supply a comma-separated list of TEI elements in the text whose contents should be ignored for tokenization.**

If this is set to "note", for example, then each bit of text in the TEI that is enclosed in `<note></note>` tags should NOT appear anywhere in the alignment.

You'll have to inspect the TEI a bit to decide what to use to test. Typically poetry has `<l></l>` tags and prose `<p></p>` tags but the texts are not marked up that consistently.

I am sure you will find bugs in this and there is more to do (e.g. see alpheios-project/tokenizer#15) before it's fully implemented.

**Comment by monzug** [comment]
see https://github.com/alpheios-project/alpheios-core/issues/587

**Comment by irina060981** [comment]
The bug is fixed inside the PR

**Comment by monzug** [comment]
Supply a comma-separated list of elements in the text that represent visual blocks works now. tested with l, p and div. update issue  #587

**Comment by monzug** [comment]
"Supply a comma-separated list of TEI elements in the text whose contents should be ignored for tokenization" works now. tested with note

**Comment by monzug** [comment]
"Supply a comma-separated list of TEI elements in the text which group segments of tokens." works fine. tested with l and body
