### ISSUE TITLE
Data Model

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alignment-editor-new#8]
![alignmentdatamodel (10)](https://user-images.githubusercontent.com/644870/88216573-474b5200-cc2b-11ea-9725-b93174a741d8.png)

An `Alignment` is composed of one `OriginText` and one or more `TargetText`s.
Both `OriginText` and `TargetText` are derivations of the abstract `AlignedText`. They have a required `language` attribute which identifies the primary language of the text.

An `AlignedText` __may__ have a `DocumentSource` which is the exact document from which the `AlignedText` was extracted
(`TeiXMLDocumentSource` and `PlainTextDocumentSource` are the supported `DocumentSource` types). 
Regardless of whether or not an `AlignedText` has a `DocumentSource` the `sourceDescription` attribute should be used to describe the original source of the text. 

(A `DocumentSource` has a `format`  original `content`and can also have a `pid` (persistent identifier).)

An `AlignedText` can have zero or more `MetadataSets` which contain `MetadataItems`. A `MetadataSet` may adhere to a specified ontology. A `MetadataItem` has a `name`, `value`, `creator` and `createdAt` attributes.

An `OriginText` is divided into one or more `Segment`s. These `Segment`s represent a semantic unit of equivalance across the texts to be aligned.

A `Segment` has required `id` and `type` attributes (e.g. "sentence", "verse") and an optional `beadType` attribute (e.g. "1-1", "1-2").

A `Segment` is composed of 2 or more `TokenSet`s. A `Segment` may have zero or more `MetadataSet`s associated with it. (Associated Metadata may contain information such as a treebank alignment, a canonical identifier, etc.)

A `TokenSequence` belongs to an `AlignedText` (either `OriginText` or `TargetText`) and is composed of one or more `Token`s from the `AlignedText`

A `Token` represents the smallest unit of text for alignment. It has  required `id`, `language` , `tokenText` and `lineBreakAfter` attributes.  If the `Token` was extracted from a `DocumentSource` at the time the `Alignment` was created, it should have one or more `Selector`s which identify the original location of the `Token` in the `DocumentSource`. (`Selector` types are per the W3C Annotation Data Model). 

A `Token` may have zero or more `MetadataSet`s associated with it. (Associated Metadata may contain information such as a treebank alignment, synset number etc.)

A `Token` may belong to a `ScrollGroup`.  A `ScrollGroup` contains start and end tokens from two AlignedTexts that identify the boundaries of a set of words that should be displayed together in the interface.

A `Token` has zero or more `TokenAlignment`s.  (Zero means it has not yet been aligned).

A `TokenAlignment` represents the alignment between a `Token` in one `AlignedText` and one token in another `AlignedText`s. It has a `creator`, a `createdDate` and a `targetToken`

An `AlignmentGroup` is composed of the set of `TokenAlignment`s that represent the union of all `Tokens` that reference each other across 2 `AlignedText`s.

Any of `Segment`, `TokenSet`, `Token`,  or `TokenAlignment`  may have zero or more `Comment`s. A `Comment` has `commentText`, a `creator` and a `createdAt` date.

**Comment by balmas** [comment]
![alignment_seq_new_from_source](https://user-images.githubusercontent.com/644870/88216642-5d591280-cc2b-11ea-951a-be2d57e8edc4.png)

![alignment_from_v1](https://user-images.githubusercontent.com/644870/88216657-64802080-cc2b-11ea-836c-5501b03c8e5d.png)

**Comment by balmas** [comment]
@irina060981 and @kirlat here's a first draft of what I think the data model might need to look like for the alignment editor, and a couple of examples of how how the model objects could be populated from a couple of different types of input data.   I would be happy to have your feedback.

**Comment by kirlat** [comment]
I have a few questions to make sure I understand the roles of participants correctly. This questions are referring to participants from the "New Alignment From Origin and Target Text" diagram:
* **Controller** - an entity that dispatches transactions;
* **Alignment** - an entity that stores aligned texts;
* **Origin Text** - this is a text that needs to be aligned. Where is it placed (stored)? From where it comes?
* **Target Text** - an origin text that has been tokenized (and probably passed through some cleaning and other transformations)
* **Document Source** - a place where origin and target texts are stored. Is this an HTML document? Is this the same document for both origin and target texts?
* **Segment** - a group of words that are related to each other by some criteria? Are these the words that form some logical groups within the alignment domain? Do we form word segments in both the original and the aligned texts and match them with each other?
* **Token Sequence** - is it something similar to the segment but stored in a different form?
* **Token** - is it some lexical logical unit that we break the text into?

What are "Alignment Group" and "Token Alignment" on the "New Alignment from Alpheios V1 Alignment XML" digram? How are their roles different from those of the "Segment"?

**Comment by balmas** [comment]
These are the conceptual models of the data the Alignment Editor needs to work with and create. How and where they are stored is a separate question that we will have to tackle but I don't think it should drive the data model.

In the diagrams **Controller** is assumed to be the entity that is responding to user requests. It isn't fully fleshed out here, as the main point of these sequence diagrams is to try to show the relationship between how the requirements around input text (in https://github.com/alpheios-project/documentation/blob/master/development/alignment-editor.md) are reflected in and accounted for in the proposed data model.

An **Alignment** is the overarching container for the results of creating a word-by-word alignment between some discretely identified text and the translation of that text.   It's up to the user to define what that text is -- it could be, for example a poem, a book, a chapter, or even a sentence that they have created.  In an Alignment there must be one Origin (or Source, but source has multiple meanings so I've used Origin to try to avoid confusion) text and one or more translations of that text.

An **Origin Text** is the container for the words to be aligned from the text which has been translated.
A **Target Text** is the container for the words to be aligned from a translation.

Both of these are derivations of the abstract **Aligned Text** and the main thing that distinguishes the Origin from the Target is that the structure of the Origin text is what drives the structure of the alignment.  In Machine Translation and Alignment, this is usually a sentence, and it needs to be driven by the origin (source) text because there may not be a one-to-one match in the translation. (For example, what takes 1 sentence to say in the original language may be expressed by 2 sentences in a translation).

A **Segment** is the model object that represents these individual structural units from the origin text. It contains the sets of words which _can be matched_ from each text. (So, to continue the earlier example with the segment being a sentence, it might contain 1 sentence form the original text and 2 sentences from the translation).  

A **TokenSequence** is just essentially a set of tokens that has some semantic or structural meaning. It might be the tokens from a single sentence or a line of verse, etc. 

In the example of a text which has been automatically aligned at the sentence level, a segment might contain 1 TokenSequence from the origin text (which represents the original sentence) and 2 TokenSequences from the translated text (if the single sentence has been translated by 2 sentences). In most cases there will be a 1-to-1 correlation between Segment and TokenSequence in the origin text but possibly not always.

Our requirements state:

>If input does not provide aligned segments, then input source and translation text is to be initially identified as a single segment of text to be aligned (no automatic segmentation)
>If input identifies aligned segments, then this information must be preserved with the alignment. 

What this means is that if the user comes to the alignment tool with a set of texts that have already been aligned at the sentence level, then they should be able to see and preserve that segmentation. But if all they give us are texts which have not been previously aligned this way, then we will initially treat the entire text as a single segment.  There are tools and services that can be used to do automatic segmentation and then alignment of sentences, but they do not work so well on non-literal translations (and often translations of poetry and other literary texts are not literal) and as the main focus of this tool is on supporting manual alignments at the word level, the cost of trying to include them in the workflow is not worth the benefit.  We may decide we want the user to be able to manually segment  the parallel texts further from within the Alignment editor but we won't do it automatically.  However we do want people to be able to use the alignment editor to work on text which has first been automatically aligned (whether only at the sentence or also at the word level) and to preserve that information with the data.


A **Token** is the smallest lexical unit that can be aligned. This is for the most part going to be a word, but it could be punctuation, or it could be a part of a word.


A **DocumentSource** holds the original text as it was supplied to the alignment editor by the user. In an alignment workflow that starts with text that has not yet been aligned in any way, they have digital representations of an original text and one or more translations of that text. The digitizations might be in plain text or they might be in a structured TEI XML file (those are the 2 input formats we are supporting). We need to tokenize those texts to identify the words to be aligned.  For a plain text file this is just a simple process of tokenization, but for a TEI XML file, there is a lot of structural markup and metadata that we will ignore. 
In #1 I discuss the pros and cons of doing the alignment directly within the original TEI structure of a TEI XML document, but ultimately decided that we need to extract the word tokens from it and operate on them outside of the original document.  However we want to be able to retain a link between the data in an alignment and the source from which it came. This is particularly true for TEI XML texts which are often full representations of a manuscript and not just the textual content of interest for an alignment.  We didn't do this in V1 of the tool, and it created problems when we wanted to use the alignment data to create pedagogical readers of texts that had been aligned.  I am not sure we will save the document source for every alignment created in the Alignment Editor (maybe it's a feature we can only offer to users who login, or who pay for storage, or some variation -- e.g. maybe you can keep up to 5 documents, etc.).  But I want the capability to do so.

We do not currently intend to support HTML as in input format although perhaps we might want to at some point. The question about whether or not it is the same document for the origin and target text is interesting -- in the case of plain text or tei xml the assumption is that the user will separate these into separate documents.  For input of other types, such as an Alpheios V1 Alignment, or a sentence pairs document, then it would be. I am not sure if we will retain to the document source in that case or not. 

**AlignmentGroup** and **TokenAlignment** are data model objects that represent data after the act of alignment has started. I have them in the _New Alignment from Alpheios V1 Alignment XML_ diagram because that represents the creation of a new alignment from existing alignment data.   A TokenAlignment represents the link between a single token in the origin text and an aligned token in the translation text. An AlignmentGroup represents a set of tokens that have been aligned, because alignments are n-to-n.  E.g. the latin text "veni" is translated as "I came". That's 1 token in the origin text and 2 tokens in the translation.  The AlignmentGroup contains 2 TokenAlignments:  ["veni" and "i"] and ["veni" and "came"]

**Comment by kirlat** [comment]
Thank you for a very detailed explanation. I think I understand it much better now!

I have an additional question about the **AlignmentGroup** and the **TokenAlignment**. Is there any reason why we have them as separate entities? Could we have just the alignment group that will store information from the example given as something like `{source: ["vani"], translation: ["i", "came"]} (i.e. that will represent a many-to-many relationship)?

**Comment by balmas** [comment]
It's a good question.  I drafted it this way because each alignment of one token to another represents a distinct action that can be done or undone separately and also people might want to comment on one word pair in a group.  These things could be handled by AlignmentGroup without TokenAlignment but I thought it might be more flexible this way.  Originally I was thinking that we might not even need to explicitly model AlignmentGroup, but I believe there will be business logic that we have to enforce related to the groups. (e.g. a token cannot be aligned in multiple groups).

**Comment by kirlat** [comment]
If we need to have tokens attached to the word pairs then having a **TokenAlignment** groups makes sense as those would be where comments are attached to.

**Comment by balmas** [comment]
The following activity diagram depicts the business logic for aligning a token. 

In working through this, I think I found that the proposed `TokenAlignment` class doesn't work in the data model --- the tokens are actually aligned as a group and not necessarily individually.   

![alignment_click_token](https://user-images.githubusercontent.com/644870/89811816-334d8e80-db0d-11ea-890f-e3c79a6e4f84.png)

**Comment by balmas** [comment]
![alignment_click_token (1)](https://user-images.githubusercontent.com/644870/89917152-77509a00-dbc6-11ea-8840-6c87673c8c88.png)

Minor revision to activity diagram.

**Comment by balmas** [comment]
Data flow diagram 

![alignmentdataflow](https://user-images.githubusercontent.com/644870/91464814-fc8cad80-e85a-11ea-9fb4-a555613d0b8b.png)

See related user data requirements in #19

**Comment by balmas** [comment]
closing as design discussion is complete.
