### ISSUE TITLE
(TIR 18) support editing of segment breaks in origin and translation texts after alignment has started

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alignment-editor-new#81]
Originally stated as:

18. May allow user to append words to the beginning or end of the source and translation texts once alignment has started

This requirement is expanded as follows.

Once an alignment has been created the interface should allow the user to do the following for any aligned text:

1. Move tokens from the end of 1 segment to the beginning of the next segment
2. Move tokens from the beginning of 1 segment to the end of the previous statement
3. Add new tokens to the beginning of the very first  segment of an aligned text
4. Remove tokens from the beginning of the very first  segment of an aligned text
5. Add new tokens to the end of the very last segment of an aligned text
4. Remove tokens from the end of the very last segment of an aligned text

If a token that is being moved already participates in an aligned group, the interface should warn the user that the existing alignment of this token will be erased if they proceed (and then do so if they continue with the action...)

**Comment by irina060981** [comment]
Merged and closed

**Comment by irina060981** [comment]
This has the features described in https://github.com/alpheios-project/alignment-editor-new/issues/39

**Comment by monzug** [comment]
the interface works as described above. In case a token is inside a created alignment group, the interface warns you to ungroup it first.
