### ISSUE TITLE
(TIR 17)  allow user to edit line breaks at any point during alignment

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alignment-editor-new#83]
Also 

17. Must allow user to edit line breaks at any point during alignment

_Originally posted by @balmas in https://github.com/alpheios-project/alignment-editor-new/issues/63#issuecomment-723237459_

**Comment by irina060981** [comment]
Done with https://github.com/alpheios-project/alignment-editor-new/pull/117

**Comment by irina060981** [comment]
This has the features described in https://github.com/alpheios-project/alignment-editor-new/issues/39

**Comment by monzug** [comment]
user can add line break after a token and remove line break after a token. Sometimes the remove line break gets stuck. will enter a new issue.
