### ISSUE TITLE
support upload of plain text files (plus refactor upload type design to better support additional formats)

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#89]
>> (6) Should be extensible to easily support creation of new alignments from other automatic alignment output formats

> @balmas, what exactly should be done here in Milestone 1?

Here's my understanding of how the code as currently designed supports this:

The  `uploadType` is set in the `TextsController`
The `UploadController` defines upload methods per `uploadType`
The `SourceText` defines a `convertFromJson` method which handles the details of converting the uploaded data to text that can be used to create an `AlignedText` (including definition of the tokenization method)

So to add a new supported upload type we would

1. Add a new `convertFrom...` method to `SourceText` to support the specific type of input 
2. Add a method to handle the new uploadType in the `UploadController` (this method would determine which convert method on `SourceText` to call) 
3. If in the the format of the new type is already tokenized, create a new tokenization class to convert those tokens into the token structure of the alignment editor.
4. Add the new type to a list of supported upload types in the `TextsController`
5. Present the list of types in a select box to the user in the `text-editor-single-block.vue` component
6. Have the `TextsController` pass the selected `uploadType` to the `UploadController`

I think this works, but I'm wondering if it makes sense to move the conversion methods out of `SourceText` and into `UploadController`. I think it reduces the places the code needs to be touched to add a new upload type. What do you think @irina060981 ?

As I look at the code, I also just realized that I  missed explicitly stating the following requirement:

8. Must accept *upload* of source and translation text in either plain text and TEI XML

_Originally posted by @balmas in https://github.com/alpheios-project/alignment-editor-new/issues/60#issuecomment-740756753_

**Comment by irina060981** [comment]
@balmas , according to the upper workflow we would have the following structure:

1) we would have two modes of upload feature:
    - **upload of the alignment** - when a user uploads origin and target source texts with its options, aligned texts (may be) and aligned groups (may be)
    - **upload of the single intstance of text** - when a user uploads one origin or target text with the options of the current source text, it could be aligned but could not have aligned groups

2) In the case of **upload of the alignment**:
   - all pieces of texts would have a single upload type
   - upload would be done through the upload file block under the main menu 
   - it would have a global option of upload type
   - it would reset the current alignment and remove all previous work in the session

3) In the case of **upload of one instance of the text**:
   - uploaded text instance would have its own uploadType
   - upload would be done through the upload file block inside text-editor-single-block
   - it would have a local option of upload type
   - if a user uploads **origin** text - it would reset origin source text, aligned text and would remove all created aligned groups
   - if a user uploads **target** text -  it would reset targetsource text, aligned text and would remove all created aligned groups that was created with tokens from the current target instance

**Comment by irina060981** [comment]
I think that the same way should be done download workflow:
- download of the alignment
- download of the single instance

And I think it is worth to do it together (at the same time) - because it would be useful to test them together.

**Comment by irina060981** [comment]
> I think this works, but I'm wondering if it makes sense to move the conversion methods out of SourceText and into UploadController. I think it reduces the places the code needs to be touched to add a new upload type.

I thought about it when was doing the first version of Upload Controller.

I could use here one of the following logics:

1. conversion method depends on the source text structure
2. conversion method depends on the upload file structure

According to the choice:

1. SourceText doesn't know anything about upload/download types. It would always convert to/from json the same away.
    UploadController/DownloadController always works with the same convertFromJson/convertToJson method and adapts data on its own side. 
    This way (in the case of upload process) UploadController parses input (file) data and converts it to the standard input of the SourceText method
    In this case SourceText and UploadController have only one dependency - If SourceText would be added a new mandatory field - we would need to update UploadController method. I think that it would be needed anyway to support previously downloaded texts.

2. Each UploadController's upload method should now current SourceText structure and support its own converToJson method to the SourceText. This way upload methods would be tightly connected to SourceText structure. 

Both approaches could be used - but from my point of view the first is more independent.

**Comment by irina060981** [comment]
@balmas , What do you think about my suggestions?

**Comment by balmas** [comment]
@irina060981 yes I agree.

**Comment by irina060981** [comment]
Decided on the meeting about the following amount of the task for the Milestone 1:

- Add an ability to upload/download a single instance of the source text in both formats TEI and TEXT to the textarea

**Comment by irina060981** [comment]
In the later Milestones:

- add an option for uploadType/downloadType for both modes (alignment/ single source text instance)
- add an ability to upload/download sourceText data, alignedText data, ready aligned groups

**Comment by irina060981** [comment]
Merged and closed
