### ISSUE TITLE
Clear all should clear all data and turn back to default settings

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#91]
Clear all should clear all fields in alignment editor. Right now, when I click on Clear all I can still see that some settings are still selected or visible:  e.g. Choose file: no file chosen or the direction (right to left) or the origin language.
Maybe we do not have default settings?
related to #48 
Shall we consider two mode: 1) clear all and 2) clear text?

**Comment by balmas** [comment]
Ah, I think the current Clear All is intended as Clear Text.  @irina060981 can you confirm?

**Comment by irina060981** [comment]
Now, it clears all and drops settings to default.
But it works the same way as reload the page:
 - settings became default
 - and loaded the last changes from the storage
and finally it became the same as before clear

So we could do the following variants:
1) remove the feature of loading local text options from the default - but then a user would always start from the default language, direction, sourceType and tokenization options

or

2) drop to default only on clear all - but then these default settings would be saved to the Storage on any change - and would be applied at the next session (on page reload)

I decided that the 1 variant is more consistent.

But, @monzug adn @balmas - if you see some better variant - would be glad to do it.

**Comment by monzug** [comment]
the easy solution would be to change the button from clear all to clear text as suggested by @balmas

**Comment by irina060981** [comment]
Oh, I didn't understand the problem properly :) Ok - let;'s change the title :)

**Comment by irina060981** [comment]
Fixed
Merged and closed

**Comment by monzug** [comment]
Thanks. @balmas, do you agree?

**Comment by balmas** [comment]
yep.

**Comment by monzug** [comment]
Actually, on reloading the page, Direction and Origin Language are sticky. I am ok with it. Just wondering if it would be possible to go back to initial state (if we have a default state)on reloading.

**Comment by balmas** [comment]
> Actually, on reloading the page, Direction and Origin Language are sticky. I am ok with it. Just wondering if it would be possible to go back to initial state (if we have a default state)on reloading.

We have a requirement to remember a user's choices.  This will be extended once we add use login.  But you're right, just like with Options in the main Alpheios app, we should have the ability to "Reset All" options.  Will make this a new issue.

**Comment by monzug** [comment]
reloading clear the alignment and the origin and target text
