### ISSUE TITLE
Add ability to "Reset All" options.

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alignment-editor-new#93]
> Actually, on reloading the page, Direction and Origin Language are sticky. I am ok with it. Just wondering if it would be possible to go back to initial state (if we have a default state)on reloading.

We have a requirement to remember a user's choices.  This will be extended once we add use login.  But you're right, just like with Options in the main Alpheios app, we should have the ability to "Reset All" options.  Will make this a new issue.

_Originally posted by @balmas in https://github.com/alpheios-project/alignment-editor-new/issues/91#issuecomment-743211578_

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
@irina060981  After "Clear text" I still have the information on the uploaded file. see screenshot
![Screen Shot 2021-01-27 at 4 42 53 PM](https://user-images.githubusercontent.com/41396793/106015761-173fa880-60bf-11eb-941e-3a1328644179.png)

**Comment by irina060981** [comment]
@monzug 
Great catch with upload file input after Clear text - will fix that

**Comment by monzug** [comment]
all good here. Thanks
