### ISSUE TITLE
Tokenization error

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#94]
I got a tokenization error few times. Could it be a connection issue? I don't know when this error should be generated. Anyhow, it did happen when switching from standard theme to vi theme, at least once. Not sure if it's related, though. 
see screenshot below:
![vi theme](https://user-images.githubusercontent.com/41396793/101913102-92d9aa80-3b90-11eb-8ccc-d3d3a3b49d44.JPG)

**Comment by irina060981** [comment]
I was not able to reproduce.
This error is from the BasicAdapter and it is catched when `windows.fetch` was failed.
There is no response from the url at all.

That's why there are no any other details.
I think that there were some problems at that moment with tokenization service.
May be there are some information in logs on the server about it?

**Comment by irina060981** [comment]
@monzug , if you could reproduce the error could you screenshot browser console with the detailed error?

**Comment by balmas** [comment]
I was wondering if maybe switching the theme caused the form for tokenization to be resubmitted with empty information, resulting in the error.

**Comment by irina060981** [comment]
>I was wondering if maybe switching the theme caused the form for tokenization to be resubmitted with empty information, resulting in the error.

I tested this case.
This forms are separated completely and couldn't influence each other.

This error looks like as from the https://github.com/alpheios-project/alignment-editor-new/issues/78
So may be we could get the error from Monica's console

**Comment by monzug** [comment]
@irina060981 , I got this error few times while testing the Options. if I get it again I will take a screenshot of the console

**Comment by irina060981** [comment]
thank you, @monzug !

**Comment by irina060981** [comment]
@monzug May be we should close this issue - if you won't reproduce this error while testing Milestone2 ?

**Comment by monzug** [comment]
I was not able to reproduce it. closed.

**Comment by monzug** [comment]
switching from vi theme to standard theme in Safari, I had to wait a really looong time for the tokenization process to finish, so I ended up reloading it.
looking at the log, I saw these errors (if it can help)

![Screen Shot 2021-01-26 at 4 18 48 PM](https://user-images.githubusercontent.com/41396793/105866236-155ce300-5ff4-11eb-94d7-a3e9216f7455.png)

**Comment by irina060981** [comment]
thank you, Monica, will check it!

**Comment by irina060981** [comment]
Monica, I couldn't reproduce this error.
The error is from creating segments from tokenizer result, it tells that for some reasons - there were passed empty tokens.
And tokenizer couldn't do this in a normal case.

So there could be two reasons:
- there were some problems with tokenizer service
- there was something in the source text that caused problems

I don't think that it could be connected with Safari browser or changing theme.
If you could reproduce it - give me please your texts.

**Comment by monzug** [comment]
Thanks Irina, I will try few more times today. again it's arabic text as in the first screenshot from Dec 11. the text is pretty much this one:

ُأبْلِغْ عَزيزاً فِي ثَنايا القَلْــــــبِ مَنْزِلُه

ُأنِّى وَإنْ كُنـْــــتُ لا ألقاهُ ألقــــــــاه

ِوإنَّ طَرَفِيَ مَوصــــــولٌ بِرُؤيَتـِـــــــه

ُوإنْ تَبَاعَــــــدَ عَنْ سُكْنايَ سُكْنــاه

**Comment by irina060981** [comment]
Tried this text in both themes in Chrome and Safari - no errors.
Will check it later again.

**Comment by monzug** [comment]
Not able to reproduce either. I will use this log as an example of error handling
